// Primary English Language Questions
// Initial batch of questions migrated to modular ChallengeQuestion format

import type { ChallengeQuestion } from '../types';

export const primaryEnglishLanguageQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Initial Batch)
  // ============================================

  // Primary English Language - Alphabet & Phonics
  {
    id: 'primary-eng-001',
    type: 'mcq',
    question: 'Which word starts with the letter "A"?',
    options: ['Ball', 'Apple', 'Cat', 'Dog'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Alphabet',
    explanation: 'Apple starts with the letter A',
    source: 'practice',
  },
  {
    id: 'primary-eng-002',
    type: 'mcq',
    question: 'Which word rhymes with "hat"?',
    options: ['hot', 'bat', 'hit', 'hut'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Phonics',
    explanation: 'Bat rhymes with hat',
    source: 'practice',
  },
  {
    id: 'primary-eng-003',
    type: 'mcq',
    question: 'Which word starts with the letter "C"?',
    options: ['Apple', 'Ball', 'Cat', 'Dog'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Alphabet',
    explanation: 'Cat starts with the letter C',
    source: 'practice',
  },

  // Primary English Language - Grammar
  {
    id: 'primary-eng-004',
    type: 'mcq',
    question: 'What is the plural of "cat"?',
    options: ['cat', 'cats', 'cates', 'caties'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of cat is cats',
    source: 'practice',
  },
  {
    id: 'primary-eng-005',
    type: 'mcq',
    question: 'What is the plural of "dog"?',
    options: ['dog', 'dogs', 'doges', 'dogies'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of dog is dogs',
    source: 'practice',
  },
  {
    id: 'primary-eng-006',
    type: 'mcq',
    question: 'What is the plural of "child"?',
    options: ['childs', 'children', 'childrens', 'childes'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of child is children (irregular plural)',
    source: 'practice',
  },
  {
    id: 'primary-eng-007',
    type: 'mcq',
    question: 'Which sentence is correct?',
    options: ['I am happy.', 'I is happy.', 'I are happy.', 'I be happy.'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'I am happy is the correct sentence',
    source: 'practice',
  },
  {
    id: 'primary-eng-008',
    type: 'mcq',
    question: 'What is the past tense of "go"?',
    options: ['go', 'goes', 'went', 'going'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The past tense of go is went',
    source: 'practice',
  },
  {
    id: 'primary-eng-009',
    type: 'mcq',
    question: 'Which word is a noun?',
    options: ['Run', 'Beautiful', 'School', 'Quickly'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'School is a noun (a place)',
    source: 'practice',
  },
  {
    id: 'primary-eng-010',
    type: 'mcq',
    question: 'What is the opposite of "big"?',
    options: ['Large', 'Small', 'Huge', 'Giant'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'The opposite of big is small',
    source: 'practice',
  },
];

