// Primary English Language Questions
// Initial batch of questions migrated to modular ChallengeQuestion format

import type { ChallengeQuestion } from '../types';

export const primaryEnglishLanguageQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Initial Batch)
  // ============================================

  // Primary English Language - Alphabet & Phonics
  {
    id: 'primary-eng-001',
    type: 'mcq',
    question: 'Which word starts with the letter "A"?',
    options: ['Ball', 'Apple', 'Cat', 'Dog'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Alphabet',
    explanation: 'Apple starts with the letter A',
    source: 'practice',
  },
  {
    id: 'primary-eng-002',
    type: 'mcq',
    question: 'Which word rhymes with "hat"?',
    options: ['hot', 'bat', 'hit', 'hut'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Phonics',
    explanation: 'Bat rhymes with hat',
    source: 'practice',
  },
  {
    id: 'primary-eng-003',
    type: 'mcq',
    question: 'Which word starts with the letter "C"?',
    options: ['Apple', 'Ball', 'Cat', 'Dog'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Alphabet',
    explanation: 'Cat starts with the letter C',
    source: 'practice',
  },

  // Primary English Language - Grammar
  {
    id: 'primary-eng-004',
    type: 'mcq',
    question: 'What is the plural of "cat"?',
    options: ['cat', 'cats', 'cates', 'caties'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of cat is cats',
    source: 'practice',
  },
  {
    id: 'primary-eng-005',
    type: 'mcq',
    question: 'What is the plural of "dog"?',
    options: ['dog', 'dogs', 'doges', 'dogies'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of dog is dogs',
    source: 'practice',
  },
  {
    id: 'primary-eng-006',
    type: 'mcq',
    question: 'What is the plural of "child"?',
    options: ['childs', 'children', 'childrens', 'childes'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of child is children (irregular plural)',
    source: 'practice',
  },
  {
    id: 'primary-eng-007',
    type: 'mcq',
    question: 'Which sentence is correct?',
    options: ['I am happy.', 'I is happy.', 'I are happy.', 'I be happy.'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'I am happy is the correct sentence',
    source: 'practice',
  },
  {
    id: 'primary-eng-008',
    type: 'mcq',
    question: 'What is the past tense of "go"?',
    options: ['go', 'goes', 'went', 'going'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The past tense of go is went',
    source: 'practice',
  },
  {
    id: 'primary-eng-009',
    type: 'mcq',
    question: 'Which word is a noun?',
    options: ['Run', 'Beautiful', 'School', 'Quickly'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'School is a noun (a place)',
    source: 'practice',
  },
  {
    id: 'primary-eng-010',
    type: 'mcq',
    question: 'What is the opposite of "big"?',
    options: ['Large', 'Small', 'Huge', 'Giant'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'The opposite of big is small',
    source: 'practice',
  },

  // ============================================
  // Primary 1 - Alphabet, Phonics & Basic Vocabulary
  // ============================================
  {
    id: 'primary-eng-011',
    type: 'mcq',
    question: 'Which word starts with the letter "B"?',
    options: ['Apple', 'Ball', 'Cat', 'Dog'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Alphabet',
    explanation: 'Ball starts with the letter B',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-012',
    type: 'mcq',
    question: 'Which word starts with the letter "D"?',
    options: ['Apple', 'Ball', 'Cat', 'Dog'],
    correctAnswer: 3,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Alphabet',
    explanation: 'Dog starts with the letter D',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-013',
    type: 'mcq',
    question: 'Which word rhymes with "sun"?',
    options: ['son', 'run', 'fun', 'All of the above'],
    correctAnswer: 3,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Phonics',
    explanation: 'Son, run, and fun all rhyme with sun',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-014',
    type: 'mcq',
    question: 'Which word rhymes with "cat"?',
    options: ['hat', 'bat', 'mat', 'All of the above'],
    correctAnswer: 3,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Phonics',
    explanation: 'Hat, bat, and mat all rhyme with cat',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-015',
    type: 'mcq',
    question: 'What is the opposite of "hot"?',
    options: ['Warm', 'Cold', 'Cool', 'Freezing'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'The opposite of hot is cold',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-016',
    type: 'mcq',
    question: 'What is the opposite of "happy"?',
    options: ['Sad', 'Angry', 'Excited', 'Tired'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'The opposite of happy is sad',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-017',
    type: 'mcq',
    question: 'Which word is a verb?',
    options: ['Jump', 'Table', 'Red', 'Happy'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'Jump is a verb (an action word)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-018',
    type: 'mcq',
    question: 'Which word is an adjective?',
    options: ['Run', 'Beautiful', 'School', 'Quickly'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'Beautiful is an adjective (describes something)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-019',
    type: 'mcq',
    question: 'Complete: "I ___ a student."',
    options: ['am', 'is', 'are', 'be'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'I am a student is correct',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-020',
    type: 'mcq',
    question: 'Complete: "She ___ my friend."',
    options: ['am', 'is', 'are', 'be'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'She is my friend is correct',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 2 - Reading & Grammar Basics
  // ============================================
  {
    id: 'primary-eng-021',
    type: 'mcq',
    question: 'What is the plural of "book"?',
    options: ['book', 'books', 'bookes', 'bookies'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of book is books',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-022',
    type: 'mcq',
    question: 'What is the plural of "box"?',
    options: ['box', 'boxs', 'boxes', 'boxies'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of box is boxes (add -es to words ending in x)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-023',
    type: 'mcq',
    question: 'What is the past tense of "eat"?',
    options: ['eat', 'eats', 'ate', 'eating'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The past tense of eat is ate',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-024',
    type: 'mcq',
    question: 'What is the past tense of "run"?',
    options: ['run', 'runs', 'ran', 'running'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The past tense of run is ran',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-025',
    type: 'mcq',
    question: 'Which sentence is correct?',
    options: ['They are playing.', 'They is playing.', 'They am playing.', 'They be playing.'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'They are playing is correct',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-026',
    type: 'mcq',
    question: 'What is the plural of "tooth"?',
    options: ['tooths', 'teeth', 'toothes', 'toothies'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of tooth is teeth (irregular plural)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-027',
    type: 'mcq',
    question: 'What is the plural of "foot"?',
    options: ['foots', 'feet', 'footes', 'footies'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of foot is feet (irregular plural)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-028',
    type: 'mcq',
    question: 'Which word means "very big"?',
    options: ['Small', 'Tiny', 'Huge', 'Little'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Huge means very big',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-029',
    type: 'mcq',
    question: 'What is a synonym for "happy"?',
    options: ['Sad', 'Angry', 'Joyful', 'Tired'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Joyful is a synonym for happy (means the same)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-030',
    type: 'mcq',
    question: 'What is a synonym for "fast"?',
    options: ['Slow', 'Quick', 'Big', 'Small'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Quick is a synonym for fast',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 3 - Advanced Grammar & Comprehension
  // ============================================
  {
    id: 'primary-eng-031',
    type: 'mcq',
    question: 'What is the past tense of "see"?',
    options: ['see', 'sees', 'saw', 'seeing'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The past tense of see is saw',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-032',
    type: 'mcq',
    question: 'What is the past tense of "come"?',
    options: ['come', 'comes', 'came', 'coming'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The past tense of come is came',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-033',
    type: 'mcq',
    question: 'Which sentence uses correct punctuation?',
    options: ['I like apples.', 'I like apples', 'i like apples.', 'I Like Apples.'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Punctuation',
    explanation: 'I like apples. has correct capitalization and period',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-034',
    type: 'mcq',
    question: 'What is the plural of "mouse"?',
    options: ['mouses', 'mice', 'mousees', 'mousies'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of mouse is mice (irregular plural)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-035',
    type: 'mcq',
    question: 'What is the plural of "man"?',
    options: ['mans', 'men', 'manes', 'manies'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of man is men (irregular plural)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-036',
    type: 'mcq',
    question: 'Which word is an adverb?',
    options: ['Run', 'Beautiful', 'Quickly', 'School'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'Quickly is an adverb (describes how something is done)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-037',
    type: 'mcq',
    question: 'Complete: "I ___ to school every day."',
    options: ['go', 'goes', 'went', 'going'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'I go to school every day is correct (present tense)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-038',
    type: 'mcq',
    question: 'Complete: "She ___ her homework yesterday."',
    options: ['do', 'does', 'did', 'doing'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'She did her homework yesterday is correct (past tense)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-039',
    type: 'mcq',
    question: 'What is a synonym for "smart"?',
    options: ['Dumb', 'Clever', 'Slow', 'Lazy'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Clever is a synonym for smart',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-040',
    type: 'mcq',
    question: 'What is an antonym for "brave"?',
    options: ['Strong', 'Afraid', 'Happy', 'Kind'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Afraid is an antonym (opposite) of brave',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 4 - Complex Grammar & Comprehension
  // ============================================
  {
    id: 'primary-eng-041',
    type: 'mcq',
    question: 'What is the past tense of "write"?',
    options: ['write', 'writes', 'wrote', 'writing'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The past tense of write is wrote',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-042',
    type: 'mcq',
    question: 'What is the past tense of "think"?',
    options: ['think', 'thinks', 'thought', 'thinking'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The past tense of think is thought',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-043',
    type: 'mcq',
    question: 'Which sentence is correct?',
    options: ['I have two books.', 'I has two books.', 'I am two books.', 'I be two books.'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'I have two books is correct',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-044',
    type: 'mcq',
    question: 'What is the plural of "leaf"?',
    options: ['leafs', 'leaves', 'leafes', 'leafies'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of leaf is leaves (change f to v and add -es)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-045',
    type: 'mcq',
    question: 'What is the plural of "knife"?',
    options: ['knifes', 'knives', 'knifees', 'knifies'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of knife is knives (change f to v and add -es)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-046',
    type: 'mcq',
    question: 'Which sentence uses "their" correctly?',
    options: ['Their going to school.', 'They\'re going to school.', 'There going to school.', 'They are going to school.'],
    correctAnswer: 3,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'They are going to school is correct (their = belonging to them, they\'re = they are)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-047',
    type: 'mcq',
    question: 'What is a synonym for "begin"?',
    options: ['End', 'Start', 'Stop', 'Finish'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Start is a synonym for begin',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-048',
    type: 'mcq',
    question: 'What is an antonym for "begin"?',
    options: ['Start', 'End', 'Continue', 'Pause'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'End is an antonym (opposite) of begin',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-049',
    type: 'mcq',
    question: 'Which word means "to make something better"?',
    options: ['Improve', 'Worsen', 'Break', 'Destroy'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Improve means to make something better',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-050',
    type: 'mcq',
    question: 'What punctuation mark ends a question?',
    options: ['.', '!', '?', ','],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Punctuation',
    explanation: 'A question mark (?) ends a question',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 5 - Advanced Grammar & Vocabulary
  // ============================================
  {
    id: 'primary-eng-051',
    type: 'mcq',
    question: 'What is the past tense of "bring"?',
    options: ['bring', 'brings', 'brought', 'bringing'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The past tense of bring is brought',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-052',
    type: 'mcq',
    question: 'What is the past tense of "teach"?',
    options: ['teach', 'teaches', 'taught', 'teaching'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The past tense of teach is taught',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-053',
    type: 'mcq',
    question: 'Which sentence uses "its" correctly?',
    options: ['The dog wagged it\'s tail.', 'The dog wagged its tail.', 'The dog wagged its\' tail.', 'The dog wagged it tail.'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The dog wagged its tail is correct (its = belonging to it, it\'s = it is)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-054',
    type: 'mcq',
    question: 'What is the plural of "woman"?',
    options: ['womans', 'women', 'womanes', 'womanies'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of woman is women (irregular plural)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-055',
    type: 'mcq',
    question: 'What is the plural of "person"?',
    options: ['persons', 'people', 'persones', 'personies'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of person is people (irregular plural)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-056',
    type: 'mcq',
    question: 'What is a synonym for "beautiful"?',
    options: ['Ugly', 'Pretty', 'Bad', 'Wrong'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Pretty is a synonym for beautiful',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-057',
    type: 'mcq',
    question: 'What is an antonym for "generous"?',
    options: ['Kind', 'Selfish', 'Nice', 'Good'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Selfish is an antonym (opposite) of generous',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-058',
    type: 'mcq',
    question: 'Which word means "very tired"?',
    options: ['Sleepy', 'Exhausted', 'Happy', 'Excited'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Exhausted means very tired',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-059',
    type: 'mcq',
    question: 'What is a homophone for "see"?',
    options: ['Sea', 'Saw', 'Sight', 'Look'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Sea is a homophone for see (sounds the same but different meaning)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-060',
    type: 'mcq',
    question: 'What is a homophone for "there"?',
    options: ['Their', 'They\'re', 'Here', 'Both A and B'],
    correctAnswer: 3,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Their and they\'re are homophones for there (sound the same)',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 6 - Advanced Grammar & Comprehension
  // ============================================
  {
    id: 'primary-eng-061',
    type: 'mcq',
    question: 'What is the past tense of "swim"?',
    options: ['swim', 'swims', 'swam', 'swimming'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The past tense of swim is swam',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-062',
    type: 'mcq',
    question: 'What is the past tense of "sing"?',
    options: ['sing', 'sings', 'sang', 'singing'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The past tense of sing is sang',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-063',
    type: 'mcq',
    question: 'Which sentence uses "your" correctly?',
    options: ['Your going to school.', 'You\'re going to school.', 'You going to school.', 'You are going to school.'],
    correctAnswer: 3,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'You are going to school is correct (your = belonging to you, you\'re = you are)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-064',
    type: 'mcq',
    question: 'What is the plural of "deer"?',
    options: ['deers', 'deer', 'deeres', 'deeries'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of deer is deer (same form for singular and plural)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-065',
    type: 'mcq',
    question: 'What is the plural of "sheep"?',
    options: ['sheeps', 'sheep', 'sheepes', 'sheepies'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of sheep is sheep (same form for singular and plural)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-066',
    type: 'mcq',
    question: 'What is a synonym for "enormous"?',
    options: ['Tiny', 'Huge', 'Small', 'Little'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Huge is a synonym for enormous',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-067',
    type: 'mcq',
    question: 'What is an antonym for "ancient"?',
    options: ['Old', 'Modern', 'Ancient', 'Historic'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Modern is an antonym (opposite) of ancient',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-068',
    type: 'mcq',
    question: 'Which word means "to look at something carefully"?',
    options: ['Glance', 'Examine', 'Ignore', 'Forget'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Examine means to look at something carefully',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-069',
    type: 'mcq',
    question: 'What is a homophone for "write"?',
    options: ['Right', 'Left', 'Wrong', 'Correct'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Right is a homophone for write (sounds the same but different meaning)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-070',
    type: 'mcq',
    question: 'What is a homophone for "break"?',
    options: ['Brake', 'Broke', 'Broken', 'Breaking'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Brake is a homophone for break (sounds the same but different meaning)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-071',
    type: 'mcq',
    question: 'Complete: "I ___ already finished my homework."',
    options: ['have', 'has', 'had', 'having'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'I have already finished my homework is correct (present perfect tense)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-072',
    type: 'mcq',
    question: 'Complete: "She ___ been waiting for an hour."',
    options: ['have', 'has', 'had', 'having'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'She has been waiting for an hour is correct (present perfect continuous)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-073',
    type: 'mcq',
    question: 'What is the comparative form of "big"?',
    options: ['big', 'bigger', 'biggest', 'bigly'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The comparative form of big is bigger (used to compare two things)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-074',
    type: 'mcq',
    question: 'What is the superlative form of "good"?',
    options: ['good', 'better', 'best', 'goodly'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The superlative form of good is best (used to compare three or more things)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-075',
    type: 'mcq',
    question: 'What is the comparative form of "beautiful"?',
    options: ['beautiful', 'beautifuler', 'more beautiful', 'most beautiful'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The comparative form of beautiful is more beautiful (for longer adjectives)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-076',
    type: 'mcq',
    question: 'Which sentence uses correct capitalization?',
    options: ['i live in accra.', 'I live in Accra.', 'I Live In Accra.', 'i live in accra'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Punctuation',
    explanation: 'I live in Accra. has correct capitalization (I, Accra are proper nouns)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-077',
    type: 'mcq',
    question: 'What punctuation mark shows strong feeling?',
    options: ['.', '!', '?', ','],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Punctuation',
    explanation: 'An exclamation mark (!) shows strong feeling',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-078',
    type: 'mcq',
    question: 'What is a prefix that means "not"?',
    options: ['un-', 're-', 'pre-', 'dis-'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'The prefix "un-" means not (e.g., unhappy = not happy)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-079',
    type: 'mcq',
    question: 'What is a prefix that means "again"?',
    options: ['un-', 're-', 'pre-', 'dis-'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'The prefix "re-" means again (e.g., rewrite = write again)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-080',
    type: 'mcq',
    question: 'What is a suffix that means "full of"?',
    options: ['-ful', '-less', '-er', '-ed'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'The suffix "-ful" means full of (e.g., beautiful = full of beauty)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-081',
    type: 'mcq',
    question: 'What is the past tense of "buy"?',
    options: ['buy', 'buys', 'bought', 'buying'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The past tense of buy is bought',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-082',
    type: 'mcq',
    question: 'What is the past tense of "catch"?',
    options: ['catch', 'catches', 'caught', 'catching'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The past tense of catch is caught',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-083',
    type: 'mcq',
    question: 'What is the plural of "city"?',
    options: ['citys', 'cities', 'cityes', 'cityies'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of city is cities (change y to i and add -es)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-084',
    type: 'mcq',
    question: 'What is the plural of "baby"?',
    options: ['babys', 'babies', 'babyes', 'babyies'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of baby is babies (change y to i and add -es)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-085',
    type: 'mcq',
    question: 'What is a synonym for "difficult"?',
    options: ['Easy', 'Hard', 'Simple', 'Light'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Hard is a synonym for difficult',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-086',
    type: 'mcq',
    question: 'What is an antonym for "difficult"?',
    options: ['Hard', 'Easy', 'Tough', 'Complex'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Easy is an antonym (opposite) of difficult',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-087',
    type: 'mcq',
    question: 'Which word means "to say something again"?',
    options: ['Repeat', 'Forget', 'Ignore', 'Delete'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Repeat means to say something again',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-088',
    type: 'mcq',
    question: 'What is a homophone for "meet"?',
    options: ['Meat', 'Met', 'Meeting', 'Meet'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Meat is a homophone for meet (sounds the same but different meaning)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-089',
    type: 'mcq',
    question: 'What is a homophone for "knight"?',
    options: ['Night', 'Day', 'Light', 'Bright'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Night is a homophone for knight (sounds the same but different meaning)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-090',
    type: 'mcq',
    question: 'Which sentence uses "who" correctly?',
    options: ['Who is your teacher?', 'Who book is this?', 'Who going to school?', 'Who is happy?'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'Who is your teacher? is correct (who = person, whose = belonging to)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-091',
    type: 'mcq',
    question: 'What is the past tense of "sleep"?',
    options: ['sleep', 'sleeps', 'slept', 'sleeping'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The past tense of sleep is slept',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-092',
    type: 'mcq',
    question: 'What is the past tense of "keep"?',
    options: ['keep', 'keeps', 'kept', 'keeping'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The past tense of keep is kept',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-093',
    type: 'mcq',
    question: 'What is the plural of "fish"?',
    options: ['fishs', 'fishes', 'fish', 'Both B and C'],
    correctAnswer: 3,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The plural of fish can be fish or fishes (both are correct)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-094',
    type: 'mcq',
    question: 'What is a synonym for "quick"?',
    options: ['Slow', 'Fast', 'Lazy', 'Tired'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Fast is a synonym for quick',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-095',
    type: 'mcq',
    question: 'What is an antonym for "quick"?',
    options: ['Fast', 'Slow', 'Quick', 'Rapid'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Slow is an antonym (opposite) of quick',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-096',
    type: 'mcq',
    question: 'Which word means "to make something clean"?',
    options: ['Dirty', 'Clean', 'Wash', 'Break'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'Wash means to make something clean',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-097',
    type: 'mcq',
    question: 'What is the comparative form of "small"?',
    options: ['small', 'smaller', 'smallest', 'smallly'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The comparative form of small is smaller',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-098',
    type: 'mcq',
    question: 'What is the superlative form of "big"?',
    options: ['big', 'bigger', 'biggest', 'bigly'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Grammar',
    explanation: 'The superlative form of big is biggest',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-099',
    type: 'mcq',
    question: 'What is a prefix that means "before"?',
    options: ['un-', 're-', 'pre-', 'dis-'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'The prefix "pre-" means before (e.g., preview = view before)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-eng-100',
    type: 'mcq',
    question: 'What is a suffix that means "without"?',
    options: ['-ful', '-less', '-er', '-ed'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Vocabulary',
    explanation: 'The suffix "-less" means without (e.g., hopeless = without hope)',
    source: 'practice',
    year: 2023,
  },
];

