// Primary Mathematics Questions
// Initial batch of questions migrated to modular ChallengeQuestion format

import type { ChallengeQuestion } from '../types';

export const primaryMathematicsQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Initial Batch)
  // ============================================

  // Primary Mathematics - Basic Operations
  {
    id: 'primary-math-001',
    type: 'mcq',
    question: 'What is 2 + 3?',
    options: ['4', '5', '6', '7'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Addition',
    explanation: '2 + 3 = 5',
    source: 'practice',
  },
  {
    id: 'primary-math-002',
    type: 'mcq',
    question: 'What is 10 - 4?',
    options: ['5', '6', '7', '8'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Subtraction',
    explanation: '10 - 4 = 6',
    source: 'practice',
  },
  {
    id: 'primary-math-003',
    type: 'mcq',
    question: 'What is 5 × 2?',
    options: ['7', '10', '12', '15'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Multiplication',
    explanation: '5 × 2 = 10',
    source: 'practice',
  },
  {
    id: 'primary-math-004',
    type: 'mcq',
    question: 'What is 8 ÷ 2?',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Division',
    explanation: '8 ÷ 2 = 4',
    source: 'practice',
  },
  {
    id: 'primary-math-005',
    type: 'mcq',
    question: 'Which number comes after 9?',
    options: ['8', '9', '10', '11'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Numbers',
    explanation: 'After 9 comes 10',
    source: 'practice',
  },

  // Primary Mathematics - Shapes & Geometry
  {
    id: 'primary-math-006',
    type: 'mcq',
    question: 'How many sides does a triangle have?',
    options: ['2', '3', '4', '5'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Shapes',
    explanation: 'A triangle has 3 sides',
    source: 'practice',
  },
  {
    id: 'primary-math-007',
    type: 'mcq',
    question: 'How many sides does a square have?',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Shapes',
    explanation: 'A square has 4 equal sides',
    source: 'practice',
  },
  {
    id: 'primary-math-008',
    type: 'mcq',
    question: 'What shape has no sides?',
    options: ['Triangle', 'Square', 'Circle', 'Rectangle'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Shapes',
    explanation: 'A circle is round with no straight sides',
    source: 'practice',
  },

  // Primary Mathematics - Number Recognition
  {
    id: 'primary-math-009',
    type: 'mcq',
    question: 'Which is the smallest number?',
    options: ['5', '2', '8', '10'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Numbers',
    explanation: '2 is smaller than 5, 8, and 10',
    source: 'practice',
  },
  {
    id: 'primary-math-010',
    type: 'mcq',
    question: 'What is 3 + 4 + 2?',
    options: ['7', '8', '9', '10'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Addition',
    explanation: '3 + 4 = 7, then 7 + 2 = 9',
    source: 'practice',
  },

  // ============================================
  // Primary 1 - Number Recognition & Counting
  // ============================================
  {
    id: 'primary-math-011',
    type: 'mcq',
    question: 'What number comes before 5?',
    options: ['3', '4', '6', '7'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Numbers',
    explanation: 'The number before 5 is 4',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-012',
    type: 'mcq',
    question: 'How many fingers are on one hand?',
    options: ['4', '5', '6', '10'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Counting',
    explanation: 'One hand has 5 fingers',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-013',
    type: 'mcq',
    question: 'Count: How many apples? 🍎🍎🍎',
    options: ['2', '3', '4', '5'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Counting',
    explanation: 'There are 3 apples',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-014',
    type: 'mcq',
    question: 'Which number is the largest?',
    options: ['3', '7', '5', '2'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Numbers',
    explanation: '7 is larger than 3, 5, and 2',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-015',
    type: 'mcq',
    question: 'What is 1 + 1?',
    options: ['1', '2', '3', '4'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Addition',
    explanation: '1 + 1 = 2',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-016',
    type: 'mcq',
    question: 'What is 6 - 2?',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Subtraction',
    explanation: '6 - 2 = 4',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-017',
    type: 'mcq',
    question: 'What is 4 + 3?',
    options: ['6', '7', '8', '9'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Addition',
    explanation: '4 + 3 = 7',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-018',
    type: 'mcq',
    question: 'What is 9 - 5?',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Subtraction',
    explanation: '9 - 5 = 4',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-019',
    type: 'mcq',
    question: 'How many corners does a rectangle have?',
    options: ['2', '3', '4', '5'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Shapes',
    explanation: 'A rectangle has 4 corners',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-020',
    type: 'mcq',
    question: 'What shape has 3 corners?',
    options: ['Square', 'Circle', 'Triangle', 'Rectangle'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Shapes',
    explanation: 'A triangle has 3 corners',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 2 - Addition & Subtraction (up to 20)
  // ============================================
  {
    id: 'primary-math-021',
    type: 'mcq',
    question: 'What is 7 + 8?',
    options: ['14', '15', '16', '17'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Addition',
    explanation: '7 + 8 = 15',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-022',
    type: 'mcq',
    question: 'What is 15 - 7?',
    options: ['7', '8', '9', '10'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Subtraction',
    explanation: '15 - 7 = 8',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-023',
    type: 'mcq',
    question: 'What is 9 + 6?',
    options: ['14', '15', '16', '17'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Addition',
    explanation: '9 + 6 = 15',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-024',
    type: 'mcq',
    question: 'What is 18 - 9?',
    options: ['8', '9', '10', '11'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Subtraction',
    explanation: '18 - 9 = 9',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-025',
    type: 'mcq',
    question: 'What is 4 × 3?',
    options: ['10', '11', '12', '13'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Multiplication',
    explanation: '4 × 3 = 12',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-026',
    type: 'mcq',
    question: 'What is 12 ÷ 3?',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Division',
    explanation: '12 ÷ 3 = 4',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-027',
    type: 'mcq',
    question: 'What is 6 × 2?',
    options: ['10', '12', '14', '16'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Multiplication',
    explanation: '6 × 2 = 12',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-028',
    type: 'mcq',
    question: 'What is 16 ÷ 4?',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Division',
    explanation: '16 ÷ 4 = 4',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-029',
    type: 'mcq',
    question: 'How many days are in a week?',
    options: ['5', '6', '7', '8'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Time',
    explanation: 'There are 7 days in a week',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-030',
    type: 'mcq',
    question: 'How many months are in a year?',
    options: ['10', '11', '12', '13'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Time',
    explanation: 'There are 12 months in a year',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 3 - Multiplication Tables & Division
  // ============================================
  {
    id: 'primary-math-031',
    type: 'mcq',
    question: 'What is 3 × 4?',
    options: ['10', '12', '14', '16'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Multiplication',
    explanation: '3 × 4 = 12',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-032',
    type: 'mcq',
    question: 'What is 5 × 5?',
    options: ['20', '25', '30', '35'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Multiplication',
    explanation: '5 × 5 = 25',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-033',
    type: 'mcq',
    question: 'What is 7 × 3?',
    options: ['20', '21', '22', '23'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Multiplication',
    explanation: '7 × 3 = 21',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-034',
    type: 'mcq',
    question: 'What is 20 ÷ 5?',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Division',
    explanation: '20 ÷ 5 = 4',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-035',
    type: 'mcq',
    question: 'What is 24 ÷ 6?',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Division',
    explanation: '24 ÷ 6 = 4',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-036',
    type: 'mcq',
    question: 'What is 8 × 4?',
    options: ['30', '32', '34', '36'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Multiplication',
    explanation: '8 × 4 = 32',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-037',
    type: 'mcq',
    question: 'What is half of 10?',
    options: ['4', '5', '6', '7'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Fractions',
    explanation: 'Half of 10 is 5 (10 ÷ 2 = 5)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-038',
    type: 'mcq',
    question: 'What is a quarter of 12?',
    options: ['2', '3', '4', '5'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Fractions',
    explanation: 'A quarter of 12 is 3 (12 ÷ 4 = 3)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-039',
    type: 'mcq',
    question: 'If a pencil costs 5 cedis, how much do 3 pencils cost?',
    options: ['10 cedis', '15 cedis', '20 cedis', '25 cedis'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Word Problems',
    explanation: '3 pencils × 5 cedis = 15 cedis',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-040',
    type: 'mcq',
    question: 'How many minutes are in one hour?',
    options: ['50', '60', '70', '80'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Time',
    explanation: 'There are 60 minutes in one hour',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 4 - Fractions, Decimals & Measurement
  // ============================================
  {
    id: 'primary-math-041',
    type: 'mcq',
    question: 'What is 1/2 + 1/2?',
    options: ['1/2', '1', '3/2', '2'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Fractions',
    explanation: '1/2 + 1/2 = 2/2 = 1',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-042',
    type: 'mcq',
    question: 'What is 1/4 + 1/4?',
    options: ['1/4', '1/2', '3/4', '1'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Fractions',
    explanation: '1/4 + 1/4 = 2/4 = 1/2',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-043',
    type: 'mcq',
    question: 'What is 0.5 + 0.3?',
    options: ['0.7', '0.8', '0.9', '1.0'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Decimals',
    explanation: '0.5 + 0.3 = 0.8',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-044',
    type: 'mcq',
    question: 'What is 1.2 - 0.5?',
    options: ['0.6', '0.7', '0.8', '0.9'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Decimals',
    explanation: '1.2 - 0.5 = 0.7',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-045',
    type: 'mcq',
    question: 'How many centimeters are in 1 meter?',
    options: ['50', '100', '150', '200'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Measurement',
    explanation: '1 meter = 100 centimeters',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-046',
    type: 'mcq',
    question: 'How many grams are in 1 kilogram?',
    options: ['500', '1000', '1500', '2000'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Measurement',
    explanation: '1 kilogram = 1000 grams',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-047',
    type: 'mcq',
    question: 'What is the perimeter of a square with sides of 5 cm?',
    options: ['15 cm', '20 cm', '25 cm', '30 cm'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Geometry',
    explanation: 'Perimeter = 4 × side = 4 × 5 = 20 cm',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-048',
    type: 'mcq',
    question: 'What is the area of a rectangle 4 cm long and 3 cm wide?',
    options: ['10 cm²', '12 cm²', '14 cm²', '16 cm²'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Geometry',
    explanation: 'Area = length × width = 4 × 3 = 12 cm²',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-049',
    type: 'mcq',
    question: 'What is 25 × 4?',
    options: ['90', '100', '110', '120'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Multiplication',
    explanation: '25 × 4 = 100',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-050',
    type: 'mcq',
    question: 'What is 48 ÷ 6?',
    options: ['6', '7', '8', '9'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Division',
    explanation: '48 ÷ 6 = 8',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 5 - Multi-digit Operations & Percentages
  // ============================================
  {
    id: 'primary-math-051',
    type: 'mcq',
    question: 'What is 234 + 156?',
    options: ['380', '390', '400', '410'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Addition',
    explanation: '234 + 156 = 390',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-052',
    type: 'mcq',
    question: 'What is 500 - 237?',
    options: ['260', '263', '267', '273'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Subtraction',
    explanation: '500 - 237 = 263',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-053',
    type: 'mcq',
    question: 'What is 23 × 4?',
    options: ['88', '92', '96', '100'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Multiplication',
    explanation: '23 × 4 = 92',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-054',
    type: 'mcq',
    question: 'What is 84 ÷ 7?',
    options: ['10', '11', '12', '13'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Division',
    explanation: '84 ÷ 7 = 12',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-055',
    type: 'mcq',
    question: 'What is 50% of 100?',
    options: ['40', '50', '60', '70'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Percentages',
    explanation: '50% of 100 = 50',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-056',
    type: 'mcq',
    question: 'What is 25% of 80?',
    options: ['15', '20', '25', '30'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Percentages',
    explanation: '25% of 80 = 20',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-057',
    type: 'mcq',
    question: 'What is 1/3 + 1/3?',
    options: ['1/3', '2/3', '1', '4/3'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Fractions',
    explanation: '1/3 + 1/3 = 2/3',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-058',
    type: 'mcq',
    question: 'What is 3/4 - 1/4?',
    options: ['1/4', '1/2', '2/4', '3/4'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Fractions',
    explanation: '3/4 - 1/4 = 2/4 = 1/2',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-059',
    type: 'mcq',
    question: 'What is the area of a square with sides of 6 cm?',
    options: ['30 cm²', '36 cm²', '42 cm²', '48 cm²'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Geometry',
    explanation: 'Area = side × side = 6 × 6 = 36 cm²',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-060',
    type: 'mcq',
    question: 'What is the perimeter of a rectangle 8 cm long and 5 cm wide?',
    options: ['24 cm', '26 cm', '28 cm', '30 cm'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Geometry',
    explanation: 'Perimeter = 2 × (length + width) = 2 × (8 + 5) = 2 × 13 = 26 cm',
    source: 'practice',
    year: 2023,
  },

  // ============================================
  // Primary 6 - Advanced Operations & Problem Solving
  // ============================================
  {
    id: 'primary-math-061',
    type: 'mcq',
    question: 'What is 456 + 789?',
    options: ['1235', '1245', '1255', '1265'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Addition',
    explanation: '456 + 789 = 1245',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-062',
    type: 'mcq',
    question: 'What is 1000 - 347?',
    options: ['643', '653', '663', '673'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Subtraction',
    explanation: '1000 - 347 = 653',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-063',
    type: 'mcq',
    question: 'What is 34 × 12?',
    options: ['396', '408', '420', '432'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Multiplication',
    explanation: '34 × 12 = 408',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-064',
    type: 'mcq',
    question: 'What is 144 ÷ 12?',
    options: ['10', '11', '12', '13'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Division',
    explanation: '144 ÷ 12 = 12',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-065',
    type: 'mcq',
    question: 'What is 75% of 200?',
    options: ['140', '150', '160', '170'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Percentages',
    explanation: '75% of 200 = 150',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-066',
    type: 'mcq',
    question: 'What is 1/2 + 1/4?',
    options: ['2/4', '3/4', '1', '5/4'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Fractions',
    explanation: '1/2 + 1/4 = 2/4 + 1/4 = 3/4',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-067',
    type: 'mcq',
    question: 'What is 2.5 + 3.7?',
    options: ['5.8', '6.0', '6.2', '6.4'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Decimals',
    explanation: '2.5 + 3.7 = 6.2',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-068',
    type: 'mcq',
    question: 'What is 5.6 - 2.9?',
    options: ['2.5', '2.7', '2.9', '3.1'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Decimals',
    explanation: '5.6 - 2.9 = 2.7',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-069',
    type: 'mcq',
    question: 'If 3 pens cost 15 cedis, how much does 1 pen cost?',
    options: ['3 cedis', '4 cedis', '5 cedis', '6 cedis'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Word Problems',
    explanation: '15 cedis ÷ 3 pens = 5 cedis per pen',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-070',
    type: 'mcq',
    question: 'A rectangle has length 10 cm and width 6 cm. What is its area?',
    options: ['50 cm²', '60 cm²', '70 cm²', '80 cm²'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Geometry',
    explanation: 'Area = length × width = 10 × 6 = 60 cm²',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-071',
    type: 'mcq',
    question: 'What is 1/5 + 2/5?',
    options: ['2/5', '3/5', '4/5', '1'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Fractions',
    explanation: '1/5 + 2/5 = 3/5',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-072',
    type: 'mcq',
    question: 'What is 0.25 as a fraction?',
    options: ['1/2', '1/4', '1/5', '1/10'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Fractions & Decimals',
    explanation: '0.25 = 25/100 = 1/4',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-073',
    type: 'mcq',
    question: 'What is 1/2 as a decimal?',
    options: ['0.2', '0.25', '0.5', '0.75'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Fractions & Decimals',
    explanation: '1/2 = 0.5',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-074',
    type: 'mcq',
    question: 'How many sides does a pentagon have?',
    options: ['4', '5', '6', '7'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Shapes',
    explanation: 'A pentagon has 5 sides',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-075',
    type: 'mcq',
    question: 'How many sides does a hexagon have?',
    options: ['5', '6', '7', '8'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Shapes',
    explanation: 'A hexagon has 6 sides',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-076',
    type: 'mcq',
    question: 'What is 9 × 7?',
    options: ['61', '63', '65', '67'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Multiplication',
    explanation: '9 × 7 = 63',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-077',
    type: 'mcq',
    question: 'What is 6 × 8?',
    options: ['46', '48', '50', '52'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Multiplication',
    explanation: '6 × 8 = 48',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-078',
    type: 'mcq',
    question: 'What is 35 ÷ 5?',
    options: ['6', '7', '8', '9'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Division',
    explanation: '35 ÷ 5 = 7',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-079',
    type: 'mcq',
    question: 'What is 42 ÷ 6?',
    options: ['6', '7', '8', '9'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Division',
    explanation: '42 ÷ 6 = 7',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-080',
    type: 'mcq',
    question: 'What is 11 + 12?',
    options: ['21', '22', '23', '24'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Addition',
    explanation: '11 + 12 = 23',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-081',
    type: 'mcq',
    question: 'What is 19 - 11?',
    options: ['7', '8', '9', '10'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Subtraction',
    explanation: '19 - 11 = 8',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-082',
    type: 'mcq',
    question: 'What is 1 + 2 + 3 + 4?',
    options: ['8', '9', '10', '11'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Addition',
    explanation: '1 + 2 + 3 + 4 = 10',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-083',
    type: 'mcq',
    question: 'What is 20 - 5 - 3?',
    options: ['10', '11', '12', '13'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Subtraction',
    explanation: '20 - 5 = 15, then 15 - 3 = 12',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-084',
    type: 'mcq',
    question: 'What is 10% of 50?',
    options: ['4', '5', '6', '7'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Percentages',
    explanation: '10% of 50 = 5',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-085',
    type: 'mcq',
    question: 'What is 20% of 100?',
    options: ['15', '20', '25', '30'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Percentages',
    explanation: '20% of 100 = 20',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-086',
    type: 'mcq',
    question: 'What is 0.1 + 0.2?',
    options: ['0.2', '0.3', '0.4', '0.5'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Decimals',
    explanation: '0.1 + 0.2 = 0.3',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-087',
    type: 'mcq',
    question: 'What is 1.5 - 0.8?',
    options: ['0.6', '0.7', '0.8', '0.9'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Decimals',
    explanation: '1.5 - 0.8 = 0.7',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-088',
    type: 'mcq',
    question: 'How many hours are in a day?',
    options: ['20', '22', '24', '26'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Time',
    explanation: 'There are 24 hours in a day',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-089',
    type: 'mcq',
    question: 'How many seconds are in 1 minute?',
    options: ['50', '60', '70', '80'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Time',
    explanation: 'There are 60 seconds in 1 minute',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-090',
    type: 'mcq',
    question: 'What is 1/3 of 12?',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Fractions',
    explanation: '1/3 of 12 = 12 ÷ 3 = 4',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-091',
    type: 'mcq',
    question: 'What is 2/3 of 9?',
    options: ['4', '5', '6', '7'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Fractions',
    explanation: '2/3 of 9 = (2 × 9) ÷ 3 = 18 ÷ 3 = 6',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-092',
    type: 'mcq',
    question: 'What is 3 × 3 × 3?',
    options: ['25', '27', '29', '31'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Multiplication',
    explanation: '3 × 3 × 3 = 27',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-093',
    type: 'mcq',
    question: 'What is 4 × 4?',
    options: ['14', '16', '18', '20'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Multiplication',
    explanation: '4 × 4 = 16',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-094',
    type: 'mcq',
    question: 'What is 5 × 5?',
    options: ['20', '25', '30', '35'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'Multiplication',
    explanation: '5 × 5 = 25',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-095',
    type: 'mcq',
    question: 'What is 10 × 10?',
    options: ['90', '100', '110', '120'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Multiplication',
    explanation: '10 × 10 = 100',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-096',
    type: 'mcq',
    question: 'If a book has 120 pages and you read 30 pages, how many pages are left?',
    options: ['80', '90', '100', '110'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Word Problems',
    explanation: '120 - 30 = 90 pages left',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-097',
    type: 'mcq',
    question: 'A box contains 24 oranges. If you share them equally among 6 children, how many does each get?',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Division',
    explanation: '24 ÷ 6 = 4 oranges per child',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-098',
    type: 'mcq',
    question: 'What is the perimeter of a triangle with sides 5 cm, 6 cm, and 7 cm?',
    options: ['16 cm', '18 cm', '20 cm', '22 cm'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 5',
    level: 'Primary',
    topic: 'Geometry',
    explanation: 'Perimeter = 5 + 6 + 7 = 18 cm',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-099',
    type: 'mcq',
    question: 'What is 1/4 + 3/4?',
    options: ['3/4', '1', '5/4', '2'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 4',
    level: 'Primary',
    topic: 'Fractions',
    explanation: '1/4 + 3/4 = 4/4 = 1',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'primary-math-100',
    type: 'mcq',
    question: 'What is 0.75 as a fraction?',
    options: ['1/2', '2/3', '3/4', '4/5'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'Primary 6',
    level: 'Primary',
    topic: 'Fractions & Decimals',
    explanation: '0.75 = 75/100 = 3/4',
    source: 'practice',
    year: 2023,
  },
];

