// Primary Mathematics Questions
// Initial batch of questions migrated to modular ChallengeQuestion format

import type { ChallengeQuestion } from '../types';

export const primaryMathematicsQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Initial Batch)
  // ============================================

  // Primary Mathematics - Basic Operations
  {
    id: 'primary-math-001',
    type: 'mcq',
    question: 'What is 2 + 3?',
    options: ['4', '5', '6', '7'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Addition',
    explanation: '2 + 3 = 5',
    source: 'practice',
  },
  {
    id: 'primary-math-002',
    type: 'mcq',
    question: 'What is 10 - 4?',
    options: ['5', '6', '7', '8'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Subtraction',
    explanation: '10 - 4 = 6',
    source: 'practice',
  },
  {
    id: 'primary-math-003',
    type: 'mcq',
    question: 'What is 5 × 2?',
    options: ['7', '10', '12', '15'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Multiplication',
    explanation: '5 × 2 = 10',
    source: 'practice',
  },
  {
    id: 'primary-math-004',
    type: 'mcq',
    question: 'What is 8 ÷ 2?',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Division',
    explanation: '8 ÷ 2 = 4',
    source: 'practice',
  },
  {
    id: 'primary-math-005',
    type: 'mcq',
    question: 'Which number comes after 9?',
    options: ['8', '9', '10', '11'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Numbers',
    explanation: 'After 9 comes 10',
    source: 'practice',
  },

  // Primary Mathematics - Shapes & Geometry
  {
    id: 'primary-math-006',
    type: 'mcq',
    question: 'How many sides does a triangle have?',
    options: ['2', '3', '4', '5'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Shapes',
    explanation: 'A triangle has 3 sides',
    source: 'practice',
  },
  {
    id: 'primary-math-007',
    type: 'mcq',
    question: 'How many sides does a square have?',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Shapes',
    explanation: 'A square has 4 equal sides',
    source: 'practice',
  },
  {
    id: 'primary-math-008',
    type: 'mcq',
    question: 'What shape has no sides?',
    options: ['Triangle', 'Square', 'Circle', 'Rectangle'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Shapes',
    explanation: 'A circle is round with no straight sides',
    source: 'practice',
  },

  // Primary Mathematics - Number Recognition
  {
    id: 'primary-math-009',
    type: 'mcq',
    question: 'Which is the smallest number?',
    options: ['5', '2', '8', '10'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Numbers',
    explanation: '2 is smaller than 5, 8, and 10',
    source: 'practice',
  },
  {
    id: 'primary-math-010',
    type: 'mcq',
    question: 'What is 3 + 4 + 2?',
    options: ['7', '8', '9', '10'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Addition',
    explanation: '3 + 4 = 7, then 7 + 2 = 9',
    source: 'practice',
  },
];

