// Primary Science Questions
// Initial batch of questions migrated to modular ChallengeQuestion format

import type { ChallengeQuestion } from '../types';

export const primaryScienceQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Initial Batch)
  // ============================================

  // Primary Science - Animals
  {
    id: 'primary-sci-001',
    type: 'mcq',
    question: 'Which animal lives on land?',
    options: ['Fish', 'Bird', 'Dog', 'Shark'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'Dogs live on land',
    source: 'practice',
  },
  {
    id: 'primary-sci-002',
    type: 'mcq',
    question: 'How many legs does a cat have?',
    options: ['2', '3', '4', '6'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'A cat has 4 legs',
    source: 'practice',
  },
  {
    id: 'primary-sci-003',
    type: 'mcq',
    question: 'Which animal can swim?',
    options: ['Dog', 'Fish', 'Bird', 'Cat'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'Fish can swim',
    source: 'practice',
  },
  {
    id: 'primary-sci-004',
    type: 'mcq',
    question: 'Which animal can fly?',
    options: ['Fish', 'Bird', 'Dog', 'Cat'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'Birds can fly',
    source: 'practice',
  },
  {
    id: 'primary-sci-005',
    type: 'mcq',
    question: 'How many legs does a dog have?',
    options: ['2', '3', '4', '6'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Animals',
    explanation: 'A dog has 4 legs',
    source: 'practice',
  },

  // Primary Science - Body Parts
  {
    id: 'primary-sci-006',
    type: 'mcq',
    question: 'What do we use to see?',
    options: ['Ears', 'Eyes', 'Nose', 'Mouth'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Body Parts',
    explanation: 'We use our eyes to see',
    source: 'practice',
  },
  {
    id: 'primary-sci-007',
    type: 'mcq',
    question: 'What do we use to hear?',
    options: ['Eyes', 'Ears', 'Nose', 'Mouth'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Body Parts',
    explanation: 'We use our ears to hear',
    source: 'practice',
  },
  {
    id: 'primary-sci-008',
    type: 'mcq',
    question: 'What do we use to smell?',
    options: ['Eyes', 'Ears', 'Nose', 'Mouth'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Body Parts',
    explanation: 'We use our nose to smell',
    source: 'practice',
  },

  // Primary Science - Plants
  {
    id: 'primary-sci-009',
    type: 'mcq',
    question: 'What do plants need to make food?',
    options: ['Water only', 'Sunlight only', 'Water and sunlight', 'Nothing'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Plants',
    explanation: 'Plants need both water and sunlight to make food',
    source: 'practice',
  },
  {
    id: 'primary-sci-010',
    type: 'mcq',
    question: 'What do plants grow from?',
    options: ['Rocks', 'Seeds', 'Water', 'Air'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Plants',
    explanation: 'Plants grow from seeds',
    source: 'practice',
  },
];

