// Primary Social Studies Questions
// Initial batch of questions migrated to modular ChallengeQuestion format

import type { ChallengeQuestion } from '../types';

export const primarySocialStudiesQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Initial Batch)
  // ============================================

  // Primary Social Studies - Geography
  {
    id: 'primary-soc-001',
    type: 'mcq',
    question: 'What is the name of your country?',
    options: ['Ghana', 'Nigeria', 'Sierra Leone', 'All of the above'],
    correctAnswer: 3,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Geography',
    explanation: 'All are countries in West Africa',
    source: 'practice',
  },
  {
    id: 'primary-soc-002',
    type: 'mcq',
    question: 'The capital city of Ghana is...',
    options: ['Kumasi', 'Accra', 'Tamale', 'Cape Coast'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Geography',
    explanation: 'Accra is the capital city of Ghana',
    source: 'practice',
  },

  // Primary Social Studies - Citizenship
  {
    id: 'primary-soc-003',
    type: 'mcq',
    question: 'What do we call the leader of a country?',
    options: ['Teacher', 'President', 'Doctor', 'Farmer'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Citizenship',
    explanation: 'The leader of a country is called the President',
    source: 'practice',
  },
  {
    id: 'primary-soc-004',
    type: 'mcq',
    question: 'Who is the head of a family?',
    options: ['Mother', 'Father', 'Uncle', 'Aunt'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Citizenship',
    explanation: 'Traditionally, the father is the head of the family',
    source: 'practice',
  },
  {
    id: 'primary-soc-005',
    type: 'mcq',
    question: 'We should respect our...',
    options: ['Friends only', 'Teachers and parents', 'Nobody', 'Only ourselves'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Citizenship',
    explanation: 'We should respect our teachers and parents',
    source: 'practice',
  },

  // Primary Social Studies - Culture
  {
    id: 'primary-soc-006',
    type: 'mcq',
    question: 'Which of these is a traditional food?',
    options: ['Pizza', 'Banku', 'Burger', 'Hot dog'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Culture',
    explanation: 'Banku is a traditional Ghanaian food',
    source: 'practice',
  },
  {
    id: 'primary-soc-007',
    type: 'mcq',
    question: 'We celebrate Independence Day on...',
    options: ['January 1st', 'March 6th', 'December 25th', 'June 1st'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'Primary 3',
    level: 'Primary',
    topic: 'History',
    explanation: 'Ghana celebrates Independence Day on March 6th',
    source: 'practice',
  },
  {
    id: 'primary-soc-008',
    type: 'mcq',
    question: 'Which of these is a national symbol?',
    options: ['Flag', 'Car', 'House', 'School'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 2',
    level: 'Primary',
    topic: 'Citizenship',
    explanation: 'The flag is a national symbol',
    source: 'practice',
  },
  {
    id: 'primary-soc-009',
    type: 'mcq',
    question: 'We should keep our environment...',
    options: ['Dirty', 'Clean', 'Messy', 'Untidy'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Environment',
    explanation: 'We should keep our environment clean',
    source: 'practice',
  },
  {
    id: 'primary-soc-010',
    type: 'mcq',
    question: 'Which of these helps us learn?',
    options: ['School', 'Playground', 'Market', 'Park'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'Primary 1',
    level: 'Primary',
    topic: 'Education',
    explanation: 'School is where we go to learn',
    source: 'practice',
  },
];

