import type { ChallengeQuestion } from '../types';

/**
 * JHS Arabic Question Bank
 * BECE Arabic
 * Topics: Alphabet, Greetings, Vocabulary, Grammar, Numbers, Colors, Days, Months, Reading, Quran
 */

export const jhsArabicQuestions: ChallengeQuestion[] = [
  // ============================================
  // Arabic Alphabet & Pronunciation
  // ============================================
  {
    id: 'jhs-ar-001',
    type: 'mcq',
    question: 'How many letters are in the Arabic alphabet?',
    options: ['26', '28', '30', '32'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Alphabet',
    explanation: 'The Arabic alphabet has 28 letters.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-002',
    type: 'mcq',
    question: 'What is the first letter of the Arabic alphabet?',
    options: ['ب (Ba)', 'أ (Alif)', 'ت (Ta)', 'ث (Tha)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Alphabet',
    explanation: 'أ (Alif) is the first letter of the Arabic alphabet.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-003',
    type: 'mcq',
    question: 'What is the last letter of the Arabic alphabet?',
    options: ['ي (Ya)', 'و (Waw)', 'ه (Ha)', 'ن (Nun)'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Alphabet',
    explanation: 'ي (Ya) is the last letter of the Arabic alphabet.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-004',
    type: 'mcq',
    question: 'Which Arabic letter is pronounced like "B" in English?',
    options: ['ت (Ta)', 'ب (Ba)', 'ث (Tha)', 'ج (Jeem)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Alphabet',
    explanation: 'ب (Ba) is pronounced like "B" in English.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-005',
    type: 'mcq',
    question: 'Which Arabic letter is pronounced like "T" in English?',
    options: ['ث (Tha)', 'ت (Ta)', 'ط (Taa)', 'ظ (Dhaa)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Alphabet',
    explanation: 'ت (Ta) is pronounced like "T" in English.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-006',
    type: 'mcq',
    question: 'What is the Arabic letter for "J" sound?',
    options: ['ح (Haa)', 'خ (Khaa)', 'ج (Jeem)', 'ذ (Dhal)'],
    correctAnswer: 2,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Alphabet',
    explanation: 'ج (Jeem) is pronounced like "J" in English.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-007',
    type: 'mcq',
    question: 'How many forms can Arabic letters take?',
    options: ['Two', 'Three', 'Four', 'Five'],
    correctAnswer: 2,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Alphabet',
    explanation: 'Arabic letters can take four forms: initial, medial, final, and isolated.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-008',
    type: 'mcq',
    question: 'What direction is Arabic written?',
    options: ['Left to right', 'Right to left', 'Top to bottom', 'Bottom to top'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Alphabet',
    explanation: 'Arabic is written from right to left.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-009',
    type: 'mcq',
    question: 'Which Arabic letters do not connect to the following letter?',
    options: ['All letters', 'أ, د, ذ, ر, ز, و, ا', 'ب, ت, ث, ج, ح, خ', 'None'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Alphabet',
    explanation: 'The letters أ, د, ذ, ر, ز, و, ا do not connect to the following letter.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-010',
    type: 'mcq',
    question: 'What are the three short vowels in Arabic called?',
    options: ['Fatha, Kasra, Damma', 'Sukun, Shadda, Tanween', 'Hamza, Alif, Waw', 'None of the above'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Alphabet',
    explanation: 'The three short vowels are Fatha (َ), Kasra (ِ), and Damma (ُ).',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Greetings & Common Phrases
  // ============================================
  {
    id: 'jhs-ar-011',
    type: 'mcq',
    question: 'How do you say "Hello" in Arabic?',
    options: ['السلام عليكم (As-salamu alaykum)', 'مع السلامة (Ma\'a as-salama)', 'شكراً (Shukran)', 'مرحباً (Marhaban)'],
    correctAnswer: 3,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Greetings',
    explanation: 'مرحباً (Marhaban) means hello or welcome.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-012',
    type: 'mcq',
    question: 'What is the Islamic greeting meaning "Peace be upon you"?',
    options: ['مرحباً (Marhaban)', 'السلام عليكم (As-salamu alaykum)', 'أهلاً وسهلاً (Ahlan wa sahlan)', 'صباح الخير (Sabah al-khair)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Greetings',
    explanation: 'السلام عليكم (As-salamu alaykum) means "Peace be upon you" and is the Islamic greeting.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-013',
    type: 'mcq',
    question: 'What is the response to "السلام عليكم"?',
    options: ['السلام عليكم', 'وعليكم السلام', 'مع السلامة', 'شكراً'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Greetings',
    explanation: 'وعليكم السلام (Wa alaykum as-salam) means "And upon you peace" - the response to the greeting.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-014',
    type: 'mcq',
    question: 'How do you say "Good morning" in Arabic?',
    options: ['مساء الخير (Masa\' al-khair)', 'صباح الخير (Sabah al-khair)', 'ليلة سعيدة (Layla sa\'ida)', 'يوم سعيد (Yawm sa\'id)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Greetings',
    explanation: 'صباح الخير (Sabah al-khair) means good morning.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-015',
    type: 'mcq',
    question: 'How do you say "Good evening" in Arabic?',
    options: ['صباح الخير (Sabah al-khair)', 'مساء الخير (Masa\' al-khair)', 'ليلة سعيدة (Layla sa\'ida)', 'مع السلامة (Ma\'a as-salama)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Greetings',
    explanation: 'مساء الخير (Masa\' al-khair) means good evening.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-016',
    type: 'mcq',
    question: 'How do you say "Goodbye" in Arabic?',
    options: ['السلام عليكم', 'مع السلامة (Ma\'a as-salama)', 'شكراً (Shukran)', 'مرحباً (Marhaban)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Greetings',
    explanation: 'مع السلامة (Ma\'a as-salama) means goodbye or "go with peace".',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-017',
    type: 'mcq',
    question: 'What does "أهلاً وسهلاً" (Ahlan wa sahlan) mean?',
    options: ['Goodbye', 'Welcome', 'Thank you', 'Please'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Greetings',
    explanation: 'أهلاً وسهلاً (Ahlan wa sahlan) means welcome.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-018',
    type: 'mcq',
    question: 'How do you say "Thank you" in Arabic?',
    options: ['من فضلك (Min fadlik)', 'شكراً (Shukran)', 'عفواً (Afwan)', 'مع السلامة (Ma\'a as-salama)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Common Phrases',
    explanation: 'شكراً (Shukran) means thank you.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-019',
    type: 'mcq',
    question: 'What is the response to "شكراً" (Shukran)?',
    options: ['شكراً', 'عفواً (Afwan)', 'من فضلك (Min fadlik)', 'السلام عليكم'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Common Phrases',
    explanation: 'عفواً (Afwan) means "you\'re welcome" or "excuse me".',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-020',
    type: 'mcq',
    question: 'How do you say "Please" in Arabic?',
    options: ['شكراً (Shukran)', 'عفواً (Afwan)', 'من فضلك (Min fadlik)', 'مع السلامة (Ma\'a as-salama)'],
    correctAnswer: 2,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Common Phrases',
    explanation: 'من فضلك (Min fadlik) means please.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Numbers
  // ============================================
  {
    id: 'jhs-ar-021',
    type: 'mcq',
    question: 'How do you say "one" in Arabic?',
    options: ['اثنان (Ithnan)', 'واحد (Wahid)', 'ثلاثة (Thalatha)', 'أربعة (Arba\'a)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'واحد (Wahid) means one.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-022',
    type: 'mcq',
    question: 'How do you say "two" in Arabic?',
    options: ['واحد (Wahid)', 'اثنان (Ithnan)', 'ثلاثة (Thalatha)', 'أربعة (Arba\'a)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'اثنان (Ithnan) means two.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-023',
    type: 'mcq',
    question: 'How do you say "three" in Arabic?',
    options: ['اثنان (Ithnan)', 'ثلاثة (Thalatha)', 'أربعة (Arba\'a)', 'خمسة (Khamsa)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'ثلاثة (Thalatha) means three.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-024',
    type: 'mcq',
    question: 'How do you say "five" in Arabic?',
    options: ['أربعة (Arba\'a)', 'خمسة (Khamsa)', 'ستة (Sitta)', 'سبعة (Sab\'a)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'خمسة (Khamsa) means five.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-025',
    type: 'mcq',
    question: 'How do you say "ten" in Arabic?',
    options: ['ثمانية (Thamaniya)', 'تسعة (Tis\'a)', 'عشرة (Ashara)', 'أحد عشر (Ahad ashar)'],
    correctAnswer: 2,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'عشرة (Ashara) means ten.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-026',
    type: 'mcq',
    question: 'What is the Arabic word for "twenty"?',
    options: ['عشرون (Ishrun)', 'ثلاثون (Thalathun)', 'عشرين (Ishreen)', 'عشرون (Ishrun)'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'عشرون (Ishrun) means twenty.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-027',
    type: 'mcq',
    question: 'What is the Arabic word for "hundred"?',
    options: ['مائة (Mi\'a)', 'ألف (Alf)', 'خمسون (Khamsun)', 'ثلاثون (Thalathun)'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'مائة (Mi\'a) means hundred.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-028',
    type: 'mcq',
    question: 'What is the Arabic word for "thousand"?',
    options: ['مائة (Mi\'a)', 'ألف (Alf)', 'مليون (Milyun)', 'مليار (Milyar)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'ألف (Alf) means thousand.',
    source: 'practice',
    year: 2019,
  },

  // ============================================
  // Colors
  // ============================================
  {
    id: 'jhs-ar-029',
    type: 'mcq',
    question: 'How do you say "red" in Arabic?',
    options: ['أحمر (Ahmar)', 'أزرق (Azraq)', 'أخضر (Akhdar)', 'أصفر (Asfar)'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Colors',
    explanation: 'أحمر (Ahmar) means red.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-030',
    type: 'mcq',
    question: 'How do you say "blue" in Arabic?',
    options: ['أحمر (Ahmar)', 'أزرق (Azraq)', 'أخضر (Akhdar)', 'أبيض (Abyad)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Colors',
    explanation: 'أزرق (Azraq) means blue.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-031',
    type: 'mcq',
    question: 'How do you say "green" in Arabic?',
    options: ['أزرق (Azraq)', 'أخضر (Akhdar)', 'أصفر (Asfar)', 'أسود (Aswad)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Colors',
    explanation: 'أخضر (Akhdar) means green.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-032',
    type: 'mcq',
    question: 'How do you say "white" in Arabic?',
    options: ['أسود (Aswad)', 'أبيض (Abyad)', 'أصفر (Asfar)', 'بني (Bunni)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Colors',
    explanation: 'أبيض (Abyad) means white.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-033',
    type: 'mcq',
    question: 'How do you say "black" in Arabic?',
    options: ['أبيض (Abyad)', 'أسود (Aswad)', 'أحمر (Ahmar)', 'رمادي (Ramadi)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Colors',
    explanation: 'أسود (Aswad) means black.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-034',
    type: 'mcq',
    question: 'How do you say "yellow" in Arabic?',
    options: ['أخضر (Akhdar)', 'أصفر (Asfar)', 'أزرق (Azraq)', 'بني (Bunni)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Colors',
    explanation: 'أصفر (Asfar) means yellow.',
    source: 'practice',
    year: 2019,
  },

  // ============================================
  // Days of the Week
  // ============================================
  {
    id: 'jhs-ar-035',
    type: 'mcq',
    question: 'How do you say "Monday" in Arabic?',
    options: ['الاثنين (Al-ithnayn)', 'الثلاثاء (Al-thulatha)', 'الأربعاء (Al-arbi\'a)', 'الخميس (Al-khamis)'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Days',
    explanation: 'الاثنين (Al-ithnayn) means Monday.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-036',
    type: 'mcq',
    question: 'How do you say "Friday" in Arabic?',
    options: ['الخميس (Al-khamis)', 'الجمعة (Al-jumu\'a)', 'السبت (As-sabt)', 'الأحد (Al-ahad)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Days',
    explanation: 'الجمعة (Al-jumu\'a) means Friday, the holy day for Muslims.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-037',
    type: 'mcq',
    question: 'How do you say "Sunday" in Arabic?',
    options: ['السبت (As-sabt)', 'الأحد (Al-ahad)', 'الاثنين (Al-ithnayn)', 'الثلاثاء (Al-thulatha)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Days',
    explanation: 'الأحد (Al-ahad) means Sunday.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-038',
    type: 'mcq',
    question: 'What is the Arabic word for "day"?',
    options: ['ليلة (Layla)', 'يوم (Yawm)', 'أسبوع (Usbu\')', 'شهر (Shahr)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Days',
    explanation: 'يوم (Yawm) means day.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-039',
    type: 'mcq',
    question: 'What is the Arabic word for "week"?',
    options: ['يوم (Yawm)', 'أسبوع (Usbu\')', 'شهر (Shahr)', 'سنة (Sana)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Days',
    explanation: 'أسبوع (Usbu\') means week.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Months
  // ============================================
  {
    id: 'jhs-ar-040',
    type: 'mcq',
    question: 'What is the Arabic word for "month"?',
    options: ['يوم (Yawm)', 'أسبوع (Usbu\')', 'شهر (Shahr)', 'سنة (Sana)'],
    correctAnswer: 2,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Months',
    explanation: 'شهر (Shahr) means month.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-041',
    type: 'mcq',
    question: 'What is the Arabic word for "year"?',
    options: ['شهر (Shahr)', 'سنة (Sana)', 'أسبوع (Usbu\')', 'يوم (Yawm)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Months',
    explanation: 'سنة (Sana) means year.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-042',
    type: 'mcq',
    question: 'What is "Ramadan" in Arabic?',
    options: ['رمضان (Ramadan)', 'شوال (Shawwal)', 'ذو الحجة (Dhul Hijjah)', 'محرم (Muharram)'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Months',
    explanation: 'رمضان (Ramadan) is the holy month of fasting in Islam.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Family Members
  // ============================================
  {
    id: 'jhs-ar-043',
    type: 'mcq',
    question: 'How do you say "father" in Arabic?',
    options: ['أم (Umm)', 'أب (Ab)', 'أخ (Akh)', 'أخت (Ukht)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Family',
    explanation: 'أب (Ab) means father.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-044',
    type: 'mcq',
    question: 'How do you say "mother" in Arabic?',
    options: ['أب (Ab)', 'أم (Umm)', 'أخ (Akh)', 'ابن (Ibn)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Family',
    explanation: 'أم (Umm) means mother.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-045',
    type: 'mcq',
    question: 'How do you say "brother" in Arabic?',
    options: ['أخت (Ukht)', 'أخ (Akh)', 'ابن (Ibn)', 'بنت (Bint)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Family',
    explanation: 'أخ (Akh) means brother.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-046',
    type: 'mcq',
    question: 'How do you say "sister" in Arabic?',
    options: ['أخ (Akh)', 'أخت (Ukht)', 'ابن (Ibn)', 'بنت (Bint)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Family',
    explanation: 'أخت (Ukht) means sister.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-047',
    type: 'mcq',
    question: 'How do you say "son" in Arabic?',
    options: ['بنت (Bint)', 'ابن (Ibn)', 'أخ (Akh)', 'أخت (Ukht)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Family',
    explanation: 'ابن (Ibn) means son.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-048',
    type: 'mcq',
    question: 'How do you say "daughter" in Arabic?',
    options: ['ابن (Ibn)', 'بنت (Bint)', 'أخت (Ukht)', 'أم (Umm)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Family',
    explanation: 'بنت (Bint) means daughter.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Common Vocabulary
  // ============================================
  {
    id: 'jhs-ar-049',
    type: 'mcq',
    question: 'How do you say "book" in Arabic?',
    options: ['قلم (Qalam)', 'كتاب (Kitab)', 'مدرسة (Madrasa)', 'طالب (Talib)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'كتاب (Kitab) means book.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-050',
    type: 'mcq',
    question: 'How do you say "pen" in Arabic?',
    options: ['كتاب (Kitab)', 'قلم (Qalam)', 'ورقة (Waraqa)', 'مدرسة (Madrasa)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'قلم (Qalam) means pen.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-051',
    type: 'mcq',
    question: 'How do you say "school" in Arabic?',
    options: ['مدرسة (Madrasa)', 'بيت (Bayt)', 'كتاب (Kitab)', 'طالب (Talib)'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'مدرسة (Madrasa) means school.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-052',
    type: 'mcq',
    question: 'How do you say "student" in Arabic?',
    options: ['معلم (Mu\'allim)', 'طالب (Talib)', 'كتاب (Kitab)', 'مدرسة (Madrasa)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'طالب (Talib) means student.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-053',
    type: 'mcq',
    question: 'How do you say "teacher" in Arabic?',
    options: ['طالب (Talib)', 'معلم (Mu\'allim)', 'مدرسة (Madrasa)', 'كتاب (Kitab)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'معلم (Mu\'allim) means teacher.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-054',
    type: 'mcq',
    question: 'How do you say "house" in Arabic?',
    options: ['مدرسة (Madrasa)', 'بيت (Bayt)', 'كتاب (Kitab)', 'قلم (Qalam)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'بيت (Bayt) means house or home.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-055',
    type: 'mcq',
    question: 'How do you say "water" in Arabic?',
    options: ['طعام (Ta\'am)', 'ماء (Ma\')', 'خبز (Khubz)', 'لبن (Laban)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'ماء (Ma\') means water.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-056',
    type: 'mcq',
    question: 'How do you say "food" in Arabic?',
    options: ['ماء (Ma\')', 'طعام (Ta\'am)', 'خبز (Khubz)', 'فاكهة (Fakiha)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'طعام (Ta\'am) means food.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-057',
    type: 'mcq',
    question: 'How do you say "bread" in Arabic?',
    options: ['ماء (Ma\')', 'خبز (Khubz)', 'لبن (Laban)', 'فاكهة (Fakiha)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'خبز (Khubz) means bread.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-058',
    type: 'mcq',
    question: 'How do you say "name" in Arabic?',
    options: ['اسم (Ism)', 'شخص (Shakhs)', 'رجل (Rajul)', 'امرأة (Imra\'a)'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'اسم (Ism) means name.',
    source: 'practice',
    year: 2019,
  },

  // ============================================
  // Basic Grammar
  // ============================================
  {
    id: 'jhs-ar-059',
    type: 'mcq',
    question: 'What is "I" in Arabic?',
    options: ['أنت (Anta)', 'أنا (Ana)', 'هو (Huwa)', 'هي (Hiya)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'أنا (Ana) means I.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-060',
    type: 'mcq',
    question: 'What is "you" (masculine) in Arabic?',
    options: ['أنا (Ana)', 'أنت (Anta)', 'أنتِ (Anti)', 'هو (Huwa)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'أنت (Anta) means you (masculine).',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-061',
    type: 'mcq',
    question: 'What is "he" in Arabic?',
    options: ['هي (Hiya)', 'هو (Huwa)', 'أنت (Anta)', 'أنا (Ana)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'هو (Huwa) means he.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-062',
    type: 'mcq',
    question: 'What is "she" in Arabic?',
    options: ['هو (Huwa)', 'هي (Hiya)', 'أنتِ (Anti)', 'أنا (Ana)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'هي (Hiya) means she.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-063',
    type: 'mcq',
    question: 'What is "we" in Arabic?',
    options: ['هم (Hum)', 'نحن (Nahnu)', 'أنتم (Antum)', 'أنتن (Antunna)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'نحن (Nahnu) means we.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-064',
    type: 'mcq',
    question: 'What is "they" (masculine) in Arabic?',
    options: ['نحن (Nahnu)', 'هم (Hum)', 'أنتم (Antum)', 'هن (Hunna)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'هم (Hum) means they (masculine).',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-065',
    type: 'mcq',
    question: 'What does "هذا" (Hatha) mean?',
    options: ['That (masculine)', 'This (masculine)', 'That (feminine)', 'This (feminine)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'هذا (Hatha) means this (masculine).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-066',
    type: 'mcq',
    question: 'What does "هذه" (Hathihi) mean?',
    options: ['This (masculine)', 'This (feminine)', 'That (masculine)', 'That (feminine)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'هذه (Hathihi) means this (feminine).',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-067',
    type: 'mcq',
    question: 'What is the Arabic word for "and"?',
    options: ['أو (Aw)', 'و (Wa)', 'لكن (Lakin)', 'أيضاً (Aydan)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'و (Wa) means and.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-068',
    type: 'mcq',
    question: 'What is the Arabic word for "or"?',
    options: ['و (Wa)', 'أو (Aw)', 'لكن (Lakin)', 'لأن (Li\'anna)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'أو (Aw) means or.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Verbs - Basic
  // ============================================
  {
    id: 'jhs-ar-069',
    type: 'mcq',
    question: 'How do you say "I go" in Arabic?',
    options: ['أذهب (Adhhab)', 'تذهب (Tadhhab)', 'يذهب (Yadhhab)', 'نذهب (Nadhhab)'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Verbs',
    explanation: 'أذهب (Adhhab) means I go.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-070',
    type: 'mcq',
    question: 'How do you say "I read" in Arabic?',
    options: ['أقرأ (Aqra\')', 'تقرأ (Taqra\')', 'يقرأ (Yaqra\')', 'نقرأ (Naqra\')'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Verbs',
    explanation: 'أقرأ (Aqra\') means I read.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-071',
    type: 'mcq',
    question: 'How do you say "I write" in Arabic?',
    options: ['أكتب (Aktub)', 'تكتب (Taktub)', 'يكتب (Yaktub)', 'نكتب (Naktub)'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Verbs',
    explanation: 'أكتب (Aktub) means I write.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-072',
    type: 'mcq',
    question: 'How do you say "I eat" in Arabic?',
    options: ['أكل (Akil)', 'تأكل (Ta\'kul)', 'يأكل (Ya\'kul)', 'نأكل (Na\'kul)'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Verbs',
    explanation: 'أكل (Akil) means I eat.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-073',
    type: 'mcq',
    question: 'How do you say "I drink" in Arabic?',
    options: ['أشرب (Ashrab)', 'تشرب (Tashrab)', 'يشرب (Yashrab)', 'نشرب (Nashrab)'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Verbs',
    explanation: 'أشرب (Ashrab) means I drink.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-074',
    type: 'mcq',
    question: 'How do you say "I study" in Arabic?',
    options: ['أدرس (Adrus)', 'تدرس (Tadrus)', 'يدرس (Yadrus)', 'ندرس (Nadrus)'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Verbs',
    explanation: 'أدرس (Adrus) means I study.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-075',
    type: 'mcq',
    question: 'How do you say "I sleep" in Arabic?',
    options: ['أنام (Anam)', 'تنام (Tanam)', 'ينام (Yanam)', 'ننام (Nanam)'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Verbs',
    explanation: 'أنام (Anam) means I sleep.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Questions & Time
  // ============================================
  {
    id: 'jhs-ar-076',
    type: 'mcq',
    question: 'What is "what" in Arabic?',
    options: ['من (Man)', 'ماذا (Matha)', 'أين (Ayna)', 'متى (Mata)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Questions',
    explanation: 'ماذا (Matha) means what.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-077',
    type: 'mcq',
    question: 'What is "who" in Arabic?',
    options: ['ماذا (Matha)', 'من (Man)', 'أين (Ayna)', 'كيف (Kayf)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Questions',
    explanation: 'من (Man) means who.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-078',
    type: 'mcq',
    question: 'What is "where" in Arabic?',
    options: ['متى (Mata)', 'أين (Ayna)', 'كيف (Kayf)', 'لماذا (Limadha)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Questions',
    explanation: 'أين (Ayna) means where.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-079',
    type: 'mcq',
    question: 'What is "when" in Arabic?',
    options: ['أين (Ayna)', 'متى (Mata)', 'كيف (Kayf)', 'لماذا (Limadha)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Questions',
    explanation: 'متى (Mata) means when.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-080',
    type: 'mcq',
    question: 'What is "how" in Arabic?',
    options: ['متى (Mata)', 'كيف (Kayf)', 'أين (Ayna)', 'ماذا (Matha)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Questions',
    explanation: 'كيف (Kayf) means how.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-081',
    type: 'mcq',
    question: 'What is "why" in Arabic?',
    options: ['كيف (Kayf)', 'لماذا (Limadha)', 'متى (Mata)', 'أين (Ayna)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Questions',
    explanation: 'لماذا (Limadha) means why.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-082',
    type: 'mcq',
    question: 'How do you say "now" in Arabic?',
    options: ['الآن (Al-ana)', 'اليوم (Al-yawm)', 'غداً (Ghadan)', 'أمس (Ams)'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Time',
    explanation: 'الآن (Al-ana) means now.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-083',
    type: 'mcq',
    question: 'How do you say "today" in Arabic?',
    options: ['الآن (Al-ana)', 'اليوم (Al-yawm)', 'غداً (Ghadan)', 'أمس (Ams)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Time',
    explanation: 'اليوم (Al-yawm) means today.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-084',
    type: 'mcq',
    question: 'How do you say "tomorrow" in Arabic?',
    options: ['أمس (Ams)', 'غداً (Ghadan)', 'اليوم (Al-yawm)', 'الآن (Al-ana)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Time',
    explanation: 'غداً (Ghadan) means tomorrow.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-085',
    type: 'mcq',
    question: 'How do you say "yesterday" in Arabic?',
    options: ['غداً (Ghadan)', 'أمس (Ams)', 'اليوم (Al-yawm)', 'الآن (Al-ana)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Time',
    explanation: 'أمس (Ams) means yesterday.',
    source: 'practice',
    year: 2019,
  },

  // ============================================
  // Reading & Quran
  // ============================================
  {
    id: 'jhs-ar-086',
    type: 'mcq',
    question: 'What is the Arabic word for "Quran"?',
    options: ['قرآن (Quran)', 'حديث (Hadith)', 'سنة (Sunnah)', 'إسلام (Islam)'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Quran',
    explanation: 'قرآن (Quran) is the holy book of Islam.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-087',
    type: 'mcq',
    question: 'What is the Arabic word for "Sunnah"?',
    options: ['قرآن (Quran)', 'سنة (Sunnah)', 'حديث (Hadith)', 'إسلام (Islam)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Quran',
    explanation: 'سنة (Sunnah) refers to the practices and teachings of Prophet Muhammad.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-088',
    type: 'mcq',
    question: 'What is the first chapter of the Quran called?',
    options: ['البقرة (Al-Baqarah)', 'الفاتحة (Al-Fatiha)', 'النساء (An-Nisa)', 'المائدة (Al-Ma\'idah)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Quran',
    explanation: 'الفاتحة (Al-Fatiha) is the opening chapter of the Quran.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-089',
    type: 'mcq',
    question: 'What does "بسم الله" (Bismillah) mean?',
    options: ['In the name of Allah', 'Praise be to Allah', 'Allah is great', 'There is no god but Allah'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Quran',
    explanation: 'بسم الله (Bismillah) means "In the name of Allah".',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-090',
    type: 'mcq',
    question: 'What does "الحمد لله" (Alhamdulillah) mean?',
    options: ['In the name of Allah', 'Praise be to Allah', 'Allah is great', 'Peace be upon you'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Quran',
    explanation: 'الحمد لله (Alhamdulillah) means "Praise be to Allah".',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-091',
    type: 'mcq',
    question: 'What does "الله أكبر" (Allahu Akbar) mean?',
    options: ['Praise be to Allah', 'Allah is great', 'In the name of Allah', 'There is no god but Allah'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Quran',
    explanation: 'الله أكبر (Allahu Akbar) means "Allah is great".',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-092',
    type: 'mcq',
    question: 'What does "لا إله إلا الله" (La ilaha illa Allah) mean?',
    options: ['Allah is great', 'Praise be to Allah', 'There is no god but Allah', 'In the name of Allah'],
    correctAnswer: 2,
    subject: 'Arabic',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Quran',
    explanation: 'لا إله إلا الله (La ilaha illa Allah) means "There is no god but Allah" - the declaration of faith.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-093',
    type: 'mcq',
    question: 'What is "prayer" in Arabic?',
    options: ['صلاة (Salah)', 'صوم (Sawm)', 'زكاة (Zakat)', 'حج (Hajj)'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Quran',
    explanation: 'صلاة (Salah) means prayer.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-094',
    type: 'mcq',
    question: 'What is "fasting" in Arabic?',
    options: ['صلاة (Salah)', 'صوم (Sawm)', 'زكاة (Zakat)', 'حج (Hajj)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Quran',
    explanation: 'صوم (Sawm) means fasting.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-095',
    type: 'mcq',
    question: 'What is "charity" in Arabic?',
    options: ['صلاة (Salah)', 'زكاة (Zakat)', 'صوم (Sawm)', 'حج (Hajj)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Quran',
    explanation: 'زكاة (Zakat) means charity or almsgiving.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-096',
    type: 'mcq',
    question: 'What is "pilgrimage" in Arabic?',
    options: ['صلاة (Salah)', 'صوم (Sawm)', 'حج (Hajj)', 'زكاة (Zakat)'],
    correctAnswer: 2,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Quran',
    explanation: 'حج (Hajj) means pilgrimage to Mecca.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Advanced Vocabulary
  // ============================================
  {
    id: 'jhs-ar-097',
    type: 'mcq',
    question: 'How do you say "good" in Arabic?',
    options: ['سيء (Sayyi\')', 'جيد (Jayyid)', 'كبير (Kabir)', 'صغير (Saghir)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'جيد (Jayyid) means good.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-098',
    type: 'mcq',
    question: 'How do you say "big" in Arabic?',
    options: ['صغير (Saghir)', 'كبير (Kabir)', 'جيد (Jayyid)', 'سيء (Sayyi\')'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'كبير (Kabir) means big or large.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-099',
    type: 'mcq',
    question: 'How do you say "small" in Arabic?',
    options: ['كبير (Kabir)', 'صغير (Saghir)', 'جيد (Jayyid)', 'قديم (Qadim)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'صغير (Saghir) means small.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-100',
    type: 'mcq',
    question: 'How do you say "new" in Arabic?',
    options: ['قديم (Qadim)', 'جديد (Jadid)', 'كبير (Kabir)', 'صغير (Saghir)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'جديد (Jadid) means new.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-101',
    type: 'mcq',
    question: 'How do you say "old" in Arabic?',
    options: ['جديد (Jadid)', 'قديم (Qadim)', 'كبير (Kabir)', 'صغير (Saghir)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'قديم (Qadim) means old.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-102',
    type: 'mcq',
    question: 'How do you say "yes" in Arabic?',
    options: ['لا (La)', 'نعم (Na\'am)', 'ربما (Rubama)', 'أيضاً (Aydan)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'نعم (Na\'am) means yes.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-103',
    type: 'mcq',
    question: 'How do you say "no" in Arabic?',
    options: ['نعم (Na\'am)', 'لا (La)', 'ربما (Rubama)', 'أيضاً (Aydan)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'لا (La) means no.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-104',
    type: 'mcq',
    question: 'How do you say "maybe" in Arabic?',
    options: ['نعم (Na\'am)', 'لا (La)', 'ربما (Rubama)', 'أيضاً (Aydan)'],
    correctAnswer: 2,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'ربما (Rubama) means maybe or perhaps.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-105',
    type: 'mcq',
    question: 'How do you say "also" in Arabic?',
    options: ['أيضاً (Aydan)', 'ربما (Rubama)', 'لكن (Lakin)', 'لأن (Li\'anna)'],
    correctAnswer: 0,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'أيضاً (Aydan) means also or too.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-106',
    type: 'mcq',
    question: 'How do you say "but" in Arabic?',
    options: ['و (Wa)', 'لكن (Lakin)', 'أو (Aw)', 'لأن (Li\'anna)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'لكن (Lakin) means but or however.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-107',
    type: 'mcq',
    question: 'How do you say "because" in Arabic?',
    options: ['لكن (Lakin)', 'لأن (Li\'anna)', 'و (Wa)', 'أو (Aw)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'لأن (Li\'anna) means because.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ar-108',
    type: 'mcq',
    question: 'How do you say "man" in Arabic?',
    options: ['امرأة (Imra\'a)', 'رجل (Rajul)', 'طفل (Tifl)', 'شخص (Shakhs)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'رجل (Rajul) means man.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ar-109',
    type: 'mcq',
    question: 'How do you say "woman" in Arabic?',
    options: ['رجل (Rajul)', 'امرأة (Imra\'a)', 'طفل (Tifl)', 'شخص (Shakhs)'],
    correctAnswer: 1,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'امرأة (Imra\'a) means woman.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ar-110',
    type: 'mcq',
    question: 'How do you say "child" in Arabic?',
    options: ['رجل (Rajul)', 'امرأة (Imra\'a)', 'طفل (Tifl)', 'شخص (Shakhs)'],
    correctAnswer: 2,
    subject: 'Arabic',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'طفل (Tifl) means child.',
    source: 'practice',
    year: 2021,
  },
];

