import type { ChallengeQuestion } from '../types';

/**
 * JHS Creative Arts Question Bank
 * BECE Creative Arts / Cultural and Creative Arts
 * Topics: Visual Arts, Music, Drama, Dance, Crafts
 */

export const jhsCreativeArtsQuestions: ChallengeQuestion[] = [
  // ============================================
  // Visual Arts - Color Theory & Basics
  // ============================================
  {
    id: 'jhs-ca-001',
    type: 'mcq',
    question: 'Which of these is a primary color?',
    options: ['Green', 'Orange', 'Red', 'Purple'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Red, blue, and yellow are primary colors that cannot be made by mixing other colors.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-002',
    type: 'mcq',
    question: 'Which color is made by mixing red and yellow?',
    options: ['Green', 'Orange', 'Blue', 'Purple'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Red + Yellow = Orange.',
    source: 'practice',
    year: 2016,
  },
  {
    id: 'jhs-ca-003',
    type: 'mcq',
    question: 'Which of these is a secondary color?',
    options: ['Red', 'Blue', 'Green', 'Yellow'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Green is made by mixing blue and yellow (two primary colors).',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-ca-004',
    type: 'mcq',
    question: 'Which of these is a warm color?',
    options: ['Blue', 'Green', 'Red', 'Purple'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Red, orange, and yellow are warm colors that evoke warmth and energy.',
    source: 'practice',
    year: 2016,
  },
  {
    id: 'jhs-ca-005',
    type: 'mcq',
    question: 'Which of these is a cool color?',
    options: ['Red', 'Orange', 'Blue', 'Yellow'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Blue, green, and purple are cool colors that evoke calmness and tranquility.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-ca-006',
    type: 'mcq',
    question: 'What color is made by mixing red and blue?',
    options: ['Green', 'Orange', 'Purple', 'Yellow'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Red + Blue = Purple (or violet).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-007',
    type: 'mcq',
    question: 'What color is made by mixing blue and yellow?',
    options: ['Green', 'Orange', 'Purple', 'Red'],
    correctAnswer: 0,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Blue + Yellow = Green.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Visual Arts - Drawing & Painting
  // ============================================
  {
    id: 'jhs-ca-008',
    type: 'mcq',
    question: 'A drawing made with pencil is called a...',
    options: ['Painting', 'Sketch', 'Sculpture', 'Collage'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Sketches are quick pencil drawings used to plan or practice.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-009',
    type: 'mcq',
    question: 'The art of cutting and pasting paper is called...',
    options: ['Drawing', 'Collage', 'Painting', 'Sculpting'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Collage involves arranging cut paper pieces to create artwork.',
    source: 'practice',
    year: 2015,
  },
  {
    id: 'jhs-ca-010',
    type: 'mcq',
    question: 'Which tool is used for painting?',
    options: ['Pencil', 'Brush', 'Chisel', 'Needle'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Brushes are used to apply paint to canvas or paper.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-011',
    type: 'mcq',
    question: 'What is the surface used for painting called?',
    options: ['Paper', 'Canvas', 'Wood', 'All of the above'],
    correctAnswer: 3,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Paintings can be done on various surfaces including paper, canvas, and wood.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-012',
    type: 'mcq',
    question: 'Which of these is a drawing tool?',
    options: ['Brush', 'Chisel', 'Pencil', 'Hammer'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Pencils are primary drawing tools for creating sketches and drawings.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-013',
    type: 'mcq',
    question: 'What is the art of creating images using lines and shading called?',
    options: ['Painting', 'Drawing', 'Sculpture', 'Printing'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Drawing uses lines, shapes, and shading to create images.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-014',
    type: 'mcq',
    question: 'Which type of paint dries quickly?',
    options: ['Oil paint', 'Watercolor', 'Acrylic paint', 'All dry at same speed'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Acrylic paint dries faster than oil paint and is water-soluble.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Visual Arts - Sculpture & 3D Art
  // ============================================
  {
    id: 'jhs-ca-015',
    type: 'mcq',
    question: 'The art of creating three-dimensional objects is called...',
    options: ['Drawing', 'Painting', 'Sculpture', 'Printing'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Sculpture creates 3D art forms that can be viewed from all sides.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-016',
    type: 'mcq',
    question: 'The art of making pots from clay is called...',
    options: ['Sculpting', 'Pottery', 'Weaving', 'Carving'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Pottery involves shaping clay into vessels and firing them in a kiln.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-017',
    type: 'mcq',
    question: 'What material is commonly used for making sculptures?',
    options: ['Paper', 'Water', 'Clay', 'Paint'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Clay is a common material for sculpting as it is malleable and can be fired.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-018',
    type: 'mcq',
    question: 'The art of cutting designs into wood or stone is called...',
    options: ['Painting', 'Drawing', 'Carving', 'Weaving'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Carving involves removing material to create designs or shapes.',
    source: 'practice',
    year: 2019,
  },

  // ============================================
  // Music - Instruments
  // ============================================
  {
    id: 'jhs-ca-019',
    type: 'mcq',
    question: 'Which instrument is played by striking?',
    options: ['Flute', 'Drum', 'Guitar', 'Piano'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Drums are percussion instruments played by striking with hands or sticks.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-ca-020',
    type: 'mcq',
    question: 'Which of these is a string instrument?',
    options: ['Drum', 'Flute', 'Guitar', 'Trumpet'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Guitar has strings that are plucked or strummed to produce sound.',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-ca-021',
    type: 'mcq',
    question: 'Which of these is a wind instrument?',
    options: ['Piano', 'Violin', 'Flute', 'Drum'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Flute produces sound when air is blown through it.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-022',
    type: 'mcq',
    question: 'Which instrument is part of the brass family?',
    options: ['Violin', 'Flute', 'Trumpet', 'Piano'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Trumpet is a brass instrument that produces sound by vibrating lips.',
    source: 'practice',
    year: 2015,
  },
  {
    id: 'jhs-ca-023',
    type: 'mcq',
    question: 'Which of these is a percussion instrument?',
    options: ['Violin', 'Flute', 'Piano', 'Trumpet'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Piano produces sound when keys are struck, making it a percussion instrument.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-024',
    type: 'mcq',
    question: 'A traditional Ghanaian drum is called...',
    options: ['Piano', 'Guitar', 'Fontomfrom', 'Violin'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Fontomfrom is a traditional Akan drum used in Ghanaian ceremonies.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-025',
    type: 'mcq',
    question: 'Which instrument has keys?',
    options: ['Guitar', 'Drum', 'Piano', 'Flute'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Piano has keys that are pressed to produce musical notes.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-026',
    type: 'mcq',
    question: 'Which of these is a woodwind instrument?',
    options: ['Trumpet', 'Violin', 'Clarinet', 'Drum'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Clarinet is a woodwind instrument that uses a reed to produce sound.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Music - Theory & Concepts
  // ============================================
  {
    id: 'jhs-ca-027',
    type: 'mcq',
    question: 'Which musical note has the longest duration?',
    options: ['Whole note', 'Half note', 'Quarter note', 'Eighth note'],
    correctAnswer: 0,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Whole notes last for 4 beats, the longest standard note duration.',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-ca-028',
    type: 'mcq',
    question: 'A group of musicians playing together is called an...',
    options: ['Solo', 'Duet', 'Orchestra', 'Quartet'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Orchestras have many musicians playing different instruments together.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-029',
    type: 'mcq',
    question: 'What is the speed of music called?',
    options: ['Pitch', 'Tempo', 'Volume', 'Rhythm'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Tempo refers to the speed or pace of a musical piece.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-030',
    type: 'mcq',
    question: 'What is the highness or lowness of a sound called?',
    options: ['Tempo', 'Pitch', 'Volume', 'Rhythm'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Pitch refers to how high or low a musical note sounds.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-031',
    type: 'mcq',
    question: 'How many lines are in a musical staff?',
    options: ['Three', 'Four', 'Five', 'Six'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Music',
    explanation: 'A standard musical staff has five horizontal lines for writing notes.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-032',
    type: 'mcq',
    question: 'What is a group of two musicians called?',
    options: ['Solo', 'Duet', 'Trio', 'Quartet'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Music',
    explanation: 'A duet is a musical performance by two people.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Drama & Theatre
  // ============================================
  {
    id: 'jhs-ca-033',
    type: 'mcq',
    question: 'A play performed on stage is called a...',
    options: ['Movie', 'Drama', 'Song', 'Poem'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Drama is live theatrical performance on stage.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-ca-034',
    type: 'mcq',
    question: 'A person who acts in a play is called an...',
    options: ['Director', 'Actor', 'Producer', 'Writer'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Actors perform roles in dramas and plays.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-035',
    type: 'mcq',
    question: 'The person who writes a play is called a...',
    options: ['Actor', 'Director', 'Playwright', 'Producer'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Playwrights create scripts for plays.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-036',
    type: 'mcq',
    question: 'The person who guides actors in a play is called a...',
    options: ['Actor', 'Playwright', 'Director', 'Producer'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Directors guide actors and oversee the overall production of a play.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-037',
    type: 'mcq',
    question: 'What is the written text of a play called?',
    options: ['Script', 'Novel', 'Poem', 'Song'],
    correctAnswer: 0,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'A script contains the dialogue and stage directions for a play.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-038',
    type: 'mcq',
    question: 'What is the area where actors perform called?',
    options: ['Backstage', 'Stage', 'Audience', 'Lobby'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'The stage is the raised platform where actors perform.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Dance
  // ============================================
  {
    id: 'jhs-ca-039',
    type: 'mcq',
    question: 'A traditional Ghanaian dance is...',
    options: ['Ballet', 'Adowa', 'Hip-hop', 'Jazz'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Dance',
    explanation: 'Adowa is a popular traditional dance in Ghana, especially among the Akan people.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-ca-040',
    type: 'mcq',
    question: 'What is a group of dancers called?',
    options: ['Choir', 'Band', 'Troupe', 'Orchestra'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Dance',
    explanation: 'A troupe is a group of dancers who perform together.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-041',
    type: 'mcq',
    question: 'Which traditional Ghanaian dance is performed at funerals?',
    options: ['Adowa', 'Kpanlogo', 'Bamaya', 'All of the above'],
    correctAnswer: 3,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Dance',
    explanation: 'Many traditional Ghanaian dances, including Adowa, Kpanlogo, and Bamaya, are performed at funerals.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Crafts
  // ============================================
  {
    id: 'jhs-ca-042',
    type: 'mcq',
    question: 'The art of making designs with thread is called...',
    options: ['Weaving', 'Pottery', 'Carving', 'Painting'],
    correctAnswer: 0,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Weaving creates patterns with threads on a loom.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-043',
    type: 'mcq',
    question: 'What is the art of making baskets called?',
    options: ['Pottery', 'Weaving', 'Carving', 'Painting'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Basket weaving involves interlacing materials like grass or reeds.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-044',
    type: 'mcq',
    question: 'What material is commonly used for making kente cloth?',
    options: ['Cotton', 'Silk', 'Wool', 'All of the above'],
    correctAnswer: 3,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Kente cloth can be made from various materials including cotton, silk, and wool.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-045',
    type: 'mcq',
    question: 'What is the traditional Ghanaian woven cloth called?',
    options: ['Kente', 'Batik', 'Tie-dye', 'Print'],
    correctAnswer: 0,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Kente is a colorful woven cloth traditionally made by the Akan people of Ghana.',
    source: 'practice',
    year: 2019,
  },

  // ============================================
  // Additional BECE Creative Arts Questions
  // ============================================

  // Visual Arts - More Concepts
  {
    id: 'jhs-ca-046',
    type: 'mcq',
    question: 'What is the art of printing designs on fabric called?',
    options: ['Weaving', 'Batik', 'Pottery', 'Carving'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Batik involves using wax and dye to create patterns on fabric.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-047',
    type: 'mcq',
    question: 'What is a self-portrait?',
    options: ['A picture of someone else', 'A picture of yourself', 'A landscape', 'A still life'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'A self-portrait is a drawing or painting of the artist by themselves.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-048',
    type: 'mcq',
    question: 'What is a picture of natural scenery called?',
    options: ['Portrait', 'Still life', 'Landscape', 'Abstract'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'A landscape shows natural scenery like mountains, rivers, or fields.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-049',
    type: 'mcq',
    question: 'What is a picture of objects like fruits or flowers called?',
    options: ['Portrait', 'Still life', 'Landscape', 'Abstract'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Still life shows inanimate objects like fruits, flowers, or vases.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-050',
    type: 'mcq',
    question: 'What is the technique of creating images using small colored pieces called?',
    options: ['Collage', 'Mosaic', 'Painting', 'Drawing'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Mosaic uses small pieces of colored glass, stone, or tile to create images.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-051',
    type: 'mcq',
    question: 'What is the art of creating images by pressing ink onto paper called?',
    options: ['Drawing', 'Painting', 'Printmaking', 'Sculpture'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Printmaking involves creating images by transferring ink from a surface to paper.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-052',
    type: 'mcq',
    question: 'What is the technique of creating art without recognizable objects called?',
    options: ['Realism', 'Abstract', 'Impressionism', 'Portrait'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Abstract art uses shapes, colors, and forms without representing recognizable objects.',
    source: 'practice',
    year: 2021,
  },

  // Music - More Concepts
  {
    id: 'jhs-ca-053',
    type: 'mcq',
    question: 'What is the pattern of beats in music called?',
    options: ['Tempo', 'Pitch', 'Rhythm', 'Volume'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Rhythm is the pattern of sounds and silences in music.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-054',
    type: 'mcq',
    question: 'What is the loudness or softness of music called?',
    options: ['Pitch', 'Tempo', 'Volume', 'Rhythm'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Volume (or dynamics) refers to how loud or soft music is.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-055',
    type: 'mcq',
    question: 'What is a person who writes music called?',
    options: ['Musician', 'Composer', 'Conductor', 'Singer'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'A composer creates original musical pieces.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-056',
    type: 'mcq',
    question: 'What is a person who leads an orchestra called?',
    options: ['Musician', 'Composer', 'Conductor', 'Singer'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'A conductor leads and directs an orchestra during performances.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-057',
    type: 'mcq',
    question: 'What is a performance by one person called?',
    options: ['Duet', 'Solo', 'Trio', 'Quartet'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Music',
    explanation: 'A solo is a musical performance by a single person.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-058',
    type: 'mcq',
    question: 'Which traditional Ghanaian instrument is a type of xylophone?',
    options: ['Fontomfrom', 'Atumpan', 'Gyil', 'Kora'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Gyil is a traditional Ghanaian xylophone made of wood and gourds.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-059',
    type: 'mcq',
    question: 'What is the main melody in a song called?',
    options: ['Harmony', 'Tune', 'Beat', 'Rhythm'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'The tune (or melody) is the main sequence of notes in a song.',
    source: 'practice',
    year: 2020,
  },

  // Drama - More Concepts
  {
    id: 'jhs-ca-060',
    type: 'mcq',
    question: 'What are the items used on stage to create a setting called?',
    options: ['Costumes', 'Props', 'Scripts', 'Lights'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Props (properties) are objects used on stage during a performance.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-061',
    type: 'mcq',
    question: 'What are the clothes worn by actors called?',
    options: ['Props', 'Costumes', 'Uniforms', 'Dresses'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Costumes are the clothing worn by actors to represent their characters.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-062',
    type: 'mcq',
    question: 'What is a short play with a moral lesson called?',
    options: ['Comedy', 'Tragedy', 'Fable', 'Drama'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'A fable is a short story or play that teaches a moral lesson.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-063',
    type: 'mcq',
    question: 'What is a play that makes people laugh called?',
    options: ['Tragedy', 'Comedy', 'Drama', 'Fable'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Comedy is a type of play intended to be humorous and make people laugh.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-064',
    type: 'mcq',
    question: 'What is a play with a sad ending called?',
    options: ['Comedy', 'Tragedy', 'Fable', 'Drama'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Tragedy is a type of play that deals with serious themes and often has a sad ending.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-065',
    type: 'mcq',
    question: 'What is the area behind the stage where actors prepare called?',
    options: ['Stage', 'Audience', 'Backstage', 'Lobby'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Backstage is the area behind the stage where actors prepare and props are stored.',
    source: 'practice',
    year: 2019,
  },

  // Dance - More Concepts
  {
    id: 'jhs-ca-066',
    type: 'mcq',
    question: 'What is the traditional dance of the Ga people called?',
    options: ['Adowa', 'Kpanlogo', 'Bamaya', 'Agbadza'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Dance',
    explanation: 'Kpanlogo is a popular traditional dance of the Ga people of Ghana.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-067',
    type: 'mcq',
    question: 'What is the traditional dance of the Dagomba people called?',
    options: ['Adowa', 'Kpanlogo', 'Bamaya', 'Agbadza'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Dance',
    explanation: 'Bamaya is a traditional dance of the Dagomba people in northern Ghana.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-068',
    type: 'mcq',
    question: 'What is the traditional dance of the Ewe people called?',
    options: ['Adowa', 'Kpanlogo', 'Bamaya', 'Agbadza'],
    correctAnswer: 3,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Dance',
    explanation: 'Agbadza is a traditional dance of the Ewe people of Ghana and Togo.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-069',
    type: 'mcq',
    question: 'What is the movement of the body to music called?',
    options: ['Singing', 'Dancing', 'Acting', 'Playing'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Dance',
    explanation: 'Dancing is the art of moving the body rhythmically to music.',
    source: 'practice',
    year: 2021,
  },

  // Crafts - More Concepts
  {
    id: 'jhs-ca-070',
    type: 'mcq',
    question: 'What is the art of decorating fabric with patterns using wax and dye called?',
    options: ['Weaving', 'Batik', 'Tie-dye', 'Printing'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Batik uses wax to resist dye, creating patterns on fabric.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-071',
    type: 'mcq',
    question: 'What is the art of creating patterns by tying fabric before dyeing called?',
    options: ['Batik', 'Tie-dye', 'Weaving', 'Printing'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Tie-dye involves tying fabric in patterns before applying dye.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-072',
    type: 'mcq',
    question: 'What tool is used for weaving?',
    options: ['Brush', 'Loom', 'Chisel', 'Hammer'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'A loom is a device used to weave threads into fabric.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-073',
    type: 'mcq',
    question: 'What is the art of making jewelry called?',
    options: ['Pottery', 'Weaving', 'Jewelry making', 'Carving'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Jewelry making involves creating decorative items from metals, beads, or stones.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-074',
    type: 'mcq',
    question: 'What material is commonly used for making beads?',
    options: ['Wood', 'Glass', 'Clay', 'All of the above'],
    correctAnswer: 3,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Beads can be made from various materials including wood, glass, and clay.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ca-075',
    type: 'mcq',
    question: 'What is the art of making decorative objects from paper called?',
    options: ['Origami', 'Collage', 'Paper mache', 'All of the above'],
    correctAnswer: 3,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Origami, collage, and paper mache are all paper-based art forms.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Additional BECE Creative Arts Questions (Batch 2)
  // ============================================

  // African Art Cultures & History
  {
    id: 'jhs-ca-076',
    type: 'mcq',
    question: 'The oldest art culture in the South of Sahara is...',
    options: ['Benin', 'Esie', 'Ife', 'Nok'],
    correctAnswer: 3,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Art History',
    explanation: 'The Nok culture is considered the oldest art culture south of the Sahara, known for its terracotta sculptures dating back to around 1000 BC.',
    source: 'practice',
    year: 2013,
  },
  {
    id: 'jhs-ca-077',
    type: 'mcq',
    question: 'Benin art is also referred to as...',
    options: ['Abstract art', 'Court art', 'Fine art', 'Naturalistic'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Art History',
    explanation: 'Benin art is known as court art because it was primarily produced for the royal court of the Benin Kingdom.',
    source: 'practice',
    year: 2012,
  },
  {
    id: 'jhs-ca-078',
    type: 'mcq',
    question: 'Which of these traditional art cultures is known for court art?',
    options: ['Benin', 'Esie', 'Ife', 'Nok'],
    correctAnswer: 0,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Art History',
    explanation: 'The Benin culture is renowned for its court art, including bronze sculptures and plaques created for the royal palace.',
    source: 'practice',
    year: 2016,
  },
  {
    id: 'jhs-ca-079',
    type: 'mcq',
    question: 'Which of the following artistic elements often reflect an African visual artist\'s background and influence in their artworks?',
    options: ['Use of bright colors and abstract shapes', 'Depiction of traditional symbols and cultural motifs', 'Emphasis on realistic portraits and landscapes', 'Minimalist and monochromatic compositions'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'African visual artists often incorporate traditional symbols and cultural motifs into their artworks to reflect their heritage and background.',
    source: 'practice',
    year: 2025,
  },

  // Visual Arts - Techniques & Methods
  {
    id: 'jhs-ca-080',
    type: 'mcq',
    question: 'What technique gives depth and volume to a 3-D drawing?',
    options: ['Scribbling', 'Erasing', 'Shading', 'Outlining'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Shading creates the illusion of depth and volume by varying the darkness of tones.',
    source: 'practice',
    year: 2025,
  },
  {
    id: 'jhs-ca-081',
    type: 'mcq',
    question: 'An outdoor drawing can be done through...',
    options: ['Abstract', 'Arrangement of objects', 'Composition of objects', 'Observation'],
    correctAnswer: 3,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Outdoor drawings, or plein air drawings, are typically created through direct observation of the environment.',
    source: 'practice',
    year: 2013,
  },
  {
    id: 'jhs-ca-082',
    type: 'mcq',
    question: 'In making an artwork, Ama gathers and joins different discarded materials to create a new whole. Select the technique Ama used.',
    options: ['Carving', 'Assemblage', 'Etching', 'Engraving'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Assemblage is an art technique where various found objects are combined to create a new artwork.',
    source: 'practice',
    year: 2025,
  },
  {
    id: 'jhs-ca-083',
    type: 'mcq',
    question: 'The term assemblage was invented by the artist called...',
    options: ['Pablo Picasso', 'Jean Dubuffet', 'John Lewis', 'Van Groh'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Art History',
    explanation: 'Jean Dubuffet coined the term "assemblage" to describe art made from found objects.',
    source: 'practice',
    year: 2025,
  },
  {
    id: 'jhs-ca-084',
    type: 'mcq',
    question: 'Which aspect of coloring is crucial for giving depth and dimension to a design?',
    options: ['Using only primary colors', 'Applying colors randomly', 'Blending and shading colors', 'Coloring within lines'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Blending and shading colors creates depth and dimension in artwork.',
    source: 'practice',
    year: 2025,
  },

  // Visual Arts - Art Types & Elements
  {
    id: 'jhs-ca-085',
    type: 'mcq',
    question: 'A printing of an expanse of sea is known as...',
    options: ['Sea scape', 'High scape', 'Natural scape', 'Land scape'],
    correctAnswer: 0,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'A seascape is an artwork that depicts an expanse of the sea.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-086',
    type: 'mcq',
    question: 'Which of these is an element of design frequently observed in nature?',
    options: ['Blueprint', 'Texture', 'Ruler', 'Paintbrush'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Texture is an element of design that can be observed in nature, such as rough bark, smooth leaves, or grainy sand.',
    source: 'practice',
    year: 2025,
  },
  {
    id: 'jhs-ca-087',
    type: 'mcq',
    question: 'What are the elements of design often observed in nature and the manmade environment?',
    options: ['Shapes, patterns, and textures', 'Blueprints, drafts, and models', 'Rulers, pencils, and erasers', 'Paints, brushes, and canvases'],
    correctAnswer: 0,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Shapes, patterns, and textures are fundamental design elements found in both nature and manmade environments.',
    source: 'practice',
    year: 2025,
  },

  // Crafts - Weaving & Materials
  {
    id: 'jhs-ca-088',
    type: 'mcq',
    question: 'Which of the following is the commonest form of weaving?',
    options: ['Basketry', 'Cane', 'Cloth', 'Hat'],
    correctAnswer: 0,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Basketry is a widespread form of weaving, involving the interlacing of flexible materials to create baskets and other items.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-ca-089',
    type: 'mcq',
    question: 'What material is commonly used for making traditional Ghanaian baskets?',
    options: ['Plastic', 'Metal', 'Raffia or palm leaves', 'Cotton'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Traditional Ghanaian baskets are often made from raffia or palm leaves, which are natural, flexible materials.',
    source: 'practice',
    year: 2021,
  },

  // Music - Traditional Instruments
  {
    id: 'jhs-ca-090',
    type: 'mcq',
    question: 'Which of the following traditional instruments belongs to the membranophone family?',
    options: ['Gankogui', 'Gyile', 'Atumpan', 'Axatse'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Music',
    explanation: 'The Atumpan is a traditional drum from Ghana, classified as a membranophone because it produces sound through the vibration of a stretched membrane.',
    source: 'practice',
    year: 2025,
  },
  {
    id: 'jhs-ca-091',
    type: 'mcq',
    question: 'Which traditional Ghanaian instrument is a double bell?',
    options: ['Fontomfrom', 'Gankogui', 'Gyil', 'Atumpan'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Gankogui is a traditional double bell instrument used in Ghanaian music, especially in Ewe music.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-092',
    type: 'mcq',
    question: 'Which traditional instrument is a rattle made from a gourd?',
    options: ['Gankogui', 'Gyil', 'Atumpan', 'Axatse'],
    correctAnswer: 3,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Music',
    explanation: 'Axatse is a traditional Ghanaian rattle made from a gourd with seeds or beads inside.',
    source: 'practice',
    year: 2020,
  },

  // Music - Concepts & Theory
  {
    id: 'jhs-ca-093',
    type: 'mcq',
    question: 'How do musical works of African art composers typically reflect history, culture, environment, and topical issues?',
    options: ['By exclusively focusing on universal themes unrelated to Africa', 'Through the incorporation of traditional instruments and rhythms', 'By avoiding any references to cultural heritage', 'By imitating Western musical styles without innovation'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Music',
    explanation: 'African composers incorporate traditional instruments and rhythms to reflect their history, culture, and environment.',
    source: 'practice',
    year: 2025,
  },
  {
    id: 'jhs-ca-094',
    type: 'mcq',
    question: 'What is the term for a group of three musicians?',
    options: ['Solo', 'Duet', 'Trio', 'Quartet'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Music',
    explanation: 'A trio is a musical performance by three people.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-095',
    type: 'mcq',
    question: 'What is the term for a group of four musicians?',
    options: ['Solo', 'Duet', 'Trio', 'Quartet'],
    correctAnswer: 3,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Music',
    explanation: 'A quartet is a musical performance by four people.',
    source: 'practice',
    year: 2021,
  },

  // Drama - Concepts
  {
    id: 'jhs-ca-096',
    type: 'mcq',
    question: 'Cultural and Creative Art is a combination of all the following except...',
    options: ['Drama', 'Fine art', 'Music', 'Religion'],
    correctAnswer: 3,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'Cultural and Creative Arts encompass drama, fine art, and music, but not religion.',
    source: 'practice',
    year: 2016,
  },
  {
    id: 'jhs-ca-097',
    type: 'mcq',
    question: 'What is the term for the people who watch a play?',
    options: ['Actors', 'Audience', 'Directors', 'Producers'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'The audience consists of people who watch and observe a theatrical performance.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-098',
    type: 'mcq',
    question: 'What is the term for the written dialogue and stage directions in a play?',
    options: ['Script', 'Novel', 'Poem', 'Song'],
    correctAnswer: 0,
    subject: 'Creative Arts',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Drama',
    explanation: 'A script contains the written dialogue and stage directions for actors and directors.',
    source: 'practice',
    year: 2020,
  },

  // Visual Arts - More Techniques
  {
    id: 'jhs-ca-099',
    type: 'mcq',
    question: 'What is the technique of creating art by cutting into a surface called?',
    options: ['Painting', 'Drawing', 'Etching', 'Collage'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Etching involves cutting or engraving into a surface to create designs.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ca-100',
    type: 'mcq',
    question: 'What is the technique of creating art by pressing a design onto paper called?',
    options: ['Drawing', 'Painting', 'Printing', 'Sculpture'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'Printing involves transferring ink or paint from a surface to paper to create multiple copies.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ca-101',
    type: 'mcq',
    question: 'What is the art of creating designs by cutting paper called?',
    options: ['Collage', 'Paper cutting', 'Origami', 'Paper mache'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Crafts',
    explanation: 'Paper cutting involves creating intricate designs by cutting paper with scissors or knives.',
    source: 'practice',
    year: 2021,
  },

  // Art & Society
  {
    id: 'jhs-ca-102',
    type: 'mcq',
    question: 'How do African visual artists contribute to solving continental issues through their artworks?',
    options: ['By avoiding controversial themes to maintain neutrality', 'Through the representation of societal challenges and solutions', 'By exclusively focusing on abstract art unrelated to societal issues', 'By imitating Western art styles and techniques'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'African visual artists address societal challenges and propose solutions through their artwork.',
    source: 'practice',
    year: 2025,
  },
  {
    id: 'jhs-ca-103',
    type: 'mcq',
    question: 'How do African visual artists often connect with other creative arts and subjects in Africa?',
    options: ['Through isolation and detachment from other artistic forms', 'By collaborating with musicians, writers, and dancers', 'By avoiding influences from other African art forms', 'By prioritizing international collaborations over local connections'],
    correctAnswer: 1,
    subject: 'Creative Arts',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'African visual artists collaborate with musicians, writers, and dancers to create interdisciplinary works.',
    source: 'practice',
    year: 2025,
  },
  {
    id: 'jhs-ca-104',
    type: 'mcq',
    question: 'In what ways do African visual artists use their influence and personal responses to connect with other creative arts?',
    options: ['By disregarding the cultural context of other art forms', 'By adapting their style to mimic other artists\' works', 'By infusing their cultural experiences and perspectives into collaborations', 'By insisting on imposing their artistic views without compromise'],
    correctAnswer: 2,
    subject: 'Creative Arts',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Visual Arts',
    explanation: 'African visual artists bring their cultural experiences and perspectives into collaborative works with other art forms.',
    source: 'practice',
    year: 2025,
  },
];

