// JHS English Language Questions
// BECE-level questions migrated to modular ChallengeQuestion format
// NOTE: These are practice-style BECE-level questions, not yet tagged as verified past questions.

import type { ChallengeQuestion } from '../types';

export const jhsEnglishLanguageQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Initial Batch)
  // ============================================

  // JHS English Language - Grammar
  {
    id: 'jhs-eng-001',
    type: 'mcq',
    question: 'Choose the word that best completes the sentence: The boy _____ to school yesterday.',
    options: ['go', 'goes', 'went', 'gone'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Past tense of go is went.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-eng-002',
    type: 'mcq',
    question: 'Which of the following is a noun?',
    options: ['Run', 'Beautiful', 'Accra', 'Quickly'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Accra is a proper noun (name of a place).',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-eng-003',
    type: 'mcq',
    question: 'The plural of "child" is...',
    options: ['childs', 'children', 'childrens', 'childes'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Irregular plural.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-eng-004',
    type: 'mcq',
    question: 'Which sentence is correct?',
    options: ['He don\'t know.', 'He doesn\'t know.', 'He didn\'t knew.', 'He not know.'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Third person singular requires "doesn\'t".',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-eng-005',
    type: 'mcq',
    question: 'Choose the correct preposition: He jumped _____ the pool.',
    options: ['on', 'at', 'into', 'in'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Into indicates movement towards the inside.',
    source: 'practice',
    year: 2015,
  },
  {
    id: 'jhs-eng-006',
    type: 'mcq',
    question: 'The past participle of "eat" is...',
    options: ['ate', 'eaten', 'eating', 'eats'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Eat, ate, eaten.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-eng-007',
    type: 'mcq',
    question: 'Identify the verb in the sentence: "She sings beautifully."',
    options: ['She', 'sings', 'beautifully', 'none'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Sings is the action word.',
    source: 'practice',
    year: 2022,
  },

  // JHS English Language - Vocabulary & Spelling
  {
    id: 'jhs-eng-008',
    type: 'mcq',
    question: 'Choose the correct spelling.',
    options: ['Recieve', 'Receive', 'Riceive', 'Receve'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Spelling',
    explanation: 'I before E except after C.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-eng-009',
    type: 'mcq',
    question: 'The opposite of "ancient" is...',
    options: ['old', 'modern', 'antique', 'past'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Antonyms',
    explanation: 'Ancient means very old; modern means new/current.',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-eng-010',
    type: 'mcq',
    question: 'A person who writes poems is called a...',
    options: ['Poet', 'Author', 'Writer', 'Novelist'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'Specific term for poetry writer.',
    source: 'practice',
    year: 2016,
  },

  // JHS English Language - Comprehension & Usage
  {
    id: 'jhs-eng-011',
    type: 'mcq',
    question: 'Choose the word that best completes: "The weather is _____ today."',
    options: ['goodly', 'good', 'well', 'gooder'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Good is an adjective describing weather. Well is an adverb.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-eng-012',
    type: 'mcq',
    question: 'Which sentence uses the correct form of "there"?',
    options: ['Their going to school.', 'There going to school.', 'They\'re going to school.', 'They going to school.'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'They\'re is the contraction of "they are".',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-eng-013',
    type: 'mcq',
    question: 'Choose the correct comparative form: "This book is _____ than that one."',
    options: ['interesting', 'more interesting', 'most interesting', 'interestinger'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'For adjectives with 3+ syllables, use "more" for comparative.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-eng-014',
    type: 'mcq',
    question: 'Which word means "to make something better"?',
    options: ['Improve', 'Improvise', 'Impose', 'Import'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'Improve means to make better or enhance.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-eng-015',
    type: 'mcq',
    question: 'Choose the correctly punctuated sentence.',
    options: ['She said, "Hello, how are you?"', 'She said "Hello, how are you?"', 'She said, Hello, how are you?', 'She said "Hello, how are you".'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Punctuation',
    explanation: 'Direct speech requires a comma before the quotation and punctuation inside quotes.',
    source: 'practice',
    year: 2022,
  },

  // ============================================
  // Additional Questions (Batch 1)
  // ============================================

  // JHS English Language - Medium (Synonyms, Idioms, Grammar)
  {
    id: 'jhs-eng-016',
    type: 'mcq',
    question: 'Choose the word nearest in meaning to "ABANDON".',
    options: ['Keep', 'Leave', 'Join', 'Build'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Synonyms',
    explanation: 'Abandon means to leave or forsake.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-eng-017',
    type: 'mcq',
    question: 'The idiom "to let the cat out of the bag" means...',
    options: ['to release a pet', 'to reveal a secret', 'to make a mistake', 'to be careless'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Idioms',
    explanation: 'It means to disclose a secret.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-eng-018',
    type: 'mcq',
    question: 'From the alternatives, choose the one that best completes the sentence: Neither the teacher nor the students _____ present.',
    options: ['is', 'are', 'was', 'has'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'When using neither/nor, the verb agrees with the noun closest to it (students -> are).',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-eng-019',
    type: 'mcq',
    question: 'Identify the figure of speech: "The wind whispered through the trees."',
    options: ['Simile', 'Metaphor', 'Personification', 'Hyperbole'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Literature',
    explanation: 'Giving human qualities (whispering) to inanimate objects (wind).',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-eng-020',
    type: 'mcq',
    question: 'The word "quickly" in the sentence "He ran quickly" is an...',
    options: ['Adjective', 'Adverb', 'Noun', 'Verb'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'It modifies the verb "ran".',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-eng-021',
    type: 'mcq',
    question: 'Choose the correct question tag: You are coming, _____?',
    options: ['aren\'t you', 'isn\'t it', 'don\'t you', 'won\'t you'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Positive statement takes negative tag.',
    source: 'practice',
    year: 2015,
  },
  {
    id: 'jhs-eng-022',
    type: 'mcq',
    question: 'The prefix "un-" in "unhappy" means...',
    options: ['very', 'not', 'always', 'too'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'It negates the meaning.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-eng-023',
    type: 'mcq',
    question: 'Which of these is a collective noun?',
    options: ['Soldiers', 'Army', 'Man', 'Gun'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Army represents a group of soldiers.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-eng-024',
    type: 'mcq',
    question: 'Complete: If I _____ you, I would study harder.',
    options: ['am', 'was', 'were', 'be'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Subjunctive mood requires "were".',
    source: 'practice',
    year: 2021,
  },

  // JHS English Language - Hard (JHS 3)
  {
    id: 'jhs-eng-025',
    type: 'mcq',
    question: 'Choose the word opposite in meaning to "DILIGENT".',
    options: ['Hardworking', 'Lazy', 'Smart', 'Careful'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Antonyms',
    explanation: 'Diligent means hardworking; lazy is the opposite.',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-eng-026',
    type: 'mcq',
    question: 'The expression "a white elephant" refers to something that is...',
    options: ['rare and valuable', 'useless and expensive', 'large and strong', 'sacred'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Idioms',
    explanation: 'An expensive item that is useless to the owner.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-eng-027',
    type: 'mcq',
    question: 'Identify the clause in: "The man who stole the car has been arrested."',
    options: ['Adverbial clause', 'Noun clause', 'Adjectival clause', 'Prepositional phrase'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Grammar',
    explanation: '"who stole the car" describes "The man".',
    source: 'practice',
    year: 2016,
  },
  {
    id: 'jhs-eng-028',
    type: 'mcq',
    question: 'Change to passive voice: "The hunter killed the lion."',
    options: ['The lion is killed by the hunter.', 'The lion was killed by the hunter.', 'The lion has been killed.', 'The hunter was killed by the lion.'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Past tense active becomes past tense passive.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-eng-029',
    type: 'mcq',
    question: 'Choose the correct order of adjectives: She bought a _____ bag.',
    options: ['leather black new', 'new black leather', 'black new leather', 'leather new black'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Order: Age, Color, Material.',
    source: 'practice',
    year: 2015,
  },
  {
    id: 'jhs-eng-030',
    type: 'mcq',
    question: 'The climax of a story is...',
    options: ['the beginning', 'the turning point', 'the conclusion', 'the setting'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Literature',
    explanation: 'The point of highest tension.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-eng-031',
    type: 'mcq',
    question: 'Which literary device is used in "He is a lion in battle"?',
    options: ['Simile', 'Metaphor', 'Irony', 'Alliteration'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Literature',
    explanation: 'Direct comparison without using "like" or "as".',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-eng-032',
    type: 'mcq',
    question: 'Choose the correct word: The committee gave _____ approval.',
    options: ['its', 'it\'s', 'their', 'theirs'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Committee is singular here, so "its".',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-eng-033',
    type: 'mcq',
    question: 'The word "magnanimous" means...',
    options: ['Huge', 'Generous', 'Powerful', 'Rich'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'Generous or forgiving.',
    source: 'practice',
    year: 2022,
  },

  // ============================================
  // Additional BECE English Questions (Batch 2 - No Duplicates)
  // ============================================

  // JHS English Language - Grammar (Gerunds, Tenses)
  {
    id: 'jhs-eng-034',
    type: 'mcq',
    question: 'Choose the word that best completes: "The teacher emphasized the importance of _____ regularly."',
    options: ['study', 'studying', 'studied', 'studies'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'After "importance of", we use a gerund (verb + -ing).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-eng-035',
    type: 'mcq',
    question: 'Choose the correct form: "She _____ to the market every Saturday."',
    options: ['go', 'goes', 'going', 'gone'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Third person singular (she) with present tense requires "goes".',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-eng-036',
    type: 'mcq',
    question: 'What is the past tense of "bring"?',
    options: ['bringed', 'brought', 'brang', 'bring'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'The past tense of bring is brought (irregular verb).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-eng-037',
    type: 'mcq',
    question: 'Choose the correct form: "I have _____ my homework."',
    options: ['do', 'did', 'done', 'doing'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'After "have", we use the past participle "done".',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-eng-038',
    type: 'mcq',
    question: 'Which sentence is in the future tense?',
    options: ['She goes to school.', 'She went to school.', 'She will go to school.', 'She is going to school.'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: '"Will go" indicates future tense.',
    source: 'practice',
    year: 2021,
  },

  // JHS English Language - More Vocabulary
  {
    id: 'jhs-eng-039',
    type: 'mcq',
    question: 'Choose the word closest in meaning to "benevolent".',
    options: ['Kind', 'Angry', 'Lazy', 'Proud'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Synonyms',
    explanation: 'Benevolent means kind, generous, or well-meaning.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-eng-040',
    type: 'mcq',
    question: 'What is the opposite of "brave"?',
    options: ['Strong', 'Cowardly', 'Bold', 'Fearless'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Antonyms',
    explanation: 'The opposite of brave is cowardly.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-eng-041',
    type: 'mcq',
    question: 'A person who writes novels is called a...',
    options: ['Poet', 'Novelist', 'Author', 'Writer'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'A novelist specifically writes novels.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-eng-042',
    type: 'mcq',
    question: 'What does "punctual" mean?',
    options: ['Late', 'On time', 'Early', 'Slow'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'Punctual means arriving or happening at the scheduled time.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-eng-043',
    type: 'mcq',
    question: 'Choose the word nearest in meaning to "enormous".',
    options: ['Small', 'Tiny', 'Huge', 'Little'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Synonyms',
    explanation: 'Enormous means extremely large or huge.',
    source: 'practice',
    year: 2021,
  },

  // JHS English Language - More Literature
  {
    id: 'jhs-eng-044',
    type: 'mcq',
    question: 'In literature, what term describes the main character in a story?',
    options: ['Antagonist', 'Narrator', 'Protagonist', 'Foil'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Literature',
    explanation: 'The protagonist is the main character around whom the story revolves.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-eng-045',
    type: 'mcq',
    question: 'In literature, what is a character who contrasts with another to highlight qualities called?',
    options: ['Protagonist', 'Antagonist', 'Foil', 'Narrator'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Literature',
    explanation: 'A foil is a character who contrasts with another character to highlight particular qualities.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-eng-046',
    type: 'mcq',
    question: 'What is the setting of a story?',
    options: ['The main character', 'The time and place', 'The conflict', 'The resolution'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Literature',
    explanation: 'Setting refers to the time and place where the story occurs.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-eng-047',
    type: 'mcq',
    question: 'Which figure of speech uses "like" or "as" to compare two things?',
    options: ['Metaphor', 'Simile', 'Personification', 'Hyperbole'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Literature',
    explanation: 'A simile uses "like" or "as" to make comparisons.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-eng-048',
    type: 'mcq',
    question: 'What is the term for an exaggeration used for emphasis?',
    options: ['Simile', 'Metaphor', 'Hyperbole', 'Personification'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Literature',
    explanation: 'Hyperbole is an exaggerated statement used for emphasis or effect.',
    source: 'practice',
    year: 2020,
  },

  // JHS English Language - More Grammar
  {
    id: 'jhs-eng-049',
    type: 'mcq',
    question: 'Choose the correct form: "Neither John nor Mary _____ present."',
    options: ['is', 'are', 'was', 'were'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'With neither/nor, the verb agrees with the noun closest to it. "Mary" is singular, so "is".',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-eng-050',
    type: 'mcq',
    question: 'Which sentence uses the correct form of "your"?',
    options: ['Your welcome.', 'You\'re welcome.', 'You welcome.', 'Yours welcome.'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: '"You\'re" is the contraction of "you are".',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-eng-051',
    type: 'mcq',
    question: 'What is the superlative form of "good"?',
    options: ['gooder', 'goodest', 'better', 'best'],
    correctAnswer: 3,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Good, better, best - irregular comparison.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-eng-052',
    type: 'mcq',
    question: 'Choose the correct form: "This is _____ book."',
    options: ['my', 'me', 'I', 'mine'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: '"My" is a possessive adjective used before a noun.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-eng-053',
    type: 'mcq',
    question: 'Which is the correct question tag: "She can swim, _____?"',
    options: ['can she', 'can\'t she', 'doesn\'t she', 'isn\'t she'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Positive statement with "can" takes negative tag "can\'t she".',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-eng-054',
    type: 'mcq',
    question: 'What type of word is "beautifully" in "She sings beautifully"?',
    options: ['Adjective', 'Adverb', 'Noun', 'Verb'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: '"Beautifully" modifies the verb "sings", so it\'s an adverb.',
    source: 'practice',
    year: 2020,
  },

  // JHS English Language - More Idioms & Expressions
  {
    id: 'jhs-eng-055',
    type: 'mcq',
    question: 'The idiom "break the ice" means...',
    options: ['to break something', 'to start a conversation', 'to end a friendship', 'to be cold'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Idioms',
    explanation: '"Break the ice" means to initiate conversation in a social setting.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-eng-056',
    type: 'mcq',
    question: 'The expression "once in a blue moon" means...',
    options: ['very often', 'very rarely', 'at night', 'during the day'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Idioms',
    explanation: '"Once in a blue moon" means very rarely or almost never.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-eng-057',
    type: 'mcq',
    question: 'The phrase "under the weather" means...',
    options: ['feeling unwell', 'feeling great', 'outside', 'inside'],
    correctAnswer: 0,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Idioms',
    explanation: '"Under the weather" means feeling sick or unwell.',
    source: 'practice',
    year: 2021,
  },

  // JHS English Language - More Spelling
  {
    id: 'jhs-eng-058',
    type: 'mcq',
    question: 'Choose the correct spelling.',
    options: ['Seperate', 'Separate', 'Seperete', 'Separete'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Spelling',
    explanation: 'Separate is spelled with "a" in the middle.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-eng-059',
    type: 'mcq',
    question: 'Choose the correct spelling.',
    options: ['Definately', 'Definitely', 'Definately', 'Definitley'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Spelling',
    explanation: 'Definitely is spelled with "i" before "tely".',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-eng-060',
    type: 'mcq',
    question: 'Choose the correct spelling.',
    options: ['Accomodate', 'Accommodate', 'Acommodate', 'Acomodate'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Spelling',
    explanation: 'Accommodate has double "c" and double "m".',
    source: 'practice',
    year: 2020,
  },

  // JHS English Language - More Comprehension Style
  {
    id: 'jhs-eng-061',
    type: 'mcq',
    question: 'If someone is known for punctuality, what trait do they have?',
    options: ['They are always late', 'They are always on time', 'They are lazy', 'They are forgetful'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Comprehension',
    explanation: 'Punctuality means being on time or prompt.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-eng-062',
    type: 'mcq',
    question: 'What time of day is described by "The sun set behind the hills"?',
    options: ['Morning', 'Afternoon', 'Evening', 'Midnight'],
    correctAnswer: 2,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Comprehension',
    explanation: 'Sunset occurs in the evening.',
    source: 'practice',
    year: 2020,
  },

  // JHS English Language - More Advanced Grammar
  {
    id: 'jhs-eng-063',
    type: 'mcq',
    question: 'Change to indirect speech: "I am tired," he said.',
    options: ['He said he is tired.', 'He said he was tired.', 'He said he am tired.', 'He said I am tired.'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'In indirect speech, present tense changes to past tense, and pronouns change.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-eng-064',
    type: 'mcq',
    question: 'Which sentence is grammatically correct?',
    options: ['The books is on the table.', 'The books are on the table.', 'The books was on the table.', 'The books were on the table.'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Plural subject "books" requires plural verb "are".',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-eng-065',
    type: 'mcq',
    question: 'What is the plural of "mouse" (the animal)?',
    options: ['mouses', 'mice', 'mouse', 'mices'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'The plural of mouse is mice (irregular plural).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-eng-066',
    type: 'mcq',
    question: 'What is the plural of "tooth"?',
    options: ['tooths', 'teeth', 'tooth', 'toothes'],
    correctAnswer: 1,
    subject: 'English Language',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'The plural of tooth is teeth (irregular plural).',
    source: 'practice',
    year: 2020,
  },
];

