import type { ChallengeQuestion } from '../types';

/**
 * JHS French Question Bank
 * BECE French
 * Topics: Greetings, Vocabulary, Grammar, Conversation, Numbers, Colors, Days, Months
 */

export const jhsFrenchQuestions: ChallengeQuestion[] = [
  // ============================================
  // Greetings & Common Phrases
  // ============================================
  {
    id: 'jhs-fr-001',
    type: 'mcq',
    question: 'How do you say "Hello" in French?',
    options: ['Bonjour', 'Au revoir', 'Merci', 'S\'il vous plaît'],
    correctAnswer: 0,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Greetings',
    explanation: 'Bonjour means hello or good day.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-002',
    type: 'mcq',
    question: 'How do you say "Goodbye" in French?',
    options: ['Bonjour', 'Au revoir', 'Bonsoir', 'Bonne nuit'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Greetings',
    explanation: 'Au revoir means goodbye.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-fr-003',
    type: 'mcq',
    question: 'How do you say "Good morning" in French?',
    options: ['Bonsoir', 'Bonne nuit', 'Bonjour', 'Au revoir'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Greetings',
    explanation: 'Bonjour is used for good morning.',
    source: 'practice',
    year: 2016,
  },
  {
    id: 'jhs-fr-004',
    type: 'mcq',
    question: 'How do you say "Good evening" in French?',
    options: ['Bonjour', 'Bonsoir', 'Bonne nuit', 'Au revoir'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Greetings',
    explanation: 'Bonsoir means good evening.',
    source: 'practice',
    year: 2015,
  },
  {
    id: 'jhs-fr-005',
    type: 'mcq',
    question: 'What does "Bonne nuit" mean?',
    options: ['Good morning', 'Good afternoon', 'Good evening', 'Good night'],
    correctAnswer: 3,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Greetings',
    explanation: 'Bonne nuit means good night.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-006',
    type: 'mcq',
    question: 'What does "Merci" mean in English?',
    options: ['Please', 'Thank you', 'Hello', 'Goodbye'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Common Phrases',
    explanation: 'Merci means thank you.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-fr-007',
    type: 'mcq',
    question: 'How do you say "Please" in French?',
    options: ['Merci', 'S\'il vous plaît', 'Excusez-moi', 'Pardon'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Common Phrases',
    explanation: 'S\'il vous plaît means please.',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-fr-008',
    type: 'mcq',
    question: 'What does "Excusez-moi" mean?',
    options: ['Thank you', 'Please', 'Excuse me', 'Goodbye'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Common Phrases',
    explanation: 'Excusez-moi means excuse me.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-fr-009',
    type: 'mcq',
    question: 'What does "Pardon" mean?',
    options: ['Please', 'Thank you', 'Sorry', 'Hello'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Common Phrases',
    explanation: 'Pardon means sorry or excuse me.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Common Words - Yes/No/Maybe
  // ============================================
  {
    id: 'jhs-fr-010',
    type: 'mcq',
    question: 'What does "Oui" mean?',
    options: ['No', 'Yes', 'Maybe', 'Hello'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Common Words',
    explanation: 'Oui means yes.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-fr-011',
    type: 'mcq',
    question: 'What does "Non" mean?',
    options: ['Yes', 'No', 'Maybe', 'Please'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Common Words',
    explanation: 'Non means no.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-fr-012',
    type: 'mcq',
    question: 'What does "Peut-être" mean?',
    options: ['Yes', 'No', 'Maybe', 'Please'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Common Words',
    explanation: 'Peut-être means maybe or perhaps.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Introductions & Conversation
  // ============================================
  {
    id: 'jhs-fr-013',
    type: 'mcq',
    question: 'How do you say "My name is" in French?',
    options: ['Je m\'appelle', 'Comment allez-vous?', 'Je suis', 'J\'ai'],
    correctAnswer: 0,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Introductions',
    explanation: 'Je m\'appelle means my name is.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-014',
    type: 'mcq',
    question: 'How do you say "What is your name?" in French?',
    options: ['Comment allez-vous?', 'Quel est votre nom?', 'Où habitez-vous?', 'Comment vous appelez-vous?'],
    correctAnswer: 3,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Conversation',
    explanation: 'Comment vous appelez-vous? means what is your name?',
    source: 'practice',
    year: 2016,
  },
  {
    id: 'jhs-fr-015',
    type: 'mcq',
    question: 'How do you say "How are you?" in French?',
    options: ['Comment allez-vous?', 'Quel est votre nom?', 'Où êtes-vous?', 'Quel âge avez-vous?'],
    correctAnswer: 0,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Conversation',
    explanation: 'Comment allez-vous? means how are you?',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-fr-016',
    type: 'mcq',
    question: 'How do you say "I am fine" in French?',
    options: ['Je suis bien', 'Je vais bien', 'Je suis malade', 'Je suis fatigué'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Conversation',
    explanation: 'Je vais bien means I am fine.',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-fr-017',
    type: 'mcq',
    question: 'How do you say "I don\'t understand" in French?',
    options: ['Je comprends', 'Je ne comprends pas', 'Je sais', 'Je ne sais pas'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Conversation',
    explanation: 'Je ne comprends pas means I don\'t understand.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-fr-018',
    type: 'mcq',
    question: 'How do you say "I don\'t know" in French?',
    options: ['Je comprends', 'Je ne comprends pas', 'Je sais', 'Je ne sais pas'],
    correctAnswer: 3,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Conversation',
    explanation: 'Je ne sais pas means I don\'t know.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-fr-019',
    type: 'mcq',
    question: 'How do you say "Where are you from?" in French?',
    options: ['Où êtes-vous?', 'D\'où venez-vous?', 'Où habitez-vous?', 'Où allez-vous?'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Conversation',
    explanation: 'D\'où venez-vous? means where are you from?',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-020',
    type: 'mcq',
    question: 'How do you say "Where do you live?" in French?',
    options: ['Où êtes-vous?', 'D\'où venez-vous?', 'Où habitez-vous?', 'Où allez-vous?'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Conversation',
    explanation: 'Où habitez-vous? means where do you live?',
    source: 'practice',
    year: 2019,
  },

  // ============================================
  // Vocabulary - Basic Words
  // ============================================
  {
    id: 'jhs-fr-021',
    type: 'mcq',
    question: 'What is the French word for "water"?',
    options: ['Pain', 'Eau', 'Lait', 'Café'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'Eau means water.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-fr-022',
    type: 'mcq',
    question: 'What is the French word for "bread"?',
    options: ['Eau', 'Pain', 'Fromage', 'Beurre'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'Pain means bread.',
    source: 'practice',
    year: 2015,
  },
  {
    id: 'jhs-fr-023',
    type: 'mcq',
    question: 'What is the French word for "milk"?',
    options: ['Eau', 'Pain', 'Lait', 'Café'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'Lait means milk.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-024',
    type: 'mcq',
    question: 'What is the French word for "school"?',
    options: ['Maison', 'École', 'Voiture', 'Livre'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'École means school.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-fr-025',
    type: 'mcq',
    question: 'What is the French word for "house"?',
    options: ['École', 'Maison', 'Voiture', 'Jardin'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'Maison means house.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-fr-026',
    type: 'mcq',
    question: 'What is the French word for "book"?',
    options: ['Crayon', 'Livre', 'Cahier', 'Stylo'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'Livre means book.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-fr-027',
    type: 'mcq',
    question: 'What is the French word for "car"?',
    options: ['Maison', 'École', 'Voiture', 'Livre'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'Voiture means car.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-028',
    type: 'mcq',
    question: 'What is the French word for "pen"?',
    options: ['Crayon', 'Livre', 'Cahier', 'Stylo'],
    correctAnswer: 3,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'Stylo means pen.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-fr-029',
    type: 'mcq',
    question: 'What is the French word for "pencil"?',
    options: ['Crayon', 'Livre', 'Cahier', 'Stylo'],
    correctAnswer: 0,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'Crayon means pencil.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-030',
    type: 'mcq',
    question: 'What is the French word for "notebook"?',
    options: ['Crayon', 'Livre', 'Cahier', 'Stylo'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Vocabulary',
    explanation: 'Cahier means notebook.',
    source: 'practice',
    year: 2019,
  },

  // ============================================
  // Numbers
  // ============================================
  {
    id: 'jhs-fr-031',
    type: 'mcq',
    question: 'What is the French word for "one"?',
    options: ['Un', 'Deux', 'Trois', 'Quatre'],
    correctAnswer: 0,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'Un (masculine) or Une (feminine) means one.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-032',
    type: 'mcq',
    question: 'What is the French word for "two"?',
    options: ['Un', 'Deux', 'Trois', 'Quatre'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'Deux means two.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-fr-033',
    type: 'mcq',
    question: 'What is the French word for "three"?',
    options: ['Un', 'Deux', 'Trois', 'Quatre'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'Trois means three.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-fr-034',
    type: 'mcq',
    question: 'What is the French word for "ten"?',
    options: ['Cinq', 'Six', 'Dix', 'Douze'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'Dix means ten.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-035',
    type: 'mcq',
    question: 'What is the French word for "twenty"?',
    options: ['Dix', 'Quinze', 'Vingt', 'Trente'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'Vingt means twenty.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Colors
  // ============================================
  {
    id: 'jhs-fr-036',
    type: 'mcq',
    question: 'What is the French word for "red"?',
    options: ['Rouge', 'Bleu', 'Vert', 'Jaune'],
    correctAnswer: 0,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Colors',
    explanation: 'Rouge means red.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-037',
    type: 'mcq',
    question: 'What is the French word for "blue"?',
    options: ['Rouge', 'Bleu', 'Vert', 'Jaune'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Colors',
    explanation: 'Bleu means blue.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-fr-038',
    type: 'mcq',
    question: 'What is the French word for "green"?',
    options: ['Rouge', 'Bleu', 'Vert', 'Jaune'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Colors',
    explanation: 'Vert means green.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-fr-039',
    type: 'mcq',
    question: 'What is the French word for "yellow"?',
    options: ['Rouge', 'Bleu', 'Vert', 'Jaune'],
    correctAnswer: 3,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Colors',
    explanation: 'Jaune means yellow.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-040',
    type: 'mcq',
    question: 'What is the French word for "white"?',
    options: ['Noir', 'Blanc', 'Gris', 'Rose'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Colors',
    explanation: 'Blanc (masculine) or Blanche (feminine) means white.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-fr-041',
    type: 'mcq',
    question: 'What is the French word for "black"?',
    options: ['Noir', 'Blanc', 'Gris', 'Rose'],
    correctAnswer: 0,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Colors',
    explanation: 'Noir (masculine) or Noire (feminine) means black.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Days of the Week
  // ============================================
  {
    id: 'jhs-fr-042',
    type: 'mcq',
    question: 'What is the French word for "Monday"?',
    options: ['Lundi', 'Mardi', 'Mercredi', 'Jeudi'],
    correctAnswer: 0,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Days',
    explanation: 'Lundi means Monday.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-fr-043',
    type: 'mcq',
    question: 'What is the French word for "Sunday"?',
    options: ['Vendredi', 'Samedi', 'Dimanche', 'Lundi'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Days',
    explanation: 'Dimanche means Sunday.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-044',
    type: 'mcq',
    question: 'What is the French word for "Saturday"?',
    options: ['Vendredi', 'Samedi', 'Dimanche', 'Lundi'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Days',
    explanation: 'Samedi means Saturday.',
    source: 'practice',
    year: 2019,
  },

  // ============================================
  // Months
  // ============================================
  {
    id: 'jhs-fr-045',
    type: 'mcq',
    question: 'What is the French word for "January"?',
    options: ['Janvier', 'Février', 'Mars', 'Avril'],
    correctAnswer: 0,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Months',
    explanation: 'Janvier means January.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-fr-046',
    type: 'mcq',
    question: 'What is the French word for "December"?',
    options: ['Octobre', 'Novembre', 'Décembre', 'Janvier'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Months',
    explanation: 'Décembre means December.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Family Members
  // ============================================
  {
    id: 'jhs-fr-047',
    type: 'mcq',
    question: 'What is the French word for "mother"?',
    options: ['Père', 'Mère', 'Frère', 'Sœur'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Family',
    explanation: 'Mère means mother.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-fr-048',
    type: 'mcq',
    question: 'What is the French word for "father"?',
    options: ['Père', 'Mère', 'Frère', 'Sœur'],
    correctAnswer: 0,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Family',
    explanation: 'Père means father.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-049',
    type: 'mcq',
    question: 'What is the French word for "brother"?',
    options: ['Père', 'Mère', 'Frère', 'Sœur'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Family',
    explanation: 'Frère means brother.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-fr-050',
    type: 'mcq',
    question: 'What is the French word for "sister"?',
    options: ['Père', 'Mère', 'Frère', 'Sœur'],
    correctAnswer: 3,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Family',
    explanation: 'Sœur means sister.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Grammar - Articles
  // ============================================
  {
    id: 'jhs-fr-051',
    type: 'mcq',
    question: 'What is the masculine definite article in French?',
    options: ['La', 'Le', 'Les', 'Un'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Le is the masculine definite article (the).',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-052',
    type: 'mcq',
    question: 'What is the feminine definite article in French?',
    options: ['La', 'Le', 'Les', 'Une'],
    correctAnswer: 0,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'La is the feminine definite article (the).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-fr-053',
    type: 'mcq',
    question: 'What is the plural definite article in French?',
    options: ['La', 'Le', 'Les', 'Des'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Les is the plural definite article (the).',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-fr-054',
    type: 'mcq',
    question: 'What is the masculine indefinite article in French?',
    options: ['La', 'Le', 'Un', 'Une'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Un is the masculine indefinite article (a/an).',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-055',
    type: 'mcq',
    question: 'What is the feminine indefinite article in French?',
    options: ['La', 'Le', 'Un', 'Une'],
    correctAnswer: 3,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Une is the feminine indefinite article (a/an).',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Grammar - Verb "To Be"
  // ============================================
  {
    id: 'jhs-fr-056',
    type: 'mcq',
    question: 'How do you say "I am" in French?',
    options: ['Je suis', 'Tu es', 'Il est', 'Nous sommes'],
    correctAnswer: 0,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Je suis means I am (from the verb être - to be).',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-057',
    type: 'mcq',
    question: 'How do you say "You are" (singular, informal) in French?',
    options: ['Je suis', 'Tu es', 'Il est', 'Vous êtes'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Tu es means you are (singular, informal).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-fr-058',
    type: 'mcq',
    question: 'How do you say "We are" in French?',
    options: ['Je suis', 'Tu es', 'Il est', 'Nous sommes'],
    correctAnswer: 3,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Nous sommes means we are.',
    source: 'practice',
    year: 2019,
  },

  // ============================================
  // Grammar - Verb "To Have"
  // ============================================
  {
    id: 'jhs-fr-059',
    type: 'mcq',
    question: 'How do you say "I have" in French?',
    options: ['J\'ai', 'Tu as', 'Il a', 'Nous avons'],
    correctAnswer: 0,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'J\'ai means I have (from the verb avoir - to have).',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-060',
    type: 'mcq',
    question: 'How do you say "You have" (singular, informal) in French?',
    options: ['J\'ai', 'Tu as', 'Il a', 'Vous avez'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Tu as means you have (singular, informal).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-fr-061',
    type: 'mcq',
    question: 'How do you say "We have" in French?',
    options: ['J\'ai', 'Tu as', 'Il a', 'Nous avons'],
    correctAnswer: 3,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Grammar',
    explanation: 'Nous avons means we have.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Time & Questions
  // ============================================
  {
    id: 'jhs-fr-062',
    type: 'mcq',
    question: 'How do you say "What time is it?" in French?',
    options: ['Quelle heure est-il?', 'Quel jour est-il?', 'Quelle date?', 'Quand?'],
    correctAnswer: 0,
    subject: 'French',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Time',
    explanation: 'Quelle heure est-il? means what time is it?',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-fr-063',
    type: 'mcq',
    question: 'How do you say "How old are you?" in French?',
    options: ['Comment allez-vous?', 'Quel est votre nom?', 'Quel âge avez-vous?', 'Où habitez-vous?'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Conversation',
    explanation: 'Quel âge avez-vous? means how old are you?',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-064',
    type: 'mcq',
    question: 'How do you say "What?" in French?',
    options: ['Qui?', 'Quoi?', 'Où?', 'Quand?'],
    correctAnswer: 1,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Questions',
    explanation: 'Quoi? means what?',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-fr-065',
    type: 'mcq',
    question: 'How do you say "Who?" in French?',
    options: ['Qui?', 'Quoi?', 'Où?', 'Quand?'],
    correctAnswer: 0,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Questions',
    explanation: 'Qui? means who?',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-fr-066',
    type: 'mcq',
    question: 'How do you say "Where?" in French?',
    options: ['Qui?', 'Quoi?', 'Où?', 'Quand?'],
    correctAnswer: 2,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Questions',
    explanation: 'Où? means where?',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-fr-067',
    type: 'mcq',
    question: 'How do you say "When?" in French?',
    options: ['Qui?', 'Quoi?', 'Où?', 'Quand?'],
    correctAnswer: 3,
    subject: 'French',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Questions',
    explanation: 'Quand? means when?',
    source: 'practice',
    year: 2021,
  },
];
