// JHS ICT (Information and Communication Technology) Questions
// BECE-level questions migrated to modular ChallengeQuestion format
// NOTE: These are practice-style BECE-level questions, not yet tagged as verified past questions.

import type { ChallengeQuestion } from '../types';

export const jhsICTQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Initial Batch - From bece-questions.ts)
  // ============================================

  // JHS ICT - Basics & Hardware
  {
    id: 'jhs-ict-001',
    type: 'mcq',
    question: 'What does ICT stand for?',
    options: ['Information and Communication Technology', 'International Computer Technology', 'Internet Communication Tools', 'Integrated Computer Technology'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Basics',
    explanation: 'ICT stands for Information and Communication Technology.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-002',
    type: 'mcq',
    question: 'Which of these is an input device?',
    options: ['Monitor', 'Printer', 'Keyboard', 'Speaker'],
    correctAnswer: 2,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Hardware',
    explanation: 'Keyboard is used to input data into a computer.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ict-003',
    type: 'mcq',
    question: 'The brain of a computer is the...',
    options: ['Monitor', 'CPU', 'Keyboard', 'Mouse'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Hardware',
    explanation: 'CPU (Central Processing Unit) processes all instructions.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-ict-004',
    type: 'mcq',
    question: 'Which of these is an output device?',
    options: ['Keyboard', 'Mouse', 'Printer', 'Scanner'],
    correctAnswer: 2,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Hardware',
    explanation: 'Printer produces output (printed documents).',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-005',
    type: 'mcq',
    question: 'RAM stands for...',
    options: ['Random Access Memory', 'Read Access Memory', 'Random Application Memory', 'Read Application Memory'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Hardware',
    explanation: 'RAM is temporary storage that the computer uses actively.',
    source: 'practice',
    year: 2016,
  },
  {
    id: 'jhs-ict-006',
    type: 'mcq',
    question: 'What does CPU stand for?',
    options: ['Central Processing Unit', 'Computer Processing Unit', 'Central Program Unit', 'Computer Program Unit'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Hardware',
    explanation: 'CPU executes instructions and processes data.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-ict-007',
    type: 'mcq',
    question: 'Which storage device has the largest capacity?',
    options: ['USB Flash Drive', 'CD', 'Hard Disk', 'Floppy Disk'],
    correctAnswer: 2,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Storage',
    explanation: 'Hard disks can store terabytes of data.',
    source: 'practice',
    year: 2020,
  },

  // JHS ICT - Software
  {
    id: 'jhs-ict-008',
    type: 'mcq',
    question: 'Which software is used to create documents?',
    options: ['Spreadsheet', 'Word Processor', 'Database', 'Presentation'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Software',
    explanation: 'Word processors like Microsoft Word create documents.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-009',
    type: 'mcq',
    question: 'A spreadsheet is used for...',
    options: ['Writing letters', 'Creating presentations', 'Organizing and calculating data', 'Browsing the internet'],
    correctAnswer: 2,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Software',
    explanation: 'Spreadsheets like Excel organize data in rows and columns.',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-ict-010',
    type: 'mcq',
    question: 'To save a document, you press...',
    options: ['Ctrl + S', 'Ctrl + C', 'Ctrl + V', 'Ctrl + X'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Software',
    explanation: 'Ctrl + S is the keyboard shortcut to save.',
    source: 'practice',
    year: 2015,
  },
  {
    id: 'jhs-ict-011',
    type: 'mcq',
    question: 'To copy text, you use...',
    options: ['Ctrl + C', 'Ctrl + V', 'Ctrl + X', 'Ctrl + Z'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Software',
    explanation: 'Ctrl + C copies selected text to clipboard.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ict-012',
    type: 'mcq',
    question: 'To paste text, you use...',
    options: ['Ctrl + C', 'Ctrl + V', 'Ctrl + X', 'Ctrl + Z'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Software',
    explanation: 'Ctrl + V pastes copied text.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-013',
    type: 'mcq',
    question: 'To undo an action, you press...',
    options: ['Ctrl + C', 'Ctrl + V', 'Ctrl + X', 'Ctrl + Z'],
    correctAnswer: 3,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Software',
    explanation: 'Ctrl + Z undoes the last action.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-014',
    type: 'mcq',
    question: 'Which file extension is for images?',
    options: ['.txt', '.jpg', '.doc', '.xls'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'File Types',
    explanation: '.jpg is a common image file format.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-015',
    type: 'mcq',
    question: 'Which file extension is for documents?',
    options: ['.jpg', '.mp3', '.doc', '.exe'],
    correctAnswer: 2,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'File Types',
    explanation: '.doc is the extension for Microsoft Word documents.',
    source: 'practice',
    year: 2020,
  },

  // JHS ICT - Internet & Networking
  {
    id: 'jhs-ict-016',
    type: 'mcq',
    question: 'The internet is a...',
    options: ['Computer', 'Network of networks', 'Software program', 'Hardware device'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Internet',
    explanation: 'The internet connects millions of networks worldwide.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-ict-017',
    type: 'mcq',
    question: 'Which of these is a web browser?',
    options: ['Microsoft Word', 'Google Chrome', 'Excel', 'PowerPoint'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Internet',
    explanation: 'Google Chrome is used to browse the internet.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-ict-018',
    type: 'mcq',
    question: 'What is the full form of URL?',
    options: ['Uniform Resource Locator', 'Universal Resource Link', 'Uniform Resource Link', 'Universal Resource Locator'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Internet',
    explanation: 'URL identifies the location of a resource on the internet.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-ict-019',
    type: 'mcq',
    question: 'Which protocol is used for secure web browsing?',
    options: ['HTTP', 'HTTPS', 'FTP', 'SMTP'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Internet',
    explanation: 'HTTPS encrypts data for secure transmission.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-020',
    type: 'mcq',
    question: 'Which of these is a search engine?',
    options: ['Facebook', 'Google', 'WhatsApp', 'Instagram'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Internet',
    explanation: 'Google helps you search for information on the internet.',
    source: 'practice',
    year: 2016,
  },
  {
    id: 'jhs-ict-021',
    type: 'mcq',
    question: 'Email stands for...',
    options: ['Electronic Mail', 'Easy Mail', 'Express Mail', 'External Mail'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Internet',
    explanation: 'Email allows sending messages electronically.',
    source: 'practice',
    year: 2018,
  },

  // JHS ICT - File Management
  {
    id: 'jhs-ict-022',
    type: 'mcq',
    question: 'A collection of related files is called a...',
    options: ['Folder', 'File', 'Document', 'Program'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'File Management',
    explanation: 'Folders organize related files together.',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-ict-023',
    type: 'mcq',
    question: 'What is the main folder on a computer called?',
    options: ['Subfolder', 'Root folder', 'Desktop', 'My Documents'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'File Management',
    explanation: 'The root folder (like C:\\) is the main directory on a computer.',
    source: 'practice',
    year: 2020,
  },

  // JHS ICT - Security
  {
    id: 'jhs-ict-024',
    type: 'mcq',
    question: 'A virus in computing is...',
    options: ['A helpful program', 'Malicious software', 'A hardware component', 'An operating system'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Security',
    explanation: 'Computer viruses are harmful programs that can damage files.',
    source: 'practice',
    year: 2015,
  },
  {
    id: 'jhs-ict-025',
    type: 'mcq',
    question: 'Which of these helps protect your computer from viruses?',
    options: ['Antivirus software', 'Word processor', 'Spreadsheet', 'Web browser'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Security',
    explanation: 'Antivirus software detects and removes viruses.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Additional BECE ICT Questions (Batch 2 - From Online Sources)
  // ============================================

  // JHS ICT - More Hardware
  {
    id: 'jhs-ict-026',
    type: 'mcq',
    question: 'Which of these is a pointing device?',
    options: ['Keyboard', 'Mouse', 'Monitor', 'Printer'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Hardware',
    explanation: 'Mouse is used to point and click on items on the screen.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-027',
    type: 'mcq',
    question: 'What does ROM stand for?',
    options: ['Random Only Memory', 'Read Only Memory', 'Random Open Memory', 'Read Open Memory'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Hardware',
    explanation: 'ROM (Read Only Memory) stores permanent instructions that cannot be changed.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-028',
    type: 'mcq',
    question: 'Which device is used to display output on screen?',
    options: ['Keyboard', 'Mouse', 'Monitor', 'Printer'],
    correctAnswer: 2,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Hardware',
    explanation: 'Monitor displays visual output from the computer.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-029',
    type: 'mcq',
    question: 'Which of these is a storage device?',
    options: ['CPU', 'RAM', 'USB Flash Drive', 'Monitor'],
    correctAnswer: 2,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Storage',
    explanation: 'USB Flash Drive is used to store and transfer data.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-030',
    type: 'mcq',
    question: 'What is the smallest unit of data in a computer?',
    options: ['Byte', 'Bit', 'Kilobyte', 'Megabyte'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Basics',
    explanation: 'A bit (binary digit) is the smallest unit, representing 0 or 1.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-031',
    type: 'mcq',
    question: 'How many bits make a byte?',
    options: ['4', '8', '16', '32'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Basics',
    explanation: '1 byte = 8 bits.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-032',
    type: 'mcq',
    question: 'Which of these is an input device?',
    options: ['Speaker', 'Printer', 'Scanner', 'Monitor'],
    correctAnswer: 2,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Hardware',
    explanation: 'Scanner inputs images or documents into the computer.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-033',
    type: 'mcq',
    question: 'Which device produces sound output?',
    options: ['Keyboard', 'Mouse', 'Speaker', 'Scanner'],
    correctAnswer: 2,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Hardware',
    explanation: 'Speaker produces audio output from the computer.',
    source: 'practice',
    year: 2021,
  },

  // JHS ICT - More Software & Applications
  {
    id: 'jhs-ict-034',
    type: 'mcq',
    question: 'Which software is used to create presentations?',
    options: ['Word Processor', 'Spreadsheet', 'Presentation Software', 'Database'],
    correctAnswer: 2,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Software',
    explanation: 'Presentation software like PowerPoint creates slideshows.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-035',
    type: 'mcq',
    question: 'Which software manages the computer\'s resources?',
    options: ['Word Processor', 'Operating System', 'Web Browser', 'Spreadsheet'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Software',
    explanation: 'Operating System (like Windows) manages hardware and software resources.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-036',
    type: 'mcq',
    question: 'To cut text, you use...',
    options: ['Ctrl + C', 'Ctrl + V', 'Ctrl + X', 'Ctrl + Z'],
    correctAnswer: 2,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Software',
    explanation: 'Ctrl + X cuts selected text (removes and copies to clipboard).',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-037',
    type: 'mcq',
    question: 'To select all text, you press...',
    options: ['Ctrl + A', 'Ctrl + S', 'Ctrl + D', 'Ctrl + F'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Software',
    explanation: 'Ctrl + A selects all content in a document.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-038',
    type: 'mcq',
    question: 'To find text in a document, you press...',
    options: ['Ctrl + A', 'Ctrl + S', 'Ctrl + D', 'Ctrl + F'],
    correctAnswer: 3,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Software',
    explanation: 'Ctrl + F opens the find/search dialog.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-039',
    type: 'mcq',
    question: 'Which file extension is for spreadsheets?',
    options: ['.doc', '.xls', '.jpg', '.mp3'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'File Types',
    explanation: '.xls is the extension for Microsoft Excel spreadsheets.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-040',
    type: 'mcq',
    question: 'Which file extension is for presentations?',
    options: ['.doc', '.xls', '.ppt', '.jpg'],
    correctAnswer: 2,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'File Types',
    explanation: '.ppt is the extension for Microsoft PowerPoint presentations.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-041',
    type: 'mcq',
    question: 'Which file extension is for audio files?',
    options: ['.jpg', '.mp3', '.doc', '.xls'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'File Types',
    explanation: '.mp3 is a common audio file format.',
    source: 'practice',
    year: 2021,
  },

  // JHS ICT - More Internet & Networking
  {
    id: 'jhs-ict-042',
    type: 'mcq',
    question: 'What does WWW stand for?',
    options: ['World Wide Web', 'World Web Wide', 'Wide World Web', 'Web World Wide'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Internet',
    explanation: 'WWW stands for World Wide Web.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-043',
    type: 'mcq',
    question: 'What does HTTP stand for?',
    options: ['HyperText Transfer Protocol', 'HyperText Transport Protocol', 'HyperTransfer Text Protocol', 'HyperTransport Text Protocol'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Internet',
    explanation: 'HTTP is the protocol used for transferring web pages.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-044',
    type: 'mcq',
    question: 'What does HTML stand for?',
    options: ['HyperText Markup Language', 'HyperText Making Language', 'HyperTransfer Markup Language', 'HyperTransfer Making Language'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Internet',
    explanation: 'HTML is used to create web pages.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-045',
    type: 'mcq',
    question: 'Which of these is a social media platform?',
    options: ['Microsoft Word', 'Google Chrome', 'Facebook', 'Excel'],
    correctAnswer: 2,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Internet',
    explanation: 'Facebook is a social networking platform.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-046',
    type: 'mcq',
    question: 'What is a website address called?',
    options: ['URL', 'CPU', 'RAM', 'ROM'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Internet',
    explanation: 'URL (Uniform Resource Locator) is the address of a website.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-047',
    type: 'mcq',
    question: 'Which of these is an email service?',
    options: ['Gmail', 'Word', 'Excel', 'PowerPoint'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Internet',
    explanation: 'Gmail is Google\'s email service.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-048',
    type: 'mcq',
    question: 'What does ISP stand for?',
    options: ['Internet Service Provider', 'Internet System Provider', 'Internet Service Program', 'Internet System Program'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Internet',
    explanation: 'ISP provides internet connection services to users.',
    source: 'practice',
    year: 2020,
  },

  // JHS ICT - More File Management
  {
    id: 'jhs-ict-049',
    type: 'mcq',
    question: 'To create a new folder, you usually...',
    options: ['Right-click and select New Folder', 'Press Ctrl + N', 'Press Delete', 'Double-click'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'File Management',
    explanation: 'Right-click in a location and select "New Folder" to create a folder.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-050',
    type: 'mcq',
    question: 'To delete a file, you can press...',
    options: ['Ctrl + D', 'Delete key', 'Ctrl + S', 'Ctrl + C'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'File Management',
    explanation: 'The Delete key removes selected files.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-051',
    type: 'mcq',
    question: 'What does PDF stand for?',
    options: ['Portable Document Format', 'Personal Document Format', 'Portable Data Format', 'Personal Data Format'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'File Types',
    explanation: 'PDF is a file format that preserves document formatting.',
    source: 'practice',
    year: 2021,
  },

  // JHS ICT - More Security & Ethics
  {
    id: 'jhs-ict-052',
    type: 'mcq',
    question: 'A strong password should...',
    options: ['Be easy to remember', 'Contain personal information', 'Be long and include numbers and symbols', 'Be your name'],
    correctAnswer: 2,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Security',
    explanation: 'Strong passwords are long, complex, and include various character types.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-053',
    type: 'mcq',
    question: 'What is cyberbullying?',
    options: ['Using the internet', 'Bullying someone online', 'Sending emails', 'Browsing websites'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Security',
    explanation: 'Cyberbullying is using technology to harass or harm others.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-054',
    type: 'mcq',
    question: 'Which of these is safe to share online?',
    options: ['Your password', 'Your home address', 'Public information', 'Your bank account number'],
    correctAnswer: 2,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Security',
    explanation: 'Only share public information online. Never share passwords or personal details.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-055',
    type: 'mcq',
    question: 'What is phishing?',
    options: ['A type of fishing', 'A scam to steal personal information', 'A type of software', 'A hardware device'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Security',
    explanation: 'Phishing is a fraudulent attempt to obtain sensitive information.',
    source: 'practice',
    year: 2021,
  },

  // JHS ICT - More Advanced Topics
  {
    id: 'jhs-ict-056',
    type: 'mcq',
    question: 'What does LAN stand for?',
    options: ['Large Area Network', 'Local Area Network', 'Long Area Network', 'Limited Area Network'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Networking',
    explanation: 'LAN connects computers in a small area like a school or office.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-057',
    type: 'mcq',
    question: 'What does WAN stand for?',
    options: ['Wide Area Network', 'Wireless Area Network', 'Web Area Network', 'World Area Network'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Networking',
    explanation: 'WAN connects computers over a large geographical area.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-058',
    type: 'mcq',
    question: 'Which of these is a database software?',
    options: ['Word', 'Excel', 'Access', 'PowerPoint'],
    correctAnswer: 2,
    subject: 'ICT',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Software',
    explanation: 'Microsoft Access is used to create and manage databases.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-059',
    type: 'mcq',
    question: 'What is the main purpose of a firewall?',
    options: ['To create fire', 'To block unauthorized access', 'To speed up internet', 'To store files'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Security',
    explanation: 'Firewall protects networks by blocking unauthorized access.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-060',
    type: 'mcq',
    question: 'What does Wi-Fi stand for?',
    options: ['Wireless Fidelity', 'Wide Fidelity', 'Wireless Frequency', 'Wide Frequency'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Networking',
    explanation: 'Wi-Fi allows wireless internet connection.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-061',
    type: 'mcq',
    question: 'Which of these is a cloud storage service?',
    options: ['Google Drive', 'Microsoft Word', 'Excel', 'PowerPoint'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Storage',
    explanation: 'Google Drive stores files in the cloud (online).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-062',
    type: 'mcq',
    question: 'What does USB stand for?',
    options: ['Universal Serial Bus', 'United Serial Bus', 'Universal System Bus', 'United System Bus'],
    correctAnswer: 0,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Hardware',
    explanation: 'USB is a standard for connecting devices to computers.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-063',
    type: 'mcq',
    question: 'Which key is used to capitalize letters?',
    options: ['Ctrl', 'Shift', 'Alt', 'Enter'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Hardware',
    explanation: 'Shift key is held while typing to produce capital letters.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-ict-064',
    type: 'mcq',
    question: 'What does CD stand for?',
    options: ['Computer Disk', 'Compact Disk', 'Central Disk', 'Common Disk'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Storage',
    explanation: 'CD (Compact Disk) is an optical storage medium.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-ict-065',
    type: 'mcq',
    question: 'What does DVD stand for?',
    options: ['Digital Video Disk', 'Digital Versatile Disk', 'Data Video Disk', 'Data Versatile Disk'],
    correctAnswer: 1,
    subject: 'ICT',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Storage',
    explanation: 'DVD (Digital Versatile Disk) stores more data than CD.',
    source: 'practice',
    year: 2021,
  },
];

