// JHS Mathematics Questions
// BECE-level questions migrated to modular ChallengeQuestion format
// NOTE: These are practice-style BECE-level questions, not yet tagged as verified past questions.

import type { ChallengeQuestion } from '../types';

export const jhsMathematicsQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Initial Batch)
  // ============================================

  // JHS Mathematics - Number & Numeration
  {
    id: 'jhs-math-001',
    type: 'mcq',
    question: 'If set A = {1, 2, 3, 4, 5} and set B = {2, 4, 6, 8}, find A ∩ B.',
    options: ['{1, 3, 5}', '{2, 4}', '{1, 2, 3, 4, 5, 6, 8}', '{6, 8}'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Sets',
    explanation: 'Intersection (∩) contains elements present in both sets. 2 and 4 are in both A and B.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-002',
    type: 'mcq',
    question: 'Convert 0.75 to a fraction in its lowest term.',
    options: ['3/4', '1/2', '2/3', '4/5'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: '0.75 = 75/100. Divide both by 25 to get 3/4.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-math-003',
    type: 'mcq',
    question: 'Find the LCM of 4, 6 and 8.',
    options: ['12', '16', '24', '48'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'Multiples of 8: 8, 16, 24... 24 is divisible by 4 and 6.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-004',
    type: 'mcq',
    question: 'What is the value of 7 in the number 87,532?',
    options: ['700', '7,000', '70', '7'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'The 7 is in the thousands place.',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-math-005',
    type: 'mcq',
    question: 'Evaluate 2³ × 3²',
    options: ['72', '54', '36', '12'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: '2³ = 8, 3² = 9. 8 × 9 = 72.',
    source: 'practice',
    year: 2022,
  },

  // JHS Mathematics - Algebra
  {
    id: 'jhs-math-006',
    type: 'mcq',
    question: 'Simplify 3x + 4y - x + 2y',
    options: ['2x + 6y', '4x + 6y', '2x + 2y', '3x + 6y'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: 'Group like terms: (3x - x) + (4y + 2y) = 2x + 6y',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-math-007',
    type: 'mcq',
    question: 'Solve for x if x + 5 = 12',
    options: ['5', '6', '7', '17'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: 'Subtract 5 from both sides: x = 12 - 5 = 7',
    source: 'practice',
    year: 2015,
  },
  {
    id: 'jhs-math-008',
    type: 'mcq',
    question: 'Solve the inequality: 2x - 5 > 3',
    options: ['x > 4', 'x < 4', 'x > -4', 'x < -4'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '2x > 8, so x > 4',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-009',
    type: 'mcq',
    question: 'If a = 3 and b = -2, evaluate 2a - b.',
    options: ['4', '8', '5', '7'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '2(3) - (-2) = 6 + 2 = 8',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-math-010',
    type: 'mcq',
    question: 'Solve for y: 3(y + 2) = 2(y + 5)',
    options: ['2', '3', '4', '5'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '3y + 6 = 2y + 10 => y = 4',
    source: 'practice',
    year: 2021,
  },

  // JHS Mathematics - Geometry & Mensuration
  {
    id: 'jhs-math-011',
    type: 'mcq',
    question: 'Calculate the area of a rectangle with length 8cm and width 5cm.',
    options: ['13cm²', '26cm²', '40cm²', '80cm²'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Area = length × width = 8 × 5 = 40cm²',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-math-012',
    type: 'mcq',
    question: 'The sum of angles in a triangle is...',
    options: ['90°', '180°', '270°', '360°'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Geometry',
    explanation: 'The interior angles of a triangle always sum to 180°.',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-math-013',
    type: 'mcq',
    question: 'Find the circumference of a circle with radius 7cm (Take π = 22/7).',
    options: ['22cm', '44cm', '154cm', '14cm'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'C = 2πr = 2 × (22/7) × 7 = 44cm',
    source: 'practice',
    year: 2022,
  },

  // JHS Mathematics - Ratios & Percentages
  {
    id: 'jhs-math-014',
    type: 'mcq',
    question: 'Express 45% as a fraction in its lowest term.',
    options: ['9/20', '4/5', '9/10', '1/2'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: '45/100 = 9/20 (dividing by 5)',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-math-015',
    type: 'mcq',
    question: 'The ratio of boys to girls in a class is 3:2. If there are 12 girls, how many boys are there?',
    options: ['12', '15', '18', '20'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Ratios',
    explanation: 'Ratio 3:2. Girls part is 2 units = 12 students. 1 unit = 6. Boys = 3 units = 3 × 6 = 18.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Additional Questions (Batch 1)
  // ============================================

  // JHS Mathematics - Numbers (Prime Numbers)
  {
    id: 'jhs-math-016',
    type: 'mcq',
    question: 'Which of the following is a prime number?',
    options: ['9', '15', '19', '21'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: '19 has only two factors: 1 and itself.',
    source: 'practice',
    year: 2016,
  },

  // JHS Mathematics - Business Math
  {
    id: 'jhs-math-017',
    type: 'mcq',
    question: 'Find the simple interest on GH₵ 5,000.00 for 3 years at 10% per annum.',
    options: ['GH₵ 150.00', 'GH₵ 500.00', 'GH₵ 1,500.00', 'GH₵ 1,000.00'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Business Math',
    explanation: 'I = (P × R × T) / 100 = (5000 × 10 × 3) / 100 = 1500',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-math-018',
    type: 'mcq',
    question: 'Factorize completely: 3x² - 12x',
    options: ['3x(x - 4)', '3(x² - 4x)', 'x(3x - 12)', '3x(x + 4)'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: 'Common factor is 3x. 3x(x - 4)',
    source: 'practice',
    year: 2016,
  },
  {
    id: 'jhs-math-019',
    type: 'mcq',
    question: 'A car travels 180km in 3 hours. What is its average speed?',
    options: ['50 km/h', '60 km/h', '70 km/h', '80 km/h'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Rates',
    explanation: 'Speed = Distance / Time = 180 / 3 = 60 km/h',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-020',
    type: 'mcq',
    question: 'Find the median of the numbers: 4, 1, 7, 3, 8, 2, 9',
    options: ['3', '4', '7', '8'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Statistics',
    explanation: 'Order: 1, 2, 3, 4, 7, 8, 9. Middle number is 4.',
    source: 'practice',
    year: 2015,
  },

  // JHS Mathematics - Hard Questions (JHS 3)
  {
    id: 'jhs-math-021',
    type: 'mcq',
    question: 'The interior angle of a regular polygon is 144°. How many sides does it have?',
    options: ['8', '9', '10', '12'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Geometry',
    explanation: 'Exterior angle = 180 - 144 = 36°. Number of sides = 360 / 36 = 10.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-math-022',
    type: 'mcq',
    question: 'Make u the subject of the relation v = u + at',
    options: ['u = v - at', 'u = v + at', 'u = (v/a) - t', 'u = v/t - a'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Algebra',
    explanation: 'Subtract at from both sides: v - at = u',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-math-023',
    type: 'mcq',
    question: 'A cylinder has a volume of 1540 cm³ and a height of 10 cm. Find its radius. (Take π = 22/7)',
    options: ['5 cm', '7 cm', '10 cm', '14 cm'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'V = πr²h. 1540 = (22/7)r²(10). 154 = (22/7)r². r² = 154 × 7 / 22 = 49. r = 7.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-024',
    type: 'mcq',
    question: 'If 2^x = 32, find x.',
    options: ['3', '4', '5', '6'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Indices',
    explanation: '2 × 2 × 2 × 2 × 2 = 32. So x = 5.',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-math-025',
    type: 'mcq',
    question: 'In a class of 40 students, 25 play football, 20 play hockey and 10 play both. How many play neither?',
    options: ['5', '10', '15', '0'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Sets',
    explanation: 'n(F∪H) = n(F) + n(H) - n(F∩H) = 25 + 20 - 10 = 35. Neither = 40 - 35 = 5.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-026',
    type: 'mcq',
    question: 'Find the gradient of the line joining points A(2, 3) and B(6, 11).',
    options: ['1', '2', '3', '4'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Coordinate Geometry',
    explanation: 'Gradient = (y2 - y1) / (x2 - x1) = (11 - 3) / (6 - 2) = 8 / 4 = 2',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-math-027',
    type: 'mcq',
    question: 'The probability of passing an exam is 0.8. If 50 students took the exam, how many are expected to fail?',
    options: ['5', '10', '20', '40'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Probability',
    explanation: 'Prob(Fail) = 1 - 0.8 = 0.2. Expected fail = 0.2 × 50 = 10.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-math-028',
    type: 'mcq',
    question: 'Solve the simultaneous equations: 2x + y = 7 and x - y = 2',
    options: ['x=3, y=1', 'x=2, y=3', 'x=4, y=-1', 'x=3, y=2'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Algebra',
    explanation: 'Add equations: 3x = 9 => x = 3. Substitute x: 3 - y = 2 => y = 1.',
    source: 'practice',
    year: 2015,
  },
  {
    id: 'jhs-math-029',
    type: 'mcq',
    question: 'Calculate the total surface area of a closed cylinder with radius 7cm and height 10cm. (π = 22/7)',
    options: ['748 cm²', '374 cm²', '528 cm²', '440 cm²'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'TSA = 2πr(r + h) = 2 × (22/7) × 7 × (7 + 10) = 44 × 17 = 748 cm²',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-math-030',
    type: 'mcq',
    question: 'Simplify: (2√3 + √2)(2√3 - √2)',
    options: ['8', '10', '12', '14'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Surds',
    explanation: 'Difference of two squares: (2√3)² - (√2)² = (4×3) - 2 = 12 - 2 = 10',
    source: 'practice',
    year: 2016,
  },

  // ============================================
  // Additional BECE Questions (Batch 2)
  // ============================================

  // JHS Mathematics - Numbers (HCF/GCF, More Operations)
  {
    id: 'jhs-math-031',
    type: 'mcq',
    question: 'Find the HCF of 12, 18 and 24.',
    options: ['4', '6', '8', '12'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'Factors of 12: 1,2,3,4,6,12. Factors of 18: 1,2,3,6,9,18. Factors of 24: 1,2,3,4,6,8,12,24. Common highest is 6.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-032',
    type: 'mcq',
    question: 'What is 15% of 240?',
    options: ['30', '36', '40', '45'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: '15% of 240 = (15/100) × 240 = 0.15 × 240 = 36',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-math-033',
    type: 'mcq',
    question: 'Express 3/5 as a percentage.',
    options: ['30%', '50%', '60%', '75%'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: '3/5 = 0.6 = 60%',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-math-034',
    type: 'mcq',
    question: 'Find the square root of 144.',
    options: ['10', '12', '14', '16'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: '12 × 12 = 144, so √144 = 12',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-035',
    type: 'mcq',
    question: 'What is the next number in the sequence: 2, 5, 8, 11, ...?',
    options: ['13', '14', '15', '16'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'The sequence increases by 3 each time. 11 + 3 = 14',
    source: 'practice',
    year: 2017,
  },

  // JHS Mathematics - More Algebra
  {
    id: 'jhs-math-036',
    type: 'mcq',
    question: 'Expand: (x + 3)(x + 2)',
    options: ['x² + 5x + 6', 'x² + 6x + 5', 'x² + 5x + 5', 'x² + 6x + 6'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '(x + 3)(x + 2) = x² + 2x + 3x + 6 = x² + 5x + 6',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-037',
    type: 'mcq',
    question: 'If 3x - 7 = 14, find x.',
    options: ['5', '6', '7', '8'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '3x - 7 = 14 => 3x = 21 => x = 7',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-math-038',
    type: 'mcq',
    question: 'Simplify: 5a - 3b + 2a - b',
    options: ['7a - 4b', '7a - 2b', '3a - 4b', '3a - 2b'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: 'Group like terms: (5a + 2a) + (-3b - b) = 7a - 4b',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-math-039',
    type: 'mcq',
    question: 'If p = 4 and q = 3, find the value of 2p² - q².',
    options: ['23', '25', '27', '29'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '2(4)² - (3)² = 2(16) - 9 = 32 - 9 = 23',
    source: 'practice',
    year: 2021,
  },

  // JHS Mathematics - More Geometry & Mensuration
  {
    id: 'jhs-math-040',
    type: 'mcq',
    question: 'Find the area of a triangle with base 10cm and height 6cm.',
    options: ['30 cm²', '32 cm²', '35 cm²', '40 cm²'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Area = (1/2) × base × height = (1/2) × 10 × 6 = 30 cm²',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-041',
    type: 'mcq',
    question: 'The perimeter of a square with side 8cm is...',
    options: ['24 cm', '32 cm', '40 cm', '64 cm'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Perimeter = 4 × side = 4 × 8 = 32 cm',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-math-042',
    type: 'mcq',
    question: 'Find the area of a circle with radius 5cm. (Take π = 22/7)',
    options: ['55 cm²', '78.5 cm²', '110 cm²', '154 cm²'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Area = πr² = (22/7) × 5² = (22/7) × 25 = 550/7 ≈ 78.5 cm²',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-math-043',
    type: 'mcq',
    question: 'In a triangle, if two angles are 45° and 60°, what is the third angle?',
    options: ['65°', '75°', '85°', '95°'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Geometry',
    explanation: 'Sum of angles = 180°. Third angle = 180° - 45° - 60° = 75°',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-044',
    type: 'mcq',
    question: 'A trapezium has parallel sides of lengths 8cm and 12cm, and height 5cm. Find its area.',
    options: ['40 cm²', '50 cm²', '60 cm²', '70 cm²'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Area = (1/2) × (sum of parallel sides) × height = (1/2) × (8 + 12) × 5 = 50 cm²',
    source: 'practice',
    year: 2020,
  },

  // JHS Mathematics - More Ratios & Proportions
  {
    id: 'jhs-math-045',
    type: 'mcq',
    question: 'If 3:5 = x:20, find x.',
    options: ['10', '12', '15', '18'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Ratios',
    explanation: '3/5 = x/20 => Cross multiply: 3 × 20 = 5x => 60 = 5x => x = 12',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-math-046',
    type: 'mcq',
    question: 'Divide 60 in the ratio 2:3.',
    options: ['20 and 40', '24 and 36', '25 and 35', '30 and 30'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Ratios',
    explanation: 'Total parts = 2 + 3 = 5. First part = (2/5) × 60 = 24. Second part = (3/5) × 60 = 36',
    source: 'practice',
    year: 2018,
  },

  // JHS Mathematics - More Statistics
  {
    id: 'jhs-math-047',
    type: 'mcq',
    question: 'Find the mean of: 5, 8, 10, 12, 15',
    options: ['9', '10', '11', '12'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Statistics',
    explanation: 'Mean = (5 + 8 + 10 + 12 + 15) / 5 = 50 / 5 = 10',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-048',
    type: 'mcq',
    question: 'What is the mode of: 3, 5, 5, 7, 9, 5, 11?',
    options: ['3', '5', '7', '9'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Statistics',
    explanation: 'Mode is the most frequent number. 5 appears 3 times.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-049',
    type: 'mcq',
    question: 'Find the range of: 12, 8, 15, 10, 20, 5',
    options: ['10', '12', '15', '20'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Statistics',
    explanation: 'Range = Maximum - Minimum = 20 - 5 = 15',
    source: 'practice',
    year: 2019,
  },

  // JHS Mathematics - More Hard Questions (JHS 3)
  {
    id: 'jhs-math-050',
    type: 'mcq',
    question: 'Find the area of a parallelogram with base 12cm and height 8cm.',
    options: ['80 cm²', '96 cm²', '100 cm²', '120 cm²'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Area = base × height = 12 × 8 = 96 cm²',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-math-051',
    type: 'mcq',
    question: 'If the sum of two numbers is 15 and their difference is 3, find the larger number.',
    options: ['6', '7', '8', '9'],
    correctAnswer: 3,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Algebra',
    explanation: 'Let numbers be x and y. x + y = 15, x - y = 3. Adding: 2x = 18 => x = 9',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-052',
    type: 'mcq',
    question: 'A shopkeeper bought an item for GH₵ 80 and sold it for GH₵ 100. What is the profit percentage?',
    options: ['20%', '25%', '30%', '35%'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Business Math',
    explanation: 'Profit = 100 - 80 = 20. Profit % = (20/80) × 100 = 25%',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-053',
    type: 'mcq',
    question: 'Find the volume of a cube with side 5cm.',
    options: ['100 cm³', '125 cm³', '150 cm³', '175 cm³'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Volume = side³ = 5³ = 125 cm³',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-math-054',
    type: 'mcq',
    question: 'If 5 workers can complete a job in 8 days, how many days will 10 workers take?',
    options: ['2 days', '3 days', '4 days', '5 days'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Rates',
    explanation: 'More workers means less time. Inverse proportion: 5 × 8 = 10 × x => x = 4 days',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-055',
    type: 'mcq',
    question: 'Find the value of x if 2x + 3 = 3x - 2.',
    options: ['3', '4', '5', '6'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '2x + 3 = 3x - 2 => 3 + 2 = 3x - 2x => 5 = x',
    source: 'practice',
    year: 2018,
  },

  // ============================================
  // Additional BECE Questions (Batch 3 - From Online Sources)
  // ============================================

  // JHS Mathematics - Numbers (Place Value, Perfect Squares)
  {
    id: 'jhs-math-056',
    type: 'mcq',
    question: 'What is the place value of 7 in the number 526.97?',
    options: ['7 units', '7 tenths', '7 hundredths', '7 thousands'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'In 526.97, the 7 is in the tenths place (first decimal place).',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-057',
    type: 'mcq',
    question: 'Find the positive difference between -8 and -14.',
    options: ['-6', '6', '-22', '22'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'Positive difference = |-8 - (-14)| = |-8 + 14| = |6| = 6',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-058',
    type: 'mcq',
    question: 'Find the smallest number that 60 must be multiplied with to give a perfect square.',
    options: ['10', '15', '20', '25'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Numbers',
    explanation: '60 = 2² × 3 × 5. To make it a perfect square, need 3 × 5 = 15. So 60 × 15 = 900 = 30²',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-math-059',
    type: 'mcq',
    question: 'Find the value of 16 × 2 – 3 + 14 ÷ 7.',
    options: ['28', '29', '30', '31'],
    correctAnswer: 3,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'Using BODMAS: 14 ÷ 7 = 2, then 16 × 2 = 32, so 32 - 3 + 2 = 31',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-060',
    type: 'mcq',
    question: 'A man spends 1/4 of his monthly income on children\'s school fees and 3/5 on home affairs. What fraction of his income is left?',
    options: ['1/20', '3/20', '1/10', '3/10'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'Total spent = 1/4 + 3/5 = 5/20 + 12/20 = 17/20. Left = 1 - 17/20 = 3/20',
    source: 'practice',
    year: 2020,
  },

  // JHS Mathematics - More Algebra & Equations
  {
    id: 'jhs-math-061',
    type: 'mcq',
    question: 'If 2/3 of a number is 24, find the number.',
    options: ['32', '36', '40', '48'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: 'Let the number be x. (2/3)x = 24 => x = 24 × (3/2) = 36',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-math-062',
    type: 'mcq',
    question: 'Solve for x: 4x - 5 = 3x + 7',
    options: ['10', '12', '14', '16'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '4x - 5 = 3x + 7 => 4x - 3x = 7 + 5 => x = 12',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-063',
    type: 'mcq',
    question: 'If x = 2 and y = -3, find the value of x² - y².',
    options: ['-5', '-1', '1', '5'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: 'x² - y² = (2)² - (-3)² = 4 - 9 = -5',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-064',
    type: 'mcq',
    question: 'Factorize: x² - 9',
    options: ['(x - 3)(x - 3)', '(x - 3)(x + 3)', '(x + 3)(x + 3)', '(x - 9)(x + 1)'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: 'Difference of two squares: x² - 9 = x² - 3² = (x - 3)(x + 3)',
    source: 'practice',
    year: 2018,
  },

  // JHS Mathematics - More Geometry
  {
    id: 'jhs-math-065',
    type: 'mcq',
    question: 'The sum of angles on a straight line is...',
    options: ['90°', '180°', '270°', '360°'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Geometry',
    explanation: 'Angles on a straight line always sum to 180°.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-066',
    type: 'mcq',
    question: 'In a right-angled triangle, one angle is 30°. What is the third angle?',
    options: ['50°', '60°', '70°', '80°'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Geometry',
    explanation: 'Right angle = 90°, so third angle = 180° - 90° - 30° = 60°',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-math-067',
    type: 'mcq',
    question: 'Find the perimeter of a rectangle with length 15cm and width 8cm.',
    options: ['38 cm', '46 cm', '56 cm', '64 cm'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Perimeter = 2(length + width) = 2(15 + 8) = 2 × 23 = 46 cm',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-068',
    type: 'mcq',
    question: 'A square has an area of 64 cm². What is the length of one side?',
    options: ['6 cm', '7 cm', '8 cm', '9 cm'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Area = side². So side = √64 = 8 cm',
    source: 'practice',
    year: 2020,
  },

  // JHS Mathematics - More Business Math & Percentages
  {
    id: 'jhs-math-069',
    type: 'mcq',
    question: 'A discount of 20% is given on an item costing GH₵ 150. What is the sale price?',
    options: ['GH₵ 120', 'GH₵ 130', 'GH₵ 140', 'GH₵ 145'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Business Math',
    explanation: 'Discount = 20% of 150 = 30. Sale price = 150 - 30 = GH₵ 120',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-070',
    type: 'mcq',
    question: 'If 25% of a number is 50, what is the number?',
    options: ['150', '200', '250', '300'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'Let the number be x. (25/100)x = 50 => x = 50 × 4 = 200',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-071',
    type: 'mcq',
    question: 'Find the compound interest on GH₵ 2,000 for 2 years at 10% per annum.',
    options: ['GH₵ 400', 'GH₵ 420', 'GH₵ 440', 'GH₵ 480'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Business Math',
    explanation: 'Amount = P(1 + r/100)ⁿ = 2000(1.1)² = 2000 × 1.21 = 2420. Interest = 2420 - 2000 = GH₵ 420',
    source: 'practice',
    year: 2021,
  },

  // JHS Mathematics - More Sets & Logic
  {
    id: 'jhs-math-072',
    type: 'mcq',
    question: 'If set P = {2, 4, 6, 8} and set Q = {1, 2, 3, 4, 5}, find P ∪ Q.',
    options: ['{2, 4}', '{1, 2, 3, 4, 5, 6, 8}', '{1, 3, 5, 6, 8}', '{2, 4, 6, 8}'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Sets',
    explanation: 'Union (∪) contains all elements from both sets: {1, 2, 3, 4, 5, 6, 8}',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-073',
    type: 'mcq',
    question: 'In a class of 30 students, 18 like Mathematics and 15 like English. If 10 like both, how many like neither?',
    options: ['5', '7', '9', '11'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Sets',
    explanation: 'n(M∪E) = n(M) + n(E) - n(M∩E) = 18 + 15 - 10 = 23. Neither = 30 - 23 = 7',
    source: 'practice',
    year: 2022,
  },

  // JHS Mathematics - More Mensuration
  {
    id: 'jhs-math-074',
    type: 'mcq',
    question: 'Find the volume of a rectangular box with length 6cm, width 4cm and height 5cm.',
    options: ['100 cm³', '110 cm³', '120 cm³', '130 cm³'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Volume = length × width × height = 6 × 4 × 5 = 120 cm³',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-075',
    type: 'mcq',
    question: 'A cylinder has radius 3.5cm and height 10cm. Find its volume. (Take π = 22/7)',
    options: ['385 cm³', '390 cm³', '395 cm³', '400 cm³'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Volume = πr²h = (22/7) × (3.5)² × 10 = (22/7) × 12.25 × 10 = 385 cm³',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-076',
    type: 'mcq',
    question: 'Find the area of a rhombus with diagonals 8cm and 6cm.',
    options: ['20 cm²', '24 cm²', '28 cm²', '32 cm²'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Area = (1/2) × d₁ × d₂ = (1/2) × 8 × 6 = 24 cm²',
    source: 'practice',
    year: 2019,
  },

  // JHS Mathematics - More Statistics & Probability
  {
    id: 'jhs-math-077',
    type: 'mcq',
    question: 'Find the mean of: 10, 12, 14, 16, 18',
    options: ['13', '14', '15', '16'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Statistics',
    explanation: 'Mean = (10 + 12 + 14 + 16 + 18) / 5 = 70 / 5 = 14',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-078',
    type: 'mcq',
    question: 'What is the probability of getting an even number when a die is thrown?',
    options: ['1/2', '1/3', '2/3', '1/6'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Probability',
    explanation: 'Even numbers on a die: 2, 4, 6. Probability = 3/6 = 1/2',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-079',
    type: 'mcq',
    question: 'The median of: 5, 8, 10, 12, 15, 18, 20 is...',
    options: ['10', '12', '15', '18'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Statistics',
    explanation: 'Already in order. Middle number (4th) is 12.',
    source: 'practice',
    year: 2019,
  },

  // JHS Mathematics - More Advanced Topics
  {
    id: 'jhs-math-080',
    type: 'mcq',
    question: 'If the ratio x:y = 3:4 and y:z = 2:5, find x:z.',
    options: ['3:10', '3:5', '6:20', '3:20'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Ratios',
    explanation: 'x:y = 3:4, y:z = 2:5. Make y same: x:y = 3:4, y:z = 4:10. So x:z = 3:10',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-081',
    type: 'mcq',
    question: 'A map is drawn to a scale of 1:50,000. If the distance on the map is 4cm, what is the actual distance?',
    options: ['1 km', '2 km', '3 km', '4 km'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Rates',
    explanation: 'Actual distance = 4 × 50,000 = 200,000 cm = 2,000 m = 2 km',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-082',
    type: 'mcq',
    question: 'Find the value of 3² + 4².',
    options: ['7', '12', '25', '49'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: '3² + 4² = 9 + 16 = 25',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Additional BECE Mathematics Questions (Batch 4)
  // ============================================

  // JHS Mathematics - More Algebra
  {
    id: 'jhs-math-083',
    type: 'mcq',
    question: 'Simplify: 2(3a + 1) - 3(4a - 3)',
    options: ['-6a + 11', '-6a - 7', '6a + 11', '6a - 7'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '2(3a + 1) - 3(4a - 3) = 6a + 2 - 12a + 9 = -6a + 11',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-084',
    type: 'mcq',
    question: 'Simplify: 3x² - 2x + 5 + 4x² + 3x - 7',
    options: ['7x² + x - 2', '7x² + 5x - 2', '7x² + x + 2', 'x² + x - 2'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: 'Combine like terms: (3x² + 4x²) + (-2x + 3x) + (5 - 7) = 7x² + x - 2',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-085',
    type: 'mcq',
    question: 'If 3x - 4 = 2x + 5, find x.',
    options: ['7', '8', '9', '10'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '3x - 4 = 2x + 5 => 3x - 2x = 5 + 4 => x = 9',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-086',
    type: 'mcq',
    question: 'Expand: (x + 5)(x - 3)',
    options: ['x² + 2x - 15', 'x² - 2x - 15', 'x² + 8x - 15', 'x² - 8x - 15'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '(x + 5)(x - 3) = x² - 3x + 5x - 15 = x² + 2x - 15',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-087',
    type: 'mcq',
    question: 'If y = 2x + 3 and y = 11, find x.',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '11 = 2x + 3 => 2x = 8 => x = 4',
    source: 'practice',
    year: 2020,
  },

  // JHS Mathematics - More Geometry & Mensuration
  {
    id: 'jhs-math-088',
    type: 'mcq',
    question: 'A triangle has sides of lengths 7cm, 24cm, and 25cm. Is it a right-angled triangle?',
    options: ['Yes', 'No', 'Cannot determine', 'Maybe'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Geometry',
    explanation: 'Check: 7² + 24² = 49 + 576 = 625. 25² = 625. Since equal, it\'s a right-angled triangle.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-089',
    type: 'mcq',
    question: 'The area of a rectangular card is 15 cm². If each side is enlarged by a scale factor of 3, find the new area.',
    options: ['45 cm²', '90 cm²', '135 cm²', '180 cm²'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Area scales by the square of the scale factor. New area = 15 × 3² = 15 × 9 = 135 cm²',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-090',
    type: 'mcq',
    question: 'Calculate the area of a trapezium with bases 8cm and 5cm, and height 4cm.',
    options: ['24 cm²', '26 cm²', '28 cm²', '30 cm²'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Area = ½ × (sum of parallel sides) × height = ½ × (8 + 5) × 4 = 26 cm²',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-091',
    type: 'mcq',
    question: 'Find the area of a circle with diameter 14cm. (Take π = 22/7)',
    options: ['154 cm²', '156 cm²', '158 cm²', '160 cm²'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Radius = 14/2 = 7cm. Area = πr² = (22/7) × 7² = (22/7) × 49 = 154 cm²',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-092',
    type: 'mcq',
    question: 'A rectangle has length 12cm and width 8cm. Find its perimeter.',
    options: ['36 cm', '38 cm', '40 cm', '42 cm'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Perimeter = 2(length + width) = 2(12 + 8) = 2 × 20 = 40 cm',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-093',
    type: 'mcq',
    question: 'Find the volume of a cuboid with length 6cm, width 4cm, and height 5cm.',
    options: ['110 cm³', '115 cm³', '120 cm³', '125 cm³'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Volume = length × width × height = 6 × 4 × 5 = 120 cm³',
    source: 'practice',
    year: 2020,
  },

  // JHS Mathematics - More Business Math
  {
    id: 'jhs-math-094',
    type: 'mcq',
    question: 'How long will the simple interest on GH₵ 550.00 at 12% per annum be GH₵ 132.00?',
    options: ['1 year', '2 years', '3 years', '4 years'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Business Math',
    explanation: 'I = PRT/100 => 132 = (550 × 12 × T)/100 => 132 = 66T => T = 2 years',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-095',
    type: 'mcq',
    question: 'A trader bought goods for GH₵ 200 and sold them for GH₵ 250. What is the profit percentage?',
    options: ['20%', '25%', '30%', '35%'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Business Math',
    explanation: 'Profit = 250 - 200 = 50. Profit % = (50/200) × 100 = 25%',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-096',
    type: 'mcq',
    question: 'If an item costs GH₵ 80 and is sold at a loss of 15%, find the selling price.',
    options: ['GH₵ 65', 'GH₵ 68', 'GH₵ 70', 'GH₵ 72'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Business Math',
    explanation: 'Loss = 15% of 80 = 12. Selling price = 80 - 12 = GH₵ 68',
    source: 'practice',
    year: 2021,
  },

  // JHS Mathematics - More Statistics & Probability
  {
    id: 'jhs-math-097',
    type: 'mcq',
    question: 'Find the mean score of: 2, 3, 0, 8, 7, 5, 9, 6',
    options: ['4', '5', '6', '7'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Statistics',
    explanation: 'Mean = (2 + 3 + 0 + 8 + 7 + 5 + 9 + 6) / 8 = 40 / 8 = 5',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-098',
    type: 'mcq',
    question: 'Find the median of: 12, 15, 11, 14, 13',
    options: ['12', '13', '14', '15'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Statistics',
    explanation: 'Arrange: 11, 12, 13, 14, 15. Middle value is 13.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-099',
    type: 'mcq',
    question: 'A bag contains 5 red, 3 blue, and 2 green balls. What is the probability of drawing a blue ball?',
    options: ['1/5', '3/10', '1/3', '2/5'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Probability',
    explanation: 'Total = 5 + 3 + 2 = 10. Probability = 3/10',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-100',
    type: 'mcq',
    question: 'What is the range of: 8, 12, 5, 15, 10, 7?',
    options: ['8', '9', '10', '11'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Statistics',
    explanation: 'Range = Maximum - Minimum = 15 - 5 = 10',
    source: 'practice',
    year: 2021,
  },

  // JHS Mathematics - More Sequences & Patterns
  {
    id: 'jhs-math-101',
    type: 'mcq',
    question: 'Find the next term in the sequence: 2, 5, 9, 14, 20, ...',
    options: ['25', '26', '27', '28'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'Pattern: +3, +4, +5, +6, so next is +7. 20 + 7 = 27',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-102',
    type: 'mcq',
    question: 'What is the 5th term in the sequence: 3, 6, 12, 24, ...?',
    options: ['36', '48', '60', '72'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'Each term is multiplied by 2. 24 × 2 = 48',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-103',
    type: 'mcq',
    question: 'Find the next number: 1, 4, 9, 16, 25, ...',
    options: ['30', '36', '40', '45'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'These are perfect squares: 1², 2², 3², 4², 5², so next is 6² = 36',
    source: 'practice',
    year: 2020,
  },

  // JHS Mathematics - More Number Operations
  {
    id: 'jhs-math-104',
    type: 'mcq',
    question: 'Find the HCF of 18 and 24.',
    options: ['4', '6', '8', '12'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'Factors of 18: 1,2,3,6,9,18. Factors of 24: 1,2,3,4,6,8,12,24. HCF = 6',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-105',
    type: 'mcq',
    question: 'What is 25% of 200?',
    options: ['40', '50', '60', '70'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: '25% of 200 = (25/100) × 200 = 0.25 × 200 = 50',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-106',
    type: 'mcq',
    question: 'Convert 2.5 to a fraction in its lowest term.',
    options: ['2/5', '5/2', '1/4', '3/4'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: '2.5 = 25/10 = 5/2 (dividing by 5)',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-107',
    type: 'mcq',
    question: 'Find the value of 5³.',
    options: ['100', '125', '150', '175'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: '5³ = 5 × 5 × 5 = 125',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-108',
    type: 'mcq',
    question: 'What is the square root of 169?',
    options: ['11', '12', '13', '14'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: '13 × 13 = 169, so √169 = 13',
    source: 'practice',
    year: 2021,
  },

  // JHS Mathematics - More Ratios & Proportions
  {
    id: 'jhs-math-109',
    type: 'mcq',
    question: 'If 4:7 = 12:x, find x.',
    options: ['18', '19', '20', '21'],
    correctAnswer: 3,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Ratios',
    explanation: '4/7 = 12/x => Cross multiply: 4x = 84 => x = 21',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-110',
    type: 'mcq',
    question: 'Share 120 in the ratio 2:3:5.',
    options: ['24, 36, 60', '20, 40, 60', '30, 40, 50', '25, 35, 60'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Ratios',
    explanation: 'Total parts = 2 + 3 + 5 = 10. First: (2/10) × 120 = 24. Second: (3/10) × 120 = 36. Third: (5/10) × 120 = 60',
    source: 'practice',
    year: 2021,
  },

  // JHS Mathematics - More Advanced Algebra
  {
    id: 'jhs-math-111',
    type: 'mcq',
    question: 'If x² - 5x + 6 = 0, which of the following is a solution?',
    options: ['x = 1', 'x = 2', 'x = 4', 'x = 5'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Algebra',
    explanation: 'Check: (2)² - 5(2) + 6 = 4 - 10 + 6 = 0. So x = 2 is a solution.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-math-112',
    type: 'mcq',
    question: 'Make t the subject of the formula: s = ut + ½at²',
    options: ['t = (s - ut)/a', 't = √(2s/a)', 't = (s - ut)/(½a)', 'Cannot be made subject'],
    correctAnswer: 3,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Algebra',
    explanation: 'This is a quadratic in t, so it requires the quadratic formula. For simple cases: s - ut = ½at² => t² = 2(s - ut)/a',
    source: 'practice',
    year: 2021,
  },

  // Additional BECE-style Questions (Batch 4 - More Practice Questions)
  // NOTE: These are BECE-level practice questions. Actual verified BECE questions should use source: 'bece'
  {
    id: 'jhs-math-113',
    type: 'mcq',
    question: 'Simplify: 3x² + 6xy - 3y² + 4x² - 8xy + 2y²',
    options: ['7x² - 2xy - y²', '7x² + 2xy - y²', '7x² - 2xy + y²', 'x² - 2xy - y²'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: 'Combine like terms: (3x² + 4x²) + (6xy - 8xy) + (-3y² + 2y²) = 7x² - 2xy - y²',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'jhs-math-114',
    type: 'mcq',
    question: 'Solve the inequality: 3x - 9 ≥ 12(x - 3)',
    options: ['x ≥ 3', 'x ≤ 3', 'x ≥ -3', 'x ≤ -3'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '3x - 9 ≥ 12x - 36 => -9x ≥ -27 => x ≤ 3 (reverse inequality when dividing by negative)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'jhs-math-115',
    type: 'mcq',
    question: 'Find the HCF of 24, 36 and 48.',
    options: ['8', '12', '16', '24'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'Factors of 24: 1,2,3,4,6,8,12,24. Factors of 36: 1,2,3,4,6,9,12,18,36. Factors of 48: 1,2,3,4,6,8,12,16,24,48. Highest common factor is 12.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-math-116',
    type: 'mcq',
    question: 'If the mean of 5, 8, x, 12, and 15 is 10, find x.',
    options: ['8', '10', '12', '14'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Statistics',
    explanation: 'Mean = (5 + 8 + x + 12 + 15)/5 = 10 => 40 + x = 50 => x = 10',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'jhs-math-117',
    type: 'mcq',
    question: 'A rectangle has length 8cm and width 5cm. Find its area.',
    options: ['13 cm²', '26 cm²', '40 cm²', '80 cm²'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Area of rectangle = length × width = 8 × 5 = 40 cm²',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-math-118',
    type: 'mcq',
    question: 'Find the perimeter of a square with side 6cm.',
    options: ['12 cm', '24 cm', '36 cm', '48 cm'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Perimeter of square = 4 × side = 4 × 6 = 24 cm',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-119',
    type: 'mcq',
    question: 'Express 0.625 as a fraction in its lowest term.',
    options: ['5/8', '6/8', '625/1000', '25/40'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Numbers',
    explanation: '0.625 = 625/1000. Divide by 125: 625/1000 = 5/8',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'jhs-math-120',
    type: 'mcq',
    question: 'If 2/3 of a number is 24, find the number.',
    options: ['32', '36', '40', '48'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'Let the number be x. (2/3)x = 24 => x = 24 × (3/2) = 36',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-math-121',
    type: 'mcq',
    question: 'Simplify: (2a + 3b) - (a - 2b)',
    options: ['a + 5b', 'a + b', '3a + b', 'a - b'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '(2a + 3b) - (a - 2b) = 2a + 3b - a + 2b = a + 5b',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-122',
    type: 'mcq',
    question: 'Find the area of a triangle with base 10cm and height 8cm.',
    options: ['18 cm²', '40 cm²', '80 cm²', '160 cm²'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Area of triangle = (1/2) × base × height = (1/2) × 10 × 8 = 40 cm²',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-math-123',
    type: 'mcq',
    question: 'If set P = {2, 4, 6, 8} and set Q = {3, 6, 9}, find P ∪ Q.',
    options: ['{6}', '{2, 3, 4, 6, 8, 9}', '{2, 4, 8}', '{3, 9}'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Sets',
    explanation: 'Union (∪) contains all elements from both sets: {2, 4, 6, 8, 3, 9} = {2, 3, 4, 6, 8, 9}',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'jhs-math-124',
    type: 'mcq',
    question: 'Find the value of 4² + 3³',
    options: ['35', '43', '49', '51'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: '4² = 16, 3³ = 27. Sum = 16 + 27 = 43',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-125',
    type: 'mcq',
    question: 'A car travels 240km in 3 hours. Find its average speed.',
    options: ['60 km/h', '70 km/h', '80 km/h', '90 km/h'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Rates',
    explanation: 'Speed = Distance/Time = 240/3 = 80 km/h',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-math-126',
    type: 'mcq',
    question: 'Factorize: x² - 9',
    options: ['(x - 3)(x - 3)', '(x + 3)(x - 3)', '(x + 9)(x - 1)', '(x - 9)(x + 1)'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: 'x² - 9 is difference of two squares: x² - 3² = (x + 3)(x - 3)',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'jhs-math-127',
    type: 'mcq',
    question: 'Convert 5/8 to a percentage.',
    options: ['52.5%', '62.5%', '72.5%', '82.5%'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Numbers',
    explanation: '5/8 = 0.625 = 62.5%',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-128',
    type: 'mcq',
    question: 'Find the circumference of a circle with diameter 14cm (Take π = 22/7).',
    options: ['22 cm', '44 cm', '88 cm', '154 cm'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Radius = 14/2 = 7cm. Circumference = 2πr = 2 × (22/7) × 7 = 44 cm',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-math-129',
    type: 'mcq',
    question: 'Solve for x: 4x - 7 = 2x + 5',
    options: ['x = 4', 'x = 5', 'x = 6', 'x = 7'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '4x - 7 = 2x + 5 => 4x - 2x = 5 + 7 => 2x = 12 => x = 6',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'jhs-math-130',
    type: 'mcq',
    question: 'If 30% of a number is 45, find the number.',
    options: ['120', '135', '150', '165'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'Let the number be x. (30/100)x = 45 => x = 45 × (100/30) = 150',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-131',
    type: 'mcq',
    question: 'Find the area of a circle with radius 5cm (Take π = 22/7).',
    options: ['78.57 cm²', '88.57 cm²', '110 cm²', '157.14 cm²'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Area = πr² = (22/7) × 5² = (22/7) × 25 = 550/7 ≈ 78.57 cm²',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-math-132',
    type: 'mcq',
    question: 'Simplify: (3x - 2y) + (5x + 4y)',
    options: ['8x + 2y', '8x - 2y', '2x + 6y', '2x - 6y'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '(3x - 2y) + (5x + 4y) = 3x + 5x - 2y + 4y = 8x + 2y',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'jhs-math-133',
    type: 'mcq',
    question: 'Find the median of: 5, 8, 12, 15, 18',
    options: ['10', '12', '13', '15'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Statistics',
    explanation: 'Numbers are already in order. Median is the middle value: 12',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-134',
    type: 'mcq',
    question: 'Evaluate: 2⁴ × 3²',
    options: ['96', '144', '288', '576'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Indices',
    explanation: '2⁴ = 16, 3² = 9. Product = 16 × 9 = 144',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-math-135',
    type: 'mcq',
    question: 'A bag contains 3 red, 4 blue, and 5 green balls. What is the probability of picking a blue ball?',
    options: ['1/3', '1/4', '1/5', '4/12'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Probability',
    explanation: 'Total balls = 3 + 4 + 5 = 12. Probability = 4/12 = 1/3',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'jhs-math-136',
    type: 'mcq',
    question: 'Find the simple interest on GH₵ 5000 at 8% per annum for 2 years.',
    options: ['GH₵ 400', 'GH₵ 800', 'GH₵ 1000', 'GH₵ 1200'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Business Math',
    explanation: 'Simple Interest = (Principal × Rate × Time)/100 = (5000 × 8 × 2)/100 = 800',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-math-137',
    type: 'mcq',
    question: 'Simplify: (x + 4)(x - 4)',
    options: ['x² - 16', 'x² - 8', 'x² + 16', 'x² - 8x + 16'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: 'Difference of two squares: (x + 4)(x - 4) = x² - 4² = x² - 16',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-138',
    type: 'mcq',
    question: 'Find the volume of a cylinder with radius 3cm and height 7cm (Take π = 22/7).',
    options: ['132 cm³', '154 cm³', '198 cm³', '231 cm³'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Volume = πr²h = (22/7) × 3² × 7 = (22/7) × 9 × 7 = 22 × 9 = 198 cm³',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'jhs-math-139',
    type: 'mcq',
    question: 'If y = 2x + 3 and y = 11, find x.',
    options: ['3', '4', '5', '6'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '11 = 2x + 3 => 2x = 8 => x = 4',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-math-140',
    type: 'mcq',
    question: 'Express 1.25 as a mixed number.',
    options: ['1 1/4', '1 1/2', '1 3/4', '2 1/4'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Numbers',
    explanation: '1.25 = 1 + 0.25 = 1 + 25/100 = 1 + 1/4 = 1 1/4',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-141',
    type: 'mcq',
    question: 'Find the mode of: 3, 5, 7, 5, 9, 5, 11',
    options: ['5', '7', '9', '11'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'easy',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Statistics',
    explanation: 'Mode is the most frequent number. 5 appears 3 times, more than any other number.',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'jhs-math-142',
    type: 'mcq',
    question: 'Solve: 2(x + 3) = 16',
    options: ['x = 4', 'x = 5', 'x = 6', 'x = 7'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '2(x + 3) = 16 => x + 3 = 8 => x = 5',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-143',
    type: 'mcq',
    question: 'Find the surface area of a cube with side 4cm.',
    options: ['64 cm²', '96 cm²', '128 cm²', '144 cm²'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Surface area = 6 × side² = 6 × 4² = 6 × 16 = 96 cm²',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-math-144',
    type: 'mcq',
    question: 'If 20% of a number is 30, find 60% of the same number.',
    options: ['60', '75', '90', '120'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Numbers',
    explanation: 'If 20% = 30, then 1% = 1.5, so 60% = 60 × 1.5 = 90. Or: (30/20) × 60 = 90',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'jhs-math-145',
    type: 'mcq',
    question: 'Expand: (2x - 3)²',
    options: ['4x² - 9', '4x² - 6x + 9', '4x² - 12x + 9', '4x² + 12x + 9'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '(2x - 3)² = (2x)² - 2(2x)(3) + 3² = 4x² - 12x + 9',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-math-146',
    type: 'mcq',
    question: 'Find the area of a trapezium with parallel sides 8cm and 12cm, and height 5cm.',
    options: ['40 cm²', '50 cm²', '60 cm²', '100 cm²'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Mensuration',
    explanation: 'Area = (1/2) × (sum of parallel sides) × height = (1/2) × (8 + 12) × 5 = (1/2) × 20 × 5 = 50 cm²',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'jhs-math-147',
    type: 'mcq',
    question: 'If a:b = 3:4 and b:c = 2:5, find a:c.',
    options: ['3:10', '3:5', '6:20', '5:9'],
    correctAnswer: 0,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Ratios',
    explanation: 'a:b = 3:4 = 6:8, b:c = 2:5 = 8:20. So a:c = 6:20 = 3:10',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-math-148',
    type: 'mcq',
    question: 'Find the value of x if 5x - 3 = 2x + 9',
    options: ['x = 2', 'x = 3', 'x = 4', 'x = 5'],
    correctAnswer: 2,
    subject: 'Mathematics',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '5x - 3 = 2x + 9 => 5x - 2x = 9 + 3 => 3x = 12 => x = 4',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-math-149',
    type: 'mcq',
    question: 'Find the compound interest on GH₵ 2000 at 10% per annum for 2 years.',
    options: ['GH₵ 400', 'GH₵ 420', 'GH₵ 440', 'GH₵ 480'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Business Math',
    explanation: 'Amount = P(1 + r/100)ⁿ = 2000(1 + 10/100)² = 2000(1.1)² = 2000(1.21) = 2420. CI = 2420 - 2000 = 420',
    source: 'practice',
    year: 2023,
  },
  {
    id: 'jhs-math-150',
    type: 'mcq',
    question: 'Factorize: 6x² + 11x + 3',
    options: ['(2x + 1)(3x + 3)', '(3x + 1)(2x + 3)', '(6x + 1)(x + 3)', '(2x + 3)(3x + 1)'],
    correctAnswer: 1,
    subject: 'Mathematics',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Algebra',
    explanation: '6x² + 11x + 3 = (3x + 1)(2x + 3). Check: 3x(2x) + 3x(3) + 1(2x) + 1(3) = 6x² + 9x + 2x + 3 = 6x² + 11x + 3',
    source: 'practice',
    year: 2022,
  },
];

