import type { ChallengeQuestion } from '../types';

/**
 * JHS RME (Religious and Moral Education) Question Bank
 * BECE RME
 * Topics: Christianity, Islam, Traditional Religion, Ethics, Moral Values
 */

export const jhsRMEQuestions: ChallengeQuestion[] = [
  // ============================================
  // Christianity - Basic Concepts
  // ============================================
  {
    id: 'jhs-rme-001',
    type: 'mcq',
    question: 'Who is the founder of Christianity?',
    options: ['Moses', 'Jesus Christ', 'Paul', 'Peter'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Jesus Christ is the founder of Christianity.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-002',
    type: 'mcq',
    question: 'What is the holy book of Christians called?',
    options: ['Quran', 'Bible', 'Torah', 'Vedas'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The Bible is the holy book of Christians.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-003',
    type: 'mcq',
    question: 'How many books are in the Bible?',
    options: ['66', '73', '27', '39'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The Protestant Bible has 66 books (39 Old Testament, 27 New Testament).',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-004',
    type: 'mcq',
    question: 'What is the place of worship for Christians called?',
    options: ['Mosque', 'Temple', 'Church', 'Shrine'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Church is the place of worship for Christians.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-005',
    type: 'mcq',
    question: 'What day of the week do Christians worship?',
    options: ['Friday', 'Saturday', 'Sunday', 'Monday'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Most Christians worship on Sunday, the day of resurrection.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-006',
    type: 'mcq',
    question: 'Who are the twelve disciples of Jesus?',
    options: ['The apostles', 'The prophets', 'The priests', 'The elders'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The twelve disciples are also called the apostles.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-007',
    type: 'mcq',
    question: 'What is the main prayer of Christians called?',
    options: ['The Lord\'s Prayer', 'The Hail Mary', 'The Apostles\' Creed', 'The Nicene Creed'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The Lord\'s Prayer (Our Father) is the main prayer taught by Jesus.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-008',
    type: 'mcq',
    question: 'What is the celebration of Jesus\' birth called?',
    options: ['Easter', 'Christmas', 'Pentecost', 'Ascension'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Christmas celebrates the birth of Jesus Christ.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-009',
    type: 'mcq',
    question: 'What is the celebration of Jesus\' resurrection called?',
    options: ['Easter', 'Christmas', 'Pentecost', 'Ascension'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Easter celebrates the resurrection of Jesus Christ.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-010',
    type: 'mcq',
    question: 'What is the symbol of Christianity?',
    options: ['Crescent', 'Star', 'Cross', 'Circle'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The cross is the main symbol of Christianity.',
    source: 'practice',
    year: 2019,
  },

  // ============================================
  // Islam - Basic Concepts
  // ============================================
  {
    id: 'jhs-rme-011',
    type: 'mcq',
    question: 'Who is the founder of Islam?',
    options: ['Moses', 'Jesus', 'Muhammad', 'Abraham'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Prophet Muhammad is the founder of Islam.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-012',
    type: 'mcq',
    question: 'What is the holy book of Muslims called?',
    options: ['Bible', 'Quran', 'Torah', 'Vedas'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'The Quran is the holy book of Muslims.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-013',
    type: 'mcq',
    question: 'What is the place of worship for Muslims called?',
    options: ['Church', 'Mosque', 'Temple', 'Shrine'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Mosque is the place of worship for Muslims.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-014',
    type: 'mcq',
    question: 'What day of the week do Muslims worship?',
    options: ['Friday', 'Saturday', 'Sunday', 'Monday'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Muslims worship on Friday, which is their holy day.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-015',
    type: 'mcq',
    question: 'What is the name of God in Islam?',
    options: ['Allah', 'Yahweh', 'Jehovah', 'Brahma'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Allah is the Arabic name for God in Islam.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-016',
    type: 'mcq',
    question: 'How many pillars of Islam are there?',
    options: ['Three', 'Four', 'Five', 'Six'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'There are five pillars of Islam: Shahada, Salat, Zakat, Sawm, and Hajj.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-017',
    type: 'mcq',
    question: 'What is the first pillar of Islam?',
    options: ['Prayer', 'Fasting', 'Pilgrimage', 'Declaration of Faith'],
    correctAnswer: 3,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'The first pillar is Shahada (Declaration of Faith).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-018',
    type: 'mcq',
    question: 'What is the holy month of fasting in Islam called?',
    options: ['Hajj', 'Ramadan', 'Eid', 'Muharram'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Ramadan is the holy month when Muslims fast from dawn to sunset.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-019',
    type: 'mcq',
    question: 'What is the pilgrimage to Mecca called?',
    options: ['Hajj', 'Ramadan', 'Eid', 'Umrah'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Hajj is the pilgrimage to Mecca that Muslims should perform at least once in their lifetime.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-020',
    type: 'mcq',
    question: 'What is the symbol of Islam?',
    options: ['Cross', 'Crescent and Star', 'Circle', 'Triangle'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'The crescent and star is a common symbol of Islam.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Traditional Religion
  // ============================================
  {
    id: 'jhs-rme-021',
    type: 'mcq',
    question: 'What is the supreme being in African Traditional Religion called?',
    options: ['Ancestors', 'Spirits', 'God or Supreme Being', 'Fetish'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Traditional Religion',
    explanation: 'African Traditional Religion believes in a Supreme Being or God.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-022',
    type: 'mcq',
    question: 'What is the place of worship in Traditional Religion called?',
    options: ['Church', 'Mosque', 'Shrine', 'Temple'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Traditional Religion',
    explanation: 'Shrine is the place of worship in Traditional Religion.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-023',
    type: 'mcq',
    question: 'Who are the intermediaries between God and humans in Traditional Religion?',
    options: ['Priests', 'Ancestors', 'Elders', 'All of the above'],
    correctAnswer: 3,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Traditional Religion',
    explanation: 'Ancestors, priests, and elders can serve as intermediaries in Traditional Religion.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-024',
    type: 'mcq',
    question: 'What is libation in Traditional Religion?',
    options: ['Prayer', 'Pouring of drink as offering', 'Dancing', 'Singing'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Traditional Religion',
    explanation: 'Libation is the pouring of drink (water, wine, or other liquid) as an offering to ancestors or gods.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-025',
    type: 'mcq',
    question: 'What is a fetish in Traditional Religion?',
    options: ['A sacred object', 'A person', 'A place', 'A song'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Traditional Religion',
    explanation: 'A fetish is a sacred object believed to have spiritual power.',
    source: 'practice',
    year: 2019,
  },

  // ============================================
  // Moral Values & Ethics
  // ============================================
  {
    id: 'jhs-rme-026',
    type: 'mcq',
    question: 'What is honesty?',
    options: ['Telling lies', 'Being truthful', 'Stealing', 'Cheating'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Honesty means being truthful and not telling lies.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-027',
    type: 'mcq',
    question: 'What is respect?',
    options: ['Disregarding others', 'Showing regard for others', 'Insulting others', 'Ignoring others'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Respect means showing regard and consideration for others.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-028',
    type: 'mcq',
    question: 'What is tolerance?',
    options: ['Accepting differences', 'Rejecting others', 'Fighting', 'Hating'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Tolerance means accepting and respecting differences in others.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-029',
    type: 'mcq',
    question: 'What is forgiveness?',
    options: ['Holding grudges', 'Letting go of anger and resentment', 'Seeking revenge', 'Hating others'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Forgiveness means letting go of anger and resentment towards someone who has wronged you.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-030',
    type: 'mcq',
    question: 'What is kindness?',
    options: ['Being cruel', 'Being friendly and helpful', 'Being mean', 'Being selfish'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Kindness means being friendly, generous, and considerate towards others.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-031',
    type: 'mcq',
    question: 'What is responsibility?',
    options: ['Avoiding duties', 'Being accountable for one\'s actions', 'Blaming others', 'Being careless'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Responsibility means being accountable for one\'s actions and duties.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-032',
    type: 'mcq',
    question: 'What is integrity?',
    options: ['Being dishonest', 'Having strong moral principles', 'Being corrupt', 'Cheating'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Integrity means having strong moral principles and being honest.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-033',
    type: 'mcq',
    question: 'What is humility?',
    options: ['Being proud', 'Being modest and not arrogant', 'Boasting', 'Showing off'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Humility means being modest and not thinking too highly of oneself.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-034',
    type: 'mcq',
    question: 'What is compassion?',
    options: ['Being cruel', 'Feeling sympathy and concern for others', 'Being indifferent', 'Ignoring suffering'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Compassion means feeling sympathy and concern for the suffering of others.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-035',
    type: 'mcq',
    question: 'What is self-discipline?',
    options: ['Being lazy', 'Controlling one\'s behavior and actions', 'Being careless', 'Lacking control'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Self-discipline means controlling one\'s behavior and actions to achieve goals.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Religious Leaders & Figures
  // ============================================
  {
    id: 'jhs-rme-036',
    type: 'mcq',
    question: 'Who was the first man according to the Bible?',
    options: ['Noah', 'Abraham', 'Adam', 'Moses'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Adam was the first man created by God according to the Bible.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-037',
    type: 'mcq',
    question: 'Who led the Israelites out of Egypt?',
    options: ['Abraham', 'Moses', 'David', 'Solomon'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Moses led the Israelites out of Egypt in the Exodus.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-038',
    type: 'mcq',
    question: 'Who was the first Caliph after Prophet Muhammad?',
    options: ['Umar', 'Abu Bakr', 'Uthman', 'Ali'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Abu Bakr was the first Caliph (successor) after Prophet Muhammad.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Religious Practices
  // ============================================
  {
    id: 'jhs-rme-039',
    type: 'mcq',
    question: 'How many times do Muslims pray daily?',
    options: ['Three', 'Four', 'Five', 'Six'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Muslims pray five times daily: Fajr, Dhuhr, Asr, Maghrib, and Isha.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-040',
    type: 'mcq',
    question: 'What is the direction Muslims face when praying?',
    options: ['North', 'South', 'East', 'Mecca (Qibla)'],
    correctAnswer: 3,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Muslims face Mecca (Qibla) when praying.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-041',
    type: 'mcq',
    question: 'What is baptism in Christianity?',
    options: ['A prayer', 'A ritual of initiation with water', 'A song', 'A reading'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Baptism is a Christian ritual of initiation using water to symbolize purification.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-042',
    type: 'mcq',
    question: 'What is the sacrament of the Lord\'s Supper called?',
    options: ['Baptism', 'Communion or Eucharist', 'Confirmation', 'Marriage'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Communion or Eucharist is the sacrament of the Lord\'s Supper.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Religious Festivals
  // ============================================
  {
    id: 'jhs-rme-043',
    type: 'mcq',
    question: 'What is Eid al-Fitr?',
    options: ['A Christian festival', 'A Muslim festival marking end of Ramadan', 'A traditional festival', 'A Hindu festival'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Eid al-Fitr is a Muslim festival that marks the end of Ramadan.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-044',
    type: 'mcq',
    question: 'What is Eid al-Adha?',
    options: ['Festival of breaking fast', 'Festival of sacrifice', 'Festival of lights', 'Festival of harvest'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Eid al-Adha is the Festival of Sacrifice in Islam.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-045',
    type: 'mcq',
    question: 'What is Good Friday?',
    options: ['Celebration of birth', 'Commemoration of Jesus\' crucifixion', 'Celebration of resurrection', 'Celebration of ascension'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Good Friday commemorates the crucifixion of Jesus Christ.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Social Issues & Ethics
  // ============================================
  {
    id: 'jhs-rme-046',
    type: 'mcq',
    question: 'What is corruption?',
    options: ['Honest behavior', 'Dishonest conduct by those in power', 'Helping others', 'Being responsible'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Corruption is dishonest conduct by those in power, often involving bribery.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-047',
    type: 'mcq',
    question: 'What is the Golden Rule?',
    options: ['Do unto others as you would have them do unto you', 'Treat others badly', 'Ignore others', 'Hurt others'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'The Golden Rule is: "Do unto others as you would have them do unto you."',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-048',
    type: 'mcq',
    question: 'What is peace?',
    options: ['Conflict', 'State of harmony and absence of violence', 'War', 'Fighting'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Peace is a state of harmony and absence of violence or conflict.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-049',
    type: 'mcq',
    question: 'What is justice?',
    options: ['Unfairness', 'Fair treatment and moral rightness', 'Discrimination', 'Inequality'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Justice is fair treatment and moral rightness.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-050',
    type: 'mcq',
    question: 'What is unity?',
    options: ['Division', 'Being together as one', 'Conflict', 'Separation'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Unity means being together as one, working in harmony.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Christianity - Advanced Topics
  // ============================================
  {
    id: 'jhs-rme-051',
    type: 'mcq',
    question: 'What are the two main parts of the Bible?',
    options: ['Old and New Testaments', 'Genesis and Revelation', 'Prophets and Gospels', 'Law and History'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The Bible is divided into the Old Testament and New Testament.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-052',
    type: 'mcq',
    question: 'Who wrote most of the letters in the New Testament?',
    options: ['Peter', 'John', 'Paul', 'James'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Paul wrote most of the epistles (letters) in the New Testament.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-053',
    type: 'mcq',
    question: 'What is the first book of the Bible?',
    options: ['Exodus', 'Genesis', 'Matthew', 'Revelation'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Genesis is the first book of the Bible, meaning "beginning".',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-054',
    type: 'mcq',
    question: 'What is a parable?',
    options: ['A prayer', 'A story with a moral lesson', 'A song', 'A law'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'A parable is a simple story used to illustrate a moral or spiritual lesson.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-055',
    type: 'mcq',
    question: 'What is the Ten Commandments?',
    options: ['Ten prayers', 'Ten laws given to Moses', 'Ten parables', 'Ten miracles'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The Ten Commandments are ten laws given by God to Moses on Mount Sinai.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-056',
    type: 'mcq',
    question: 'What is the first commandment?',
    options: ['Honor your parents', 'You shall not steal', 'You shall have no other gods', 'You shall not kill'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The first commandment is: "You shall have no other gods before me."',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-057',
    type: 'mcq',
    question: 'What is a miracle?',
    options: ['A normal event', 'An extraordinary event that cannot be explained by natural laws', 'A story', 'A prayer'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'A miracle is an extraordinary event that cannot be explained by natural laws.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-058',
    type: 'mcq',
    question: 'Who baptized Jesus?',
    options: ['Peter', 'John the Baptist', 'Paul', 'James'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'John the Baptist baptized Jesus in the River Jordan.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-059',
    type: 'mcq',
    question: 'What is the Sermon on the Mount?',
    options: ['A mountain', 'A famous teaching by Jesus', 'A prayer', 'A miracle'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The Sermon on the Mount is a collection of teachings by Jesus, including the Beatitudes.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-060',
    type: 'mcq',
    question: 'What is the Great Commission?',
    options: ['A commandment to love', 'Jesus\' instruction to spread the gospel', 'A prayer', 'A miracle'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The Great Commission is Jesus\' instruction to his disciples to spread the gospel to all nations.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Islam - Advanced Topics
  // ============================================
  {
    id: 'jhs-rme-061',
    type: 'mcq',
    question: 'What is the second pillar of Islam?',
    options: ['Shahada', 'Salat (Prayer)', 'Zakat', 'Sawm (Fasting)'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Salat (Prayer) is the second pillar of Islam.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-062',
    type: 'mcq',
    question: 'What is the third pillar of Islam?',
    options: ['Salat', 'Zakat (Charity)', 'Sawm', 'Hajj'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Zakat (Charity) is the third pillar of Islam.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-063',
    type: 'mcq',
    question: 'What is the fourth pillar of Islam?',
    options: ['Zakat', 'Sawm (Fasting)', 'Hajj', 'Shahada'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Sawm (Fasting during Ramadan) is the fourth pillar of Islam.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-064',
    type: 'mcq',
    question: 'What is the fifth pillar of Islam?',
    options: ['Sawm', 'Hajj (Pilgrimage)', 'Zakat', 'Salat'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Hajj (Pilgrimage to Mecca) is the fifth pillar of Islam.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-065',
    type: 'mcq',
    question: 'What is the first revelation received by Prophet Muhammad?',
    options: ['Surah Al-Fatiha', 'Surah Al-Baqarah', 'Surah Al-Alaq (Iqra)', 'Surah Al-Ikhlas'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Surah Al-Alaq (Iqra) was the first revelation received by Prophet Muhammad.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-066',
    type: 'mcq',
    question: 'What is the night journey of Prophet Muhammad called?',
    options: ['Hijra', 'Isra and Mi\'raj', 'Hajj', 'Umrah'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Isra and Mi\'raj is the night journey of Prophet Muhammad from Mecca to Jerusalem and then to heaven.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-067',
    type: 'mcq',
    question: 'What is the migration of Prophet Muhammad from Mecca to Medina called?',
    options: ['Hajj', 'Hijra', 'Umrah', 'Isra'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Hijra is the migration of Prophet Muhammad from Mecca to Medina in 622 CE.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-068',
    type: 'mcq',
    question: 'What is the opening chapter of the Quran called?',
    options: ['Surah Al-Baqarah', 'Surah Al-Fatiha', 'Surah Al-Ikhlas', 'Surah Al-Nas'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Surah Al-Fatiha is the opening chapter of the Quran and is recited in every prayer.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-069',
    type: 'mcq',
    question: 'What is the direction Muslims face when praying called?',
    options: ['Mecca', 'Qibla', 'Medina', 'Jerusalem'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Qibla is the direction Muslims face when praying, which is towards Mecca.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-070',
    type: 'mcq',
    question: 'What is the annual charity that Muslims give called?',
    options: ['Sadaqah', 'Zakat', 'Khums', 'Fitrah'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Zakat is the annual charity that Muslims give (usually 2.5% of their wealth).',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Traditional Religion - Advanced Topics
  // ============================================
  {
    id: 'jhs-rme-071',
    type: 'mcq',
    question: 'What is the role of ancestors in Traditional Religion?',
    options: ['They are forgotten', 'They serve as intermediaries between God and humans', 'They are gods', 'They have no role'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Traditional Religion',
    explanation: 'Ancestors serve as intermediaries between God and humans in Traditional Religion.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-072',
    type: 'mcq',
    question: 'What is a priest in Traditional Religion called?',
    options: ['Pastor', 'Imam', 'Okomfo or Priest', 'Reverend'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Traditional Religion',
    explanation: 'In Traditional Religion, a priest is called Okomfo or Priest.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-073',
    type: 'mcq',
    question: 'What is a sacred grove in Traditional Religion?',
    options: ['A forest', 'A sacred forest area for worship', 'A building', 'A river'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Traditional Religion',
    explanation: 'A sacred grove is a sacred forest area set aside for worship and religious activities.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-074',
    type: 'mcq',
    question: 'What is a totem in Traditional Religion?',
    options: ['An animal', 'A symbol representing a clan or family', 'A god', 'A prayer'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Traditional Religion',
    explanation: 'A totem is a symbol (usually an animal) representing a clan or family in Traditional Religion.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-075',
    type: 'mcq',
    question: 'What is divination in Traditional Religion?',
    options: ['Prayer', 'A method of seeking knowledge from the spiritual world', 'Dancing', 'Singing'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Traditional Religion',
    explanation: 'Divination is a method of seeking knowledge or guidance from the spiritual world.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Moral Values & Ethics - Advanced
  // ============================================
  {
    id: 'jhs-rme-076',
    type: 'mcq',
    question: 'What is empathy?',
    options: ['Ignoring others', 'Understanding and sharing the feelings of others', 'Being selfish', 'Being cruel'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Empathy is the ability to understand and share the feelings of others.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-077',
    type: 'mcq',
    question: 'What is perseverance?',
    options: ['Giving up easily', 'Continuing despite difficulties', 'Being lazy', 'Avoiding challenges'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Perseverance means continuing to work towards a goal despite difficulties.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-078',
    type: 'mcq',
    question: 'What is gratitude?',
    options: ['Being ungrateful', 'Being thankful and appreciative', 'Complaining', 'Being selfish'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Gratitude is being thankful and appreciative for what one has received.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-079',
    type: 'mcq',
    question: 'What is loyalty?',
    options: ['Betrayal', 'Faithfulness and commitment to someone or something', 'Disloyalty', 'Abandonment'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Loyalty is faithfulness and commitment to someone or something.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-080',
    type: 'mcq',
    question: 'What is courage?',
    options: ['Fear', 'Bravery in facing danger or difficulty', 'Cowardice', 'Running away'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Courage is bravery in facing danger, difficulty, or pain.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-081',
    type: 'mcq',
    question: 'What is fairness?',
    options: ['Unfairness', 'Treating everyone equally and justly', 'Discrimination', 'Favoritism'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Fairness means treating everyone equally and justly without favoritism.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-082',
    type: 'mcq',
    question: 'What is cooperation?',
    options: ['Working alone', 'Working together for a common goal', 'Competition', 'Conflict'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Cooperation means working together with others for a common goal.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-083',
    type: 'mcq',
    question: 'What is stewardship?',
    options: ['Wastefulness', 'Responsible management of resources', 'Neglect', 'Abuse'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Stewardship is the responsible management and care of resources entrusted to us.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-084',
    type: 'mcq',
    question: 'What is reconciliation?',
    options: ['Conflict', 'Restoring friendly relations after a disagreement', 'War', 'Fighting'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Reconciliation is the process of restoring friendly relations after a disagreement or conflict.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-085',
    type: 'mcq',
    question: 'What is social responsibility?',
    options: ['Ignoring society', 'Acting for the benefit of society', 'Being selfish', 'Avoiding duties'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Social responsibility is acting for the benefit of society as a whole.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Religious Stories & Narratives
  // ============================================
  {
    id: 'jhs-rme-086',
    type: 'mcq',
    question: 'What is the story of the Good Samaritan about?',
    options: ['A journey', 'Showing love and compassion to neighbors', 'A war', 'A miracle'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The Good Samaritan is a parable about showing love and compassion to neighbors, even strangers.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-087',
    type: 'mcq',
    question: 'What is the story of the Prodigal Son about?',
    options: ['A journey', 'Forgiveness and redemption', 'A war', 'A miracle'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The Prodigal Son is a parable about forgiveness and the joy of redemption.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-088',
    type: 'mcq',
    question: 'Who built the Ark according to the Bible?',
    options: ['Moses', 'Noah', 'Abraham', 'David'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Noah built the Ark according to the Bible to save his family and animals from the flood.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-089',
    type: 'mcq',
    question: 'Who was known as the "Father of Faith" in the Bible?',
    options: ['Moses', 'Noah', 'Abraham', 'David'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Abraham is known as the "Father of Faith" because of his unwavering trust in God.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-090',
    type: 'mcq',
    question: 'What is the story of David and Goliath about?',
    options: ['A war', 'Courage and faith overcoming obstacles', 'A journey', 'A miracle'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The story of David and Goliath is about courage and faith overcoming seemingly impossible obstacles.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-091',
    type: 'mcq',
    question: 'Who was the first prophet in Islam?',
    options: ['Muhammad', 'Adam', 'Ibrahim (Abraham)', 'Musa (Moses)'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Adam is considered the first prophet in Islam.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-092',
    type: 'mcq',
    question: 'What is the story of Prophet Ibrahim (Abraham) and his son about?',
    options: ['A journey', 'Obedience and sacrifice', 'A war', 'A miracle'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'The story of Prophet Ibrahim and his son is about obedience to God and willingness to sacrifice.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-093',
    type: 'mcq',
    question: 'Who was the mother of Prophet Isa (Jesus) in Islam?',
    options: ['Maryam (Mary)', 'Khadija', 'Aisha', 'Fatima'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Maryam (Mary) is the mother of Prophet Isa (Jesus) in Islam.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-094',
    type: 'mcq',
    question: 'What is the significance of the Battle of Badr in Islam?',
    options: ['A defeat', 'An important victory for early Muslims', 'A journey', 'A migration'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'The Battle of Badr was an important victory for early Muslims against their enemies.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-095',
    type: 'mcq',
    question: 'What is the significance of Ananse stories in Traditional Religion?',
    options: ['Entertainment only', 'Teaching moral lessons and cultural values', 'Religious rituals', 'Historical records'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Traditional Religion',
    explanation: 'Ananse stories are used to teach moral lessons and cultural values in Traditional Religion.',
    source: 'practice',
    year: 2022,
  },

  // ============================================
  // Religious Laws & Commandments
  // ============================================
  {
    id: 'jhs-rme-096',
    type: 'mcq',
    question: 'What is the Golden Rule in Christianity?',
    options: ['Do unto others as you would have them do unto you', 'Love yourself only', 'Hate your enemies', 'Ignore others'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The Golden Rule is: "Do unto others as you would have them do unto you."',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-097',
    type: 'mcq',
    question: 'What is the greatest commandment according to Jesus?',
    options: ['Love your neighbor', 'Love God with all your heart', 'Love God and love your neighbor', 'Honor your parents'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The greatest commandment is to love God with all your heart and love your neighbor as yourself.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-098',
    type: 'mcq',
    question: 'What is Halal in Islam?',
    options: ['Forbidden', 'Permitted or lawful', 'Sacred', 'Prohibited'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Halal means permitted or lawful according to Islamic law.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-099',
    type: 'mcq',
    question: 'What is Haram in Islam?',
    options: ['Permitted', 'Forbidden or prohibited', 'Sacred', 'Lawful'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Haram means forbidden or prohibited according to Islamic law.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-100',
    type: 'mcq',
    question: 'What is the Islamic law called?',
    options: ['Torah', 'Sharia', 'Bible', 'Vedas'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Sharia is the Islamic law derived from the Quran and Hadith.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Religious Communities & Organizations
  // ============================================
  {
    id: 'jhs-rme-101',
    type: 'mcq',
    question: 'What is a denomination in Christianity?',
    options: ['A building', 'A distinct branch of Christianity', 'A prayer', 'A festival'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'A denomination is a distinct branch of Christianity with its own beliefs and practices.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-102',
    type: 'mcq',
    question: 'What is the Ummah in Islam?',
    options: ['A prayer', 'The global community of Muslims', 'A festival', 'A building'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Ummah is the global community of Muslims worldwide.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-103',
    type: 'mcq',
    question: 'What is interfaith dialogue?',
    options: ['Conflict between religions', 'Conversation between different religious groups', 'A prayer', 'A festival'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Interfaith dialogue is conversation and cooperation between different religious groups.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-104',
    type: 'mcq',
    question: 'What is religious tolerance?',
    options: ['Rejecting other religions', 'Accepting and respecting different religious beliefs', 'Forcing beliefs', 'Ignoring religion'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Religious tolerance is accepting and respecting different religious beliefs and practices.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-105',
    type: 'mcq',
    question: 'What is the role of religious leaders in society?',
    options: ['To cause conflict', 'To guide, teach, and serve their communities', 'To ignore people', 'To be selfish'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Religious leaders guide, teach, and serve their communities, promoting moral values.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Additional Moral & Social Issues
  // ============================================
  {
    id: 'jhs-rme-106',
    type: 'mcq',
    question: 'What is bullying?',
    options: ['Helping others', 'Repeated aggressive behavior intended to harm', 'Being friendly', 'Cooperation'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Bullying is repeated aggressive behavior intended to harm someone physically or emotionally.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-107',
    type: 'mcq',
    question: 'What is peer pressure?',
    options: ['Independence', 'Influence from people of the same age group', 'Adult guidance', 'Self-control'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Peer pressure is influence from people of the same age group to behave in a certain way.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-rme-108',
    type: 'mcq',
    question: 'What is environmental stewardship?',
    options: ['Polluting the environment', 'Caring for and protecting the environment', 'Ignoring nature', 'Wasting resources'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Environmental stewardship is the responsible care and protection of the environment.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-109',
    type: 'mcq',
    question: 'What is the importance of family in religious teachings?',
    options: ['Family is not important', 'Family is the foundation of society and moral values', 'Family should be ignored', 'Family causes problems'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Family is considered the foundation of society and where moral values are first taught.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-110',
    type: 'mcq',
    question: 'What is the purpose of religious education?',
    options: ['To cause division', 'To teach moral values, respect, and understanding', 'To force beliefs', 'To ignore ethics'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Religious education teaches moral values, respect for others, and understanding of different beliefs.',
    source: 'practice',
    year: 2022,
  },
];
