import type { ChallengeQuestion } from '../types';

/**
 * JHS RME (Religious and Moral Education) Question Bank
 * BECE RME
 * Topics: Christianity, Islam, Traditional Religion, Ethics, Moral Values
 */

export const jhsRMEQuestions: ChallengeQuestion[] = [
  // ============================================
  // Christianity - Basic Concepts
  // ============================================
  {
    id: 'jhs-rme-001',
    type: 'mcq',
    question: 'Who is the founder of Christianity?',
    options: ['Moses', 'Jesus Christ', 'Paul', 'Peter'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Jesus Christ is the founder of Christianity.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-002',
    type: 'mcq',
    question: 'What is the holy book of Christians called?',
    options: ['Quran', 'Bible', 'Torah', 'Vedas'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The Bible is the holy book of Christians.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-003',
    type: 'mcq',
    question: 'How many books are in the Bible?',
    options: ['66', '73', '27', '39'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The Protestant Bible has 66 books (39 Old Testament, 27 New Testament).',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-004',
    type: 'mcq',
    question: 'What is the place of worship for Christians called?',
    options: ['Mosque', 'Temple', 'Church', 'Shrine'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Church is the place of worship for Christians.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-005',
    type: 'mcq',
    question: 'What day of the week do Christians worship?',
    options: ['Friday', 'Saturday', 'Sunday', 'Monday'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Most Christians worship on Sunday, the day of resurrection.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-006',
    type: 'mcq',
    question: 'Who are the twelve disciples of Jesus?',
    options: ['The apostles', 'The prophets', 'The priests', 'The elders'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The twelve disciples are also called the apostles.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-007',
    type: 'mcq',
    question: 'What is the main prayer of Christians called?',
    options: ['The Lord\'s Prayer', 'The Hail Mary', 'The Apostles\' Creed', 'The Nicene Creed'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The Lord\'s Prayer (Our Father) is the main prayer taught by Jesus.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-008',
    type: 'mcq',
    question: 'What is the celebration of Jesus\' birth called?',
    options: ['Easter', 'Christmas', 'Pentecost', 'Ascension'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Christmas celebrates the birth of Jesus Christ.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-009',
    type: 'mcq',
    question: 'What is the celebration of Jesus\' resurrection called?',
    options: ['Easter', 'Christmas', 'Pentecost', 'Ascension'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Easter celebrates the resurrection of Jesus Christ.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-010',
    type: 'mcq',
    question: 'What is the symbol of Christianity?',
    options: ['Crescent', 'Star', 'Cross', 'Circle'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'The cross is the main symbol of Christianity.',
    source: 'practice',
    year: 2019,
  },

  // ============================================
  // Islam - Basic Concepts
  // ============================================
  {
    id: 'jhs-rme-011',
    type: 'mcq',
    question: 'Who is the founder of Islam?',
    options: ['Moses', 'Jesus', 'Muhammad', 'Abraham'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Prophet Muhammad is the founder of Islam.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-012',
    type: 'mcq',
    question: 'What is the holy book of Muslims called?',
    options: ['Bible', 'Quran', 'Torah', 'Vedas'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'The Quran is the holy book of Muslims.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-013',
    type: 'mcq',
    question: 'What is the place of worship for Muslims called?',
    options: ['Church', 'Mosque', 'Temple', 'Shrine'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Mosque is the place of worship for Muslims.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-014',
    type: 'mcq',
    question: 'What day of the week do Muslims worship?',
    options: ['Friday', 'Saturday', 'Sunday', 'Monday'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Muslims worship on Friday, which is their holy day.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-015',
    type: 'mcq',
    question: 'What is the name of God in Islam?',
    options: ['Allah', 'Yahweh', 'Jehovah', 'Brahma'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Allah is the Arabic name for God in Islam.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-016',
    type: 'mcq',
    question: 'How many pillars of Islam are there?',
    options: ['Three', 'Four', 'Five', 'Six'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'There are five pillars of Islam: Shahada, Salat, Zakat, Sawm, and Hajj.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-017',
    type: 'mcq',
    question: 'What is the first pillar of Islam?',
    options: ['Prayer', 'Fasting', 'Pilgrimage', 'Declaration of Faith'],
    correctAnswer: 3,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'The first pillar is Shahada (Declaration of Faith).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-018',
    type: 'mcq',
    question: 'What is the holy month of fasting in Islam called?',
    options: ['Hajj', 'Ramadan', 'Eid', 'Muharram'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Ramadan is the holy month when Muslims fast from dawn to sunset.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-019',
    type: 'mcq',
    question: 'What is the pilgrimage to Mecca called?',
    options: ['Hajj', 'Ramadan', 'Eid', 'Umrah'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Hajj is the pilgrimage to Mecca that Muslims should perform at least once in their lifetime.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-020',
    type: 'mcq',
    question: 'What is the symbol of Islam?',
    options: ['Cross', 'Crescent and Star', 'Circle', 'Triangle'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'The crescent and star is a common symbol of Islam.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Traditional Religion
  // ============================================
  {
    id: 'jhs-rme-021',
    type: 'mcq',
    question: 'What is the supreme being in African Traditional Religion called?',
    options: ['Ancestors', 'Spirits', 'God or Supreme Being', 'Fetish'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Traditional Religion',
    explanation: 'African Traditional Religion believes in a Supreme Being or God.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-022',
    type: 'mcq',
    question: 'What is the place of worship in Traditional Religion called?',
    options: ['Church', 'Mosque', 'Shrine', 'Temple'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Traditional Religion',
    explanation: 'Shrine is the place of worship in Traditional Religion.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-023',
    type: 'mcq',
    question: 'Who are the intermediaries between God and humans in Traditional Religion?',
    options: ['Priests', 'Ancestors', 'Elders', 'All of the above'],
    correctAnswer: 3,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Traditional Religion',
    explanation: 'Ancestors, priests, and elders can serve as intermediaries in Traditional Religion.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-024',
    type: 'mcq',
    question: 'What is libation in Traditional Religion?',
    options: ['Prayer', 'Pouring of drink as offering', 'Dancing', 'Singing'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Traditional Religion',
    explanation: 'Libation is the pouring of drink (water, wine, or other liquid) as an offering to ancestors or gods.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-025',
    type: 'mcq',
    question: 'What is a fetish in Traditional Religion?',
    options: ['A sacred object', 'A person', 'A place', 'A song'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Traditional Religion',
    explanation: 'A fetish is a sacred object believed to have spiritual power.',
    source: 'practice',
    year: 2019,
  },

  // ============================================
  // Moral Values & Ethics
  // ============================================
  {
    id: 'jhs-rme-026',
    type: 'mcq',
    question: 'What is honesty?',
    options: ['Telling lies', 'Being truthful', 'Stealing', 'Cheating'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Honesty means being truthful and not telling lies.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-027',
    type: 'mcq',
    question: 'What is respect?',
    options: ['Disregarding others', 'Showing regard for others', 'Insulting others', 'Ignoring others'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Respect means showing regard and consideration for others.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-028',
    type: 'mcq',
    question: 'What is tolerance?',
    options: ['Accepting differences', 'Rejecting others', 'Fighting', 'Hating'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Tolerance means accepting and respecting differences in others.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-029',
    type: 'mcq',
    question: 'What is forgiveness?',
    options: ['Holding grudges', 'Letting go of anger and resentment', 'Seeking revenge', 'Hating others'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Forgiveness means letting go of anger and resentment towards someone who has wronged you.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-030',
    type: 'mcq',
    question: 'What is kindness?',
    options: ['Being cruel', 'Being friendly and helpful', 'Being mean', 'Being selfish'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Kindness means being friendly, generous, and considerate towards others.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-031',
    type: 'mcq',
    question: 'What is responsibility?',
    options: ['Avoiding duties', 'Being accountable for one\'s actions', 'Blaming others', 'Being careless'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Responsibility means being accountable for one\'s actions and duties.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-032',
    type: 'mcq',
    question: 'What is integrity?',
    options: ['Being dishonest', 'Having strong moral principles', 'Being corrupt', 'Cheating'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Integrity means having strong moral principles and being honest.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-033',
    type: 'mcq',
    question: 'What is humility?',
    options: ['Being proud', 'Being modest and not arrogant', 'Boasting', 'Showing off'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Humility means being modest and not thinking too highly of oneself.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-034',
    type: 'mcq',
    question: 'What is compassion?',
    options: ['Being cruel', 'Feeling sympathy and concern for others', 'Being indifferent', 'Ignoring suffering'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Compassion means feeling sympathy and concern for the suffering of others.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-035',
    type: 'mcq',
    question: 'What is self-discipline?',
    options: ['Being lazy', 'Controlling one\'s behavior and actions', 'Being careless', 'Lacking control'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Moral Values',
    explanation: 'Self-discipline means controlling one\'s behavior and actions to achieve goals.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Religious Leaders & Figures
  // ============================================
  {
    id: 'jhs-rme-036',
    type: 'mcq',
    question: 'Who was the first man according to the Bible?',
    options: ['Noah', 'Abraham', 'Adam', 'Moses'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Adam was the first man created by God according to the Bible.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-037',
    type: 'mcq',
    question: 'Who led the Israelites out of Egypt?',
    options: ['Abraham', 'Moses', 'David', 'Solomon'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Moses led the Israelites out of Egypt in the Exodus.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-038',
    type: 'mcq',
    question: 'Who was the first Caliph after Prophet Muhammad?',
    options: ['Umar', 'Abu Bakr', 'Uthman', 'Ali'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Abu Bakr was the first Caliph (successor) after Prophet Muhammad.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Religious Practices
  // ============================================
  {
    id: 'jhs-rme-039',
    type: 'mcq',
    question: 'How many times do Muslims pray daily?',
    options: ['Three', 'Four', 'Five', 'Six'],
    correctAnswer: 2,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Muslims pray five times daily: Fajr, Dhuhr, Asr, Maghrib, and Isha.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-040',
    type: 'mcq',
    question: 'What is the direction Muslims face when praying?',
    options: ['North', 'South', 'East', 'Mecca (Qibla)'],
    correctAnswer: 3,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Muslims face Mecca (Qibla) when praying.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-041',
    type: 'mcq',
    question: 'What is baptism in Christianity?',
    options: ['A prayer', 'A ritual of initiation with water', 'A song', 'A reading'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Baptism is a Christian ritual of initiation using water to symbolize purification.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-042',
    type: 'mcq',
    question: 'What is the sacrament of the Lord\'s Supper called?',
    options: ['Baptism', 'Communion or Eucharist', 'Confirmation', 'Marriage'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Communion or Eucharist is the sacrament of the Lord\'s Supper.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Religious Festivals
  // ============================================
  {
    id: 'jhs-rme-043',
    type: 'mcq',
    question: 'What is Eid al-Fitr?',
    options: ['A Christian festival', 'A Muslim festival marking end of Ramadan', 'A traditional festival', 'A Hindu festival'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Eid al-Fitr is a Muslim festival that marks the end of Ramadan.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-044',
    type: 'mcq',
    question: 'What is Eid al-Adha?',
    options: ['Festival of breaking fast', 'Festival of sacrifice', 'Festival of lights', 'Festival of harvest'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Islam',
    explanation: 'Eid al-Adha is the Festival of Sacrifice in Islam.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-045',
    type: 'mcq',
    question: 'What is Good Friday?',
    options: ['Celebration of birth', 'Commemoration of Jesus\' crucifixion', 'Celebration of resurrection', 'Celebration of ascension'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Christianity',
    explanation: 'Good Friday commemorates the crucifixion of Jesus Christ.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Social Issues & Ethics
  // ============================================
  {
    id: 'jhs-rme-046',
    type: 'mcq',
    question: 'What is corruption?',
    options: ['Honest behavior', 'Dishonest conduct by those in power', 'Helping others', 'Being responsible'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Corruption is dishonest conduct by those in power, often involving bribery.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-047',
    type: 'mcq',
    question: 'What is the Golden Rule?',
    options: ['Do unto others as you would have them do unto you', 'Treat others badly', 'Ignore others', 'Hurt others'],
    correctAnswer: 0,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'The Golden Rule is: "Do unto others as you would have them do unto you."',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-rme-048',
    type: 'mcq',
    question: 'What is peace?',
    options: ['Conflict', 'State of harmony and absence of violence', 'War', 'Fighting'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Peace is a state of harmony and absence of violence or conflict.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-rme-049',
    type: 'mcq',
    question: 'What is justice?',
    options: ['Unfairness', 'Fair treatment and moral rightness', 'Discrimination', 'Inequality'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Justice is fair treatment and moral rightness.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-rme-050',
    type: 'mcq',
    question: 'What is unity?',
    options: ['Division', 'Being together as one', 'Conflict', 'Separation'],
    correctAnswer: 1,
    subject: 'RME',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Ethics',
    explanation: 'Unity means being together as one, working in harmony.',
    source: 'practice',
    year: 2021,
  },
];
