// JHS Science (Integrated Science) Questions
// BECE-level questions migrated to modular ChallengeQuestion format
// NOTE: These are practice-style BECE-level questions, not yet tagged as verified past questions.

import type { ChallengeQuestion } from '../types';

export const jhsScienceQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Initial Batch)
  // ============================================

  // JHS Science - Biology
  {
    id: 'jhs-sci-001',
    type: 'mcq',
    question: 'Which of the following is a living thing?',
    options: ['Stone', 'Water', 'Plant', 'Air'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Plants show characteristics of life.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-002',
    type: 'mcq',
    question: 'The basic unit of life is the...',
    options: ['Cell', 'Tissue', 'Organ', 'System'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'All living things are made of cells.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-sci-003',
    type: 'mcq',
    question: 'The organ for pumping blood in the human body is the...',
    options: ['Lung', 'Liver', 'Heart', 'Kidney'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'The heart pumps blood.',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-sci-004',
    type: 'mcq',
    question: 'Which gas is needed for respiration?',
    options: ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Living things need oxygen to release energy.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-sci-005',
    type: 'mcq',
    question: 'The process by which plants make their own food is...',
    options: ['Respiration', 'Digestion', 'Photosynthesis', 'Excretion'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Using sunlight, CO2 and water.',
    source: 'practice',
    year: 2019,
  },

  // JHS Science - Chemistry
  {
    id: 'jhs-sci-006',
    type: 'mcq',
    question: 'Water freezes at...',
    options: ['100°C', '0°C', '37°C', '50°C'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Freezing point of water.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-sci-007',
    type: 'mcq',
    question: 'A mixture of salt and water can be separated by...',
    options: ['Filtration', 'Evaporation', 'Decantation', 'Sieving'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Water evaporates leaving salt behind.',
    source: 'practice',
    year: 2016,
  },
  {
    id: 'jhs-sci-008',
    type: 'mcq',
    question: 'Which of these is a metal?',
    options: ['Sulfur', 'Carbon', 'Iron', 'Oxygen'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Iron is a metal.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-009',
    type: 'mcq',
    question: 'Which of the following is a chemical change?',
    options: ['Melting ice', 'Burning wood', 'Boiling water', 'Breaking glass'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Burning wood forms new substances (ash, smoke).',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-sci-010',
    type: 'mcq',
    question: 'The three states of matter are...',
    options: ['Solid, liquid, gas', 'Hot, warm, cold', 'Big, medium, small', 'Heavy, light, weightless'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Matter exists in three main states.',
    source: 'practice',
    year: 2021,
  },

  // JHS Science - Physics & Astronomy
  {
    id: 'jhs-sci-011',
    type: 'mcq',
    question: 'Which planet is known as the Red Planet?',
    options: ['Venus', 'Mars', 'Jupiter', 'Saturn'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Astronomy',
    explanation: 'Mars appears red due to iron oxide.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-012',
    type: 'mcq',
    question: 'The sun rises in the...',
    options: ['West', 'North', 'East', 'South'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Astronomy',
    explanation: 'Due to Earth\'s rotation.',
    source: 'practice',
    year: 2015,
  },
  {
    id: 'jhs-sci-013',
    type: 'mcq',
    question: 'What is the main source of energy for the Earth?',
    options: ['Moon', 'Stars', 'Sun', 'Wind'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'The sun provides light and heat energy.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-sci-014',
    type: 'mcq',
    question: 'Which force pulls objects towards the Earth?',
    options: ['Magnetism', 'Gravity', 'Friction', 'Electricity'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Gravity is the force of attraction between objects.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-015',
    type: 'mcq',
    question: 'Sound travels fastest through...',
    options: ['Air', 'Water', 'Solid', 'Vacuum'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Sound waves travel faster in denser materials.',
    source: 'practice',
    year: 2021,
  },

  // ============================================
  // Additional Questions (Batch 1)
  // ============================================

  // JHS Science - Medium (Chemistry, Biology, Physics)
  {
    id: 'jhs-sci-016',
    type: 'mcq',
    question: 'The chemical symbol for Gold is...',
    options: ['Ag', 'Au', 'Fe', 'Pb'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Au comes from Aurum.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-017',
    type: 'mcq',
    question: 'Which part of the flower produces pollen grains?',
    options: ['Stigma', 'Style', 'Anther', 'Ovary'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'The anther is part of the stamen.',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-sci-018',
    type: 'mcq',
    question: 'Force is measured in...',
    options: ['Joules', 'Watts', 'Newtons', 'Meters'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Unit of force is Newton (N).',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-sci-019',
    type: 'mcq',
    question: 'An example of a lever of the first class is...',
    options: ['Wheelbarrow', 'Scissors', 'Nutcracker', 'Sugar tongs'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Fulcrum is between load and effort.',
    source: 'practice',
    year: 2016,
  },
  {
    id: 'jhs-sci-020',
    type: 'mcq',
    question: 'Which vitamin prevents scurvy?',
    options: ['Vitamin A', 'Vitamin B', 'Vitamin C', 'Vitamin D'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Vitamin C deficiency causes scurvy.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-sci-021',
    type: 'mcq',
    question: 'The pH of pure water is...',
    options: ['0', '7', '14', '1'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: '7 is neutral.',
    source: 'practice',
    year: 2015,
  },
  {
    id: 'jhs-sci-022',
    type: 'mcq',
    question: 'Which blood cells fight infections?',
    options: ['Red blood cells', 'White blood cells', 'Platelets', 'Plasma'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'WBCs are part of the immune system.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-023',
    type: 'mcq',
    question: 'The transfer of heat through a solid is called...',
    options: ['Conduction', 'Convection', 'Radiation', 'Emission'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Heat travels through solids by conduction.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-sci-024',
    type: 'mcq',
    question: 'Which of these is a renewable source of energy?',
    options: ['Coal', 'Petroleum', 'Solar energy', 'Natural gas'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Solar energy is replenished naturally.',
    source: 'practice',
    year: 2021,
  },

  // JHS Science - Hard (JHS 3)
  {
    id: 'jhs-sci-025',
    type: 'mcq',
    question: 'The atomic number of an element is equal to the number of...',
    options: ['Neutrons', 'Protons', 'Electrons + Protons', 'Neutrons + Protons'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Atomic number = number of protons.',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-sci-026',
    type: 'mcq',
    question: 'Which law states that "Energy can neither be created nor destroyed"?',
    options: ['Newton\'s Law', 'Ohm\'s Law', 'Law of Conservation of Energy', 'Hooke\'s Law'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'First law of thermodynamics.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-sci-027',
    type: 'mcq',
    question: 'The digestion of protein begins in the...',
    options: ['Mouth', 'Stomach', 'Small intestine', 'Large intestine'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Pepsin in the stomach starts protein digestion.',
    source: 'practice',
    year: 2016,
  },
  {
    id: 'jhs-sci-028',
    type: 'mcq',
    question: 'Calculate the work done when a force of 10N moves a body through 5m.',
    options: ['2 J', '15 J', '50 J', '0.5 J'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Work = Force × Distance = 10 × 5 = 50 Joules.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-sci-029',
    type: 'mcq',
    question: 'Which of the following is an alloy?',
    options: ['Copper', 'Zinc', 'Brass', 'Aluminum'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Brass is an alloy of copper and zinc.',
    source: 'practice',
    year: 2015,
  },
  {
    id: 'jhs-sci-030',
    type: 'mcq',
    question: 'The hormone responsible for the development of male secondary sexual characteristics is...',
    options: ['Estrogen', 'Progesterone', 'Testosterone', 'Insulin'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Testosterone is the male sex hormone.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-031',
    type: 'mcq',
    question: 'In an electric circuit, the ammeter is connected in...',
    options: ['Series', 'Parallel', 'Both', 'None'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Ammeter measures current and must be in series.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-sci-032',
    type: 'mcq',
    question: 'The chemical formula for Table Salt is...',
    options: ['H2O', 'CO2', 'NaCl', 'HCl'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Sodium Chloride.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-033',
    type: 'mcq',
    question: 'Which part of the brain controls balance and posture?',
    options: ['Cerebrum', 'Cerebellum', 'Medulla oblongata', 'Hypothalamus'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Cerebellum coordinates movement.',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-sci-034',
    type: 'mcq',
    question: 'What is the valency of Carbon?',
    options: ['2', '3', '4', '5'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Carbon is in Group 4 and has 4 valence electrons.',
    source: 'practice',
    year: 2022,
  },

  // ============================================
  // Additional BECE Science Questions (Batch 2 - From Online Sources)
  // ============================================

  // JHS Science - Energy & Physics
  {
    id: 'jhs-sci-035',
    type: 'mcq',
    question: 'Which of the following is a source of energy?',
    options: ['Water only', 'Wind only', 'Solar only', 'All of the above'],
    correctAnswer: 3,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Water, wind, and solar are all sources of energy.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-036',
    type: 'mcq',
    question: 'What is the unit of force in the International System of Units (SI)?',
    options: ['Newton', 'Joule', 'Watt', 'Pascal'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Force is measured in Newtons (N).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-037',
    type: 'mcq',
    question: 'Which of the following is a type of simple machine?',
    options: ['Lever', 'Engine', 'Generator', 'Motor'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'A lever is one of the six simple machines.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-038',
    type: 'mcq',
    question: 'What is the SI unit of energy?',
    options: ['Newton', 'Joule', 'Watt', 'Volt'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Energy is measured in Joules (J).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-039',
    type: 'mcq',
    question: 'What is the SI unit of power?',
    options: ['Newton', 'Joule', 'Watt', 'Volt'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Power is measured in Watts (W).',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-040',
    type: 'mcq',
    question: 'The rate of change of velocity is called...',
    options: ['Speed', 'Acceleration', 'Momentum', 'Force'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Acceleration is the rate of change of velocity.',
    source: 'practice',
    year: 2021,
  },

  // JHS Science - Chemistry (Chemical Symbols, Compounds)
  {
    id: 'jhs-sci-041',
    type: 'mcq',
    question: 'What is the chemical symbol for water?',
    options: ['H₂O', 'O₂', 'CO₂', 'H₂'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Water is composed of two hydrogen atoms and one oxygen atom: H₂O.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-042',
    type: 'mcq',
    question: 'What is the chemical symbol for carbon dioxide?',
    options: ['CO', 'CO₂', 'C₂O', 'CaO'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Carbon dioxide consists of one carbon and two oxygen atoms: CO₂.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-043',
    type: 'mcq',
    question: 'Which gas makes up about 78% of the atmosphere?',
    options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Argon'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Nitrogen makes up approximately 78% of Earth\'s atmosphere.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-044',
    type: 'mcq',
    question: 'What is the chemical symbol for oxygen gas?',
    options: ['O', 'O₂', 'O₃', 'OH'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Oxygen exists as a diatomic molecule: O₂.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-sci-045',
    type: 'mcq',
    question: 'Which of the following is an acid?',
    options: ['NaOH', 'HCl', 'NaCl', 'CaCO₃'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'HCl (Hydrochloric acid) is an acid. NaOH is a base, NaCl and CaCO₃ are salts.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-046',
    type: 'mcq',
    question: 'Which of the following is a base?',
    options: ['H₂SO₄', 'HNO₃', 'NaOH', 'HCl'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'NaOH (Sodium hydroxide) is a base. The others are acids.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-047',
    type: 'mcq',
    question: 'What happens when an acid reacts with a base?',
    options: ['Formation of salt and water', 'Formation of gas', 'Formation of acid', 'No reaction'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Acid + Base → Salt + Water (neutralization reaction).',
    source: 'practice',
    year: 2021,
  },

  // JHS Science - Astronomy & Space
  {
    id: 'jhs-sci-048',
    type: 'mcq',
    question: 'Which of the following planets is closest to the sun?',
    options: ['Earth', 'Mars', 'Venus', 'Mercury'],
    correctAnswer: 3,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Astronomy',
    explanation: 'Mercury is the closest planet to the sun.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-049',
    type: 'mcq',
    question: 'Which planet is known as the "Morning Star"?',
    options: ['Mars', 'Venus', 'Jupiter', 'Saturn'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Astronomy',
    explanation: 'Venus is often called the Morning Star or Evening Star.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-050',
    type: 'mcq',
    question: 'How many planets are in our solar system?',
    options: ['7', '8', '9', '10'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Astronomy',
    explanation: 'There are 8 planets: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-051',
    type: 'mcq',
    question: 'What causes day and night on Earth?',
    options: ['Revolution around the sun', 'Rotation on its axis', 'Tilt of Earth', 'Distance from sun'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Astronomy',
    explanation: 'Earth\'s rotation on its axis causes day and night.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-sci-052',
    type: 'mcq',
    question: 'What causes seasons on Earth?',
    options: ['Rotation on axis', 'Revolution around sun', 'Tilt of Earth\'s axis', 'Distance from sun'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Astronomy',
    explanation: 'The tilt of Earth\'s axis (23.5°) causes different parts to receive varying sunlight, creating seasons.',
    source: 'practice',
    year: 2021,
  },

  // JHS Science - More Biology
  {
    id: 'jhs-sci-053',
    type: 'mcq',
    question: 'Which system in the human body is responsible for breathing?',
    options: ['Circulatory system', 'Respiratory system', 'Digestive system', 'Nervous system'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'The respiratory system handles breathing and gas exchange.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-054',
    type: 'mcq',
    question: 'What is the largest organ in the human body?',
    options: ['Liver', 'Heart', 'Skin', 'Lungs'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'The skin is the largest organ, covering the entire body.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-055',
    type: 'mcq',
    question: 'Which blood type is known as the universal donor?',
    options: ['A', 'B', 'AB', 'O'],
    correctAnswer: 3,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Type O blood can be donated to all blood types (universal donor).',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-056',
    type: 'mcq',
    question: 'What is the function of red blood cells?',
    options: ['Fight infection', 'Carry oxygen', 'Clot blood', 'Produce antibodies'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Red blood cells contain hemoglobin which carries oxygen throughout the body.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-057',
    type: 'mcq',
    question: 'Which part of the plant is responsible for making food?',
    options: ['Root', 'Stem', 'Leaf', 'Flower'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Leaves contain chlorophyll and perform photosynthesis to make food.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-058',
    type: 'mcq',
    question: 'What is the process by which plants lose water through their leaves?',
    options: ['Photosynthesis', 'Transpiration', 'Respiration', 'Digestion'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Transpiration is the loss of water vapor from plant leaves.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-059',
    type: 'mcq',
    question: 'Which system transports nutrients and oxygen throughout the body?',
    options: ['Respiratory system', 'Circulatory system', 'Digestive system', 'Nervous system'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'The circulatory system (heart, blood vessels, blood) transports nutrients and oxygen.',
    source: 'practice',
    year: 2020,
  },

  // JHS Science - More Physics (Heat, Light, Sound)
  {
    id: 'jhs-sci-060',
    type: 'mcq',
    question: 'Which method of heat transfer occurs in fluids (liquids and gases)?',
    options: ['Conduction', 'Convection', 'Radiation', 'Insulation'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Convection is heat transfer through the movement of fluids.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-061',
    type: 'mcq',
    question: 'Heat transfer through electromagnetic waves is called...',
    options: ['Conduction', 'Convection', 'Radiation', 'Convection'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Radiation transfers heat through electromagnetic waves (e.g., from the sun).',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-062',
    type: 'mcq',
    question: 'What is the speed of light in vacuum?',
    options: ['3 × 10⁸ m/s', '3 × 10⁶ m/s', '3 × 10⁴ m/s', '3 × 10² m/s'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Light travels at approximately 3 × 10⁸ meters per second in vacuum.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-063',
    type: 'mcq',
    question: 'Sound cannot travel through...',
    options: ['Air', 'Water', 'Vacuum', 'Solid'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Sound requires a medium (matter) to travel. Vacuum has no matter.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-064',
    type: 'mcq',
    question: 'What is the normal human body temperature in Celsius?',
    options: ['35°C', '36°C', '37°C', '38°C'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Normal human body temperature is approximately 37°C (98.6°F).',
    source: 'practice',
    year: 2021,
  },

  // JHS Science - More Chemistry (Elements, Compounds)
  {
    id: 'jhs-sci-065',
    type: 'mcq',
    question: 'What is the chemical symbol for Iron?',
    options: ['Ir', 'In', 'Fe', 'Fr'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Fe comes from the Latin word "ferrum" for iron.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-066',
    type: 'mcq',
    question: 'What is the chemical symbol for Sodium?',
    options: ['So', 'Sd', 'Na', 'Sa'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Na comes from the Latin word "natrium" for sodium.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-067',
    type: 'mcq',
    question: 'Which of the following is a compound?',
    options: ['Oxygen', 'Hydrogen', 'Water', 'Nitrogen'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Water (H₂O) is a compound made of hydrogen and oxygen. Others are elements.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-068',
    type: 'mcq',
    question: 'What is the chemical formula for methane?',
    options: ['CH₄', 'C₂H₆', 'C₃H₈', 'CO₂'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Methane is CH₄ - one carbon atom and four hydrogen atoms.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-069',
    type: 'mcq',
    question: 'Which process separates a mixture using differences in boiling points?',
    options: ['Filtration', 'Distillation', 'Evaporation', 'Decantation'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Distillation separates mixtures based on different boiling points.',
    source: 'practice',
    year: 2020,
  },

  // JHS Science - More Advanced Topics
  {
    id: 'jhs-sci-070',
    type: 'mcq',
    question: 'What is the main function of the nervous system?',
    options: ['Transport nutrients', 'Control body activities', 'Digest food', 'Exchange gases'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'The nervous system controls and coordinates all body activities.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-071',
    type: 'mcq',
    question: 'Which type of energy is stored in food?',
    options: ['Kinetic energy', 'Chemical energy', 'Potential energy', 'Heat energy'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Food contains chemical energy that is released during digestion.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-072',
    type: 'mcq',
    question: 'What is the main function of the kidneys?',
    options: ['Pump blood', 'Filter waste from blood', 'Digest food', 'Exchange gases'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Kidneys filter waste products and excess water from the blood to form urine.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-073',
    type: 'mcq',
    question: 'Which simple machine has a fulcrum, load, and effort?',
    options: ['Pulley', 'Lever', 'Wheel and axle', 'Inclined plane'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'A lever has three parts: fulcrum (pivot point), load, and effort.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-074',
    type: 'mcq',
    question: 'What is the process by which green plants make their own food?',
    options: ['Respiration', 'Photosynthesis', 'Transpiration', 'Digestion'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Photosynthesis is the process where plants use sunlight, CO₂, and water to make glucose.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-075',
    type: 'mcq',
    question: 'Which gas is produced during photosynthesis?',
    options: ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Plants release oxygen as a byproduct of photosynthesis.',
    source: 'practice',
    year: 2020,
  },

  // ============================================
  // Additional BECE Science Questions (Batch 3)
  // ============================================

  // JHS Science - More Biology (Human Body, Health)
  {
    id: 'jhs-sci-076',
    type: 'mcq',
    question: 'Which organ produces bile?',
    options: ['Stomach', 'Liver', 'Pancreas', 'Gallbladder'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'The liver produces bile, which helps in the digestion of fats.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-077',
    type: 'mcq',
    question: 'What is the main function of the small intestine?',
    options: ['Absorb nutrients', 'Store food', 'Produce enzymes', 'Filter blood'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'The small intestine is where most nutrient absorption occurs.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-078',
    type: 'mcq',
    question: 'Which vitamin is produced by the skin when exposed to sunlight?',
    options: ['Vitamin A', 'Vitamin B', 'Vitamin C', 'Vitamin D'],
    correctAnswer: 3,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'The skin produces Vitamin D when exposed to UV rays from sunlight.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-079',
    type: 'mcq',
    question: 'What is the function of platelets in the blood?',
    options: ['Carry oxygen', 'Fight infection', 'Clot blood', 'Transport nutrients'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Platelets help in blood clotting to prevent excessive bleeding.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-080',
    type: 'mcq',
    question: 'Which part of the eye controls the amount of light entering?',
    options: ['Retina', 'Iris', 'Cornea', 'Lens'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'The iris controls the size of the pupil, regulating light entry.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-081',
    type: 'mcq',
    question: 'What is the main function of the large intestine?',
    options: ['Absorb nutrients', 'Absorb water', 'Produce enzymes', 'Digest proteins'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'The large intestine primarily absorbs water and forms feces.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-082',
    type: 'mcq',
    question: 'Which disease is caused by a deficiency of Vitamin C?',
    options: ['Rickets', 'Scurvy', 'Beriberi', 'Night blindness'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Scurvy is caused by Vitamin C deficiency.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-083',
    type: 'mcq',
    question: 'What is the function of the ribcage?',
    options: ['Digest food', 'Protect the heart and lungs', 'Pump blood', 'Filter waste'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'The ribcage protects vital organs like the heart and lungs.',
    source: 'practice',
    year: 2020,
  },

  // JHS Science - More Chemistry (Reactions, Properties)
  {
    id: 'jhs-sci-084',
    type: 'mcq',
    question: 'What happens when iron is exposed to air and moisture?',
    options: ['It melts', 'It rusts', 'It evaporates', 'It freezes'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Iron reacts with oxygen and water to form rust (iron oxide).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-085',
    type: 'mcq',
    question: 'Which of the following is a physical change?',
    options: ['Burning wood', 'Rusting iron', 'Melting ice', 'Cooking food'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Melting ice is a physical change (state change, no new substance formed).',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-086',
    type: 'mcq',
    question: 'What is the chemical symbol for Calcium?',
    options: ['Ca', 'C', 'Cl', 'Cu'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Ca is the chemical symbol for Calcium.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-087',
    type: 'mcq',
    question: 'Which gas is used in fire extinguishers?',
    options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Carbon dioxide is used in fire extinguishers as it doesn\'t support combustion.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-088',
    type: 'mcq',
    question: 'What is the pH of an acidic solution?',
    options: ['Greater than 7', 'Equal to 7', 'Less than 7', 'Equal to 14'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Acids have pH less than 7. pH 7 is neutral, pH > 7 is basic.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-089',
    type: 'mcq',
    question: 'Which method is used to separate salt from water?',
    options: ['Filtration', 'Evaporation', 'Distillation', 'Decantation'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Evaporation removes water, leaving salt behind.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-090',
    type: 'mcq',
    question: 'What is the chemical formula for table salt?',
    options: ['NaCl', 'Na₂CO₃', 'CaCO₃', 'KCl'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Table salt is sodium chloride: NaCl.',
    source: 'practice',
    year: 2021,
  },

  // JHS Science - More Physics (Motion, Forces, Energy)
  {
    id: 'jhs-sci-091',
    type: 'mcq',
    question: 'What is the formula for calculating speed?',
    options: ['Distance × Time', 'Distance ÷ Time', 'Time ÷ Distance', 'Distance + Time'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Speed = Distance ÷ Time',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-092',
    type: 'mcq',
    question: 'What is the formula for calculating work done?',
    options: ['Force × Distance', 'Force ÷ Distance', 'Force + Distance', 'Force - Distance'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Work = Force × Distance (when force and distance are in same direction).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-093',
    type: 'mcq',
    question: 'Which type of energy is stored in a stretched spring?',
    options: ['Kinetic energy', 'Potential energy', 'Heat energy', 'Sound energy'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'A stretched spring has elastic potential energy.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-094',
    type: 'mcq',
    question: 'What happens to the pressure when the area decreases?',
    options: ['Increases', 'Decreases', 'Stays the same', 'Becomes zero'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Pressure = Force ÷ Area. If area decreases, pressure increases (inverse relationship).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-095',
    type: 'mcq',
    question: 'Which simple machine is a wheelbarrow?',
    options: ['First class lever', 'Second class lever', 'Third class lever', 'Pulley'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'A wheelbarrow is a second class lever (load between fulcrum and effort).',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-096',
    type: 'mcq',
    question: 'What is the unit of pressure?',
    options: ['Newton', 'Joule', 'Pascal', 'Watt'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Pressure is measured in Pascals (Pa) or N/m².',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-097',
    type: 'mcq',
    question: 'Which type of mirror is used in vehicles for rear view?',
    options: ['Plane mirror', 'Concave mirror', 'Convex mirror', 'Flat mirror'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Convex mirrors provide a wider field of view, used in vehicle side mirrors.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-098',
    type: 'mcq',
    question: 'What is the frequency of sound measured in?',
    options: ['Hertz', 'Decibels', 'Watts', 'Newtons'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Frequency is measured in Hertz (Hz) - cycles per second.',
    source: 'practice',
    year: 2021,
  },

  // JHS Science - More Plant Biology
  {
    id: 'jhs-sci-099',
    type: 'mcq',
    question: 'Which part of the plant anchors it to the ground?',
    options: ['Stem', 'Leaf', 'Root', 'Flower'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Roots anchor the plant and absorb water and minerals.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-100',
    type: 'mcq',
    question: 'What is the green pigment in plants called?',
    options: ['Hemoglobin', 'Chlorophyll', 'Melanin', 'Carotene'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Chlorophyll is the green pigment that captures light for photosynthesis.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-101',
    type: 'mcq',
    question: 'Which part of the flower contains the male reproductive organ?',
    options: ['Petal', 'Stamen', 'Pistil', 'Sepal'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'The stamen (anther and filament) is the male reproductive part.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-102',
    type: 'mcq',
    question: 'What is the process by which plants take in carbon dioxide?',
    options: ['Respiration', 'Photosynthesis', 'Transpiration', 'Digestion'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'During photosynthesis, plants take in CO₂ from the atmosphere.',
    source: 'practice',
    year: 2021,
  },

  // JHS Science - Environmental Science
  {
    id: 'jhs-sci-103',
    type: 'mcq',
    question: 'Which of the following is a renewable source of energy?',
    options: ['Coal', 'Petroleum', 'Solar energy', 'Natural gas'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'Solar energy is renewable and replenished naturally.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-104',
    type: 'mcq',
    question: 'What is the main cause of air pollution?',
    options: ['Water', 'Wind', 'Burning of fossil fuels', 'Sunlight'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Burning fossil fuels releases harmful gases that pollute the air.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-105',
    type: 'mcq',
    question: 'Which gas is responsible for the greenhouse effect?',
    options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Carbon dioxide and other greenhouse gases trap heat in the atmosphere.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-106',
    type: 'mcq',
    question: 'What is the process of converting waste materials into reusable materials?',
    options: ['Recycling', 'Burning', 'Dumping', 'Evaporation'],
    correctAnswer: 0,
    subject: 'Science',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Chemistry',
    explanation: 'Recycling converts waste into new useful materials.',
    source: 'practice',
    year: 2021,
  },

  // JHS Science - More Advanced Topics
  {
    id: 'jhs-sci-107',
    type: 'mcq',
    question: 'What is the main component of the cell membrane?',
    options: ['Protein', 'Lipid', 'Carbohydrate', 'Nucleic acid'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'The cell membrane is primarily made of lipids (phospholipids).',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-108',
    type: 'mcq',
    question: 'Which process releases energy from food?',
    options: ['Photosynthesis', 'Respiration', 'Transpiration', 'Digestion'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'Cellular respiration breaks down food to release energy (ATP).',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-sci-109',
    type: 'mcq',
    question: 'What is the function of the spinal cord?',
    options: ['Pump blood', 'Digest food', 'Transmit nerve signals', 'Filter waste'],
    correctAnswer: 2,
    subject: 'Science',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Biology',
    explanation: 'The spinal cord transmits nerve signals between the brain and body.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-sci-110',
    type: 'mcq',
    question: 'Which type of circuit allows current to flow through multiple paths?',
    options: ['Series circuit', 'Parallel circuit', 'Open circuit', 'Closed circuit'],
    correctAnswer: 1,
    subject: 'Science',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Physics',
    explanation: 'In a parallel circuit, current flows through multiple separate paths.',
    source: 'practice',
    year: 2020,
  },
];

