// JHS Social Studies Questions
// BECE-level questions migrated to modular ChallengeQuestion format
// NOTE: These are practice-style BECE-level questions, not yet tagged as verified past questions.

import type { ChallengeQuestion } from '../types';

export const jhsSocialStudiesQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Initial Batch)
  // ============================================

  // JHS Social Studies - Geography
  {
    id: 'jhs-soc-001',
    type: 'mcq',
    question: 'The capital city of Ghana is...',
    options: ['Kumasi', 'Accra', 'Tamale', 'Cape Coast'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Accra is the capital.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-002',
    type: 'mcq',
    question: 'The highest mountain in Ghana is...',
    options: ['Mt. Everest', 'Mt. Afadja', 'Mt. Kilimanjaro', 'Mt. Sinai'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Mount Afadja (Afadjato).',
    source: 'practice',
    year: 2017,
  },
  {
    id: 'jhs-soc-003',
    type: 'mcq',
    question: 'Which region of Ghana is known for gold mining?',
    options: ['Northern Region', 'Ashanti Region', 'Western Region', 'Eastern Region'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Western Region has major gold mining activities.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-soc-004',
    type: 'mcq',
    question: 'The largest lake in Ghana is...',
    options: ['Lake Bosomtwe', 'Lake Volta', 'Lake Chad', 'Lake Tanganyika'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Geography',
    explanation: 'Lake Volta is the largest man-made lake in Ghana.',
    source: 'practice',
    year: 2021,
  },

  // JHS Social Studies - History
  {
    id: 'jhs-soc-005',
    type: 'mcq',
    question: 'Ghana became independent in...',
    options: ['1957', '1960', '1966', '1992'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'History',
    explanation: 'March 6, 1957.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-006',
    type: 'mcq',
    question: 'The first President of Ghana was...',
    options: ['J.J. Rawlings', 'K.A. Busia', 'Kwame Nkrumah', 'J.A. Kufuor'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'History',
    explanation: 'Dr. Kwame Nkrumah was the first President.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-007',
    type: 'mcq',
    question: 'Ghana became a republic in...',
    options: ['1957', '1960', '1966', '1992'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'History',
    explanation: 'Ghana became a republic on July 1, 1960.',
    source: 'practice',
    year: 2018,
  },

  // JHS Social Studies - Economics
  {
    id: 'jhs-soc-008',
    type: 'mcq',
    question: 'Which of these is a primary product?',
    options: ['Cocoa', 'Chocolate', 'Cloth', 'Furniture'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Cocoa is a raw material.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-soc-009',
    type: 'mcq',
    question: 'The main cash crop of Ghana is...',
    options: ['Maize', 'Cocoa', 'Yam', 'Cassava'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Cocoa is the major export crop.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-010',
    type: 'mcq',
    question: 'The currency of Ghana is...',
    options: ['Cedi', 'Dollar', 'Pound', 'Euro'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Ghana uses the Ghana Cedi (GHS).',
    source: 'practice',
    year: 2022,
  },

  // JHS Social Studies - Citizenship & Government
  {
    id: 'jhs-soc-011',
    type: 'mcq',
    question: 'The head of the family is the...',
    options: ['Mother', 'Father', 'Uncle', 'Grandfather'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'easy',
    classLevel: 'JHS 1',
    level: 'JHS',
    topic: 'Citizenship',
    explanation: 'Traditionally, the father heads the nuclear family.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-soc-012',
    type: 'mcq',
    question: 'Which of the following is a function of the police?',
    options: ['Making laws', 'Interpreting laws', 'Maintaining law and order', 'Judging criminals'],
    correctAnswer: 2,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Government',
    explanation: 'Police enforce laws.',
    source: 'practice',
    year: 2022,
  },
  {
    id: 'jhs-soc-013',
    type: 'mcq',
    question: 'The constitution of Ghana is the...',
    options: ['Supreme law', 'Ordinary law', 'Customary law', 'Decree'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Government',
    explanation: 'It is the highest law of the land.',
    source: 'practice',
    year: 2016,
  },
  {
    id: 'jhs-soc-014',
    type: 'mcq',
    question: 'Adolescence is the period between...',
    options: ['Childhood and adulthood', 'Birth and childhood', 'Adulthood and old age', 'Infancy and childhood'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Citizenship',
    explanation: 'Transition period.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-soc-015',
    type: 'mcq',
    question: 'Which of these is an environmental problem?',
    options: ['Afforestation', 'Pollution', 'Recycling', 'Conservation'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'medium',
    classLevel: 'JHS 2',
    level: 'JHS',
    topic: 'Environment',
    explanation: 'Pollution harms the environment.',
    source: 'practice',
    year: 2015,
  },

  // ============================================
  // Additional Questions (Batch 1)
  // ============================================

  // JHS Social Studies - Hard (JHS 3)
  {
    id: 'jhs-soc-016',
    type: 'mcq',
    question: 'The three arms of government are...',
    options: ['Executive, Legislature, Judiciary', 'President, Parliament, Courts', 'Ministry, Assembly, Police', 'Executive, Military, Police'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Government',
    explanation: 'Separation of powers ensures checks and balances.',
    source: 'practice',
    year: 2020,
  },
  {
    id: 'jhs-soc-017',
    type: 'mcq',
    question: 'Which of the following is a right of a citizen?',
    options: ['To pay taxes', 'To vote', 'To break laws', 'To avoid responsibilities'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Citizenship',
    explanation: 'Voting is a fundamental right of citizens.',
    source: 'practice',
    year: 2019,
  },
  {
    id: 'jhs-soc-018',
    type: 'mcq',
    question: 'The main export of Ghana is...',
    options: ['Gold', 'Cocoa', 'Oil', 'Diamonds'],
    correctAnswer: 0,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Economics',
    explanation: 'Gold is Ghana\'s largest export by value.',
    source: 'practice',
    year: 2021,
  },
  {
    id: 'jhs-soc-019',
    type: 'mcq',
    question: 'Which of these is a responsibility of a citizen?',
    options: ['To demand rights only', 'To pay taxes', 'To avoid voting', 'To break laws'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Citizenship',
    explanation: 'Paying taxes is a civic responsibility.',
    source: 'practice',
    year: 2018,
  },
  {
    id: 'jhs-soc-020',
    type: 'mcq',
    question: 'The main cause of deforestation in Ghana is...',
    options: ['Natural disasters', 'Illegal logging', 'Wildlife', 'Rainfall'],
    correctAnswer: 1,
    subject: 'Social Studies',
    difficulty: 'hard',
    classLevel: 'JHS 3',
    level: 'JHS',
    topic: 'Environment',
    explanation: 'Illegal logging and farming are major causes.',
    source: 'practice',
    year: 2022,
  },
];

