import type { ChallengeQuestion } from '../types';

export const agriculturalScienceQuestions: ChallengeQuestion[] = [
  {
    id: 'ags-2024-001',
    type: 'mcq',
    question: 'The primary goal of soil testing is to determine:',
    options: ['Market prices', 'Nutrient status and pH', 'Tractor speed', 'Seed color'],
    correctAnswer: 1,
    subject: 'Agricultural Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Soil Science',
    explanation: 'Soil testing helps decide fertilizer and amendment needs for crops.',
    year: 2024,
  },
  {
    id: 'ags-2024-002',
    type: 'mcq',
    question: 'Crop rotation helps to:',
    options: ['Increase one pest population', 'Maintain soil fertility and reduce disease pressure', 'Eliminate irrigation', 'Reduce seed quality'],
    correctAnswer: 1,
    subject: 'Agricultural Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Crop Production',
    explanation: 'Rotating crops interrupts pest cycles and balances nutrient demand.',
    year: 2024,
  },
  {
    id: 'ags-2024-003',
    type: 'mcq',
    question: 'A major indicator of good livestock welfare is:',
    options: ['Overcrowding', 'Adequate feed, water, and clean shelter', 'No vaccination', 'Irregular feeding'],
    correctAnswer: 1,
    subject: 'Agricultural Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Animal Management',
    explanation: 'Animal welfare depends on proper nutrition, health care, and housing.',
    year: 2024,
  },
  {
    id: 'ags-2024-004',
    type: 'mcq',
    question: 'Integrated pest management (IPM) combines:',
    options: ['Only pesticides', 'Biological, cultural, and chemical controls', 'Only hand weeding', 'Only crop burning'],
    correctAnswer: 1,
    subject: 'Agricultural Science',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Pest Management',
    explanation: 'IPM uses multiple strategies for effective and sustainable pest control.',
    year: 2024,
  },
  {
    id: 'ags-2024-005',
    type: 'mcq',
    question: 'Agribusiness planning should begin with:',
    options: ['Guesswork', 'Market and cost analysis', 'Advertising only', 'Hiring immediately'],
    correctAnswer: 1,
    subject: 'Agricultural Science',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Agribusiness',
    explanation: 'Market and cost analysis helps assess viability and profitability.',
    year: 2024,
  },
];
