import type { ChallengeQuestion } from '../types';

export const animalHusbandryQuestions: ChallengeQuestion[] = [
  {
    id: 'ah-2024-001',
    type: 'mcq',
    question: 'A balanced ration for livestock should provide:',
    options: ['Only carbohydrates', 'Required nutrients for growth and production', 'Only water', 'Only vitamins'],
    correctAnswer: 1,
    subject: 'Animal Husbandry',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Animal Nutrition',
    explanation: 'Balanced rations include energy, protein, minerals, vitamins, and water.',
    year: 2024,
  },
  {
    id: 'ah-2024-002',
    type: 'mcq',
    question: 'Biosecurity on a farm helps to:',
    options: ['Spread diseases faster', 'Prevent disease introduction and spread', 'Increase feed costs only', 'Replace vaccination'],
    correctAnswer: 1,
    subject: 'Animal Husbandry',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Animal Health',
    explanation: 'Biosecurity controls movement, hygiene, and exposure risks.',
    year: 2024,
  },
  {
    id: 'ah-2024-003',
    type: 'mcq',
    question: 'Selective breeding is done mainly to:',
    options: ['Reduce all productivity', 'Improve desirable traits in offspring', 'Eliminate management needs', 'Avoid record keeping'],
    correctAnswer: 1,
    subject: 'Animal Husbandry',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Breeding',
    explanation: 'Selection improves traits like growth rate, milk yield, and disease resistance.',
    year: 2024,
  },
  {
    id: 'ah-2024-004',
    type: 'mcq',
    question: 'Good housing for poultry should ensure:',
    options: ['Poor ventilation', 'Ventilation, hygiene, and predator protection', 'Darkness all day', 'No access to water'],
    correctAnswer: 1,
    subject: 'Animal Husbandry',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Housing Systems',
    explanation: 'Proper housing supports health, growth, and productivity.',
    year: 2024,
  },
  {
    id: 'ah-2024-005',
    type: 'mcq',
    question: 'Farm records are important because they support:',
    options: ['Guess-based decisions', 'Performance tracking and better management', 'Disease spread', 'Feed wastage'],
    correctAnswer: 1,
    subject: 'Animal Husbandry',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Farm Management',
    explanation: 'Records provide evidence for cost control, health planning, and productivity analysis.',
    year: 2024,
  },
];
