import type { ChallengeQuestion } from '../types';

export const autoMechanicsQuestions: ChallengeQuestion[] = [
  {
    id: 'am-2023-001',
    type: 'mcq',
    question: 'The engine converts:',
    options: ['Electrical energy to mechanical', 'Chemical energy to mechanical', 'Mechanical to electrical', 'Light to heat'],
    correctAnswer: 1,
    explanation: 'Internal combustion engines convert chemical energy (fuel combustion) into mechanical energy (movement).',
    subject: 'Auto Mechanics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Engine Fundamentals',
    year: 2023,
  },
  {
    id: 'am-2023-002',
    type: 'mcq',
    question: 'A four-stroke engine cycle consists of:',
    options: ['Intake, compression, power, exhaust', 'Start, run, stop, rest', 'Forward, reverse, neutral, park', 'Idle, accelerate, cruise, brake'],
    correctAnswer: 0,
    explanation: 'The four strokes are: 1) Intake (fuel-air in), 2) Compression, 3) Power (combustion), 4) Exhaust (gases out).',
    subject: 'Auto Mechanics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Engine Operation',
    year: 2023,
  },
  {
    id: 'am-2022-003',
    type: 'mcq',
    question: 'The battery provides:',
    options: ['Fuel to engine', 'Electrical power to start engine and run accessories', 'Oil for lubrication', 'Cooling water'],
    correctAnswer: 1,
    explanation: 'Car batteries store electrical energy to power the starter motor, ignition system, lights, and electronics.',
    subject: 'Auto Mechanics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Electrical System',
    year: 2022,
  },
  {
    id: 'am-2023-004',
    type: 'mcq',
    question: 'Engine oil functions to:',
    options: ['Cool and lubricate engine parts', 'Provide fuel', 'Generate electricity', 'Clean windshield'],
    correctAnswer: 0,
    explanation: 'Engine oil lubricates moving parts (reducing friction/wear), cools components, and cleans by carrying away contaminants.',
    subject: 'Auto Mechanics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Lubrication System',
    year: 2023,
  },
  {
    id: 'am-2022-005',
    type: 'mcq',
    question: 'The alternator:',
    options: ['Starts the engine', 'Charges the battery while engine runs', 'Filters air', 'Cools the engine'],
    correctAnswer: 1,
    explanation: 'The alternator generates electricity when the engine runs, charging the battery and powering electrical systems.',
    subject: 'Auto Mechanics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Electrical System',
    year: 2022,
  },
  {
    id: 'am-2023-006',
    type: 'mcq',
    question: 'Brake fluid is used in:',
    options: ['Engine lubrication', 'Hydraulic brake system', 'Fuel injection', 'Cooling system'],
    correctAnswer: 1,
    explanation: 'Brake fluid transmits pressure through hydraulic lines from brake pedal to brake calipers/drums.',
    subject: 'Auto Mechanics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Braking System',
    year: 2023,
  },
  {
    id: 'am-2022-007',
    type: 'mcq',
    question: 'The radiator helps to:',
    options: ['Generate power', 'Cool the engine', 'Filter fuel', 'Start the engine'],
    correctAnswer: 1,
    explanation: 'The radiator dissipates heat from engine coolant to air, preventing overheating.',
    subject: 'Auto Mechanics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Cooling System',
    year: 2022,
  },
  {
    id: 'am-2023-008',
    type: 'mcq',
    question: 'Spark plugs are used in:',
    options: ['Diesel engines', 'Petrol (gasoline) engines', 'Electric motors', 'Hydraulic systems'],
    correctAnswer: 1,
    explanation: 'Spark plugs ignite the fuel-air mixture in petrol engines. Diesel engines use compression ignition instead.',
    subject: 'Auto Mechanics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Ignition System',
    year: 2023,
  },
  {
    id: 'am-2022-009',
    type: 'mcq',
    question: 'The gearbox/transmission:',
    options: ['Stores fuel', 'Changes gear ratios to vary speed and torque', 'Filters air', 'Generates electricity'],
    correctAnswer: 1,
    explanation: 'The transmission adjusts gear ratios, trading speed for torque (pulling power) to match driving conditions.',
    subject: 'Auto Mechanics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Transmission System',
    year: 2022,
  },
  {
    id: 'am-2023-010',
    type: 'mcq',
    question: 'Regular vehicle maintenance includes:',
    options: ['Oil changes, filter replacements, tire checks', 'Only washing the car', 'Only refueling', 'Never checking anything'],
    correctAnswer: 0,
    explanation: 'Preventive maintenance (oil, filters, tires, brakes, fluids) extends vehicle life and ensures safe, reliable operation.',
    subject: 'Auto Mechanics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Vehicle Maintenance',
    year: 2023,
  },
  {
    id: 'am-2022-011',
    type: 'mcq',
    question: 'The carburetor mixes:',
    options: ['Oil and water', 'Air and fuel in proper ratio', 'Brake fluid and coolant', 'Only air'],
    correctAnswer: 1,
    explanation: 'Carburetors atomize fuel and mix it with air in optimal ratios for combustion (replaced by fuel injection in modern cars).',
    subject: 'Auto Mechanics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Fuel System',
    year: 2022,
  },
  {
    id: 'am-2023-012',
    type: 'mcq',
    question: 'Tire pressure should be checked:',
    options: ['Never', 'Regularly when tires are cold', 'Only when flat', 'Only after driving'],
    correctAnswer: 1,
    explanation: 'Check tire pressure when cold (before driving) as heat from driving increases pressure, giving inaccurate readings.',
    subject: 'Auto Mechanics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Tire Maintenance',
    year: 2023,
  },
  {
    id: 'am-2022-013',
    type: 'mcq',
    question: 'The differential allows:',
    options: ['Engine to start', 'Wheels to rotate at different speeds in turns', 'Brakes to work', 'Lights to function'],
    correctAnswer: 1,
    explanation: 'Differentials enable outer wheels to rotate faster than inner wheels during turns, preventing tire scrubbing.',
    subject: 'Auto Mechanics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Drivetrain',
    year: 2022,
  },
  {
    id: 'am-2023-014',
    type: 'mcq',
    question: 'The air filter prevents:',
    options: ['Fuel leaks', 'Dirt and debris from entering the engine', 'Overheating', 'Brake failure'],
    correctAnswer: 1,
    explanation: 'Air filters trap dust, dirt, and debris from intake air, protecting engine cylinders, pistons, and valves from damage.',
    subject: 'Auto Mechanics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Engine Systems',
    year: 2023,
  },
  {
    id: 'am-2022-015',
    type: 'mcq',
    question: 'The clutch in manual transmission:',
    options: ['Generates power', 'Connects/disconnects engine from transmission', 'Steers the car', 'Provides braking'],
    correctAnswer: 1,
    explanation: 'The clutch engages/disengages power from engine to transmission, allowing gear changes without engine stalling.',
    subject: 'Auto Mechanics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Transmission System',
    year: 2022,
  },
  {
    id: 'am-2023-016',
    type: 'mcq',
    question: 'The thermostat in cooling system:',
    options: ['Measures speed', 'Regulates engine temperature by controlling coolant flow', 'Filters oil', 'Charges battery'],
    correctAnswer: 1,
    explanation: 'Thermostats stay closed when cold (fast warm-up) and open when hot, allowing coolant to flow to radiator.',
    subject: 'Auto Mechanics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Cooling System',
    year: 2023,
  },
  {
    id: 'am-2022-017',
    type: 'mcq',
    question: 'Disc brakes use:',
    options: ['Magnets', 'Calipers squeezing brake pads against rotating disc', 'Water pressure', 'Springs only'],
    correctAnswer: 1,
    explanation: 'Disc brakes clamp brake pads against spinning disc (rotor) using hydraulic calipers, creating friction to stop wheels.',
    subject: 'Auto Mechanics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Braking System',
    year: 2022,
  },
  {
    id: 'am-2023-018',
    type: 'mcq',
    question: 'The catalytic converter:',
    options: ['Cools engine', 'Reduces harmful exhaust emissions', 'Increases fuel capacity', 'Powers radio'],
    correctAnswer: 1,
    explanation: 'Catalytic converters use chemical catalysts to convert toxic exhaust gases (CO, NOx, HC) into less harmful emissions.',
    subject: 'Auto Mechanics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Exhaust System',
    year: 2023,
  },
  {
    id: 'am-2022-019',
    type: 'mcq',
    question: 'Wheel alignment ensures:',
    options: ['Better fuel economy', 'Proper tire contact and even wear', 'Louder exhaust', 'Faster acceleration'],
    correctAnswer: 1,
    explanation: 'Proper alignment (camber, caster, toe) ensures tires contact road correctly, preventing uneven wear and improving handling.',
    subject: 'Auto Mechanics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Suspension and Steering',
    year: 2022,
  },
  {
    id: 'am-2023-020',
    type: 'mcq',
    question: 'The purpose of shock absorbers is to:',
    options: ['Generate electricity', 'Dampen suspension movement for smooth ride', 'Increase speed', 'Store fuel'],
    correctAnswer: 1,
    explanation: 'Shock absorbers control spring oscillations, preventing bouncing and maintaining tire contact with road for stability.',
    subject: 'Auto Mechanics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Suspension System',
    year: 2023,
  },
];
