import type { ChallengeQuestion } from '../types';

export const buildingConstructionQuestions: ChallengeQuestion[] = [
  {
    id: 'bc-2023-001',
    type: 'mcq',
    question: 'The foundation of a building is designed to:',
    options: ['Support the roof only', 'Transfer the building load to the ground', 'Provide insulation', 'Create storage space'],
    correctAnswer: 1,
    explanation: 'Foundations transfer and distribute the entire building load safely to the ground, preventing settlement and structural failure.',
    subject: 'Building Construction',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Foundations',
    year: 2023,
  },
  {
    id: 'bc-2023-002',
    type: 'mcq',
    question: 'Concrete is a mixture of:',
    options: ['Sand and water only', 'Cement, sand, aggregate, and water', 'Cement and water only', 'Bricks and mortar'],
    correctAnswer: 1,
    explanation: 'Concrete consists of cement (binder), sand (fine aggregate), coarse aggregate (stones), and water in specific proportions.',
    subject: 'Building Construction',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Building Materials',
    year: 2023,
  },
  {
    id: 'bc-2022-003',
    type: 'mcq',
    question: 'A damp proof course (DPC) is used to:',
    options: ['Strengthen walls', 'Prevent moisture from rising', 'Support the roof', 'Improve appearance'],
    correctAnswer: 1,
    explanation: 'DPC is a waterproof layer placed above ground level to prevent moisture from rising into walls through capillary action.',
    subject: 'Building Construction',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Waterproofing',
    year: 2022,
  },
  {
    id: 'bc-2023-004',
    type: 'mcq',
    question: 'Bricks are bonded in walls to:',
    options: ['Save materials', 'Increase strength and distribute loads', 'Speed up construction', 'Reduce cost only'],
    correctAnswer: 1,
    explanation: 'Bonding (overlapping bricks) increases wall strength, distributes loads evenly, and prevents vertical joints from aligning.',
    subject: 'Building Construction',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Brickwork',
    year: 2023,
  },
  {
    id: 'bc-2022-005',
    type: 'mcq',
    question: 'The main function of a lintel is to:',
    options: ['Support floor loads', 'Support the load above door/window openings', 'Connect walls', 'Provide ventilation'],
    correctAnswer: 1,
    explanation: 'A lintel is a horizontal beam placed above door and window openings to support the wall load above the opening.',
    subject: 'Building Construction',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Structural Elements',
    year: 2022,
  },
  {
    id: 'bc-2023-006',
    type: 'mcq',
    question: 'Reinforcement steel bars in concrete serve to:',
    options: ['Increase weight', 'Resist tensile stresses', 'Improve color', 'Speed up curing'],
    correctAnswer: 1,
    explanation: 'Steel reinforcement resists tensile forces in concrete (which is strong in compression but weak in tension).',
    subject: 'Building Construction',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Reinforced Concrete',
    year: 2023,
  },
  {
    id: 'bc-2022-007',
    type: 'mcq',
    question: 'A pitched roof is designed to:',
    options: ['Save materials', 'Allow rainwater to drain off easily', 'Provide flat surface', 'Reduce building height'],
    correctAnswer: 1,
    explanation: 'Pitched (sloped) roofs allow rainwater to drain quickly, preventing leaks and water damage.',
    subject: 'Building Construction',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Roofing',
    year: 2022,
  },
  {
    id: 'bc-2023-008',
    type: 'mcq',
    question: 'Site excavation should be done:',
    options: ['After roofing', 'Before laying foundations', 'After plastering', 'During painting'],
    correctAnswer: 1,
    explanation: 'Excavation (digging) is the first construction step, creating trenches for foundations at the correct depth and width.',
    subject: 'Building Construction',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Construction Process',
    year: 2023,
  },
  {
    id: 'bc-2022-009',
    type: 'mcq',
    question: 'Mortar is used in brickwork to:',
    options: ['Paint walls', 'Bond bricks together', 'Reinforce concrete', 'Create foundations'],
    correctAnswer: 1,
    explanation: 'Mortar (cement, sand, water mix) bonds bricks together, filling gaps and distributing loads between bricks.',
    subject: 'Building Construction',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Building Materials',
    year: 2022,
  },
  {
    id: 'bc-2023-010',
    type: 'mcq',
    question: 'Scaffolding in construction is used for:',
    options: ['Permanent structure', 'Temporary access to heights during construction', 'Foundation support', 'Roof structure'],
    correctAnswer: 1,
    explanation: 'Scaffolding provides temporary safe access platforms for workers and materials at different building heights during construction.',
    subject: 'Building Construction',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Construction Safety',
    year: 2023,
  },
  {
    id: 'bc-2022-011',
    type: 'mcq',
    question: 'A column in building construction is designed to:',
    options: ['Support horizontal loads only', 'Support vertical loads from beams and slabs', 'Provide decoration', 'Hold windows'],
    correctAnswer: 1,
    explanation: 'Columns are vertical structural members that transfer loads from beams, slabs, and roofs down to foundations.',
    subject: 'Building Construction',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Structural Elements',
    year: 2022,
  },
  {
    id: 'bc-2023-012',
    type: 'mcq',
    question: 'Plastering is applied to walls to:',
    options: ['Weaken them', 'Provide smooth finish and protect from weather', 'Make them transparent', 'Reduce height'],
    correctAnswer: 1,
    explanation: 'Plaster provides smooth, durable finish for interior walls and protects exterior walls from rain and weathering.',
    subject: 'Building Construction',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Finishes',
    year: 2023,
  },
  {
    id: 'bc-2022-013',
    type: 'mcq',
    question: 'A beam functions to:',
    options: ['Support vertical loads only', 'Support horizontal loads and transfer to columns', 'Provide insulation', 'Hold doors'],
    correctAnswer: 1,
    explanation: 'Beams are horizontal structural members that carry loads from slabs and transfer them to columns or walls.',
    subject: 'Building Construction',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Structural Elements',
    year: 2022,
  },
  {
    id: 'bc-2023-014',
    type: 'mcq',
    question: 'Expansion joints in concrete structures allow for:',
    options: ['Water drainage', 'Thermal expansion and contraction', 'Electrical wiring', 'Decoration'],
    correctAnswer: 1,
    explanation: 'Expansion joints provide gaps that allow concrete to expand in heat and contract in cold without cracking.',
    subject: 'Building Construction',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Concrete Structures',
    year: 2023,
  },
  {
    id: 'bc-2022-015',
    type: 'mcq',
    question: 'Formwork (shuttering) is used for:',
    options: ['Permanent walls', 'Temporary molds to shape wet concrete', 'Roof covering', 'Floor tiles'],
    correctAnswer: 1,
    explanation: 'Formwork are temporary wooden or metal molds that hold liquid concrete until it sets and gains strength.',
    subject: 'Building Construction',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Concrete Construction',
    year: 2022,
  },
  {
    id: 'bc-2023-016',
    type: 'mcq',
    question: 'The correct water-cement ratio for concrete is important for:',
    options: ['Color only', 'Strength and workability', 'Weight reduction', 'Faster construction'],
    correctAnswer: 1,
    explanation: 'Proper water-cement ratio (typically 0.4-0.6) ensures concrete is workable yet achieves required strength when cured.',
    subject: 'Building Construction',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Concrete Technology',
    year: 2023,
  },
  {
    id: 'bc-2022-017',
    type: 'mcq',
    question: 'A footing is:',
    options: ['Roof support', 'Widened base of foundation that spreads load', 'Window frame', 'Wall decoration'],
    correctAnswer: 1,
    explanation: 'Footings are widened concrete bases under foundations that spread building loads over larger soil area.',
    subject: 'Building Construction',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Foundations',
    year: 2022,
  },
  {
    id: 'bc-2023-018',
    type: 'mcq',
    question: 'Curing of concrete involves:',
    options: ['Breaking it', 'Keeping it moist for proper hardening', 'Painting it immediately', 'Removing formwork'],
    correctAnswer: 1,
    explanation: 'Curing keeps concrete moist (water spraying, covering) for 7-28 days, allowing cement hydration for full strength.',
    subject: 'Building Construction',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Concrete Technology',
    year: 2023,
  },
  {
    id: 'bc-2022-019',
    type: 'mcq',
    question: 'Cavity walls consist of:',
    options: ['Single brick layer', 'Two parallel walls with air gap between', 'Solid concrete', 'Glass panels'],
    correctAnswer: 1,
    explanation: 'Cavity walls have two brick/block layers separated by air gap, providing thermal insulation and moisture protection.',
    subject: 'Building Construction',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Wall Construction',
    year: 2022,
  },
  {
    id: 'bc-2023-020',
    type: 'mcq',
    question: 'Personal protective equipment (PPE) on construction sites includes:',
    options: ['Casual clothes only', 'Hard hats, safety boots, gloves, goggles', 'Formal wear', 'Sandals'],
    correctAnswer: 1,
    explanation: 'PPE protects workers from falling objects (hard hats), sharp materials (gloves), and foot injuries (steel-toe boots).',
    subject: 'Building Construction',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Construction Safety',
    year: 2023,
  },
];
