import type { ChallengeQuestion } from '../types';

export const christianReligiousStudiesQuestions: ChallengeQuestion[] = [
  {
    id: 'crs-2024-001',
    type: 'mcq',
    question: 'In Christian teaching, the "Good Samaritan" parable emphasizes:',
    options: ['Religious rituals only', 'Love for neighbors in need', 'Political leadership', 'Temple sacrifices'],
    correctAnswer: 1,
    subject: 'Christian Religious Studies',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Moral Teachings',
    explanation: 'The parable teaches compassion and practical love for others, regardless of background.',
    year: 2024,
  },
  {
    id: 'crs-2024-002',
    type: 'mcq',
    question: 'The New Testament is mainly centered on:',
    options: ['Kings of Israel only', 'Life and teachings of Jesus and the early Church', 'Roman law', 'Greek mythology'],
    correctAnswer: 1,
    subject: 'Christian Religious Studies',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Bible Knowledge',
    explanation: 'The New Testament focuses on Jesus Christ, the apostles, and the early Church.',
    year: 2024,
  },
  {
    id: 'crs-2024-003',
    type: 'mcq',
    question: 'Which Christian value best supports honest public service?',
    options: ['Partiality', 'Integrity', 'Greed', 'Revenge'],
    correctAnswer: 1,
    subject: 'Christian Religious Studies',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Faith and Society',
    explanation: 'Integrity means being truthful and morally upright in both private and public life.',
    year: 2024,
  },
  {
    id: 'crs-2024-004',
    type: 'mcq',
    question: 'Forgiveness in Christianity is primarily seen as:',
    options: ['A sign of weakness', 'A command and virtue that restores relationships', 'Only for leaders', 'Optional in family life'],
    correctAnswer: 1,
    subject: 'Christian Religious Studies',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Character Formation',
    explanation: 'Christian ethics encourages forgiveness as a pathway to peace and reconciliation.',
    year: 2024,
  },
  {
    id: 'crs-2024-005',
    type: 'mcq',
    question: 'A Christian response to corruption should include:',
    options: ['Silence to avoid trouble', 'Active honesty and accountability', 'Personal revenge', 'Ignoring laws'],
    correctAnswer: 1,
    subject: 'Christian Religious Studies',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Ethics and Citizenship',
    explanation: 'Biblical ethics supports justice, accountability, and rejecting dishonest gain.',
    year: 2024,
  },
];
