import type { ChallengeQuestion } from '../types';

export const clothingAndTextilesQuestions: ChallengeQuestion[] = [
  {
    id: 'cat-2024-001',
    type: 'mcq',
    question: 'A seam allowance is the:',
    options: ['Decorative line only', 'Extra fabric between stitching and raw edge', 'Thread thickness', 'Pattern label'],
    correctAnswer: 1,
    subject: 'Clothing and Textiles',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Garment Construction',
    explanation: 'Seam allowance is left to join fabric pieces securely.',
    year: 2024,
  },
  {
    id: 'cat-2024-002',
    type: 'mcq',
    question: 'Before cutting fabric, a key step is to:',
    options: ['Skip measurements', 'Lay and align pattern pieces correctly', 'Cut freehand', 'Ignore grainline'],
    correctAnswer: 1,
    subject: 'Clothing and Textiles',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Pattern Work',
    explanation: 'Correct pattern placement improves fit and reduces waste.',
    year: 2024,
  },
  {
    id: 'cat-2024-003',
    type: 'mcq',
    question: 'Fabric grain direction influences:',
    options: ['Nothing significant', 'Drape, strength, and fit', 'Only color', 'Only price'],
    correctAnswer: 1,
    subject: 'Clothing and Textiles',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Fabric Properties',
    explanation: 'Cutting with grain direction supports garment shape and durability.',
    year: 2024,
  },
  {
    id: 'cat-2024-004',
    type: 'mcq',
    question: 'The main purpose of pressing during sewing is to:',
    options: ['Burn fabric', 'Set seams and improve finish quality', 'Shrink all garments', 'Remove stitch lines'],
    correctAnswer: 1,
    subject: 'Clothing and Textiles',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Finishing Techniques',
    explanation: 'Pressing improves accuracy and professional garment appearance.',
    year: 2024,
  },
  {
    id: 'cat-2024-005',
    type: 'mcq',
    question: 'Quality control in garment production focuses on:',
    options: ['Speed only', 'Fit, stitching accuracy, and finish', 'Brand name only', 'Color trends only'],
    correctAnswer: 1,
    subject: 'Clothing and Textiles',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Production Standards',
    explanation: 'Good quality garments meet fit, durability, and finishing standards.',
    year: 2024,
  },
];
