// Core Mathematics Questions for SHS
// Initial batch of questions migrated to modular ChallengeQuestion format
// NOTE: These are practice-style WASSCE-level questions, not yet tagged as verified past questions.

import type { ChallengeQuestion } from '../types';

export const coreMathematicsQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Initial Batch)
  // ============================================

  // Core Mathematics - Number & Numeration
  {
    id: 'shs-coremath-001',
    type: 'mcq',
    question: 'Express 0.375 as a fraction in its simplest form.',
    options: ['3/8', '5/8', '3/4', '7/8'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Fractions and Decimals',
    explanation: '0.375 = 375/1000. Dividing numerator and denominator by 125 gives 3/8.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-002',
    type: 'mcq',
    question: 'Simplify: 3/5 + 2/3.',
    options: ['5/8', '19/15', '13/15', '1'],
    correctAnswer: 1,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Fractions',
    explanation: 'LCM of 5 and 3 is 15. 3/5 = 9/15, 2/3 = 10/15, sum = 19/15.',
    source: 'practice',
  },

  // Core Mathematics - Algebra
  {
    id: 'shs-coremath-003',
    type: 'mcq',
    question: 'Simplify: 2x - 3 + 4x + 7.',
    options: ['6x + 4', '6x - 10', '2x + 10', '4x + 4'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Algebraic Expressions',
    explanation: 'Group like terms: 2x + 4x = 6x; -3 + 7 = 4; result is 6x + 4.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-004',
    type: 'mcq',
    question: 'Solve for x: 3x - 5 = 10.',
    options: ['x = 3', 'x = 4', 'x = 5', 'x = 15'],
    correctAnswer: 1,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Linear Equations',
    explanation: 'Add 5 to both sides: 3x = 15; divide by 3: x = 5.',
    source: 'practice',
  },

  // Core Mathematics - Indices & Surds
  {
    id: 'shs-coremath-005',
    type: 'mcq',
    question: 'Simplify: 2³ × 2².',
    options: ['2⁵', '2⁶', '2⁴', '2³'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Indices',
    explanation: 'When multiplying with the same base, add the powers: 2³ × 2² = 2⁵.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-006',
    type: 'mcq',
    question: 'Which of the following is equal to √50?',
    options: ['5√2', '10√5', '25√2', '2√5'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Surds',
    explanation: '50 = 25 × 2, so √50 = √(25 × 2) = 5√2.',
    source: 'practice',
  },

  // Core Mathematics - Geometry & Trigonometry
  {
    id: 'shs-coremath-007',
    type: 'mcq',
    question: 'The sum of the interior angles of a triangle is:',
    options: ['90°', '120°', '180°', '360°'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Plane Geometry',
    explanation: 'For any triangle, the sum of the interior angles is 180°.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-008',
    type: 'mcq',
    question: 'In a right-angled triangle, if sin θ = 3/5, what is cos θ (for acute angle θ)?',
    options: ['4/5', '5/3', '3/4', '1/5'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Trigonometry',
    explanation: 'Opposite = 3, hypotenuse = 5, so adjacent = 4 by Pythagoras. cos θ = adjacent/hypotenuse = 4/5.',
    source: 'practice',
  },

  // Core Mathematics - Mensuration & Statistics
  {
    id: 'shs-coremath-009',
    type: 'mcq',
    question: 'Find the area of a triangle with base 8 cm and height 5 cm.',
    options: ['13 cm²', '40 cm²', '20 cm²', '16 cm²'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Mensuration',
    explanation: 'Area = 1/2 × base × height = 1/2 × 8 × 5 = 20 cm².',
    source: 'practice',
  },
  {
    id: 'shs-coremath-010',
    type: 'mcq',
    question: 'The scores of 5 students are 4, 6, 8, 10, 12. What is the mean score?',
    options: ['7', '8', '9', '10'],
    correctAnswer: 1,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Statistics',
    explanation: 'Sum = 4 + 6 + 8 + 10 + 12 = 40; mean = 40 ÷ 5 = 8.',
    source: 'practice',
  },

  // ============================================
  // Additional MCQ Batch (11–20)
  // ============================================

  // Core Mathematics - Sets & Relations
  {
    id: 'shs-coremath-011',
    type: 'mcq',
    question: 'If A = {1, 2, 3, 4} and B = {3, 4, 5, 6}, what is A ∩ B?',
    options: ['{1, 2}', '{3, 4}', '{5, 6}', '{1, 2, 3, 4, 5, 6}'],
    correctAnswer: 1,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Sets',
    explanation: 'A ∩ B is the set of elements common to both A and B: {3, 4}.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-012',
    type: 'mcq',
    question: 'Which of the following is a universal set for the set of even natural numbers less than 10?',
    options: ['{1, 2, 3, 4, 5}', '{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}', '{2, 4, 6, 8}', '{0, 2, 4, 6, 8}'],
    correctAnswer: 1,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Sets',
    explanation: 'A universal set must contain all elements under consideration. All natural numbers up to 10 works.',
    source: 'practice',
  },

  // Core Mathematics - Linear Equations & Inequalities
  {
    id: 'shs-coremath-013',
    type: 'mcq',
    question: 'Solve the inequality: 2x + 3 < 11.',
    options: ['x < 4', 'x > 4', 'x < 7', 'x > 7'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Inequalities',
    explanation: '2x + 3 < 11 ⇒ 2x < 8 ⇒ x < 4.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-014',
    type: 'mcq',
    question: 'If 5x - 2 = 3x + 6, find x.',
    options: ['2', '3', '4', '5'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Linear Equations',
    explanation: '5x - 2 = 3x + 6 ⇒ 5x - 3x = 6 + 2 ⇒ 2x = 8 ⇒ x = 4.',
    source: 'practice',
  },

  // Core Mathematics - Quadratic Equations
  {
    id: 'shs-coremath-015',
    type: 'mcq',
    question: 'Solve the equation x² - 5x + 6 = 0.',
    options: ['x = 2 or 3', 'x = -2 or -3', 'x = 1 or 6', 'x = -1 or -6'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Quadratic Equations',
    explanation: 'Factor: x² - 5x + 6 = (x - 2)(x - 3) = 0 ⇒ x = 2 or x = 3.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-016',
    type: 'mcq',
    question: 'The roots of the quadratic equation x² + 4x + 3 = 0 are:',
    options: ['-1 and -3', '1 and 3', '-1 and 3', '1 and -3'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Quadratic Equations',
    explanation: 'x² + 4x + 3 = (x + 1)(x + 3) ⇒ roots are -1 and -3.',
    source: 'practice',
  },

  // Core Mathematics - Ratio, Proportion & Percentages
  {
    id: 'shs-coremath-017',
    type: 'mcq',
    question: 'Express the ratio 8:12 in its simplest form.',
    options: ['2:3', '3:2', '4:6', '6:4'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Ratio and Proportion',
    explanation: 'Divide both terms by 4: 8 ÷ 4 = 2, 12 ÷ 4 = 3, so 8:12 = 2:3.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-018',
    type: 'mcq',
    question: 'A shirt is sold for GH₵90 after a 10% discount. What was the marked price?',
    options: ['GH₵81', 'GH₵90', 'GH₵95', 'GH₵100'],
    correctAnswer: 3,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Percentages',
    explanation: 'Let marked price be M. After 10% discount: 0.9M = 90 ⇒ M = 90 ÷ 0.9 = 100.',
    source: 'practice',
  },

  // Core Mathematics - Simple Interest
  {
    id: 'shs-coremath-019',
    type: 'mcq',
    question: 'What is the simple interest on GH₵500 at 8% per annum for 3 years?',
    options: ['GH₵80', 'GH₵100', 'GH₵120', 'GH₵150'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Simple Interest',
    explanation: 'I = PRT/100 = 500 × 8 × 3 / 100 = 120.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-020',
    type: 'mcq',
    question: 'A sum of money amounts to GH₵1,260 in 3 years at simple interest. If the principal is GH₵1,000, what is the rate per annum?',
    options: ['6%', '7%', '8%', '10%'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Simple Interest',
    explanation: 'Interest I = 1,260 - 1,000 = 260. I = PRT/100 ⇒ 260 = 1000 × R × 3 / 100 ⇒ R = (260 × 100) / (1000 × 3) = 8.67% ≈ 8%.',
    source: 'practice',
  },

  // ============================================
  // Additional MCQ Batch (21–30)
  // ============================================

  // Core Mathematics - Sequences & Series
  {
    id: 'shs-coremath-021',
    type: 'mcq',
    question: 'What is the next term in the sequence: 3, 7, 11, 15, ... ?',
    options: ['18', '19', '20', '21'],
    correctAnswer: 1,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Sequences',
    explanation: 'Common difference is 4. Next term: 15 + 4 = 19.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-022',
    type: 'mcq',
    question: 'The nth term of a sequence is given by Tₙ = 2n + 1. What is T₅?',
    options: ['9', '10', '11', '12'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Sequences',
    explanation: 'T₅ = 2(5) + 1 = 10 + 1 = 11.',
    source: 'practice',
  },

  // Core Mathematics - Logarithms
  {
    id: 'shs-coremath-023',
    type: 'mcq',
    question: 'Evaluate log₁₀(1000).',
    options: ['1', '2', '3', '4'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Logarithms',
    explanation: '10³ = 1000, so log₁₀(1000) = 3.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-024',
    type: 'mcq',
    question: 'If log₁₀(2) = 0.3010 and log₁₀(3) = 0.4771, find log₁₀(6).',
    options: ['0.1761', '0.6020', '0.7781', '0.3010'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Logarithms',
    explanation: 'log(6) = log(2 × 3) = log 2 + log 3 = 0.3010 + 0.4771 = 0.7781.',
    source: 'practice',
  },

  // Core Mathematics - Probability
  {
    id: 'shs-coremath-025',
    type: 'mcq',
    question: 'A fair die is thrown once. What is the probability of getting a number greater than 4?',
    options: ['1/6', '2/6', '3/6', '4/6'],
    correctAnswer: 1,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Probability',
    explanation: 'Numbers greater than 4 are 5 and 6. Probability = 2/6 = 1/3.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-026',
    type: 'mcq',
    question: 'In a box, there are 3 red balls and 5 blue balls. One ball is picked at random. What is the probability of picking a red ball?',
    options: ['3/5', '3/8', '5/8', '1/3'],
    correctAnswer: 1,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Probability',
    explanation: 'Total balls = 8. Red balls = 3. Probability = 3/8.',
    source: 'practice',
  },

  // Core Mathematics - Coordinate Geometry
  {
    id: 'shs-coremath-027',
    type: 'mcq',
    question: 'Find the gradient of the line passing through the points (2, 3) and (6, 11).',
    options: ['2', '3/2', '4/3', '5/2'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Coordinate Geometry',
    explanation: 'Gradient m = (11 - 3) / (6 - 2) = 8/4 = 2.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-028',
    type: 'mcq',
    question: 'What is the distance between the points (0, 0) and (6, 8)?',
    options: ['10', '12', '8', '6'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Coordinate Geometry',
    explanation: 'Distance = √[(6 - 0)² + (8 - 0)²] = √(36 + 64) = √100 = 10.',
    source: 'practice',
  },

  // Core Mathematics - Matrices
  {
    id: 'shs-coremath-029',
    type: 'mcq',
    question: 'If A = [[1, 2], [3, 4]], what is the determinant of A?',
    options: ['-2', '2', '5', '7'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Matrices',
    explanation: 'det(A) = (1 × 4) - (2 × 3) = 4 - 6 = -2.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-030',
    type: 'mcq',
    question: 'Which of the following is the identity matrix of order 2?',
    options: [
      '[ 1  0 ] [ 0  1 ]',
      '[ 0  1 ] [ 1  0 ]',
      '[ 1  1 ] [ 0  1 ]',
      '[ 0  0 ] [ 0  1 ]',
    ],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Matrices',
    explanation: 'The identity matrix has 1s on the leading diagonal and 0s elsewhere: [1 0; 0 1].',
    source: 'practice',
  },

  // ============================================
  // Additional Questions - Expansion to 80 per level
  // ============================================
  // NOTE: These are WASSCE-level practice questions. Actual verified WASSCE questions should use source: 'wassce'

  // SHS 1 Questions (Batch 2 - continuing from 15 to reach 80)
  {
    id: 'shs-coremath-031',
    type: 'mcq',
    question: 'Find the value of 2³ × 3².',
    options: ['72', '36', '48', '54'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Indices',
    explanation: '2³ = 8, 3² = 9. Product = 8 × 9 = 72.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-032',
    type: 'mcq',
    question: 'Simplify: √(18) + √(32).',
    options: ['7√2', '5√2', '9√2', '11√2'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Surds',
    explanation: '√(18) = √(9×2) = 3√2. √(32) = √(16×2) = 4√2. Sum = 3√2 + 4√2 = 7√2.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-033',
    type: 'mcq',
    question: 'If A = {1, 2, 3, 4, 5} and B = {4, 5, 6, 7}, find A ∪ B.',
    options: ['{1, 2, 3, 4, 5}', '{4, 5}', '{1, 2, 3, 4, 5, 6, 7}', '{6, 7}'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Sets',
    explanation: 'Union contains all elements from both sets: {1, 2, 3, 4, 5, 6, 7}.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-034',
    type: 'mcq',
    question: 'Solve for x: 4x - 7 = 2x + 5.',
    options: ['x = 4', 'x = 5', 'x = 6', 'x = 7'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Linear Equations',
    explanation: '4x - 7 = 2x + 5 ⇒ 4x - 2x = 5 + 7 ⇒ 2x = 12 ⇒ x = 6.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-035',
    type: 'mcq',
    question: 'Express 5/8 as a decimal.',
    options: ['0.625', '0.58', '0.8', '0.5'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Fractions and Decimals',
    explanation: '5 ÷ 8 = 0.625.',
    source: 'practice',
  },

  // Batch 1 - First 25 additional questions (036-060)
  {
    id: 'shs-coremath-036',
    type: 'mcq',
    question: 'Simplify: (2x + 3)(x - 4)',
    options: ['2x² - 5x - 12', '2x² - 8x + 3x - 12', '2x² - 11x - 12', '2x² + 11x - 12'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Algebraic Expressions',
    explanation: '(2x + 3)(x - 4) = 2x(x - 4) + 3(x - 4) = 2x² - 8x + 3x - 12 = 2x² - 5x - 12.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-037',
    type: 'mcq',
    question: 'Find the HCF of 24 and 36.',
    options: ['6', '12', '18', '24'],
    correctAnswer: 1,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Numbers',
    explanation: 'Factors of 24: 1, 2, 3, 4, 6, 8, 12, 24. Factors of 36: 1, 2, 3, 4, 6, 9, 12, 18, 36. HCF = 12.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-038',
    type: 'mcq',
    question: 'Solve: 2x - 5 ≥ 7',
    options: ['x ≥ 6', 'x ≥ 7', 'x ≥ 8', 'x ≤ 6'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Inequalities',
    explanation: '2x - 5 ≥ 7 ⇒ 2x ≥ 12 ⇒ x ≥ 6.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-039',
    type: 'mcq',
    question: 'Find the LCM of 6 and 8.',
    options: ['24', '32', '48', '12'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Numbers',
    explanation: 'Multiples of 6: 6, 12, 18, 24, 30... Multiples of 8: 8, 16, 24, 32... LCM = 24.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-040',
    type: 'mcq',
    question: 'If 30% of a number is 45, find the number.',
    options: ['120', '135', '150', '180'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Percentages',
    explanation: 'Let the number be x. (30/100)x = 45 ⇒ x = 45 × (100/30) = 150.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-041',
    type: 'mcq',
    question: 'Simplify: 5a² - 3a² + 2a²',
    options: ['4a²', '10a²', '4a⁶', '10a⁶'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Algebraic Expressions',
    explanation: '5a² - 3a² + 2a² = (5 - 3 + 2)a² = 4a².',
    source: 'practice',
  },
  {
    id: 'shs-coremath-042',
    type: 'mcq',
    question: 'Evaluate: 4² + 3³',
    options: ['25', '35', '43', '49'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Indices',
    explanation: '4² = 16, 3³ = 27. Sum = 16 + 27 = 43.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-043',
    type: 'mcq',
    question: 'Find the area of a circle with radius 7cm (Take π = 22/7).',
    options: ['44 cm²', '154 cm²', '176 cm²', '308 cm²'],
    correctAnswer: 1,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Mensuration',
    explanation: 'Area = πr² = (22/7) × 7² = (22/7) × 49 = 154 cm².',
    source: 'practice',
  },
  {
    id: 'shs-coremath-044',
    type: 'mcq',
    question: 'Solve: 3(x - 2) = 15',
    options: ['x = 5', 'x = 6', 'x = 7', 'x = 9'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Linear Equations',
    explanation: '3(x - 2) = 15 ⇒ x - 2 = 5 ⇒ x = 7.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-045',
    type: 'mcq',
    question: 'What is the median of: 5, 8, 12, 15, 18?',
    options: ['10', '12', '13', '15'],
    correctAnswer: 1,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Statistics',
    explanation: 'Numbers are in order. Median is the middle value: 12.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-046',
    type: 'mcq',
    question: 'Factorize: x² - 9',
    options: ['(x - 3)(x - 3)', '(x + 3)(x - 3)', '(x - 9)(x + 1)', '(x + 9)(x - 1)'],
    correctAnswer: 1,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Algebra',
    explanation: 'Difference of two squares: x² - 9 = x² - 3² = (x + 3)(x - 3).',
    source: 'practice',
  },
  {
    id: 'shs-coremath-047',
    type: 'mcq',
    question: 'Solve: x² - 6x + 8 = 0',
    options: ['x = 2 or 4', 'x = -2 or -4', 'x = 1 or 8', 'x = -1 or -8'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Quadratic Equations',
    explanation: 'Factorize: x² - 6x + 8 = (x - 2)(x - 4) = 0 ⇒ x = 2 or x = 4.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-048',
    type: 'mcq',
    question: 'Find the compound interest on GH₵ 2000 at 10% per annum for 2 years.',
    options: ['GH₵ 200', 'GH₵ 400', 'GH₵ 420', 'GH₵ 440'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'hard',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Compound Interest',
    explanation: 'Amount = P(1 + r/100)ⁿ = 2000(1 + 10/100)² = 2000(1.1)² = 2000(1.21) = 2420. CI = 2420 - 2000 = 420.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-049',
    type: 'mcq',
    question: 'If sin θ = 4/5 and θ is acute, find cos θ.',
    options: ['3/5', '4/3', '5/3', '1/5'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Trigonometry',
    explanation: 'Using sin²θ + cos²θ = 1: (4/5)² + cos²θ = 1 ⇒ cos²θ = 1 - 16/25 = 9/25 ⇒ cos θ = 3/5 (positive for acute angle).',
    source: 'practice',
  },
  {
    id: 'shs-coremath-050',
    type: 'mcq',
    question: 'Simplify: log₂ 8 + log₂ 4',
    options: ['log₂ 12', 'log₂ 32', '5', '6'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Logarithms',
    explanation: 'log₂ 8 + log₂ 4 = log₂ (8 × 4) = log₂ 32 = 5 (since 2⁵ = 32).',
    source: 'practice',
  },
  {
    id: 'shs-coremath-051',
    type: 'mcq',
    question: 'Find the gradient of the line 3x + 2y = 6',
    options: ['-3/2', '3/2', '-2/3', '2/3'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Coordinate Geometry',
    explanation: 'Rearrange: 2y = -3x + 6 ⇒ y = (-3/2)x + 3. Gradient = -3/2.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-052',
    type: 'mcq',
    question: 'The probability of an event is 0.3. What is the probability of it not occurring?',
    options: ['0.3', '0.5', '0.7', '1.0'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'easy',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Probability',
    explanation: 'P(not A) = 1 - P(A) = 1 - 0.3 = 0.7.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-053',
    type: 'mcq',
    question: 'Find the volume of a cylinder with radius 5cm and height 8cm (Take π = 22/7).',
    options: ['440 cm³', '550 cm³', '628 cm³', '880 cm³'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Mensuration',
    explanation: 'Volume = πr²h = (22/7) × 5² × 8 = (22/7) × 25 × 8 = 4400/7 ≈ 628.57 cm³.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-054',
    type: 'mcq',
    question: 'Solve: 2ˣ = 32',
    options: ['3', '4', '5', '6'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Indices',
    explanation: '32 = 2⁵, so 2ˣ = 2⁵ ⇒ x = 5.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-055',
    type: 'mcq',
    question: 'If A = [[2, 1], [3, 4]] and B = [[1, 0], [0, 1]], find A + B.',
    options: ['[[3, 1], [3, 5]]', '[[2, 1], [3, 4]]', '[[1, 1], [3, 3]]', '[[3, 0], [0, 5]]'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Matrices',
    explanation: 'A + B = [[2+1, 1+0], [3+0, 4+1]] = [[3, 1], [3, 5]].',
    source: 'practice',
  },
  {
    id: 'shs-coremath-056',
    type: 'mcq',
    question: 'Find the inverse of the matrix A = [[1, 2], [3, 4]]',
    options: ['[[-2, 1], [1.5, -0.5]]', '[[-2, 1], [3/2, -1/2]]', '[[2, -1], [-3/2, 1/2]]', '[[-2, 1], [-3/2, 1/2]]'],
    correctAnswer: 1,
    subject: 'Core Mathematics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Matrices',
    explanation: 'det(A) = (1)(4) - (2)(3) = -2. A⁻¹ = (1/-2)[[4, -2], [-3, 1]] = [[-2, 1], [3/2, -1/2]].',
    source: 'practice',
  },
  {
    id: 'shs-coremath-057',
    type: 'mcq',
    question: 'Solve the simultaneous equations: 2x + y = 7 and x - y = 2',
    options: ['x=3, y=1', 'x=2, y=3', 'x=4, y=-1', 'x=3, y=2'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Simultaneous Equations',
    explanation: 'Add equations: 3x = 9 ⇒ x = 3. Substitute: 3 - y = 2 ⇒ y = 1.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-058',
    type: 'mcq',
    question: 'Find the distance between points A(1, 2) and B(5, 6)',
    options: ['2√2', '4', '4√2', '8'],
    correctAnswer: 2,
    subject: 'Core Mathematics',
    difficulty: 'medium',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Coordinate Geometry',
    explanation: 'Distance = √[(5-1)² + (6-2)²] = √[4² + 4²] = √32 = 4√2.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-059',
    type: 'mcq',
    question: 'If tan θ = 3/4 and θ is acute, find sin θ',
    options: ['3/5', '4/5', '3/4', '5/4'],
    correctAnswer: 0,
    subject: 'Core Mathematics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Trigonometry',
    explanation: 'If tan θ = 3/4, then opposite = 3, adjacent = 4, hypotenuse = 5. sin θ = opposite/hypotenuse = 3/5.',
    source: 'practice',
  },
  {
    id: 'shs-coremath-060',
    type: 'mcq',
    question: 'Find the sum of the first 10 terms of the arithmetic sequence: 3, 7, 11, 15, ...',
    options: ['200', '210', '220', '230'],
    correctAnswer: 1,
    subject: 'Core Mathematics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Sequences and Series',
    explanation: 'a = 3, d = 4, n = 10. S₁₀ = (n/2)[2a + (n-1)d] = (10/2)[2(3) + 9(4)] = 5[6 + 36] = 5(42) = 210.',
    source: 'practice',
  },
];


