import type { ChallengeQuestion } from '../types';

export const cropHusbandryQuestions: ChallengeQuestion[] = [
  {
    id: 'ch-2024-001',
    type: 'mcq',
    question: 'Seed viability testing helps farmers to:',
    options: ['Increase storage pests', 'Estimate expected germination rate', 'Color seeds', 'Delay planting'],
    correctAnswer: 1,
    subject: 'Crop Husbandry',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Seed Management',
    explanation: 'Viability tests predict germination success before planting.',
    year: 2024,
  },
  {
    id: 'ch-2024-002',
    type: 'mcq',
    question: 'Mulching in crop production mainly helps to:',
    options: ['Increase erosion', 'Conserve moisture and suppress weeds', 'Reduce soil fertility', 'Prevent all pests permanently'],
    correctAnswer: 1,
    subject: 'Crop Husbandry',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Field Management',
    explanation: 'Mulch protects soil, limits evaporation, and reduces weed growth.',
    year: 2024,
  },
  {
    id: 'ch-2024-003',
    type: 'mcq',
    question: 'Spacing recommendations are important because they affect:',
    options: ['Only seed color', 'Plant competition, yield, and disease spread', 'Cloud cover', 'Tractor fuel only'],
    correctAnswer: 1,
    subject: 'Crop Husbandry',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Plant Population',
    explanation: 'Correct spacing optimizes light, airflow, and nutrient access.',
    year: 2024,
  },
  {
    id: 'ch-2024-004',
    type: 'mcq',
    question: 'A pre-harvest maturity index is used to:',
    options: ['Estimate fertilizer prices', 'Determine best harvest time', 'Choose farm machinery color', 'Set market taxes'],
    correctAnswer: 1,
    subject: 'Crop Husbandry',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Harvesting',
    explanation: 'Maturity indices improve quality and reduce post-harvest losses.',
    year: 2024,
  },
  {
    id: 'ch-2024-005',
    type: 'mcq',
    question: 'Post-harvest crop losses can be reduced most effectively by:',
    options: ['Open-air storage in rain', 'Proper drying and storage hygiene', 'Mixing damaged produce', 'Delayed transport only'],
    correctAnswer: 1,
    subject: 'Crop Husbandry',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Post-Harvest Management',
    explanation: 'Drying, clean storage, and pest control preserve crop quality.',
    year: 2024,
  },
];
