import type { ChallengeQuestion } from '../types';

export const electronicsQuestions: ChallengeQuestion[] = [
  {
    id: 'el-2023-001',
    type: 'mcq',
    question: 'A resistor is used to:',
    options: ['Store energy', 'Limit current flow', 'Amplify signals', 'Generate voltage'],
    correctAnswer: 1,
    explanation: 'Resistors oppose current flow, reducing voltage and limiting current to safe levels in circuits.',
    subject: 'Electronics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Electronic Components',
    year: 2023,
  },
  {
    id: 'el-2023-002',
    type: 'mcq',
    question: 'A diode allows current to flow:',
    options: ['In both directions equally', 'In one direction only', 'Not at all', 'Only in AC circuits'],
    correctAnswer: 1,
    explanation: 'Diodes are one-way valves for electricity, allowing current from anode to cathode but blocking reverse flow.',
    subject: 'Electronics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Semiconductors',
    year: 2023,
  },
  {
    id: 'el-2022-003',
    type: 'mcq',
    question: 'A transistor can function as:',
    options: ['Only a switch', 'A switch or amplifier', 'Only a resistor', 'A power source'],
    correctAnswer: 1,
    explanation: 'Transistors can amplify weak signals (making them stronger) or act as electronic switches in digital circuits.',
    subject: 'Electronics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Semiconductors',
    year: 2022,
  },
  {
    id: 'el-2023-004',
    type: 'mcq',
    question: 'A capacitor stores:',
    options: ['Magnetic energy', 'Electrical charge', 'Light energy', 'Sound waves'],
    correctAnswer: 1,
    explanation: 'Capacitors store electrical charge (energy) in an electric field between two conductive plates.',
    subject: 'Electronics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Electronic Components',
    year: 2023,
  },
  {
    id: 'el-2022-005',
    type: 'mcq',
    question: 'An LED (Light Emitting Diode) must be connected:',
    options: ['Any direction', 'With correct polarity (anode to positive)', 'In series only', 'Without resistor'],
    correctAnswer: 1,
    explanation: 'LEDs are polarized - anode (long leg) connects to positive, cathode to negative. Wrong polarity prevents lighting.',
    subject: 'Electronics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Electronic Components',
    year: 2022,
  },
  {
    id: 'el-2023-006',
    type: 'mcq',
    question: 'Ohm\'s Law states:',
    options: ['V = I × R', 'V = I ÷ R', 'V = I + R', 'V = I - R'],
    correctAnswer: 0,
    explanation: 'Ohm\'s Law: Voltage (V) = Current (I) × Resistance (R). Fundamental relationship in electrical circuits.',
    subject: 'Electronics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Circuit Theory',
    year: 2023,
  },
  {
    id: 'el-2022-007',
    type: 'mcq',
    question: 'A soldering iron is used to:',
    options: ['Cut wires', 'Join electronic components by melting solder', 'Test circuits', 'Measure voltage'],
    correctAnswer: 1,
    explanation: 'Soldering irons heat up to melt solder (tin-lead alloy) creating permanent electrical and mechanical connections.',
    subject: 'Electronics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Tools and Techniques',
    year: 2022,
  },
  {
    id: 'el-2023-008',
    type: 'mcq',
    question: 'An integrated circuit (IC) contains:',
    options: ['One transistor', 'Many electronic components on a single chip', 'Only resistors', 'Batteries'],
    correctAnswer: 1,
    explanation: 'ICs contain thousands to billions of transistors, resistors, and capacitors miniaturized on a silicon chip.',
    subject: 'Electronics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Integrated Circuits',
    year: 2023,
  },
  {
    id: 'el-2022-009',
    type: 'mcq',
    question: 'A multimeter measures:',
    options: ['Only voltage', 'Voltage, current, and resistance', 'Only temperature', 'Only frequency'],
    correctAnswer: 1,
    explanation: 'Multimeters are versatile instruments measuring voltage (V), current (A), resistance (Ω), and often continuity/diodes.',
    subject: 'Electronics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Test Equipment',
    year: 2022,
  },
  {
    id: 'el-2023-010',
    type: 'mcq',
    question: 'A breadboard is used for:',
    options: ['Permanent circuits', 'Temporary circuit prototyping without soldering', 'Cutting components', 'Storing parts'],
    correctAnswer: 1,
    explanation: 'Breadboards allow temporary component connections for testing circuits before permanent soldering.',
    subject: 'Electronics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Tools and Techniques',
    year: 2023,
  },
  {
    id: 'el-2022-011',
    type: 'mcq',
    question: 'An inductor stores energy in:',
    options: ['Electric field', 'Magnetic field', 'Chemical bonds', 'Heat'],
    correctAnswer: 1,
    explanation: 'Inductors (coils of wire) store energy in magnetic fields when current flows through them, opposing current changes.',
    subject: 'Electronics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Electronic Components',
    year: 2022,
  },
  {
    id: 'el-2023-012',
    type: 'mcq',
    question: 'A relay is used to:',
    options: ['Store data', 'Control high-power circuits with low-power signals', 'Generate electricity', 'Measure current'],
    correctAnswer: 1,
    explanation: 'Relays are electromagnetic switches where small control current activates coil to switch larger power circuits on/off.',
    subject: 'Electronics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Electromechanical Devices',
    year: 2023,
  },
  {
    id: 'el-2022-013',
    type: 'mcq',
    question: 'In a series circuit, if one component fails:',
    options: ['Others continue working', 'Entire circuit stops working', 'Voltage increases', 'Current doubles'],
    correctAnswer: 1,
    explanation: 'Series circuits have only one current path, so if any component opens (fails), current stops and circuit breaks.',
    subject: 'Electronics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Circuit Theory',
    year: 2022,
  },
  {
    id: 'el-2023-014',
    type: 'mcq',
    question: 'A Zener diode is primarily used for:',
    options: ['Amplification', 'Voltage regulation', 'Current amplification', 'Data storage'],
    correctAnswer: 1,
    explanation: 'Zener diodes conduct in reverse at specific voltage, maintaining constant output voltage despite input variations.',
    subject: 'Electronics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Semiconductors',
    year: 2023,
  },
  {
    id: 'el-2022-015',
    type: 'mcq',
    question: 'A transformer works on the principle of:',
    options: ['Ohm\'s Law', 'Electromagnetic induction', 'Static electricity', 'Chemical reaction'],
    correctAnswer: 1,
    explanation: 'Transformers use electromagnetic induction between coils to change AC voltage levels up or down.',
    subject: 'Electronics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Electromagnetic Devices',
    year: 2022,
  },
  {
    id: 'el-2023-016',
    type: 'mcq',
    question: 'In parallel circuits, voltage across each branch is:',
    options: ['Different', 'The same', 'Zero', 'Doubled'],
    correctAnswer: 1,
    explanation: 'Parallel circuits share the same voltage across all branches, but current divides among paths based on resistance.',
    subject: 'Electronics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Circuit Theory',
    year: 2023,
  },
  {
    id: 'el-2022-017',
    type: 'mcq',
    question: 'An oscilloscope is used to:',
    options: ['Generate signals', 'Visualize and measure electrical waveforms', 'Store energy', 'Amplify signals'],
    correctAnswer: 1,
    explanation: 'Oscilloscopes display voltage signals over time on a screen, allowing visualization and measurement of waveforms.',
    subject: 'Electronics',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Test Equipment',
    year: 2022,
  },
  {
    id: 'el-2023-018',
    type: 'mcq',
    question: 'A photoresistor (LDR) changes resistance based on:',
    options: ['Temperature', 'Light intensity', 'Pressure', 'Humidity'],
    correctAnswer: 1,
    explanation: 'Light Dependent Resistors decrease resistance when light increases, useful in light-sensing circuits and automatic lighting.',
    subject: 'Electronics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Sensors',
    year: 2023,
  },
  {
    id: 'el-2022-019',
    type: 'mcq',
    question: 'An operational amplifier (op-amp) is used for:',
    options: ['Power generation', 'Signal amplification and processing', 'Energy storage', 'Current limiting'],
    correctAnswer: 1,
    explanation: 'Op-amps are versatile ICs for amplifying, filtering, adding, subtracting, and processing analog signals in circuits.',
    subject: 'Electronics',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Integrated Circuits',
    year: 2022,
  },
  {
    id: 'el-2023-020',
    type: 'mcq',
    question: 'The purpose of a heat sink on electronic components is to:',
    options: ['Increase power', 'Dissipate excess heat', 'Store energy', 'Amplify signals'],
    correctAnswer: 1,
    explanation: 'Heat sinks are metal structures that absorb and radiate heat from power transistors and ICs, preventing thermal damage.',
    subject: 'Electronics',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Component Protection',
    year: 2023,
  },
];
