import type { ChallengeQuestion } from '../types';

export const foodNutritionQuestions: ChallengeQuestion[] = [
  // Basic Nutrition
  {
    id: 'fn-2023-001',
    type: 'mcq',
    question: 'Which nutrient is the body\'s main source of energy?',
    options: ['Proteins', 'Carbohydrates', 'Vitamins', 'Minerals'],
    correctAnswer: 1,
    explanation: 'Carbohydrates are the body\'s primary and preferred source of energy, broken down into glucose for cell fuel.',
    subject: 'Food and Nutrition',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Basic Nutrition',
    year: 2023,
  },
  {
    id: 'fn-2023-002',
    type: 'mcq',
    question: 'Proteins are essential for:',
    options: [
      'Energy production only',
      'Growth and repair of body tissues',
      'Digestion only',
      'Bone strength only'
    ],
    correctAnswer: 1,
    explanation: 'Proteins are building blocks for growth, tissue repair, enzyme production, and immune function.',
    subject: 'Food and Nutrition',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Basic Nutrition',
    year: 2023,
  },

  // Vitamins
  {
    id: 'fn-2022-003',
    type: 'mcq',
    question: 'Vitamin C deficiency causes:',
    options: ['Rickets', 'Scurvy', 'Beriberi', 'Night blindness'],
    correctAnswer: 1,
    explanation: 'Scurvy results from vitamin C deficiency, causing bleeding gums, weakness, and poor wound healing.',
    subject: 'Food and Nutrition',
    difficulty: 'medium',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Vitamins',
    year: 2022,
  },
  {
    id: 'fn-2023-004',
    type: 'mcq',
    question: 'Which vitamin is produced when skin is exposed to sunlight?',
    options: ['Vitamin A', 'Vitamin B12', 'Vitamin D', 'Vitamin K'],
    correctAnswer: 2,
    explanation: 'The body produces vitamin D when skin is exposed to UVB rays from sunlight. It\'s essential for calcium absorption.',
    subject: 'Food and Nutrition',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Vitamins',
    year: 2023,
  },

  // Minerals
  {
    id: 'fn-2022-005',
    type: 'mcq',
    question: 'Iron is important for:',
    options: [
      'Bone formation',
      'Blood clotting',
      'Oxygen transport in blood',
      'Nerve function'
    ],
    correctAnswer: 2,
    explanation: 'Iron is crucial for hemoglobin production, which transports oxygen in red blood cells throughout the body.',
    subject: 'Food and Nutrition',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Minerals',
    year: 2022,
  },
  {
    id: 'fn-2023-006',
    type: 'mcq',
    question: 'Which mineral is essential for strong bones and teeth?',
    options: ['Sodium', 'Calcium', 'Potassium', 'Zinc'],
    correctAnswer: 1,
    explanation: 'Calcium is the primary mineral in bones and teeth. It also plays roles in muscle contraction and nerve signaling.',
    subject: 'Food and Nutrition',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Minerals',
    year: 2023,
  },

  // Balanced Diet
  {
    id: 'fn-2022-007',
    type: 'mcq',
    question: 'A balanced diet should contain:',
    options: [
      'Only carbohydrates',
      'All nutrients in the right proportions',
      'Large amounts of fats',
      'Mostly proteins'
    ],
    correctAnswer: 1,
    explanation: 'A balanced diet includes carbohydrates, proteins, fats, vitamins, minerals, and water in appropriate amounts for health.',
    subject: 'Food and Nutrition',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Balanced Diet',
    year: 2022,
  },
  {
    id: 'fn-2023-008',
    type: 'mcq',
    question: 'Which food group provides the most concentrated source of energy?',
    options: ['Fruits', 'Vegetables', 'Fats and oils', 'Dairy products'],
    correctAnswer: 2,
    explanation: 'Fats provide 9 calories per gram, more than double the energy from carbohydrates (4 cal/g) or proteins (4 cal/g).',
    subject: 'Food and Nutrition',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Balanced Diet',
    year: 2023,
  },

  // Malnutrition
  {
    id: 'fn-2022-009',
    type: 'mcq',
    question: 'Kwashiorkor is caused by deficiency of:',
    options: ['Carbohydrates', 'Proteins', 'Fats', 'Water'],
    correctAnswer: 1,
    explanation: 'Kwashiorkor results from severe protein deficiency, common in children. Signs include swollen belly, skin changes, and growth failure.',
    subject: 'Food and Nutrition',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Malnutrition',
    year: 2022,
  },
  {
    id: 'fn-2023-010',
    type: 'mcq',
    question: 'Obesity is primarily caused by:',
    options: [
      'Eating more calories than the body burns',
      'Lack of vitamins',
      'Too much water intake',
      'Protein deficiency'
    ],
    correctAnswer: 0,
    explanation: 'Obesity occurs when calorie intake exceeds energy expenditure over time, leading to excess fat storage.',
    subject: 'Food and Nutrition',
    difficulty: 'easy',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Malnutrition',
    year: 2023,
  },

  // Food Preservation
  {
    id: 'fn-2022-011',
    type: 'mcq',
    question: 'Which method preserves food by removing moisture?',
    options: ['Freezing', 'Drying', 'Canning', 'Salting'],
    correctAnswer: 1,
    explanation: 'Drying removes water from food, preventing microorganism growth. Examples include dried fish, fruits, and vegetables.',
    subject: 'Food and Nutrition',
    difficulty: 'easy',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Food Preservation',
    year: 2022,
  },
  {
    id: 'fn-2023-012',
    type: 'mcq',
    question: 'Pasteurization is commonly used to preserve:',
    options: ['Meat', 'Milk', 'Vegetables', 'Bread'],
    correctAnswer: 1,
    explanation: 'Pasteurization heats milk to 72°C for 15 seconds to kill harmful bacteria while maintaining nutritional value.',
    subject: 'Food and Nutrition',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Food Preservation',
    year: 2023,
  },

  // Food Safety
  {
    id: 'fn-2022-013',
    type: 'mcq',
    question: 'Food poisoning is most commonly caused by:',
    options: [
      'Overcooking food',
      'Bacteria in contaminated food',
      'Eating too quickly',
      'Cold food'
    ],
    correctAnswer: 1,
    explanation: 'Food poisoning results from eating food contaminated with harmful bacteria like Salmonella, E. coli, or Staphylococcus.',
    subject: 'Food and Nutrition',
    difficulty: 'easy',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Food Safety',
    year: 2022,
  },
  {
    id: 'fn-2023-014',
    type: 'mcq',
    question: 'The danger zone for food storage is:',
    options: [
      'Below 0°C',
      'Between 5°C and 60°C',
      'Above 100°C',
      'Between -5°C and 0°C'
    ],
    correctAnswer: 1,
    explanation: 'The danger zone (5-60°C) allows rapid bacterial growth. Food should be kept out of this temperature range.',
    subject: 'Food and Nutrition',
    difficulty: 'medium',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Food Safety',
    year: 2023,
  },

  // Special Diets
  {
    id: 'fn-2023-015',
    type: 'mcq',
    question: 'A person with diabetes should:',
    options: [
      'Avoid all carbohydrates',
      'Monitor and control carbohydrate intake',
      'Eat only proteins',
      'Avoid drinking water'
    ],
    correctAnswer: 1,
    explanation: 'Diabetics should monitor carbohydrate intake and choose complex carbs to manage blood sugar levels effectively.',
    subject: 'Food and Nutrition',
    difficulty: 'medium',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Special Diets',
    year: 2023,
  },
];
