import type { ChallengeQuestion } from '../types';

export const generalKnowledgeArtQuestions: ChallengeQuestion[] = [
  // Art History
  {
    id: 'gka-2023-001',
    type: 'mcq',
    question: 'Who painted the famous Mona Lisa?',
    options: ['Michelangelo', 'Leonardo da Vinci', 'Pablo Picasso', 'Vincent van Gogh'],
    correctAnswer: 1,
    explanation: 'Leonardo da Vinci painted the Mona Lisa in the early 16th century. It is housed in the Louvre Museum in Paris.',
    subject: 'General Knowledge in Art',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Art History',
    year: 2023,
  },
  {
    id: 'gka-2023-002',
    type: 'mcq',
    question: 'The Renaissance period in art originated in:',
    options: ['France', 'England', 'Italy', 'Spain'],
    correctAnswer: 2,
    explanation: 'The Renaissance began in Italy in the 14th century, centered in Florence, before spreading across Europe.',
    subject: 'General Knowledge in Art',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Art History',
    year: 2023,
  },

  // Elements of Art
  {
    id: 'gka-2022-003',
    type: 'mcq',
    question: 'Which of the following is NOT an element of art?',
    options: ['Line', 'Color', 'Texture', 'Perspective'],
    correctAnswer: 3,
    explanation: 'The seven elements of art are: line, shape, form, space, color, value, and texture. Perspective is a technique, not an element.',
    subject: 'General Knowledge in Art',
    difficulty: 'medium',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Elements of Art',
    year: 2022,
  },
  {
    id: 'gka-2023-004',
    type: 'mcq',
    question: 'Primary colors are:',
    options: [
      'Red, Green, Blue',
      'Red, Yellow, Blue',
      'Orange, Green, Purple',
      'Black, White, Gray'
    ],
    correctAnswer: 1,
    explanation: 'In traditional color theory, the primary colors are red, yellow, and blue. They cannot be created by mixing other colors.',
    subject: 'General Knowledge in Art',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Elements of Art',
    year: 2023,
  },

  // Principles of Design
  {
    id: 'gka-2022-005',
    type: 'mcq',
    question: 'Balance in art refers to:',
    options: [
      'The distribution of visual weight in a composition',
      'The number of colors used',
      'The size of the artwork',
      'The price of the artwork'
    ],
    correctAnswer: 0,
    explanation: 'Balance is the distribution of visual weight in artwork. It can be symmetrical, asymmetrical, or radial.',
    subject: 'General Knowledge in Art',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Principles of Design',
    year: 2022,
  },
  {
    id: 'gka-2023-006',
    type: 'mcq',
    question: 'Emphasis in design is achieved by:',
    options: [
      'Making all elements equal',
      'Creating a focal point',
      'Using only one color',
      'Removing all details'
    ],
    correctAnswer: 1,
    explanation: 'Emphasis creates a focal point that draws the viewer\'s attention to the most important part of the composition.',
    subject: 'General Knowledge in Art',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Principles of Design',
    year: 2023,
  },

  // African Art
  {
    id: 'gka-2022-007',
    type: 'mcq',
    question: 'Traditional African masks were primarily used for:',
    options: [
      'Decoration only',
      'Ceremonies and rituals',
      'Warfare',
      'Trade'
    ],
    correctAnswer: 1,
    explanation: 'African masks played important spiritual and social roles in ceremonies, rituals, and performances.',
    subject: 'General Knowledge in Art',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'African Art',
    year: 2022,
  },
  {
    id: 'gka-2023-008',
    type: 'mcq',
    question: 'Adinkra symbols originate from:',
    options: ['Nigeria', 'Ghana', 'Kenya', 'South Africa'],
    correctAnswer: 1,
    explanation: 'Adinkra symbols are visual symbols from Ghana (Akan people) that represent concepts, proverbs, and traditional wisdom.',
    subject: 'General Knowledge in Art',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'African Art',
    year: 2023,
  },

  // Art Movements
  {
    id: 'gka-2022-009',
    type: 'mcq',
    question: 'Cubism is associated with which artist?',
    options: ['Claude Monet', 'Pablo Picasso', 'Salvador Dali', 'Andy Warhol'],
    correctAnswer: 1,
    explanation: 'Pablo Picasso co-founded Cubism with Georges Braque, revolutionizing art by showing multiple perspectives simultaneously.',
    subject: 'General Knowledge in Art',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Art Movements',
    year: 2022,
  },
  {
    id: 'gka-2023-010',
    type: 'mcq',
    question: 'Impressionism focused on:',
    options: [
      'Precise details and realism',
      'Light, color, and immediate impressions',
      'Religious themes',
      'Abstract shapes'
    ],
    correctAnswer: 1,
    explanation: 'Impressionists captured the changing effects of light and color, painting their immediate impressions rather than precise details.',
    subject: 'General Knowledge in Art',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Art Movements',
    year: 2023,
  },

  // Drawing Techniques
  {
    id: 'gka-2022-011',
    type: 'mcq',
    question: 'Shading technique that uses parallel lines is called:',
    options: ['Stippling', 'Hatching', 'Blending', 'Scribbling'],
    correctAnswer: 1,
    explanation: 'Hatching uses parallel lines to create shading and tonal values. Cross-hatching uses intersecting lines.',
    subject: 'General Knowledge in Art',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Drawing Techniques',
    year: 2022,
  },

  // Sculpture
  {
    id: 'gka-2023-012',
    type: 'mcq',
    question: 'The process of removing material to create a sculpture is called:',
    options: ['Modeling', 'Carving', 'Casting', 'Assembling'],
    correctAnswer: 1,
    explanation: 'Carving is a subtractive process where material (wood, stone) is removed to reveal the sculpture.',
    subject: 'General Knowledge in Art',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Sculpture',
    year: 2023,
  },

  // Photography
  {
    id: 'gka-2022-013',
    type: 'mcq',
    question: 'The rule of thirds is used in:',
    options: ['Color mixing', 'Composition', 'Perspective drawing', 'Sculpting'],
    correctAnswer: 1,
    explanation: 'The rule of thirds divides an image into nine equal parts to help create balanced, interesting compositions.',
    subject: 'General Knowledge in Art',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Photography',
    year: 2022,
  },

  // Printmaking
  {
    id: 'gka-2023-014',
    type: 'mcq',
    question: 'Screen printing is also known as:',
    options: ['Etching', 'Lithography', 'Serigraphy', 'Engraving'],
    correctAnswer: 2,
    explanation: 'Screen printing (serigraphy) uses a mesh screen to transfer ink onto a surface, widely used for textiles and posters.',
    subject: 'General Knowledge in Art',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Printmaking',
    year: 2023,
  },

  // Contemporary Art
  {
    id: 'gka-2023-015',
    type: 'mcq',
    question: 'Installation art is characterized by:',
    options: [
      'Small paintings',
      'Three-dimensional artworks that transform a space',
      'Traditional portraits',
      'Digital illustrations only'
    ],
    correctAnswer: 1,
    explanation: 'Installation art creates immersive experiences by transforming entire spaces with three-dimensional constructions.',
    subject: 'General Knowledge in Art',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Contemporary Art',
    year: 2023,
  },
];
