import type { ChallengeQuestion } from '../types';

export const graphicDesignQuestions: ChallengeQuestion[] = [
  {
    id: 'gd-2024-001',
    type: 'mcq',
    question: 'Which element is most responsible for readability in posters?',
    options: ['Random textures', 'Clear typography hierarchy', 'Excess decoration', 'Very low contrast'],
    correctAnswer: 1,
    subject: 'Graphic Design',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Typography',
    explanation: 'Hierarchy helps viewers scan and understand information quickly.',
    year: 2024,
  },
  {
    id: 'gd-2024-002',
    type: 'mcq',
    question: 'In color theory, complementary colors are:',
    options: ['Adjacent on the wheel', 'Opposite on the color wheel', 'Only warm colors', 'Only neutral colors'],
    correctAnswer: 1,
    subject: 'Graphic Design',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Color Theory',
    explanation: 'Complementary pairs provide strong visual contrast.',
    year: 2024,
  },
  {
    id: 'gd-2024-003',
    type: 'mcq',
    question: 'A logo should primarily be:',
    options: ['Complex and hard to remember', 'Simple, memorable, and scalable', 'Always multicolored', 'Text-heavy only'],
    correctAnswer: 1,
    subject: 'Graphic Design',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Brand Design',
    explanation: 'Effective logos remain recognizable across sizes and contexts.',
    year: 2024,
  },
  {
    id: 'gd-2024-004',
    type: 'mcq',
    question: 'Whitespace in layout is used to:',
    options: ['Waste space', 'Improve clarity and focus', 'Hide important text', 'Reduce accessibility'],
    correctAnswer: 1,
    subject: 'Graphic Design',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Layout',
    explanation: 'Whitespace improves visual balance and helps users process content.',
    year: 2024,
  },
  {
    id: 'gd-2024-005',
    type: 'mcq',
    question: 'For social-impact campaigns, design success is best measured by:',
    options: ['Fancy effects only', 'Audience understanding and response', 'File size', 'Number of fonts used'],
    correctAnswer: 1,
    subject: 'Graphic Design',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Design Communication',
    explanation: 'Design should communicate clearly and influence intended behavior.',
    year: 2024,
  },
];
