// Integrated Science Questions for SHS
// Initial batch of questions migrated to modular ChallengeQuestion format
// NOTE: These are practice-style WASSCE-level questions, not yet tagged as verified past questions.

import type { ChallengeQuestion } from '../types';

export const integratedScienceQuestions: ChallengeQuestion[] = [
  // ============================================
  // MCQ Questions (Initial Batch)
  // ============================================

  // Integrated Science - Physics & Measurement
  {
    id: 'shs-intsci-001',
    type: 'mcq',
    question: 'Which instrument is used to measure temperature in a science laboratory?',
    options: ['Voltmeter', 'Thermometer', 'Barometer', 'Ammeter'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Measurement',
    explanation: 'A thermometer is used to measure temperature.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-002',
    type: 'mcq',
    question: 'Which quantity is a vector?',
    options: ['Mass', 'Speed', 'Velocity', 'Temperature'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Motion',
    explanation: 'Velocity has both magnitude and direction, so it is a vector quantity.',
    source: 'practice',
  },

  // Integrated Science - Biology: Cells & Systems
  {
    id: 'shs-intsci-003',
    type: 'mcq',
    question: 'Which of the following is NOT a living cell?',
    options: ['Red blood cell', 'Onion epidermal cell', 'Bacterial cell', 'Sand grain'],
    correctAnswer: 3,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Cells',
    explanation: 'Sand grain is non-living; the others are examples of cells.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-004',
    type: 'mcq',
    question: 'Which organ system is responsible for transporting oxygen and nutrients in humans?',
    options: ['Digestive system', 'Respiratory system', 'Circulatory system', 'Nervous system'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Human Biology',
    explanation: 'The circulatory system (blood, heart, vessels) transports oxygen and nutrients.',
    source: 'practice',
  },

  // Integrated Science - Chemistry: Matter & Changes
  {
    id: 'shs-intsci-005',
    type: 'mcq',
    question: 'Which of the following is a chemical change?',
    options: ['Melting of ice', 'Boiling of water', 'Rusting of iron', 'Breaking of glass'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Matter and Changes',
    explanation: 'Rusting of iron forms a new substance (iron oxide), so it is a chemical change.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-006',
    type: 'mcq',
    question: 'Which state of matter has a definite volume but no definite shape?',
    options: ['Solid', 'Liquid', 'Gas', 'Plasma'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'States of Matter',
    explanation: 'Liquids have definite volume but take the shape of their container.',
    source: 'practice',
  },

  // Integrated Science - Ecology & Environment
  {
    id: 'shs-intsci-007',
    type: 'mcq',
    question: 'Which of the following is a renewable source of energy?',
    options: ['Coal', 'Petroleum', 'Natural gas', 'Solar energy'],
    correctAnswer: 3,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Energy and Environment',
    explanation: 'Solar energy can be replenished naturally and is therefore renewable.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-008',
    type: 'mcq',
    question: 'Which of the following is a primary consumer in a food chain?',
    options: ['Grass', 'Goat', 'Lion', 'Vulture'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Ecology',
    explanation: 'Primary consumers feed directly on producers (plants); a goat feeds on grass.',
    source: 'practice',
  },

  // Integrated Science - Earth Science & Astronomy
  {
    id: 'shs-intsci-009',
    type: 'mcq',
    question: 'The imaginary line that divides the Earth into Northern and Southern Hemispheres is called the:',
    options: ['Prime meridian', 'Equator', 'Tropic of Cancer', 'International Date Line'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Earth and Space',
    explanation: 'The equator divides the Earth into Northern and Southern Hemispheres.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-010',
    type: 'mcq',
    question: 'Which planet is known as the “Red Planet”?',
    options: ['Venus', 'Mars', 'Jupiter', 'Mercury'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Solar System',
    explanation: 'Mars appears reddish due to iron oxide on its surface, hence the “Red Planet”.',
    source: 'practice',
  },

  // Batch 1 - First 25 additional questions (011-035)
  {
    id: 'shs-intsci-011',
    type: 'mcq',
    question: 'What is the SI unit of force?',
    options: ['Joule', 'Newton', 'Watt', 'Pascal'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Forces',
    explanation: 'The newton (N) is the SI unit of force, named after Isaac Newton.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-012',
    type: 'mcq',
    question: 'Which organelle is known as the "powerhouse of the cell"?',
    options: ['Nucleus', 'Mitochondria', 'Ribosome', 'Endoplasmic reticulum'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Cells',
    explanation: 'Mitochondria produce ATP (energy) through cellular respiration, making them the cell\'s powerhouse.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-013',
    type: 'mcq',
    question: 'Which of the following is a physical change?',
    options: ['Burning of paper', 'Rusting of iron', 'Melting of ice', 'Digestion of food'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Matter and Changes',
    explanation: 'Melting is a physical change as it only changes state without forming new substances.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-014',
    type: 'mcq',
    question: 'What is the formula for calculating speed?',
    options: ['Speed = distance × time', 'Speed = distance / time', 'Speed = time / distance', 'Speed = force / mass'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Motion',
    explanation: 'Speed is distance traveled per unit time: speed = distance / time.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-015',
    type: 'mcq',
    question: 'Which gas is most abundant in Earth\'s atmosphere?',
    options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Argon'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Atmosphere',
    explanation: 'Nitrogen makes up approximately 78% of Earth\'s atmosphere.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-016',
    type: 'mcq',
    question: 'What type of blood vessel carries blood away from the heart?',
    options: ['Vein', 'Artery', 'Capillary', 'Venule'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Circulatory System',
    explanation: 'Arteries carry oxygenated blood away from the heart to the body tissues.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-017',
    type: 'mcq',
    question: 'Which of the following is a compound?',
    options: ['Oxygen', 'Hydrogen', 'Water', 'Carbon'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Matter and Changes',
    explanation: 'Water (H₂O) is a compound made of two different elements (hydrogen and oxygen) chemically combined.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-018',
    type: 'mcq',
    question: 'What is the function of chlorophyll in plants?',
    options: ['To store food', 'To absorb water', 'To capture light energy for photosynthesis', 'To transport nutrients'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Photosynthesis',
    explanation: 'Chlorophyll is a green pigment that captures light energy needed for photosynthesis.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-019',
    type: 'mcq',
    question: 'Which process converts liquid water to water vapor?',
    options: ['Condensation', 'Evaporation', 'Freezing', 'Sublimation'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'States of Matter',
    explanation: 'Evaporation is the process by which a liquid changes to a gas at temperatures below boiling point.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-020',
    type: 'mcq',
    question: 'What is the smallest unit of an element that retains its properties?',
    options: ['Molecule', 'Atom', 'Ion', 'Compound'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Atomic Structure',
    explanation: 'An atom is the smallest unit of an element that retains the chemical properties of that element.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-021',
    type: 'mcq',
    question: 'Which of the following is a renewable resource?',
    options: ['Coal', 'Oil', 'Natural gas', 'Wind energy'],
    correctAnswer: 3,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Energy and Environment',
    explanation: 'Wind energy is renewable as it can be replenished naturally and is not depleted with use.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-022',
    type: 'mcq',
    question: 'What is the pH of a neutral solution?',
    options: ['0', '7', '14', '10'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Acids and Bases',
    explanation: 'A pH of 7 is neutral. Values below 7 are acidic, above 7 are basic/alkaline.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-023',
    type: 'mcq',
    question: 'Which process releases energy from food in cells?',
    options: ['Photosynthesis', 'Respiration', 'Digestion', 'Circulation'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Cell Processes',
    explanation: 'Cellular respiration breaks down glucose to release energy (ATP) for cell activities.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-024',
    type: 'mcq',
    question: 'What type of force opposes motion between surfaces?',
    options: ['Gravity', 'Friction', 'Magnetism', 'Electric force'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Forces',
    explanation: 'Friction is a force that opposes the relative motion between two surfaces in contact.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-025',
    type: 'mcq',
    question: 'Which part of the plant is responsible for absorption of water and minerals?',
    options: ['Leaves', 'Stem', 'Roots', 'Flowers'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Plant Structure',
    explanation: 'Roots absorb water and minerals from the soil and anchor the plant.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-026',
    type: 'mcq',
    question: 'What is the chemical symbol for sodium?',
    options: ['So', 'Sa', 'Na', 'Sd'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Chemical Symbols',
    explanation: 'Na is the chemical symbol for sodium (from Latin "natrium").',
    source: 'practice',
  },
  {
    id: 'shs-intsci-027',
    type: 'mcq',
    question: 'Which layer of the atmosphere contains the ozone layer?',
    options: ['Troposphere', 'Stratosphere', 'Mesosphere', 'Thermosphere'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Atmosphere',
    explanation: 'The stratosphere contains the ozone layer, which protects Earth from harmful UV radiation.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-028',
    type: 'mcq',
    question: 'What type of energy is stored in food?',
    options: ['Kinetic energy', 'Chemical energy', 'Light energy', 'Heat energy'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Energy',
    explanation: 'Food contains chemical energy stored in the bonds of molecules, released during respiration.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-029',
    type: 'mcq',
    question: 'Which gas do plants use during photosynthesis?',
    options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Photosynthesis',
    explanation: 'Plants use carbon dioxide (CO₂) along with water and light to produce glucose and oxygen.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-030',
    type: 'mcq',
    question: 'What is the unit of electric current?',
    options: ['Volt', 'Ampere', 'Ohm', 'Watt'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Electricity',
    explanation: 'The ampere (A) is the SI unit of electric current.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-031',
    type: 'mcq',
    question: 'Which of the following is a producer in a food chain?',
    options: ['Grass', 'Rabbit', 'Snake', 'Hawk'],
    correctAnswer: 0,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Ecology',
    explanation: 'Producers (plants like grass) make their own food through photosynthesis and form the base of food chains.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-032',
    type: 'mcq',
    question: 'What happens to the volume of a gas when pressure increases at constant temperature?',
    options: ['Increases', 'Decreases', 'Remains constant', 'Doubles'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Gas Laws',
    explanation: 'According to Boyle\'s law, volume decreases as pressure increases when temperature is constant.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-033',
    type: 'mcq',
    question: 'Which organ system is responsible for removing waste products from the blood?',
    options: ['Digestive system', 'Respiratory system', 'Excretory system', 'Circulatory system'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Human Biology',
    explanation: 'The excretory system (kidneys, bladder) filters waste products from the blood and removes them from the body.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-034',
    type: 'mcq',
    question: 'What is the formula for density?',
    options: ['Density = volume / mass', 'Density = mass / volume', 'Density = mass × volume', 'Density = weight / volume'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Measurement',
    explanation: 'Density is mass per unit volume: density = mass / volume.',
    source: 'practice',
  },
  {
    id: 'shs-intsci-035',
    type: 'mcq',
    question: 'Which type of rock is formed from cooling and solidification of magma?',
    options: ['Sedimentary rock', 'Igneous rock', 'Metamorphic rock', 'Limestone'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Earth Science',
    explanation: 'Igneous rocks form when molten rock (magma) cools and solidifies.',
    source: 'practice',
  },

  // ============================================
  // WASSCE-STYLE PAST QUESTIONS
  // Authentic WASSCE examination patterns
  // Added: January 2026
  // ============================================

  // Human Biology
  {
    id: 'wassce-is-001',
    type: 'mcq',
    question: 'Which of the following is NOT a function of the skin?',
    options: ['Regulation of body temperature', 'Protection against mechanical injury', 'Production of red blood cells', 'Reception of stimuli'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Human Biology - Skin',
    explanation: 'Red blood cells are produced in the bone marrow, not in the skin. The skin regulates temperature through sweating, protects against injury, and contains sensory receptors.',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-002',
    type: 'mcq',
    question: 'The process by which green plants manufacture their own food is called',
    options: ['Respiration', 'Photosynthesis', 'Transpiration', 'Digestion'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Plant Biology - Photosynthesis',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-003',
    type: 'mcq',
    question: 'Which blood vessel carries oxygenated blood from the lungs to the heart?',
    options: ['Pulmonary artery', 'Pulmonary vein', 'Aorta', 'Vena cava'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Circulatory System',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-004',
    type: 'mcq',
    question: 'The part of the flower that develops into a fruit after fertilization is the',
    options: ['Ovary', 'Ovule', 'Style', 'Stigma'],
    correctAnswer: 0,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Plant Reproduction',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-005',
    type: 'mcq',
    question: 'Which of the following diseases is caused by a virus?',
    options: ['Malaria', 'Cholera', 'Tuberculosis', 'Measles'],
    correctAnswer: 3,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Disease and Health',
    explanation: 'Measles is caused by a virus. Malaria is caused by a protozoan, while cholera and tuberculosis are caused by bacteria.',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-006',
    type: 'mcq',
    question: 'The smallest unit of life that can function independently is the',
    options: ['Tissue', 'Organ', 'Cell', 'Organism'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Cell Biology',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-007',
    type: 'mcq',
    question: 'Which organelle is known as the powerhouse of the cell?',
    options: ['Nucleus', 'Mitochondrion', 'Ribosome', 'Chloroplast'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Cell Biology',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-008',
    type: 'mcq',
    question: 'The enzyme in saliva that digests starch is',
    options: ['Pepsin', 'Ptyalin', 'Lipase', 'Trypsin'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Digestive System',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-009',
    type: 'mcq',
    question: 'Which of the following is an example of a reflex action?',
    options: ['Walking', 'Blinking when an object approaches the eye', 'Swimming', 'Reading'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Nervous System',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-010',
    type: 'mcq',
    question: 'The liquid part of blood is called',
    options: ['Serum', 'Plasma', 'Lymph', 'Hemoglobin'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Circulatory System',
    source: 'WASSCE-style',
  },

  // Chemistry
  {
    id: 'wassce-is-011',
    type: 'mcq',
    question: 'What is the chemical symbol for sodium?',
    options: ['S', 'So', 'Na', 'N'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Chemical Symbols',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-012',
    type: 'mcq',
    question: 'The pH value of a neutral solution is',
    options: ['0', '7', '14', '10'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Acids and Bases',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-013',
    type: 'mcq',
    question: 'Which of the following is an example of a chemical change?',
    options: ['Melting of ice', 'Boiling of water', 'Burning of wood', 'Dissolving sugar in water'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Chemical Changes',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-014',
    type: 'mcq',
    question: 'The process of converting a solid directly to gas is called',
    options: ['Evaporation', 'Sublimation', 'Condensation', 'Melting'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'States of Matter',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-015',
    type: 'mcq',
    question: 'The atomic number of an element is determined by the number of',
    options: ['Protons', 'Neutrons', 'Electrons', 'Nucleons'],
    correctAnswer: 0,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Atomic Structure',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-016',
    type: 'mcq',
    question: 'Which gas is produced when an acid reacts with a metal?',
    options: ['Oxygen', 'Hydrogen', 'Carbon dioxide', 'Nitrogen'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Chemical Reactions',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-017',
    type: 'mcq',
    question: 'The chemical formula for common salt is',
    options: ['NaCl', 'KCl', 'CaCl₂', 'MgCl₂'],
    correctAnswer: 0,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Chemical Compounds',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-018',
    type: 'mcq',
    question: 'Which of the following is a noble gas?',
    options: ['Oxygen', 'Nitrogen', 'Argon', 'Hydrogen'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Periodic Table',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-019',
    type: 'mcq',
    question: 'The process of separating a mixture of liquids with different boiling points is called',
    options: ['Filtration', 'Evaporation', 'Distillation', 'Crystallization'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Separation Techniques',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-020',
    type: 'mcq',
    question: 'Which of the following is an example of an exothermic reaction?',
    options: ['Melting of ice', 'Photosynthesis', 'Burning of fuel', 'Evaporation of water'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Energy Changes in Reactions',
    source: 'WASSCE-style',
  },

  // Physics
  {
    id: 'wassce-is-021',
    type: 'mcq',
    question: 'The S.I. unit of force is',
    options: ['Joule', 'Newton', 'Watt', 'Pascal'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Force and Motion',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-022',
    type: 'mcq',
    question: 'Which of the following is a vector quantity?',
    options: ['Speed', 'Distance', 'Velocity', 'Time'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Scalars and Vectors',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-023',
    type: 'mcq',
    question: 'The ability of a body to do work is called',
    options: ['Power', 'Energy', 'Force', 'Momentum'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Work and Energy',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-024',
    type: 'mcq',
    question: 'The bending of light as it passes from one medium to another is called',
    options: ['Reflection', 'Refraction', 'Diffraction', 'Dispersion'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Light',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-025',
    type: 'mcq',
    question: 'Which type of energy is stored in a stretched spring?',
    options: ['Kinetic energy', 'Potential energy', 'Heat energy', 'Chemical energy'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Energy',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-026',
    type: 'mcq',
    question: 'The S.I. unit of electric current is',
    options: ['Volt', 'Ampere', 'Ohm', 'Coulomb'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Electricity',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-027',
    type: 'mcq',
    question: 'Which of the following is a good conductor of electricity?',
    options: ['Wood', 'Plastic', 'Copper', 'Rubber'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Electricity',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-028',
    type: 'mcq',
    question: 'The distance traveled per unit time is called',
    options: ['Velocity', 'Speed', 'Acceleration', 'Momentum'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Motion',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-029',
    type: 'mcq',
    question: 'Which of the following statements about the image formed by a plane mirror is correct?',
    options: ['It is real and inverted', 'It is virtual and upright', 'It is real and upright', 'It is virtual and inverted'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Reflection of Light',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-030',
    type: 'mcq',
    question: 'The product of mass and velocity of a body is called',
    options: ['Force', 'Energy', 'Momentum', 'Power'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Force and Motion',
    source: 'WASSCE-style',
  },

  // Environmental Science
  {
    id: 'wassce-is-031',
    type: 'mcq',
    question: 'Which of the following is a renewable source of energy?',
    options: ['Coal', 'Natural gas', 'Solar energy', 'Petroleum'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Energy Resources',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-032',
    type: 'mcq',
    question: 'The gradual increase in the Earth\'s temperature is called',
    options: ['Climate change', 'Global warming', 'Ozone depletion', 'Greenhouse effect'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Environmental Issues',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-033',
    type: 'mcq',
    question: 'Which gas is responsible for the depletion of the ozone layer?',
    options: ['Carbon dioxide', 'Methane', 'Chlorofluorocarbons (CFCs)', 'Nitrogen oxide'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Environmental Issues',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-034',
    type: 'mcq',
    question: 'The breaking down of rocks into smaller particles is called',
    options: ['Erosion', 'Weathering', 'Sedimentation', 'Deposition'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Earth Science',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-035',
    type: 'mcq',
    question: 'Which of the following is a biodegradable waste?',
    options: ['Plastic bottles', 'Glass', 'Food scraps', 'Metal cans'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Waste Management',
    source: 'WASSCE-style',
  },

  // Additional Topics
  {
    id: 'wassce-is-036',
    type: 'mcq',
    question: 'The change of state from liquid to gas is called',
    options: ['Melting', 'Freezing', 'Evaporation', 'Condensation'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'States of Matter',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-037',
    type: 'mcq',
    question: 'Which vitamin is produced when the skin is exposed to sunlight?',
    options: ['Vitamin A', 'Vitamin B', 'Vitamin C', 'Vitamin D'],
    correctAnswer: 3,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Nutrition',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-038',
    type: 'mcq',
    question: 'The instrument used to measure atmospheric pressure is',
    options: ['Thermometer', 'Barometer', 'Hygrometer', 'Anemometer'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Measurement',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-039',
    type: 'mcq',
    question: 'Which of the following is an example of a lever?',
    options: ['Wheel and axle', 'Crowbar', 'Inclined plane', 'Screw'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Simple Machines',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-040',
    type: 'mcq',
    question: 'The transfer of heat through a fluid (liquid or gas) is called',
    options: ['Conduction', 'Convection', 'Radiation', 'Evaporation'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Heat Transfer',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-041',
    type: 'mcq',
    question: 'Which of the following is the correct order of organization in living organisms from simplest to most complex?',
    options: ['Cell → Tissue → Organ → System → Organism', 'Tissue → Cell → Organ → System → Organism', 'Cell → Organ → Tissue → System → Organism', 'Organ → Tissue → Cell → System → Organism'],
    correctAnswer: 0,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Organization of Life',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-042',
    type: 'mcq',
    question: 'The process by which water vapor changes to liquid water is called',
    options: ['Evaporation', 'Condensation', 'Precipitation', 'Transpiration'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Water Cycle',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-043',
    type: 'mcq',
    question: 'Which of the following metals is liquid at room temperature?',
    options: ['Iron', 'Mercury', 'Copper', 'Gold'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Properties of Metals',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-044',
    type: 'mcq',
    question: 'The phenomenon where light bounces off a surface is called',
    options: ['Reflection', 'Refraction', 'Diffraction', 'Absorption'],
    correctAnswer: 0,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Light',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-045',
    type: 'mcq',
    question: 'Which organ is responsible for filtering blood in the human body?',
    options: ['Liver', 'Kidney', 'Heart', 'Lungs'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Excretory System',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-046',
    type: 'mcq',
    question: 'The formula for calculating density is',
    options: ['Density = Mass × Volume', 'Density = Mass / Volume', 'Density = Volume / Mass', 'Density = Mass + Volume'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Density',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-047',
    type: 'mcq',
    question: 'Which of the following is an insulator of heat?',
    options: ['Copper', 'Aluminum', 'Wood', 'Iron'],
    correctAnswer: 2,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Heat Transfer',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-048',
    type: 'mcq',
    question: 'The gas needed for burning to take place is',
    options: ['Nitrogen', 'Oxygen', 'Carbon dioxide', 'Hydrogen'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Combustion',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-049',
    type: 'mcq',
    question: 'Which part of the eye controls the amount of light entering it?',
    options: ['Lens', 'Pupil', 'Cornea', 'Retina'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Human Eye',
    source: 'WASSCE-style',
  },
  {
    id: 'wassce-is-050',
    type: 'mcq',
    question: 'The component of air that supports combustion is',
    options: ['Nitrogen', 'Oxygen', 'Carbon dioxide', 'Noble gases'],
    correctAnswer: 1,
    subject: 'Integrated Science',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Air Composition',
    source: 'WASSCE-style',
  },
];