import type { ChallengeQuestion } from '../types';

export const islamicReligiousStudiesQuestions: ChallengeQuestion[] = [
  {
    id: 'irs-2024-001',
    type: 'mcq',
    question: 'In Islam, the concept of "Taqwa" is best understood as:',
    options: ['Material wealth', 'God-consciousness and piety', 'Political authority', 'Tribal identity'],
    correctAnswer: 1,
    subject: 'Islamic Religious Studies',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Core Beliefs',
    explanation: 'Taqwa refers to awareness of Allah that guides moral and disciplined living.',
    year: 2024,
  },
  {
    id: 'irs-2024-002',
    type: 'mcq',
    question: 'Which of these is one of the Five Pillars of Islam?',
    options: ['Monastic life', 'Zakat (obligatory charity)', 'Pilgrimage to Rome', 'Ancestral worship'],
    correctAnswer: 1,
    subject: 'Islamic Religious Studies',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Pillars of Islam',
    explanation: 'Zakat is a compulsory act of charity and a pillar of Islam.',
    year: 2024,
  },
  {
    id: 'irs-2024-003',
    type: 'mcq',
    question: 'A key Islamic principle in social dealings is:',
    options: ['Dishonest trade', 'Justice and fairness', 'Discrimination', 'Exploitative contracts'],
    correctAnswer: 1,
    subject: 'Islamic Religious Studies',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Islamic Ethics',
    explanation: 'Islam teaches justice (adl) and fairness in individual and community relationships.',
    year: 2024,
  },
  {
    id: 'irs-2024-004',
    type: 'mcq',
    question: 'Sawm during Ramadan primarily develops:',
    options: ['Pride and status', 'Self-discipline and empathy', 'Economic power', 'Political influence'],
    correctAnswer: 1,
    subject: 'Islamic Religious Studies',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Worship and Character',
    explanation: 'Fasting builds discipline, gratitude, and concern for the less privileged.',
    year: 2024,
  },
  {
    id: 'irs-2024-005',
    type: 'mcq',
    question: 'In civic life, Islamic teachings encourage believers to:',
    options: ['Break social trust', 'Promote peace and accountability', 'Avoid all community service', 'Spread misinformation'],
    correctAnswer: 1,
    subject: 'Islamic Religious Studies',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Faith and Society',
    explanation: 'Islam emphasizes amanah (trust), justice, and peaceful coexistence in society.',
    year: 2024,
  },
];
