import type { ChallengeQuestion } from '../types';

export const managementInLivingQuestions: ChallengeQuestion[] = [
  {
    id: 'mil-2024-001',
    type: 'mcq',
    question: 'A realistic family budget should start with:',
    options: ['Borrowing first', 'Identifying income and expenses', 'Buying luxuries', 'Ignoring savings'],
    correctAnswer: 1,
    subject: 'Management in Living',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Family Resource Management',
    explanation: 'Budgeting requires clear tracking of available income and planned spending.',
    year: 2024,
  },
  {
    id: 'mil-2024-002',
    type: 'mcq',
    question: 'Effective time management at home includes:',
    options: ['No planning', 'Prioritizing tasks and schedules', 'Doing tasks randomly', 'Avoiding shared roles'],
    correctAnswer: 1,
    subject: 'Management in Living',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Time Management',
    explanation: 'Priorities and schedules improve productivity and reduce stress.',
    year: 2024,
  },
  {
    id: 'mil-2024-003',
    type: 'mcq',
    question: 'Consumer education mainly helps families to:',
    options: ['Spend impulsively', 'Make informed purchase decisions', 'Ignore product labels', 'Avoid budgeting'],
    correctAnswer: 1,
    subject: 'Management in Living',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Consumer Skills',
    explanation: 'Informed decisions improve value, safety, and long-term financial outcomes.',
    year: 2024,
  },
  {
    id: 'mil-2024-004',
    type: 'mcq',
    question: 'Conflict resolution in family settings is best achieved through:',
    options: ['Blame and insults', 'Communication and empathy', 'Avoidance forever', 'Social media arguments'],
    correctAnswer: 1,
    subject: 'Management in Living',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Interpersonal Skills',
    explanation: 'Constructive communication and empathy help solve household conflicts.',
    year: 2024,
  },
  {
    id: 'mil-2024-005',
    type: 'mcq',
    question: 'A sustainable household practice is to:',
    options: ['Waste water daily', 'Plan reuse and reduce waste', 'Burn plastics indoors', 'Use unsafe storage'],
    correctAnswer: 1,
    subject: 'Management in Living',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Sustainable Living',
    explanation: 'Reducing waste and reusing resources improves household and environmental health.',
    year: 2024,
  },
];
