import type { ChallengeQuestion } from '../types';

export const metalworkQuestions: ChallengeQuestion[] = [
  {
    id: 'mw-2023-001',
    type: 'mcq',
    question: 'Ferrous metals contain:',
    options: ['Copper', 'Iron', 'Aluminum', 'Zinc'],
    correctAnswer: 1,
    explanation: 'Ferrous metals contain iron and are magnetic. Examples: steel, cast iron, wrought iron.',
    subject: 'Metalwork',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Types of Metals',
    year: 2023,
  },
  {
    id: 'mw-2023-002',
    type: 'mcq',
    question: 'Annealing is a heat treatment process used to:',
    options: ['Harden metal', 'Soften metal and relieve stress', 'Color metal', 'Join metals'],
    correctAnswer: 1,
    explanation: 'Annealing involves heating metal and slow cooling to soften it, making it easier to work and less brittle.',
    subject: 'Metalwork',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Heat Treatment',
    year: 2023,
  },
  {
    id: 'mw-2022-003',
    type: 'mcq',
    question: 'Brazing joins metals using:',
    options: ['Welding torch only', 'Filler metal with lower melting point than base metals', 'Glue', 'Rivets'],
    correctAnswer: 1,
    explanation: 'Brazing uses a filler metal (brass/bronze) that melts at lower temperature than base metals, flowing into the joint.',
    subject: 'Metalwork',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Joining Methods',
    year: 2022,
  },
  {
    id: 'mw-2023-004',
    type: 'mcq',
    question: 'A hacksaw is used to:',
    options: ['Bend metal', 'Cut metal', 'Polish metal', 'Measure metal'],
    correctAnswer: 1,
    explanation: 'A hacksaw has a fine-toothed blade tensioned in a frame, designed for cutting metal and hard materials.',
    subject: 'Metalwork',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Hand Tools',
    year: 2023,
  },
  {
    id: 'mw-2022-005',
    type: 'mcq',
    question: 'Galvanizing protects steel by:',
    options: ['Painting it', 'Coating with zinc', 'Heating it', 'Polishing it'],
    correctAnswer: 1,
    explanation: 'Galvanizing coats steel with zinc, which corrodes instead of the steel, providing rust protection.',
    subject: 'Metalwork',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Metal Protection',
    year: 2022,
  },
  {
    id: 'mw-2023-006',
    type: 'mcq',
    question: 'Tempering follows hardening to:',
    options: ['Make metal softer', 'Reduce brittleness while maintaining hardness', 'Melt the metal', 'Change color'],
    correctAnswer: 1,
    explanation: 'Tempering reheats hardened steel to reduce brittleness, making it tougher while keeping it reasonably hard.',
    subject: 'Metalwork',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Heat Treatment',
    year: 2023,
  },
  {
    id: 'mw-2022-007',
    type: 'mcq',
    question: 'A ball peen hammer is used in metalwork for:',
    options: ['Driving nails', 'Riveting and shaping metal', 'Cutting', 'Polishing'],
    correctAnswer: 1,
    explanation: 'The ball peen hammer has a flat face and rounded ball end, used for shaping metal and closing rivets.',
    subject: 'Metalwork',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Hand Tools',
    year: 2022,
  },
  {
    id: 'mw-2023-008',
    type: 'mcq',
    question: 'Arc welding uses:',
    options: ['Glue', 'Electrical arc to melt and fuse metals', 'Cold bonding', 'Magnetic force'],
    correctAnswer: 1,
    explanation: 'Arc welding creates an electric arc between electrode and workpiece, generating heat to melt and join metals.',
    subject: 'Metalwork',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Joining Methods',
    year: 2023,
  },
  {
    id: 'mw-2022-009',
    type: 'mcq',
    question: 'Aluminum is classified as a:',
    options: ['Ferrous metal', 'Non-ferrous metal', 'Alloy only', 'Plastic'],
    correctAnswer: 1,
    explanation: 'Aluminum is non-ferrous (contains no iron), lightweight, corrosion-resistant, and non-magnetic.',
    subject: 'Metalwork',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Types of Metals',
    year: 2022,
  },
  {
    id: 'mw-2023-010',
    type: 'mcq',
    question: 'Safety in the metalwork workshop requires:',
    options: ['Bare hands', 'Safety goggles, gloves, and protective clothing', 'Open-toed shoes', 'Loose clothing'],
    correctAnswer: 1,
    explanation: 'PPE (goggles, gloves, apron, closed shoes) protects from hot metal, sparks, sharp edges, and flying debris.',
    subject: 'Metalwork',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Workshop Safety',
    year: 2023,
  },
  {
    id: 'mw-2022-011',
    type: 'mcq',
    question: 'A file is used in metalwork to:',
    options: ['Heat metal', 'Remove metal by abrasion and smooth surfaces', 'Bend metal', 'Paint metal'],
    correctAnswer: 1,
    explanation: 'Files have hardened teeth that cut and smooth metal surfaces through abrasive action when pushed across the work.',
    subject: 'Metalwork',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Hand Tools',
    year: 2022,
  },
  {
    id: 'mw-2023-012',
    type: 'mcq',
    question: 'Brass is an alloy of:',
    options: ['Iron and carbon', 'Copper and zinc', 'Aluminum and tin', 'Lead and silver'],
    correctAnswer: 1,
    explanation: 'Brass combines copper (60-90%) with zinc, creating a corrosion-resistant alloy used in fittings, instruments, and decorative items.',
    subject: 'Metalwork',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Types of Metals',
    year: 2023,
  },
  {
    id: 'mw-2022-013',
    type: 'mcq',
    question: 'Case hardening makes:',
    options: ['Entire object brittle', 'Surface hard while keeping core tough', 'Metal softer', 'Metal magnetic'],
    correctAnswer: 1,
    explanation: 'Case hardening adds carbon to the surface layer, creating hard wear-resistant surface with tough, shock-resistant core.',
    subject: 'Metalwork',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Heat Treatment',
    year: 2022,
  },
  {
    id: 'mw-2023-014',
    type: 'mcq',
    question: 'A center punch is used to:',
    options: ['Cut metal', 'Make indentation to guide drill bits', 'Measure thickness', 'Polish surfaces'],
    correctAnswer: 1,
    explanation: 'Center punches create small dimples that prevent drill bits from wandering when starting holes in metal.',
    subject: 'Metalwork',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Hand Tools',
    year: 2023,
  },
  {
    id: 'mw-2022-015',
    type: 'mcq',
    question: 'Soldering differs from welding in that:',
    options: ['It melts base metals', 'It uses lower temperature and filler metal only', 'It is stronger', 'It requires no heat'],
    correctAnswer: 1,
    explanation: 'Soldering uses filler metal (solder) melting below 450°C without melting base metals, while welding melts base metals.',
    subject: 'Metalwork',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Joining Methods',
    year: 2022,
  },
  {
    id: 'mw-2023-016',
    type: 'mcq',
    question: 'A vice is used to:',
    options: ['Cut metal', 'Hold workpieces securely during operations', 'Heat metal', 'Measure angles'],
    correctAnswer: 1,
    explanation: 'Vices have jaws that clamp workpieces firmly to benches, allowing safe hands-free filing, sawing, or drilling.',
    subject: 'Metalwork',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Workshop Equipment',
    year: 2023,
  },
  {
    id: 'mw-2022-017',
    type: 'mcq',
    question: 'Quenching in heat treatment involves:',
    options: ['Slow cooling in air', 'Rapid cooling in water or oil', 'Reheating', 'Polishing'],
    correctAnswer: 1,
    explanation: 'Quenching rapidly cools heated steel in water, oil, or brine to harden it by trapping carbon in the crystal structure.',
    subject: 'Metalwork',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Heat Treatment',
    year: 2022,
  },
  {
    id: 'mw-2023-018',
    type: 'mcq',
    question: 'Taps and dies are used for:',
    options: ['Cutting curves', 'Creating internal (taps) and external (dies) threads', 'Polishing', 'Bending metal'],
    correctAnswer: 1,
    explanation: 'Taps cut internal threads in holes; dies cut external threads on rods, allowing nuts and bolts to be created.',
    subject: 'Metalwork',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Threading Tools',
    year: 2023,
  },
  {
    id: 'mw-2022-019',
    type: 'mcq',
    question: 'Stainless steel resists corrosion due to:',
    options: ['Paint coating', 'Chromium content forming protective oxide layer', 'Plastic covering', 'Oil application'],
    correctAnswer: 1,
    explanation: 'Stainless steel contains chromium (10.5%+) which forms a self-repairing chromium oxide layer preventing rust.',
    subject: 'Metalwork',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Types of Metals',
    year: 2022,
  },
  {
    id: 'mw-2023-020',
    type: 'mcq',
    question: 'Cold working of metal:',
    options: ['Weakens it', 'Strengthens it through strain hardening', 'Has no effect', 'Only changes color'],
    correctAnswer: 1,
    explanation: 'Cold working (hammering, rolling, drawing) at room temperature deforms crystal structure, increasing strength and hardness.',
    subject: 'Metalwork',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Metal Forming',
    year: 2023,
  },
];
