import type { ChallengeQuestion } from '../types';

export const technicalDrawingQuestions: ChallengeQuestion[] = [
  {
    id: 'td-2023-001',
    type: 'mcq',
    question: 'The standard paper size A4 measures:',
    options: ['210mm × 297mm', '297mm × 420mm', '148mm × 210mm', '420mm × 594mm'],
    correctAnswer: 0,
    explanation: 'A4 is the most common paper size, measuring 210mm × 297mm. It is part of the ISO 216 standard.',
    subject: 'Technical Drawing',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Drawing Standards',
    year: 2023,
  },
  {
    id: 'td-2023-002',
    type: 'mcq',
    question: 'An HB pencil is used for:',
    options: ['Very light sketching', 'General purpose drawing', 'Heavy dark lines', 'Lettering only'],
    correctAnswer: 1,
    explanation: 'HB pencils have medium hardness and are ideal for general purpose technical drawing work.',
    subject: 'Technical Drawing',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Drawing Instruments',
    year: 2023,
  },
  {
    id: 'td-2022-003',
    type: 'mcq',
    question: 'Orthographic projection shows:',
    options: ['3D view only', 'Multiple 2D views of an object', 'Perspective view', 'Cross-section only'],
    correctAnswer: 1,
    explanation: 'Orthographic projection displays an object using multiple 2D views (front, top, side) at right angles.',
    subject: 'Technical Drawing',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Projections',
    year: 2022,
  },
  {
    id: 'td-2023-004',
    type: 'mcq',
    question: 'A hidden line on a technical drawing is represented by:',
    options: ['Continuous thick line', 'Dashed line', 'Chain line', 'Continuous thin line'],
    correctAnswer: 1,
    explanation: 'Hidden or invisible edges are shown with short dashed lines to indicate features not visible in that view.',
    subject: 'Technical Drawing',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Line Types',
    year: 2023,
  },
  {
    id: 'td-2022-005',
    type: 'mcq',
    question: 'The scale 1:50 means:',
    options: ['1mm represents 50mm', '50mm represents 1mm', '1cm represents 50cm', 'Actual size'],
    correctAnswer: 0,
    explanation: 'A 1:50 scale means the drawing is 50 times smaller than the actual object. 1mm on paper = 50mm in reality.',
    subject: 'Technical Drawing',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Scales',
    year: 2022,
  },
  {
    id: 'td-2023-006',
    type: 'mcq',
    question: 'Isometric projection produces:',
    options: ['True plan view', '3D pictorial view', 'Side elevation only', 'Cross-sectional view'],
    correctAnswer: 1,
    explanation: 'Isometric projection creates a 3D pictorial view with axes at 30° to the horizontal, showing three faces.',
    subject: 'Technical Drawing',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Projections',
    year: 2023,
  },
  {
    id: 'td-2022-007',
    type: 'mcq',
    question: 'Dimensioning rules require dimension lines to be:',
    options: ['Thick continuous lines', 'Thin continuous lines', 'Dashed lines', 'Chain lines'],
    correctAnswer: 1,
    explanation: 'Dimension lines are thin continuous lines with arrows at each end, placed outside the object outline.',
    subject: 'Technical Drawing',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Dimensioning',
    year: 2022,
  },
  {
    id: 'td-2023-008',
    type: 'mcq',
    question: 'A section view is used to show:',
    options: ['External features only', 'Internal features', 'Perspective', 'Color details'],
    correctAnswer: 1,
    explanation: 'Section views reveal internal features by imagining the object is cut through, showing what is inside.',
    subject: 'Technical Drawing',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Sectional Views',
    year: 2023,
  },
  {
    id: 'td-2022-009',
    type: 'mcq',
    question: 'The title block on a drawing sheet contains:',
    options: ['Only the drawing title', 'Title, scale, date, drafter name', 'Measurements only', 'Color codes'],
    correctAnswer: 1,
    explanation: 'The title block provides essential information: drawing title, scale, date, drafter, revisions, and project details.',
    subject: 'Technical Drawing',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Drawing Standards',
    year: 2022,
  },
  {
    id: 'td-2023-010',
    type: 'mcq',
    question: 'First angle projection differs from third angle projection in:',
    options: ['The scale used', 'The position of views relative to each other', 'The line types', 'The paper size'],
    correctAnswer: 1,
    explanation: 'In first angle, the object is between observer and plane. In third angle, the plane is between observer and object, affecting view positions.',
    subject: 'Technical Drawing',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Projections',
    year: 2023,
  },
  {
    id: 'td-2022-011',
    type: 'mcq',
    question: 'Centre lines on a drawing are represented by:',
    options: ['Thick continuous lines', 'Thin chain lines (long-short-long)', 'Dashed lines', 'Dotted lines'],
    correctAnswer: 1,
    explanation: 'Centre lines use thin chain lines (long-short-long pattern) to indicate axes of symmetry and centers of circles.',
    subject: 'Technical Drawing',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Line Types',
    year: 2022,
  },
  {
    id: 'td-2023-012',
    type: 'mcq',
    question: 'A compass is primarily used for:',
    options: ['Drawing straight lines', 'Drawing circles and arcs', 'Measuring angles', 'Erasing mistakes'],
    correctAnswer: 1,
    explanation: 'A compass is a drawing instrument with two legs used to draw accurate circles and arcs of various radii.',
    subject: 'Technical Drawing',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Drawing Instruments',
    year: 2023,
  },
  {
    id: 'td-2022-013',
    type: 'mcq',
    question: 'Hatching or section lining is used to:',
    options: ['Decorate drawings', 'Indicate cut surfaces in sectional views', 'Show dimensions', 'Mark errors'],
    correctAnswer: 1,
    explanation: 'Hatching consists of thin parallel lines at 45° drawn on cut surfaces to show where material has been sectioned.',
    subject: 'Technical Drawing',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Sectional Views',
    year: 2022,
  },
  {
    id: 'td-2023-014',
    type: 'mcq',
    question: 'The auxiliary view is used to show:',
    options: ['Standard orthographic views', 'True shape of inclined surfaces', 'Perspective views', 'Exploded views'],
    correctAnswer: 1,
    explanation: 'Auxiliary views are projected at angles other than 90° to show the true shape and size of inclined or oblique surfaces.',
    subject: 'Technical Drawing',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Projections',
    year: 2023,
  },
  {
    id: 'td-2022-015',
    type: 'mcq',
    question: 'A T-square is used for:',
    options: ['Drawing circles', 'Drawing horizontal parallel lines', 'Measuring lengths', 'Cutting paper'],
    correctAnswer: 1,
    explanation: 'The T-square has a straight edge and crosshead that slides along the drawing board edge to draw horizontal lines.',
    subject: 'Technical Drawing',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Drawing Instruments',
    year: 2022,
  },
  {
    id: 'td-2023-016',
    type: 'mcq',
    question: 'Leader lines are used to:',
    options: ['Connect dimension lines', 'Point from notes to specific features', 'Show hidden edges', 'Draw borders'],
    correctAnswer: 1,
    explanation: 'Leader lines are thin lines with arrows that connect notes, labels, or dimensions to specific parts of the drawing.',
    subject: 'Technical Drawing',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Dimensioning',
    year: 2023,
  },
  {
    id: 'td-2022-017',
    type: 'mcq',
    question: 'The correct pencil grade for construction lines is:',
    options: ['2H or harder', '6B soft', 'HB medium', 'F firm'],
    correctAnswer: 0,
    explanation: 'Hard pencils (2H, 3H, 4H) create light, thin lines ideal for construction work that may need erasing.',
    subject: 'Technical Drawing',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Drawing Instruments',
    year: 2022,
  },
  {
    id: 'td-2023-018',
    type: 'mcq',
    question: 'An exploded view shows:',
    options: ['Damaged parts', 'Components separated to show assembly order', 'Cross-sections', 'Perspective only'],
    correctAnswer: 1,
    explanation: 'Exploded views separate components along an axis showing how parts fit together, useful for assembly instructions.',
    subject: 'Technical Drawing',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Types of Drawings',
    year: 2023,
  },
  {
    id: 'td-2022-019',
    type: 'mcq',
    question: 'Oblique projection shows:',
    options: ['True plan view only', 'Front face true size with depth at 45°', 'Isometric view', 'Section only'],
    correctAnswer: 1,
    explanation: 'Oblique projection shows the front face in true shape while depth lines recede at 45° (cavalier) or 30° (cabinet).',
    subject: 'Technical Drawing',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Projections',
    year: 2022,
  },
  {
    id: 'td-2023-020',
    type: 'mcq',
    question: 'Break lines are used to:',
    options: ['Show hidden features', 'Indicate where a view has been shortened', 'Mark center points', 'Show dimensions'],
    correctAnswer: 1,
    explanation: 'Break lines show where long uniform objects (pipes, beams) have been shortened to save drawing space.',
    subject: 'Technical Drawing',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Line Types',
    year: 2023,
  },
];
