import type { ChallengeQuestion } from '../types';

export const textilesQuestions: ChallengeQuestion[] = [
  {
    id: 'txt-2024-001',
    type: 'mcq',
    question: 'A textile fiber obtained from plants is:',
    options: ['Nylon', 'Polyester', 'Cotton', 'Acrylic'],
    correctAnswer: 2,
    subject: 'Textiles',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Fibers',
    explanation: 'Cotton is a natural cellulose fiber from plants.',
    year: 2024,
  },
  {
    id: 'txt-2024-002',
    type: 'mcq',
    question: 'Which process improves color fastness in fabric?',
    options: ['Random washing', 'Proper dye fixation', 'Excess heat only', 'Dry brushing'],
    correctAnswer: 1,
    subject: 'Textiles',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Dyeing and Finishing',
    explanation: 'Dye fixation helps dyes bond with fibers, improving fastness.',
    year: 2024,
  },
  {
    id: 'txt-2024-003',
    type: 'mcq',
    question: 'A plain weave is characterized by:',
    options: ['Long floating yarns', 'One-over-one interlacing', 'Knitted loops', 'Pile structure'],
    correctAnswer: 1,
    subject: 'Textiles',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Weaving',
    explanation: 'Plain weave alternates warp and weft in a one-over-one pattern.',
    year: 2024,
  },
  {
    id: 'txt-2024-004',
    type: 'mcq',
    question: 'The main purpose of fabric finishing is to:',
    options: ['Increase yarn count only', 'Improve appearance and performance', 'Reduce all costs', 'Eliminate design choice'],
    correctAnswer: 1,
    subject: 'Textiles',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Fabric Finishing',
    explanation: 'Finishing modifies handle, appearance, durability, and function.',
    year: 2024,
  },
  {
    id: 'txt-2024-005',
    type: 'mcq',
    question: 'Sustainable textile practice includes:',
    options: ['Ignoring waste', 'Recycling and efficient water use', 'Overuse of chemicals', 'Burning usable scraps'],
    correctAnswer: 1,
    subject: 'Textiles',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Sustainability',
    explanation: 'Sustainable textiles reduce waste and conserve resources in production.',
    year: 2024,
  },
];
