import type { ChallengeQuestion } from '../types';

export const woodworkQuestions: ChallengeQuestion[] = [
  {
    id: 'ww-2023-001',
    type: 'mcq',
    question: 'Hardwood comes from:',
    options: ['Pine trees', 'Deciduous (broad-leaved) trees', 'Palm trees', 'Bamboo'],
    correctAnswer: 1,
    explanation: 'Hardwoods come from deciduous trees (mahogany, oak, teak) which lose leaves seasonally. They are denser and more durable.',
    subject: 'Woodwork',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Types of Wood',
    year: 2023,
  },
  {
    id: 'ww-2023-002',
    type: 'mcq',
    question: 'Seasoning of timber is done to:',
    options: ['Add color', 'Remove moisture and prevent warping', 'Increase weight', 'Make it softer'],
    correctAnswer: 1,
    explanation: 'Seasoning reduces moisture content to prevent shrinking, warping, and fungal attack after construction.',
    subject: 'Woodwork',
    difficulty: 'medium',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Wood Processing',
    year: 2023,
  },
  {
    id: 'ww-2022-003',
    type: 'mcq',
    question: 'A mortise and tenon joint is used for:',
    options: ['Temporary fixing', 'Strong permanent joints in frames', 'Surface finishing', 'Wood bending'],
    correctAnswer: 1,
    explanation: 'Mortise and tenon is a strong traditional joint where a tenon (projection) fits into a mortise (hole), used in furniture frames.',
    subject: 'Woodwork',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Wood Joints',
    year: 2022,
  },
  {
    id: 'ww-2023-004',
    type: 'mcq',
    question: 'A hand plane is used to:',
    options: ['Cut wood', 'Smooth and flatten wood surfaces', 'Make holes', 'Join wood'],
    correctAnswer: 1,
    explanation: 'A hand plane shaves thin layers from wood surfaces to smooth, flatten, and reduce thickness.',
    subject: 'Woodwork',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Hand Tools',
    year: 2023,
  },
  {
    id: 'ww-2022-005',
    type: 'mcq',
    question: 'Sandpaper grits are numbered:',
    options: ['Higher number = coarser', 'Lower number = coarser', 'All the same', 'Random numbering'],
    correctAnswer: 1,
    explanation: 'Lower grit numbers (40-60) are coarse for rough work. Higher numbers (180-400) are fine for smooth finishing.',
    subject: 'Woodwork',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Surface Finishing',
    year: 2022,
  },
  {
    id: 'ww-2023-006',
    type: 'mcq',
    question: 'Plywood is made by:',
    options: ['Solid wood cut lengthwise', 'Gluing thin wood layers with alternating grain', 'Compressed sawdust', 'Painted boards'],
    correctAnswer: 1,
    explanation: 'Plywood consists of thin wood veneers glued together with grain directions alternating for strength and stability.',
    subject: 'Woodwork',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Manufactured Boards',
    year: 2023,
  },
  {
    id: 'ww-2022-007',
    type: 'mcq',
    question: 'A try square is used for:',
    options: ['Measuring angles', 'Checking right angles', 'Cutting curves', 'Drilling holes'],
    correctAnswer: 1,
    explanation: 'A try square checks if edges are at perfect right angles (90°) and for marking perpendicular lines.',
    subject: 'Woodwork',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Marking Tools',
    year: 2022,
  },
  {
    id: 'ww-2023-008',
    type: 'mcq',
    question: 'Wood preservatives are applied to:',
    options: ['Change color only', 'Protect against insects, fungi, and decay', 'Make wood heavier', 'Speed up drying'],
    correctAnswer: 1,
    explanation: 'Preservatives (creosote, copper-based) protect wood from termites, fungi, rot, and weathering, extending lifespan.',
    subject: 'Woodwork',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Wood Treatment',
    year: 2023,
  },
  {
    id: 'ww-2022-009',
    type: 'mcq',
    question: 'A dovetail joint is commonly used in:',
    options: ['Roof frames', 'Drawer construction', 'Window frames', 'Door panels'],
    correctAnswer: 1,
    explanation: 'Dovetail joints have interlocking "tails" and "pins" providing excellent tensile strength, ideal for drawers.',
    subject: 'Woodwork',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Wood Joints',
    year: 2022,
  },
  {
    id: 'ww-2023-010',
    type: 'mcq',
    question: 'Safety goggles should be worn during woodwork to:',
    options: ['Improve vision', 'Protect eyes from dust and flying chips', 'Look professional', 'Reduce glare'],
    correctAnswer: 1,
    explanation: 'Safety goggles protect eyes from wood chips, sawdust, and splinters that can fly during cutting, drilling, or sanding.',
    subject: 'Woodwork',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Workshop Safety',
    year: 2023,
  },
  {
    id: 'ww-2022-011',
    type: 'mcq',
    question: 'A chisel is used for:',
    options: ['Cutting curves', 'Removing waste wood and creating joints', 'Measuring angles', 'Drilling holes'],
    correctAnswer: 1,
    explanation: 'Chisels have sharp beveled edges for paring, shaping wood, and cutting mortises and other joints.',
    subject: 'Woodwork',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Hand Tools',
    year: 2022,
  },
  {
    id: 'ww-2023-012',
    type: 'mcq',
    question: 'A coping saw is designed for:',
    options: ['Straight cuts only', 'Cutting curves and intricate shapes', 'Planing surfaces', 'Joining wood'],
    correctAnswer: 1,
    explanation: 'The coping saw has a thin, narrow blade in a C-shaped frame, ideal for cutting curves, circles, and detailed work.',
    subject: 'Woodwork',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Hand Tools',
    year: 2023,
  },
  {
    id: 'ww-2022-013',
    type: 'mcq',
    question: 'Varnish is applied to wood to:',
    options: ['Weaken it', 'Protect and enhance appearance', 'Make it softer', 'Change its structure'],
    correctAnswer: 1,
    explanation: 'Varnish forms a transparent protective coat that shields wood from moisture, enhances grain, and provides glossy finish.',
    subject: 'Woodwork',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Surface Finishing',
    year: 2022,
  },
  {
    id: 'ww-2023-014',
    type: 'mcq',
    question: 'A lap joint is formed by:',
    options: ['Overlapping two pieces with half removed from each', 'Gluing surfaces only', 'Nailing at angles', 'Using screws'],
    correctAnswer: 0,
    explanation: 'In lap joints, half the thickness is cut from each piece so they overlap flush, creating a strong flat joint.',
    subject: 'Woodwork',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Wood Joints',
    year: 2023,
  },
  {
    id: 'ww-2022-015',
    type: 'mcq',
    question: 'Softwood typically comes from:',
    options: ['Hardwood trees', 'Coniferous (cone-bearing) trees', 'Fruit trees', 'Desert plants'],
    correctAnswer: 1,
    explanation: 'Softwoods come from conifers (pine, cedar, fir) - evergreen trees with needles. They grow faster and are less dense.',
    subject: 'Woodwork',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Types of Wood',
    year: 2022,
  },
  {
    id: 'ww-2023-016',
    type: 'mcq',
    question: 'A marking gauge is used to:',
    options: ['Measure angles', 'Scribe parallel lines at set distance from edge', 'Cut wood', 'Drill holes'],
    correctAnswer: 1,
    explanation: 'Marking gauges have adjustable pins/cutters on a beam that scribe lines parallel to wood edges for accurate marking.',
    subject: 'Woodwork',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Marking Tools',
    year: 2023,
  },
  {
    id: 'ww-2022-017',
    type: 'mcq',
    question: 'Wood warping occurs due to:',
    options: ['Proper seasoning', 'Uneven moisture content and drying', 'Correct storage', 'Good quality'],
    correctAnswer: 1,
    explanation: 'Warping (twisting, bending, cupping) happens when wood dries unevenly, causing differential shrinkage across the grain.',
    subject: 'Woodwork',
    difficulty: 'medium',
    classLevel: 'SHS 2',
    level: 'SHS',
    topic: 'Wood Defects',
    year: 2022,
  },
  {
    id: 'ww-2023-018',
    type: 'mcq',
    question: 'MDF (Medium Density Fiberboard) is:',
    options: ['Solid hardwood', 'Engineered board made from compressed wood fibers', 'Type of plywood', 'Metal sheet'],
    correctAnswer: 1,
    explanation: 'MDF is made from wood fibers bonded with resin under heat/pressure, creating smooth uniform boards ideal for painting.',
    subject: 'Woodwork',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Manufactured Boards',
    year: 2023,
  },
  {
    id: 'ww-2022-019',
    type: 'mcq',
    question: 'A housing joint (dado) is cut:',
    options: ['Along the grain', 'Across the grain to receive another piece', 'At 45 degrees', 'Diagonally'],
    correctAnswer: 1,
    explanation: 'Housing joints are grooves cut across the grain where the edge of another board fits, common in shelf construction.',
    subject: 'Woodwork',
    difficulty: 'hard',
    classLevel: 'SHS 3',
    level: 'SHS',
    topic: 'Wood Joints',
    year: 2022,
  },
  {
    id: 'ww-2023-020',
    type: 'mcq',
    question: 'The grain direction in wood affects:',
    options: ['Color only', 'Strength, splitting tendency, and cutting direction', 'Weight', 'Price only'],
    correctAnswer: 1,
    explanation: 'Wood is strongest along the grain, splits easily with the grain, and requires different techniques for cross-grain vs. with-grain work.',
    subject: 'Woodwork',
    difficulty: 'easy',
    classLevel: 'SHS 1',
    level: 'SHS',
    topic: 'Wood Properties',
    year: 2023,
  },
];
