import type { TenantConfig } from './types';

/**
 * Tenant data (registry entries only).
 * Split from registry.ts to avoid Turbopack chunk generation issues with large object literals.
 */
export const TENANT_REGISTRY: Record<string, TenantConfig> = {
  smartclass24: {
    id: 'smartclass24',
    slug: 'smartclass24',
    name: 'SmartClass24',
    market: 'global',
    branding: {
      name: 'SmartClass24',
      logoUrl: undefined,
      primaryColor: '#7c3aed',
      accentColor: '#ec4899',
      domain: 'smartclass24.app',
      supportEmail: 'ukashasolution@gmail.com',
    },
    curriculum: {
      system: 'west-african',
      gradeLevels: ['Primary', 'JHS', 'SHS'],
      description: 'Demo deployment using West African curriculum for testing',
      examSystems: ['BECE', 'WASSCE', 'NECO'],
    },
    features: {
      enableJHSCampus: true,
      enableSHSCampus: true,
      enableUniversityCampus: true,
      enableVirtualLabs: true,
      enableArenaChallenge: true,
      enableLocalization: true,
      enableParentDashboard: true,
      enableOfflineMode: true,
      enableReferrals: true,
      enablePublicPricing: true,
      enableB2BOnly: false,
    },
    content: {
      subjectsEnabled: ['all'],
      curriculumLabel: 'West African Curriculum (BECE/WASSCE/NECO)',
    },
    license: {
      tier: 'enterprise',
      maxStudents: 100000,
    },
    status: 'active',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-02-12T00:00:00Z',
  },

  wisdomwarehouse: {
    id: 'wisdomwarehouse',
    slug: 'wisdomwarehouse',
    name: 'Wisdom Warehouse',
    market: 'middle-east',
    branding: {
      name: 'Wisdom Warehouse',
      logoUrl: '/logos/wisdom-warehouse.png',
      primaryColor: '#1e40af',
      accentColor: '#f59e0b',
      domain: 'learn.wisdomwarehouseuae.com',
      supportEmail: 'admin@wisdomwarehousedubai.com',
      supportPhone: '+971 54 306 8648',
      supportLocation: 'Alserkal Avenue, Warehouse 49A, Al Quoz 1, Dubai, UAE',
      pwaIcons: { icon192: '/logos/wisdom-warehouse.png', icon512: '/logos/wisdom-warehouse.png' },
      educationLevelLabels: {
        primary: 'Primary School',
        jhs: 'Middle School',
        shs: 'High School',
      },
      contentTransformationRules: {
        'Ghana': 'your country',
        'Ghanaian': 'local',
        'Nigerian': 'local',
        'Nigeria': 'your region',
        'Accra': 'the capital',
        'Lagos': 'the capital',
        'Kumasi': 'a major city',
        'cedis': 'dollars',
        'cedi': 'dollar',
        'GH₵': '$',
        '₵': '$',
        'pesewas': 'cents',
        'BECE': 'assessment',
        'WASSCE': 'final exam',
        'NECO': 'standardized test',
        'West African Examinations Council': 'examination board',
        'WAEC': 'examination board',
        'JHS': 'Junior School',
        'JHS 1': 'Grade 7',
        'JHS 2': 'Grade 8',
        'JHS 3': 'Grade 9',
        'SHS': 'Senior School',
        'SHS 1': 'Grade 10',
        'SHS 2': 'Grade 11',
        'SHS 3': 'Grade 12',
        'Primary School': 'Elementary School',
        'tro-tro': 'bus',
        'chop bar': 'restaurant',
        'Ghana Education Service': 'Department of Education',
        'in Ghana': 'locally',
        'across Ghana': 'in your region',
        'Ghanaians': 'people',
        'in West Africa': 'in your region',
        'West African': 'regional',
        'across West Africa': 'regionally',
      },
      countryLabel: 'Location',
      footer: {
        tagline: 'Empowering curious, creative, and developing young minds through alternative, holistic education rooted in real-world learning, emotional resilience, and individual potential.',
        emoji: '🧠',
        showSocialMedia: true,
        socialLinks: {
          instagram: 'https://www.instagram.com/wisdomwarehousedubai/',
        },
      },
    },
    curriculum: {
      system: 'alternative-holistic',
      examSystems: [],
      gradeLevels: ['K-12'],
      description: 'Project-based, hands-on learning focused on emotional resilience and individual potential',
      curriculumId: 'us-common-core',
    },
    features: {
      enableJHSCampus: true,
      enableSHSCampus: true,
      enableUniversityCampus: true,
      enableVirtualLabs: true,
      enableArenaChallenge: true,
      enableLocalization: false,
      enableParentDashboard: true,
      enableOfflineMode: false,
      enableReferrals: false,
      enablePublicPricing: false,
      enableB2BOnly: true,
    },
    content: {
      subjectsEnabled: [
        'Mathematics',
        'Science',
        'English',
        'Computer Science',
        'Creative Arts',
        'Life Skills',
        'Social Studies',
      ],
      curriculumLabel: 'US Common Core • Holistic & Personalized Learning',
    },
    license: {
      tier: 'enterprise',
      maxStudents: 500,
      expiresAt: '2027-02-01T00:00:00Z',
    },
    status: 'active',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-02T00:00:00Z',
  },

  demo: {
    id: 'demo',
    slug: 'demo',
    name: 'Demo Academy',
    market: 'global',
    curriculum: {
      system: 'west-african',
      gradeLevels: ['Primary', 'JHS', 'SHS'],
      description: 'Demo deployment using West African curriculum for testing',
      examSystems: ['BECE', 'WASSCE', 'NECO'],
    },
    branding: {
      name: 'Demo Academy',
      logoUrl: undefined,
      primaryColor: '#0ea5e9',
      accentColor: '#8b5cf6',
      domain: 'demo.smartclass24.app',
      supportEmail: 'ukashasolution@gmail.com',
    },
    features: {
      enableJHSCampus: true,
      enableSHSCampus: true,
      enableUniversityCampus: true,
      enableVirtualLabs: true,
      enableArenaChallenge: true,
      enableLocalization: false,
      enableReferrals: false,
    },
    content: {
      subjectsEnabled: ['all'],
      curriculumLabel: 'Global',
    },
    license: {
      tier: 'standard',
      maxStudents: 500,
      expiresAt: '2026-12-31T00:00:00Z',
    },
    status: 'trial',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-02T00:00:00Z',
  },
};
